### ISSUE TITLE
Remove `third_party/testdata` from the main libjxl repo

### ISSUE THREAD

**Issue by malaterre** [libjxl/libjxl#1013]
**Is your feature request related to a problem? Please describe.**

I've uploaded jpeg-xl to Debian repo. To keep source code small in between patch release, I'd like to have the testdata in a separate repo:

Typically:

```
% du -sh third_party/testdata
19M     third_party/testdata
```

It is very unlikely that this testdata changes as often as the source code.

**Describe the solution you'd like**

Have a separate repo (submodule?) for testdata.

**Describe alternatives you've considered**

I could do it myself of course. It would be nice to have a comment from upstream, if feature is accepted or not.

**Comment by jonsneyers** [comment]
Sounds like a good idea indeed to put that in a separate repo that is included as a submodule.

**Comment by malaterre** [comment]
@jonsneyers Any time estimate (eg. before next release) ? Now that #929 is fixed, I can prepare the next Debian package upload much more easily (I can trim the testdata on my side, so this is not a blocker).
