### ISSUE TITLE
Add an API to fill basic info in some scenarii

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#1021]
**Is your feature request related to a problem? Please describe.**
for a neophite user like me, correctly filling basic_info could be hard.

**Describe the solution you'd like**
Adding an API to fill basic_info for colorspaces like RGB, RGBA, etc...

thank you

**Comment by mo271** [comment]
Are the functions https://github.com/libjxl/libjxl/blob/1f1b94a39d770cb39eab33585b688a04ce585780/lib/include/jxl/encode.h#L786
or
https://github.com/libjxl/libjxl/blob/1f1b94a39d770cb39eab33585b688a04ce585780/lib/include/jxl/encode.h#L824

what you are looking for?
