### ISSUE TITLE
Adding a 3-channel RGB frame to a 4-channel RGBA image results in a fully-transparent frame.

### ISSUE THREAD

**Issue by alistair7** [libjxl/libjxl#1026]
When encoding an image, if the JxlBasicInfo specifies an alpha channel, and I add a frame that has no alpha channel, the resulting encoded frame is completely transparent.

**To Reproduce**
- Call JxlEncoderSetBasicInfo using a JxlBasicInfo with, e.g., `num_color_channels = 3, num_extra_channels = 1, alpha_bits = 8`.

- Call JxlEncoderAddImageFrame using a JxlPixelFormat with `num_channels = 3`.

- The resulting encoded frame is transparent.

**Expected behavior**
Assuming it's valid API usage to mix frames with different JxlPixelFormats, I'd expect that when I call JxlEncoderAddImageFrame with a JxlPixelFormat that specifies only 3 channels, the encoder treats every pixel as fully opaque, regardless of whether the overall image has an alpha channel.

If it's not valid I'd expect an error :)

**Environment**
 - OS: Linux 5.11.0-41-generic (Kubuntu)
 - Compiler version: gcc 10.3.0
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 f8c9f02 [AVX2,SSE4,SSSE3,Scalar]
 
**Additional context**
This situation came about when I was testing some code that merges several JXLs into a single multi-layer JXL.  For each input file, I use the minimal pixel format that can accurately represent the encoded pixels - some include an alpha channel and some don't.

**Workaround**
Always use a pixel buffer with an interleaved alpha channel for frames that will be added to JXL with transparency, at the cost of higher memory use.

**Comment by alistair7** [comment]
@jonsneyers,
Adding an RGB frame with no extra channels to an image with alpha now produces an error during encoding:

```
./lib/jxl/encode.cc:403: Extra channel 0 is not initialized
```

...which is fair enough, but seems to be at odds with the newly documented behaviour of JxlEncoderAddImageFrame:

```
 * If the image has alpha, and alpha is not passed here, it will implicitly be
 * set to all-opaque (an alpha value of 1.0 everywhere).
```

(Is this change possibly conflicting with 949fb0fb7e5ec4d228f3e160ce17bad2f01de654 where this validation was added?)

**Comment by jonsneyers** [comment]
I guess we need to decide what we want to do here: be strict about it (like we seem to do atm), or allow implicit alpha (which could be more convenient but also encourages redundantly encoding an RGB image as RGBA). I have no strong opinion on this.
