### ISSUE TITLE
Decoding is inconsistent across output formats

### ISSUE THREAD

**Issue by eustas** [libjxl/libjxl#1029]
Run `./build/tools/djxl ./third_party/testdata/jxl/spline_on_first_frame.jxl ./out.{format}`
|{format}|result|debug messages|
|-|-|-|
|jpg|OK|
|exr|OK|
|png|wrong image (intermediate frame)|
|apng|"Failed to write decoded image."|"Cannot encode using Codec::kUnknown"|
|gif|"Failed to write decoded image."|"Encoding to GIF is not implemented"|
|pnm|"Failed to write decoded image."|"Cannot encode using Codec::kUnknown"|
|psd|"Failed to write decoded image."|"PSD encoding not yet implemented"|
|pgx|"Failed to write decoded image."|"PGX encoder ignoring metadata - use a different codec", "PGX: must be grayscale"|
|pfm|"terminated by signal SIGILL (Illegal instruction)"|JXL_ASSERT: io.frames.size() == 1 || io.metadata.m.have_animation|
|abracadabra|"Failed to write decoded image."|"Cannot encode using Codec::kUnknown"|

At least, for "gif" and _unknown_ we should have more meaningful report.

**Comment by mo271** [comment]
Seems to be more consistent now. Do you think more is needed, @eustas?

|{format}|result|debug messages|
|-|-|-|
|jpg|OK|
|exr|OK|
|png|OK|
|apng|OK|
|gif|can't decode to the file extension '.gif'||
|pnm|can't decode to the file extension '.pnm'||
|psd|can't decode to the file extension '.psd'||
|pgx|SelectFormat failed <br>DecompressJxlToPackedPixelFile failed| JXL_FAILURE: no appropriate format found|
|pfm|OK|
|abracadabra|can't decode to the file extension '.abracadabra'||
|pgm|SelectFormat failed <br>DecompressJxlToPackedPixelFile failed| JXL_FAILURE: no appropriate format found|

**Comment by eustas** [comment]
Yup! Thanks.
