### ISSUE TITLE
require gflags only if tools are enabled

### ISSUE THREAD

**Issue by Hello71** [libjxl/libjxl#1062]
normally for multilib builds, tools are disabled (you may need lib32/libjxl.so but probably not bin32/cjxl). according to fb8369735ac9c55fcbd19c312c41d4f288334f78, gflags will be used for cjxl (and i guess maybe djxl too?) so it shouldn't be required for non-tools builds.

**Comment by Vargol** [comment]
[cmake_exclude_gflags.txt](https://github.com/libjxl/libjxl/files/7890333/cmake_exclude_gflags.txt)

That patch should fix it and here's the patched CMake file from libjxl/third_party

[CMakeLists.txt](https://github.com/libjxl/libjxl/files/7890375/CMakeLists.txt)

**Comment by veluca93** [comment]
Could you make that a pull request?

**Comment by Vargol** [comment]
GFLAGS is supposed to be used by tools only 
pull request #1103
