### ISSUE TITLE
Add cjxl option to output JXL inside ISO BMFF container file

### ISSUE THREAD

**Issue by pavelxkrejci** [libjxl/libjxl#1092]
**Is your feature request related to a problem? Please describe.**
I'm trying to (batch) convert images without discarding their EXIF info. Neither Exiftool nor Exiv2 are currently able to modify the raw JXL files cjxl outputs, but they support the containerized JXL files. I am not able to use JXL without metadata support in my workflow.

**Describe the solution you'd like**
I'd like to add "-iso" or "-bmff" option to cjxl that would add the 40 byte ISO BMFF header to output JXL files.

**Describe alternatives you've considered**
I have tried prepending the header manually. There is also value indicating JXL stream size (jxlc), which seems to be ignored, but I am not sure if could cause problems with other/future software if it is not set correctly.

**Additional context**
I have tried mostly free Windows software with JXL support, but they are just using cjxl or libjxl and produce the same raw JXL files. Gimp JXL plugin supports ISO BMFF, but the plugin windows binary is not publicly available and it seems difficult to use Gimp in batch processing scripts.
I do not know of any current Windows software supporting JXL to be able to output JXL in ISO BMFF container. This makes easy task like saving/copying/editing EXIF info into mission impossible even for advanced users.
There are also some reports, that JXL files inside ISO BMFF containers might be more widely supported (https://teddit.sethforprivacy.com/r/jpegxl/comments/pr2sk6/facebook_now_seems_to_accept_jpeg_xl_image_uploads/hdg252q/?context=10)

**Comment by jonsneyers** [comment]
The option `--container` does exactly this.

**Comment by pavelxkrejci** [comment]
Thanks. 
Maybe such important option could be promoted to "cjxl -h".

**Comment by jonsneyers** [comment]
I think it might be a good idea to open issues with exiftool/exiv2 to make them wrap a naked jxl in a container if needed, it's easy enough to do that.

It's not in the low-verbosity help of cjxl because in normal use, you don't need the option: it will automatically add the container if the input png or jpg contains exif/xmp metadata.

Closing the issue now, feel free to reopen if needed.
