### ISSUE TITLE
How to build for mac os

### ISSUE THREAD

**Issue by fredprodibi** [libjxl/libjxl#115]
Hello,

Can someone help building cjxl and djxl for mac os? (I managed to build a debian version with the advanced guide for debian)

may be a documentation page to build for different platform like macos, ios, and android could be done at some point?

Thank you

**Comment by jan-wassenberg** [comment]
Hi, we have a README.OSX.md in the root folder, does that help?

**Comment by fredprodibi** [comment]
@jan-wassenberg yes it helps a lot! I will try that.

Any idea if someone managed to build at least the decoder for android or ios?

**Comment by jan-wassenberg** [comment]
@fredprodibi Great! We do build for Android, not sure about iOS, but if you encounter any issues, please let us know.

**Comment by fredprodibi** [comment]
@jan-wassenberg  excellent, where is the page for android? I can't find it, can I do it with docker?

the docker build seems to work great

**Comment by jan-wassenberg** [comment]
@fredprodibi glad to hear. We don't have a page for it yet, would you like to add one with your experience?

Here's a command line:
```
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo \
	-DCMAKE_TOOLCHAIN_FILE=/usr/lib/android-ndk/build/cmake/android.toolchain.cmake \
	-DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=30 -DBUILD_TESTING=0 \
	-DCMAKE_CXX_FLAGS='-Wno-unused-command-line-argument -DJXL_DISABLE_PINNING=1 -DJXL_HIGH_PRECISION=0' \
	-DCMAKE_C_FLAGS='-Wno-unused-command-line-argument' -DPKG_CONFIG_EXECUTABLE=/dev/null
make -j
```

**Comment by eustas** [comment]
BTW: should we add as an artifact a docker image for running JXL encoder / decoder; it is an overkill, but looks like a very portable solution to quickly try JXL.

**Comment by jan-wassenberg** [comment]
@eustas good idea, this sounds useful for people with less common build systems who would otherwise hit some roadblocks.

**Comment by deymo** [comment]
We are not currently building for Android from libjxl in presubmit or post-submit, but we manually tested building with the Android NDK several times including older versions of the NDK. We should look into adding these builders.

@eustas the docker artifact is maybe an overkill given that all we need is a binary. Static binaries would probably be enough.

**Comment by mo271** [comment]
Feel free to re-open if you still have trouble building on mac os.
