### ISSUE TITLE
Ask for an example code of wasm usage.

### ISSUE THREAD

**Issue by duckker** [libjxl/libjxl#1165]
Hi 

I had build the wasm version, but cannot figure out how to run the djxl or decode_oneshot, decode_progressive in javascript.
Please provide some example code to run djxl or decode_oneshot, decode_progressive in javascript.

Thanks in advance.

**Comment by KoromaruKoruko** [comment]
currently wasm support is limited, to the usage of djxl and cjxl

in short, you need to call the module as if it were a program.

I would however recommend making your own wrapper of now, or waiting a while as wasm support is still being worked on.
