### ISSUE TITLE
How to link to libjxl with Cmake?

### ISSUE THREAD

**Issue by zanazakaryaie** [libjxl/libjxl#1175]
I've compiled libjxl from source on my ubuntu machine. Now, I want to ```find_package(LibJxl)``` or something similar in my own CMake project so that I can use libjxl in my codes. But it seems that libjxl does not provide any config.cmake file.

**Comment by zanazakaryaie** [comment]
Oh, I found a solution. libjxl has a package config file (.pc). I used:
```
find_package(PkgConfig)
if(${PkgConfig_FOUND})
    pkg_check_modules(libjxl REQUIRED)
    if (${libjxl_FOUND})
        message(STATUS "Found LibJxl")
        list(APPEND LIBRARIES ${LibJxl_LIBRARIES})
        include_directories (${LibJxl_INCLUDE_DIRS})
    endif()
endif()
```
and it works :) 
But let me know if I should do it better

**Comment by jonsneyers** [comment]
Closing since it seems to be self-resolved :)

**Comment by kmilos** [comment]
Or you could write your [own FindJXL.cmake module like this](https://github.com/darktable-org/darktable/pull/10044/files#diff-4ce019fd9ca1bfcb084641e1e816d1017a725ce8dc0587613fd649db2853aea1) that basically wraps this approach so your CMakeLists is a bit more modular/readable...

But ideally, yes, libjxl should supply the config.cmake file, pretty please!
