### ISSUE TITLE
How to know if a jxl file is 8bit or 16bit?

### ISSUE THREAD

**Issue by fredprodibi** [libjxl/libjxl#1183]
Hello, 

I have a series of 16 bits TIFF that I would like to compress with jxl and I would like them to stay in 16bit.

How can I ensure that the compression preserve the bit depth and how can I check the bit depth of a resulting jxl file?

Thank you

**Comment by fredprodibi** [comment]
I found a jxlinfo tool, and the jxl file is 8bit is their a rule to know how the bit depth is adjusted?

with libvips that uses libjxl it seems that 16bit tiff input results in 8 bit jxl, did they integrate libjxl incorrectly?

**Comment by jonsneyers** [comment]
Closing, feel free to reopen if you have further questions.
