### ISSUE TITLE
Complementary metrics for assessing image quality

### ISSUE THREAD

**Issue by LifeIsStrange** [libjxl/libjxl#1186]
PSNR is a start but it seems there are new metrics that can be complementary:

https://paperswithcode.com/paper/nima-neural-image-assessment

https://paperswithcode.com/paper/a-study-of-deep-perceptual-metrics-for-image

And much more here:
https://paperswithcode.com/task/image-quality-assessment

Generally, using neural networks to assess image quality might give complementary insights that are closer to human judgment in pathological cases where PSNR would diverge from human judgment.

**Comment by jonsneyers** [comment]
We currently mostly use butteraugli as a quality metric. There's also ssimulacra. Anyway, what is the reason for opening an issue here? This is not really in the scope of libjxl...

**Comment by LifeIsStrange** [comment]
I figured that it would be useful for libjxl devs to be aware about those advances in automated image quality assesment. Now that jonsneyers has seen it, my mission is done here.

**Comment by LifeIsStrange** [comment]
@jonsneyers BTW I had opened a discussion on one of your repositories: https://github.com/jonsneyers/jonsneyers.github.io/issues/1
feel free to ignore :)
