### ISSUE TITLE
Identical condition

### ISSUE THREAD

**Issue by maddin200** [libjxl/libjxl#1187]
/libjxl-main/tools/djxl_ng_main.cc line 327 same as line 302
Code:
  } else if (status == JXL_DEC_NEED_IMAGE_OUT_BUFFER) {

**Comment by KoromaruKoruko** [comment]
yup, its identical. likely snuck in while someone was working on something else in the code, and they just didn't notice it.
not that big of a deal though.

**Comment by eustas** [comment]
Using "switch" would be a clear win here.
