### ISSUE TITLE
Unused extra channel name in djxl_conformance

### ISSUE THREAD

**Issue by veluca93** [libjxl/libjxl#1191]
Doesn’t it mean that this is also not used? (Should it be?)

_Originally posted by @sboukortt in https://github.com/libjxl/libjxl/pull/1189#discussion_r811075496_

**Comment by veluca93** [comment]
@eustas can you take a look?

**Comment by eustas** [comment]
Indeed, the name seems to be dropped.
Ideally, we should dump it to metadata.

**Comment by szabadka** [comment]
djxl_conformance does not exist any more
