### ISSUE TITLE
CMake Error at third_party/CMakeLists.txt:170 (find_package): By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "gflags", but CMake did not find one.

### ISSUE THREAD

**Issue by bejelentkezni** [libjxl/libjxl#1206]
**Describe the bug**
CMake fails to find gflags.

**To Reproduce**
Clone the repository, pull down deps with git submodule, and run CMake with or without any flags.

**Expected behavior**
I expected CMake to configure the project correctly.

**Environment**
 - OS: Windows 10 21H2 and up-to-date no-testing-repos Arch Linux
 - Compiler version: MSVC 2022 17.1.0 Build Tools or Community, with Windows SDK 10.0.19041.685 or clang 11.0.0 on same Windows or gcc 11.2.0 on same Windows or clang 13.0.1 on said Arch Linux or gcc 11.2.0 on same Arch Linux. CMake 3.22.2 in all cases.
 - CPU type: x86_64
 - cjxl/djxl version string: Ain't one cuz it didn't build but it was from libjxl commit [89875cb](https://github.com/libjxl/libjxl/commit/89875cba4d18485ec9692c80b747b59b73ce712e) and gflags commit [986e8ee](https://github.com/gflags/gflags/commit/986e8eed00ded8168ef4eaa6f925dc6be50b40fa)

**Comment by fredprodibi** [comment]
Do you have a quick fix that we can do on our side to get a build out of docker? I m having the same issue

**Comment by kihot122** [comment]
I am facing the very same problem. Currently unable to build on both Win and Arch. Both CMake and GCC are up to date.

**Comment by mo271** [comment]
related: https://github.com/libjxl/libjxl/pull/1234

**Comment by mo271** [comment]
Is this still happening, or was it fixed by #1234

**Comment by bejelentkezni** [comment]
Sorry for the tardy response, yes I'm still getting the same error on both targets.

**Comment by mo271** [comment]
Should be fixed by https://github.com/libjxl/libjxl/pull/1588, please reopen if there is still a problem!
