### ISSUE TITLE
Hard limit at extra_channels=4 when encoding via API? Throws error at 5 or more.

### ISSUE THREAD

**Issue by alexjc** [libjxl/libjxl#1237]
**Describe the bug**
I'm using `JxlEncoderSetExtraChannelBuffer` to encode extra channel data for a base image that's RGB.  It work great up-to 4 channels, but then adding a 5th (even if it's the exact same data or new data) causes an error in `JxlEncoderProcessOutput` which returns status code 1.

**To Reproduce**
Encode an RGB image with 5 extra_channels of greyscale data.  This does not seem to depend on the image resolution.  I fetched the main branch yesterday (bd074245ad2d96d818ed253d0571550dc95e600c).

(I'm calling `libjxl` wrapped via `jxlpy`, but the error is passed back directly from `JxlEncoderProcessOutput`.)

**Expected behavior**
Either one of the following:
* An error is returned earlier in `JxlEncoderSetExtraChannelBuffer` if there's a hard-limit or other reason why the extra_channel can't be processed.
* No error is returned at any stage and `JxlEncoderProcessOutput` processes channels beyond 4.

**Environment**
 - OS: Linux 20.04 LTS
 - Compiler version: gcc
 - CPU type: AMD Threadripper
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 bd07424 [AVX2,SSE4,SSSE3,Scalar]

**Comment by jonsneyers** [comment]
You need to set the codestream level to 10 if you want more than 4 extra channels. The default/implicit codestream level is 5 which doesn't allow more than 4 extra channels.

Perhaps it would make more sense if we would bump up the level automatically based on the basicinfo, or at least return error if basicinfo is given with more channels than allowed by the level that was (implicitly) set.
