### ISSUE TITLE
Error converting PNG

### ISSUE THREAD

**Issue by Jamaika1** [libjxl/libjxl#1244]
Hi. I found such a bug if I did everything right.
```
JPEG XL encoder v0.7.0 0.7.0-373c592 [Scalar]
color_hints.cc:56: No color_space/icc_pathname given, assuming sRGB
Read 1563x1558 image, 25.8 MP/s
Encoding [Modular, lossless, hare], 4 threads.
enc_palette.cc:558: JXL_RETURN_IF_ERROR code=1: FwdPaletteIteration( input, begin_c, end_c, nb_colors, nb_deltas, ordered, lossy, predictor, wp_header, palette_iteration_data)
```
cjxl.exe image_21447_24bit.png image_21447_24bit.jxl -v -m -q 100 -s 5 -C 1 --num_threads=4

**Comment by jonsneyers** [comment]
Could you share the image for which this happens?

**Comment by Jamaika1** [comment]
I add photo.
https://www.sendspace.com/file/1525a3

**Comment by jonsneyers** [comment]
Thanks for the report! Good catch!
https://github.com/libjxl/libjxl/pull/1256 should fix this.

**Comment by Jamaika1** [comment]
Thanks
