### ISSUE TITLE
Error building on VCPKG 2022 x86_64... trying build on #544

### ISSUE THREAD

**Issue by MartinEesmaa** [libjxl/libjxl#1272]
Hello, libjxl community. I have a problem of build failed on libjxl.
I tried build libjxl of cjxl and djxl, I build all using keyboard shortcut CTRL + SHIFT + B.
During building, I got my build all failed. See the error log:
https://pastebin.com/wkKFqWPx

Visual Studio version: 2022 (17.10.2)
Windows (winver): Windows Server 2022 (Version Dev OS Build 22483.1011)
System type: x86_64
Clang version: 13.0.0
VCPKG version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
Cmake version: 3.23.0-rc2

Cmake configure and generation finished log:
https://pastebin.com/PxF72Uzi

Is there any possible to fix?

I followed the docs of libjxl and vcpkg on Github.
1. Install vcpkg on C:/src/vcpkg, used .bat Microsoft/vcpkg
2. Install packages with vcpkg and integrated with Visual Studio 2022
3. Git cloned libjxl with checking out code.
4. Open libjxl folder with Visual Studio, right clicked CMakeLists.txt, changed from debug to Clang Release x64
5. Clicked edit json and saved file before editor pop up... replaced json with [JSON Example](https://github.com/libjxl/libjxl/blob/main/doc/developing_in_windows_vcpkg.md#building)
6. Waiting for configuring and generating in Cmake. https://pastebin.com/PxF72Uzi
7. I pressed F7, but nothing happened. I pressed CTRL + SHIFT + B as Build all.
8. Log file error: https://pastebin.com/wkKFqWPx

# Update 25th February 2022 18:53 (AEDT)
I used configure, build and install and it worked without GUI.

Configure:
```
cmake -Bbuild -H. -A x64 -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Users/Administrator/Downloads/libjxl/prefix -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake -DJPEGXL_ENABLE_OPENEXR=OFF -DJPEGXL_ENABLE_PLUGINS=OFF -DJPEGXL_ENABLE_TCMALLOC=OFF -DJPEGXL_ENABLE_VIEWERS=OFF -DVCPKG_TARGET_TRIPLET=x64-windows-static -DJPEGXL_BUNDLE_GFLAGS=ON
```

Build:
```
cmake --build build --config Release
```

Install:
```
cmake --build build --config Release --target install
```

**Comment by MartinEesmaa** [comment]
I will test sec if EXIF works...

**Comment by MartinEesmaa** [comment]
Message to @jonsneyers 

Nope not quite success, the issue is compiler crash since effort 5 to 9. But less 5, three and four effort made success, others are not tested yet. I tried minimum threads, but it did not work from effort 5 to 9.
```
cjxl INPUT.jpg RESAMPLING2E4.jxl -e 4 -d 3 --resampling=2 -v
JPEG XL encoder v0.7.0 2ddc687 [AVX2,SSE4,SSSE3,Scalar]
Read 8000x6000 image, 179.9 MP/s
Encoding [Container | VarDCT, d3.000, cheetah | 904-byte Exif], 16 threads.
Compressed to 660294 bytes (0.110 bpp).
8000 x 6000, 10.03 MP/s [10.03, 10.03], 1 reps, 16 threads.
Average butteraugli iters:       0.00
Total layer bits headers          0.001837%        97
Total layer bits TOC              0.057994%      3063
Total layer bits quantizer        0.000284%        15
Total layer bits quant tables     0.000038%         2
Total layer bits order            0.004147%       219   [c/i:  1.00 | hst:       1 | ex:       5 | h+c+e:      28.255]
Total layer bits DC              23.903302%   1262467
Total layer bits ControlFields    0.003976%       210
Total layer bits AC               0.279842%     14780   [c/i: 97.00 | hst:    1829 | ex:       0 | h+c+e:  494209.810]
Total layer bits ACTokens        75.623182%   3994083
Total layer bits modularGlobal    0.107109%      5657   [c/i: 30.00 | hst:     707 | ex:       0 | h+c+e:  149859.779]
Total layer bits modularTree      0.018290%       966   [c/i:  2.00 | hst:      20 | ex:      28 | h+c+e:     118.717]
Total image size              5281559   [c/i:130.00 | hst:    2558 | ex:   14554 | h+c+e:  658736.686]
Including container: 661250 bytes (0.110 bpp).
Allocations: 730 (max bytes in use: 1.547541E+09)
```

**Comment by mo271** [comment]
Could you check that this problem still exists at the current head?

**Comment by szabadka** [comment]
We have replaced both cjxl and djxl with new versions using the API, so I am closing this now. Please reopen if you still experience problems.
