### ISSUE TITLE
build problem on riscv64: undefined reference to `__atomic_fetch_or_1

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#1283]
Hello,
On Gentoo Linux on riscv64 architecture, we have problems to build libjxl.a
```
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: lib/libjxl.a(dec_group_border.cc.o): in function `.L0 ':
dec_group_border.cc:(.text+0x158): undefined reference to `__atomic_fetch_and_1'
```

Complete build log: 
[build.log.txt](https://github.com/libjxl/libjxl/files/8355338/build.log.txt)

**Comment by jonsneyers** [comment]
Closing, should be resolved. Please reopen if needed.
