### ISSUE TITLE
Provide a jxltran command line tool

### ISSUE THREAD

**Issue by malaterre** [libjxl/libjxl#1291]
**Is your feature request related to a problem? Please describe.**

When libjpeg v6 was released (Aug 1995) it cames with a low level tool: `jpegtran`. this is a tool to provide lossless editing mode to existing JPEG files.

Currently supported operations are:

```
Switches for modifying the image:
  -crop WxH+X+Y  Crop to a rectangular region
  -drop +X+Y filename          Drop (insert) another image
  -flip [horizontal|vertical]  Mirror image (left-right or top-bottom)
  -grayscale     Reduce to grayscale (omit color data)
  -perfect       Fail if there is non-transformable edge blocks
  -rotate [90|180|270]         Rotate image (degrees clockwise)
  -transpose     Transpose image
  -transverse    Transverse transpose image
  -trim          Drop non-transformable edge blocks
                 with -drop: Requantize drop file to match source file
  -wipe WxH+X+Y  Wipe (gray out) a rectangular region
```

**Describe the solution you'd like**

It would make sense to provide an equivalent tool (eg. `jxltran`) at least to edit JPEG-XL files containing JPEG bitstream.

**Describe alternatives you've considered**

```
% djxl input.jxl output.tmp.jpg
% jpegtran -outfile output.jpg -rotate 90 output.tmp.jpg
% cjxl output.tmp.jpg output.jxl
```

**Comment by jonsneyers** [comment]
See also: https://github.com/libjxl/libjxl/issues/871
