### ISSUE TITLE
Poor compression ratio for 32bits float 

### ISSUE THREAD

**Issue by malaterre** [libjxl/libjxl#1323]
**Describe the bug**

I'd like to achieve good compression ratio using `-e 9` using cjxl command line tool with pfm (rgb) input.

Here is the entropy plot (-d 0 -e 9):

![sample_1920×1280 pfm jxl](https://user-images.githubusercontent.com/228803/162136470-4245431e-4b8d-46af-a5d0-38bf4c83d8e8.png)

Compared to a zstd (no option) :

![sample_1920×1280 pfm zstd](https://user-images.githubusercontent.com/228803/162136525-cf5daa55-7267-4df3-964d-ef5d85a63cdb.png)

or gzip (no option):

![sample_1920×1280 pfm gz](https://user-images.githubusercontent.com/228803/162138253-36a5db6a-6a5c-4f4c-a8c1-21467840e4ba.png)

**To Reproduce**
```
% wget https://telparia.com/fileFormatSamples/image/pfm/sample_1920×1280.pfm
% sha1sum sample_1920×1280.pfm
bd579ee0144d6d3dd4495de3cb95d2283fd6c0e0  sample_1920×1280.pfm
% time cjxl -d 0 -e 9 sample_1920×1280.pfm sample_1920×1280.pfm.9.jxl
JPEG XL encoder v0.7.0 e3a3558 [AVX2,SSE4,SSSE3,Scalar]
./lib/extras/dec/color_hints.cc:56: No color_space/icc_pathname given, assuming sRGB
Read 1920x1280 image, 107.4 MP/s
Encoding [Modular, lossless, tortoise], 8 threads.
Compressed to 13425615 bytes (43.703 bpp).
1920 x 1280, 0.01 MP/s [0.01, 0.01], 1 reps, 8 threads.
cjxl -d 0 -e 9 sample_1920×1280.pfm sample_1920×1280.pfm.9.jxl  197.76s user 0.20s system 102% cpu 3:12.67 total
```
For comparison:
```
% time zstd -o sample_1920×1280.pfm.zstd sample_1920×1280.pfm
sample_1920×1280.pfm : 30.04%   (29491217 => 8858010 bytes, sample_1920×1280.pfm.zstd)
zstd -o sample_1920×1280.pfm.zstd sample_1920×1280.pfm  0.19s user 0.02s system 106% cpu 0.198 total
```
```
% time gzip -c  sample_1920×1280.pfm >  sample_1920×1280.pfm.gz
gzip -c sample_1920×1280.pfm > sample_1920×1280.pfm.gz  1.91s user 0.01s system 99% cpu 1.920 total

```
**Expected behavior**

I'd like to have a flat entropy histogram on pfm inputs (32bits float). Here is a typical plot for uint16 (grayscale pgm original input):

![MG jxl](https://user-images.githubusercontent.com/228803/162138689-d410e409-3f4d-4b92-92da-ef322518df63.png)

**Screenshots**

See above

**Environment**
 - OS: Linux
 - Compiler version: gcc-10
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 e3a3558 [AVX2,SSE4,SSSE3,Scalar]

**Additional context**

To generate plot I used:

```
% binwalk -EJ <input file>
```

**Comment by malaterre** [comment]
For reference:

```
% du -sh sample_1920×1280.pfm*
29M     sample_1920×1280.pfm
13M     sample_1920×1280.pfm.9.jxl
8.2M    sample_1920×1280.pfm.gz
8.5M    sample_1920×1280.pfm.zstd
```

**Comment by malaterre** [comment]
Another experiment with the same input:

% pfmtopam -maxval=65535 sample_1920×1280.pfm > sample_1920×1280.ppm
% cjxl -d 0 -e 9 sample_1920×1280.ppm sample_1920×1280.ppm.9.jxl

Gives the following entropy histogram:

![sample_1920×1280 ppm 9 jxl](https://user-images.githubusercontent.com/228803/162144359-57ac768c-c095-4413-adc4-d70f28fb7bac.png)

For reference:

```
% jxlinfo sample_1920×1280.ppm.jxl
dimensions: 1920x1280
have_container: 0
uses_original_profile: 1
bits_per_sample: 16
have_preview: 0
have_animation: 0
intrinsic xsize: 1920
intrinsic ysize: 1280
orientation: 1 (Normal)
num_color_channels: 3
num_extra_channels: 0
color profile:
  format: JPEG XL encoded color profile
  color_space: 0 (RGB color)
  white_point: 1 (D65)
  primaries: 1 (sRGB)
  transfer_function: 13 (sRGB)
  rendering_intent: 0 (Perceptual)
frame:
  still frame, unnamed
```

**Comment by jonsneyers** [comment]
#1341 considerably improves compression ratio for cases like this by allowing the encoder to actually use the (channel) Palette transform to reduce the sample range from 0..1065353216 (floats reinterpreted as ints) to 0..255 in this example (presumably the pfm was converted from an 8-bit original image).

Currently the encoder wasn't trying to do channel palettes in this case (it has a fast lookup-table based fwd transform, but here the lookup table would be too large). It also wasn't trying to do reversible color transforms. Fixing both of those things makes it compress a lot better.

**Comment by hohMiyazawa** [comment]
Ah, that explains it. Not surprising that the compression ratio isn't better than general purpose compression algorithms if image specific tools aren't actually used.
