### ISSUE TITLE
How to convert 8-bit grayscale png to same jxl?

### ISSUE THREAD

**Issue by AKmatiAK** [libjxl/libjxl#1342]
Hi. When converting 8-bit grayscale images to jpeg xl output is 32-bit. How to make 8-bit grayscale jxl?

**Comment by jonsneyers** [comment]
What output are you talking about?

**Comment by AKmatiAK** [comment]
.jxl image, and bit depth checked in XnView MP. However, ImageMagick identify command says 8-bit sRGB. Also, where can I download jxlinfo.exe?

**Comment by HappySeaFox** [comment]
Beware that xnview may upconvert images losing their source information, see https://newsgroup.xnview.com/viewtopic.php?f=36&t=43205

**Comment by AKmatiAK** [comment]
To be more precise - created image is 32-bit (8-bit RGB + alpha?) when using cjxl. I also tried converting in XnView MP and output image is 24-bit (8-bit RGB without alpha).

**Comment by jonsneyers** [comment]
Can you be more specific about what the real issue is? E.g. can you provide an input image, a cjxl command line, and say what is wrong/unexpected about the output? When I run default cjxl on 8-bit pgm or grayscale png input, it produces an 8-bit grayscale jxl file, as expected.

Various tools might incorrectly report information about jxl files, but that would be a bug in those tools, not in libjxl.

**Comment by AKmatiAK** [comment]
sorry, cjxl output is marked 24-bit too in xnview, I just converted earlier version of image which was 32-bit. Images attached, but in jxl .txt is added because github doesn't allow .jxl

`E:\Pobrane\jxl-x64-windows-static>cjxl E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\przekonwertowane\Application1(2022-3-28)0005.PNG E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test.jxl
JPEG XL encoder v0.6.1 a205468 [AVX2,SSE4,Scalar]
Read 5388x4094 image, 63.7 MP/s
Encoding [VarDCT, d1.000, squirrel], 4 threads.
Compressed to 3735524 bytes (1.355 bpp).
5388 x 4094, 5.30 MP/s [5.30, 5.30], 1 reps, 4 threads.

E:\Pobrane\jxl-x64-windows-static>cjxl -d 0 E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\przekonwertowane\Application1(2022-3-28)0005.PNG E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test_lossless.jxl
JPEG XL encoder v0.6.1 a205468 [AVX2,SSE4,Scalar]
Read 5388x4094 image, 63.6 MP/s
Encoding [Modular, lossless, squirrel], 4 threads.
Compressed to 9809711 bytes (3.558 bpp).
5388 x 4094, 0.71 MP/s [0.71, 0.71], 1 reps, 4 threads.

E:\Pobrane\jxl-x64-windows-static>identify E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test.jxl
E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test.jxl JXL 5388x4094 5388x4094+0+0 8-bit sRGB 3.56247MiB 0.047u 0:00.035

E:\Pobrane\jxl-x64-windows-static>identify E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test_lossless.jxl
E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test_lossless.jxl JXL 5388x4094 5388x4094+0+0 8-bit sRGB 9.35527MiB 0.047u 0:00.035

E:\Pobrane\jxl-x64-windows-static>identify E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test_xn.jxl
E:\Obrazy\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\test_xn.jxl JXL 5388x4094 5388x4094+0+0 8-bit sRGB 9.35517MiB 0.031u 0:00.035`

![obraz_testowy](https://user-images.githubusercontent.com/51701971/163405173-9f5b7834-67e8-49b7-bb72-6ee597cdeed9.png)

[test.jxl.txt](https://github.com/libjxl/libjxl/files/8489671/test.jxl.txt)

**Comment by jonsneyers** [comment]
Looks like a bug in `identify` then. Best to file a bug report at the ImageMagick repo.

The jxl you shared, as well as the one currently produced by latest git cjxl, is in fact 8-bit grayscale, as it should be:
```
$ jxlinfo test.jxl.txt 
JPEG XL image, 2549x4094, (possibly) lossless, 8-bit Grayscale
Color space: Grayscale, D65, sRGB transfer function, rendering intent: Relative
```

**Comment by AKmatiAK** [comment]
Ok, thanks for figuring where the problem is.

**Comment by AKmatiAK** [comment]
One more question: Is there cjxl setting that creates .jxl always in grayscale?

**Comment by jonsneyers** [comment]
No, cjxl just encodes whatever the input is.

If you want to force grayscale, you can always do something like `convert input.png gray.pgm` and encode that.
