### ISSUE TITLE
cjxl -m -d 1 converts to lossless instead of lossy

### ISSUE THREAD

**Issue by AKmatiAK** [libjxl/libjxl#1355]
**Describe the bug**
When converting image to visually lossless in modular mode, cmd output says lossless encoding, and image size is same as loslessy encoded.

E:\Pobrane\jxl-x64-windows-static>cjxl -d 1 -m "E:\Pictures\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\skan1.png" E:\Pictures\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\skan1.jxl
JPEG XL encoder v0.6.1 a205468 [AVX2,SSE4,Scalar]
Read 2624x4479 image, 52.8 MP/s
Encoding [Modular, lossless, squirrel], 4 threads.
Compressed to 3760029 bytes (2.559 bpp).
2624 x 4479, 1.02 MP/s [1.02, 1.02], 1 reps, 4 threads.

E:\Pobrane\jxl-x64-windows-static>cjxl -d 0 -m "E:\Pictures\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\skan1.png" E:\Pictures\ActKey\ScanToApplication1\Czas_przestrzen_kwanty\jpeg_xl\skan1_d0.jxl
JPEG XL encoder v0.6.1 a205468 [AVX2,SSE4,Scalar]
Read 2624x4479 image, 52.7 MP/s
Encoding [Modular, lossless, squirrel], 4 threads.
Compressed to 3760029 bytes (2.559 bpp).
2624 x 4479, 1.03 MP/s [1.03, 1.03], 1 reps, 4 threads.

However, cjxl -m -q 95 produces lossy image as expected.

**To Reproduce**
cjxl -m -d 1 [input] [output]

**Expected behavior**
-d 1 -m should encode to lossy and show this in CLI

**Environment**
 - OS: Windows 10 x64
 - Compiler version: precompiled binary
 - CPU type: x86_64

**Comment by jonsneyers** [comment]
This behavior is fixed already on current git head.
