### ISSUE TITLE
pkg-config files are broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [libjxl/libjxl#1400]
**Describe the bug**

As per title: `lib/jxl/libjxl.pc.in` and `lib/threads/libjxl_threads.pc.in` have

```
prefix=@INSTALLDIR@
exec_prefix=${prefix}
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```

and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to broken .pc files on NixOS in particular.

Similar to https://github.com/open-source-parsers/jsoncpp/pull/1199. See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a discussion of the problem and a suggested fix (I don’t know CMake myself, sorry).

**Environment**
```
$ uname -a
Linux localhost 5.15.36 #1-NixOS SMP Wed Apr 27 12:39:02 UTC 2022 x86_64 GNU/Linux
```

**Comment by kmilos** [comment]
Yeah, not sure about this either - [usually all other OS-es then have to revert/patch this by converting absolute to relative](https://github.com/msys2/MINGW-packages/blob/fed9c186f9c795843116002112e1c8e2e33be8fa/mingw-w64-cjson/PKGBUILD#L47) so relocation would work...

You want to convert the NixOS absolute case to a relative one somehow (would some CMake equivalent of removing CMAKE_INSTALL_PREFIX from CMAKE_INSTALL_{INCLUDE,LIB}DIR work?), or treat is as an exception and let it be absolute like in the suggested jsoncpp example fix linked above...

For the first option, something like this?

```
if(IS_ABSOLUTE CMAKE_INSTALL_INCLUDEDIR)
  string(REPLACE CMAKE_INSTALL_PREFIX "\${prefix}" includedir_for_pc_file CMAKE_INSTALL_INCLUDEDIR)
endif()
```

**Comment by mo271** [comment]
> Yeah, not sure about this either - [usually all other OS-es then have to revert/patch this by converting absolute to relative](https://github.com/msys2/MINGW-packages/blob/fed9c186f9c795843116002112e1c8e2e33be8fa/mingw-w64-cjson/PKGBUILD#L47) (see also [this](https://gitlab.com/libtiff/libtiff/-/issues/394) and [this](https://gitlab.com/libtiff/libtiff/-/merge_requests/292)) so relocation would work...
> 
> You want to convert the NixOS absolute case to a relative one somehow (would some CMake equivalent of removing CMAKE_INSTALL_PREFIX from CMAKE_INSTALL_{INCLUDE,LIB}DIR work?), or treat is as an exception and let it be absolute like in the suggested jsoncpp example fix linked above...
> 
> For the first option, something like this?
> 
> ```
> if(IS_ABSOLUTE $CMAKE_INSTALL_INCLUDEDIR)
>   string(REPLACE $CMAKE_INSTALL_PREFIX "\${prefix}" includedir_for_pc_file $CMAKE_INSTALL_INCLUDEDIR)
> else
>   set(includedir_for_pc_file "\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}")
> endif()
> ```

What would be the use of having a relative path here? Perhaps the easiest would be to let it be absolute and figure out something if some other OS requires relative paths.

**Comment by kmilos** [comment]
> What would be the use of having a relative path here?

Cross building, changing toolchains... See also [the comment about CPack again](https://gitlab.com/libtiff/libtiff/-/merge_requests/292).

> Perhaps the easiest would be to let it be absolute and figure out something if some other OS requires relative paths.

Wouldn't the easiest be to handle the exception (NixOS), rather than break everybody else?

**Comment by alexshpilkin** [comment]
@kmilos I understand that (even if not the reason why) encoding the way the paths are derived with variable expansions (and not just including the end result) is the accepted pkg-config style, which is why I converted the paths to absolute in the NixOS patch but did not just propose it to you.

Your first approach is possible, but the second seems cleaner to me. If the user said to make it an absolute path, I say let them. Now that I’ve looked at this issue a bit more closely (in a dozen other projects :face_exhaling: ), I’ve come to think the jsoncpp approach may be a bit overcomplicated and the KDE build system [gets it right][1]:

```cmake
if(IS_ABSOLUTE "${EGPF_INCLUDE_INSTALL_DIR}")
    set(PKGCONFIG_TARGET_INCLUDES "${EGPF_INCLUDE_INSTALL_DIR}")
else()
    set(PKGCONFIG_TARGET_INCLUDES "\${prefix}/${EGPF_INCLUDE_INSTALL_DIR}")
endif()
```

Same LoC, simpler behaviour (hardly *could* be simpler without just sticking the absolute path in there). Won’t give you the full lexical dot-dot treatment like actual path joining would, but if you care about CMake versions that don’t have [builtin path manipulation][2] it’s probably an acceptable substitute.

[1]: https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166
[2]: https://cmake.org/cmake/help/latest/command/cmake_path.html

**Comment by kmilos** [comment]
> I’ve come to think the jsoncpp approach may be a bit overcomplicated and the KDE build system [gets it right](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166):
> 
> ```cmake
> if(IS_ABSOLUTE "${EGPF_INCLUDE_INSTALL_DIR}")
>     set(PKGCONFIG_TARGET_INCLUDES "${EGPF_INCLUDE_INSTALL_DIR}")
> else()
>     set(PKGCONFIG_TARGET_INCLUDES "\${prefix}/${EGPF_INCLUDE_INSTALL_DIR}")
> endif()
> ```
> 
> Same LoC, simpler behaviour (hardly _could_ be simpler without just sticking the absolute path in there). Won’t give you the full lexical dot-dot treatment like actual path joining would, but if you care about CMake versions that don’t have [builtin path manipulation](https://cmake.org/cmake/help/latest/command/cmake_path.html) it’s probably an acceptable substitute.

Thanks for the summary, that indeed seems the most pragmatic approach.

**Comment by mo271** [comment]
I have adapted the solution from kde, see https://github.com/libjxl/libjxl/pull/1403/files.
Could you confirm, @alexshpilkin, that this would fix the Issue?
Thanks for your input, @kmilos.
