### ISSUE TITLE
`Passes::GetDownsamplingBracket` is wildly different from the ISO specification

### ISSUE THREAD

**Issue by lifthrasiir** [libjxl/libjxl#1401]
I've noticed this during the independent reimplementation efforts. As specified, `minshift` is determined to be `downsample[n]` if there is an index `n` such that `last_pass[n]` is equal to the pass index, otherwise it's set to `maxshift`. In the current implementation though, `n` is the largest index such that `last_pass[n]` is **no less than** the pass index, or **0** if there's no such `n`.

Theoretically, and with my limited understanding of the modular mode, this can result in the following problems:

* Some modular group data will be placed in wrong passes. By itself they will decode just fine (as the decoder and encoder have the exactly same bug), but it degrades the progressive decoding performance.
* Some modular group data will be *omitted* (concrete example: `num_passes` = 2, `num_ds` = 1, `downsample[0]` = 2, `last_pass[0]` = 1). I believe the bitstream still decodes, but the decoded image would no longer match the original.
* Some modular group data will be *duplicated* (concrete example: `num_passes` = 3, `num_ds` = 2, `downsample[0..1]` = [4, 2], `last_pass[0..1]` = [1, 0]; keep in mind that the bitstream has zero guarantee about the sortedness of these arrays). I believe the bitstream still decodes, but the same channel might get painted multiple times so again the decoded image would no longer match the original.

Thankfully the current libjxl only emits five combinations of `Passes`, which greatly limit the issue's extent. The following is a summary:

| Case | A | B | C | D | E |
|---|---|---|---|---|---|
| **`--progressive_ac`** | Yes | Yes | Yes | Yes | No |
| **`--saliency_num_progressive_steps=`** | 1 | 2 | 3 | 4¹ | - |
| | | | | | |
| **`num_passes`** | 1 | 2 | 3 | 4 | 2 |
| **`downsample[0 .. num_ds-1]`** | - | 4 | 4, 2 | 4, 2 | 2 |
| **`last_pass[0 .. num_ds-1]`** | - | 0 | 0, 1 | 0, 1 | 0 |
| | | | | | |
| **`[minshift, maxshift)` (spec)** | [0,3) | [2,3), [0,2) | [2,3), [1,2), [0,1) | [2,3), [1,2), [1,1), [0,1) | [1,3), [0,1) |
| **`[minshift, maxshift)` (libjxl)²** | [0,3) | [2,3), [0,2) | **[1,3), [1,1), [0,1)** | **[1,3), [1,1), [0,1), [0,0)** | [1,3), [0,1) |

1. Also requires a non-zero `--saliency_threshold`, otherwise it's same to the case C.
2. libjxl actually uses an inclusive `maxshift`, which is converted to an exclusive bound in this table.

So the normal case is just fine; even the ordinary progressive option `-p` is actually `--qprogressive_ac` and not affected by this bug. Even in rare cases where `--progressive_ac --saliency_num_progressive_steps=3/4` are used some modular group data is just misplaced, but they will be technically an invalid bitstream under the specification.

I've written a simple [Python script](https://gist.github.com/lifthrasiir/86f15edcc5b10db27839b917c602592c) to enumerate all cases where the specification and libjxl disagrees.

**Comment by lifthrasiir** [comment]
I should note that the specification is ambiguous when there are multiple `n` such that `last_pass[n]` is equal to the pass index, so if we are going to fix libjxl to match the specification, we also need to clarify the specification as well ;-)

**Comment by veluca93** [comment]
Thanks for reporting this!

Note for future me: looking at the table and cjxl code, the only way to produce weird values for shifts is to pass a non-default `--saliency_num_progressive_steps`, which should be rare at best.

**Comment by veluca93** [comment]
This seems pretty reasonable to me.

**Comment by mo271** [comment]
Closing, feel free to re-open if there is still a need.
