### ISSUE TITLE
latest libjxl source code fails to compile for aarch64-linux with:  ../jxl/modular/transform/palette.h:124:20: error: variable ‘std::atomic<int> num_errors’ has initializer but incomplete type

### ISSUE THREAD

**Issue by stefson** [libjxl/libjxl#1407]
compiling latest git of libjxl for aarch64 is currently broken with: 

```
In file included from /usr/aarch64-unknown-linux-gnu/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/transform.cc:11:
/usr/aarch64-unknown-linux-gnu/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/palette.h: In function ‘jxl::Status jxl::InvPalette(jxl::Image&, uint32_t, uint32_t, uint32_t, jxl::Predictor, const jxl::weighted::Header&, jxl::ThreadPool*)’:
/usr/aarch64-unknown-linux-gnu/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/palette.h:124:20: error: variable ‘std::atomic<int> num_errors’ has initializer but incomplete type
  124 |   std::atomic<int> num_errors{0};
      |                    ^~~~~~~~~~
``` 

to reproduce download latest git sources and compile libjxl for aarch64

**Environment**
 - OS: Linux
 - Compiler version: gcc-10.3.1
 - CPU type: cross-compile from amd64 to aarch64
 - cjxl/djxl version string: latest git snapshot

**Additional context**
this is cross compile, but I don't see anything cross-compile specific about the error. 

the compressed build log is attached: [build.log.gz](https://github.com/libjxl/libjxl/files/8661800/build.log.gz)

**Comment by veluca93** [comment]
That seems like a missing #include - could you perhaps try adding `#include <atomic>` to palette.h around line 15?

**Comment by veluca93** [comment]
I guess one needs a similar line in enc_image_bundle.cc (and in other files where this happens)...

I'm not sure why this started happening now. Would you terribly mind creating a PR that adds headers until this starts compiling again? :)

**Comment by stefson** [comment]
well, its only these two files which have the missing include, so I can open a pullrequest. 

but please be aware that my knowledge of c++ is exactly 0

**Comment by stefson** [comment]
I'm not interested into signing any contract with google over this, please take the patch from the pullrequest - I was only adding input from you anyway - and add it with your credentials. Thank you.
