### ISSUE TITLE
Request for new release tag

### ISSUE THREAD

**Issue by joshuakraemer** [libjxl/libjxl#144]
Could you please consider adding a new release tag? I would like to package libjxl for Void Linux (draft PR at https://github.com/void-linux/void-packages/pull/31397), which requires a release version. However, the last release (0.3.7) is outdated (old license, does not work with qt-jpegxl-image-plugin).

**Comment by deymo** [comment]
We are working on making a new release from v0.4.x branch Very Soon (still Apache 2.0 license on that branch); would that be enough for qt-jpegxl-image-plugin to work?

**Comment by novomesk** [comment]
JxlEncoderSetICCProfile function is used by the plugin.

**Comment by joshuakraemer** [comment]
The latest commit of the v0.4.x branch (74ca6ba912fc1a682143ec2c5a1b193e008ec92b) seems to work fine.

**Comment by TheHardew** [comment]
0.5 released
