### ISSUE TITLE
cjxl crashes with --progressive_dc=2 -e 9

### ISSUE THREAD

**Issue by szabadka** [libjxl/libjxl#1448]
**Describe the bug**
Encoder crashes with the following assert:

../lib/jxl/dec_group.cc:245: JXL_ASSERT: r[i].IsInside({0, 0, dec_state->shared->dc->Plane(i).xsize(), dec_state->shared->dc->Plane(i).ysize()})

**To Reproduce**
cjxl wollerau.png wollerau.jxl --progressive_dc=2 -e 9

**Environment**
 - OS: ChromeOS
 - Compiler version: clang 11.0.1
 - CPU type:  x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 dbe51c6 [AVX2,SSE4,SSSE3,Scalar]

**Comment by szabadka** [comment]
I found this while trying to reproduce #1424, it may or may not be the same bug.

**Comment by ziemek99** [comment]
I've just successfully compressed an image with these settings using the latest GitHub artifacts. I think the issue should be fixed now.

**Comment by szabadka** [comment]
Thanks for verifying, I am closing it now.
