### ISSUE TITLE
error encoding very large PNG file

### ISSUE THREAD

**Issue by RubenFasola** [libjxl/libjxl#1456]
"./lib/jxl/enc_ans.cc:478: JXL_ASSERT: cost >= 0" when trying to encode ~880MP uncompreesed png wit q=100 or d=0.0 at effort=1, works fine when using d>0 or q<100

**To Reproduce**

1. get the image
2. try to encode it with cjxl with -q 100 -e 1
3. wait 60s or so (needs ~54GB of RAM)
4. error

**Expected behavior**
the encode does not throw an error.

**Screenshots**
screenshot of the full cjxl terminal output
![command output](https://user-images.githubusercontent.com/38555290/170790369-3fee3743-fd02-46f9-afee-cdddf0649106.png)

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 13.0.1
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.7.0 1706491c [AVX2,SSE4,SSSE3,Emu128]

**Additional context**

original image
https://drive.google.com/file/d/1DpcAHnvMD2t7TqszsF4Kj1tUYsj4_2mc/view?usp=sharing

image encoded using q=1.0
https://drive.google.com/file/d/1oiA61m5O6OrIPI4cwZWN-zJyBaDoEd17/view?usp=sharing

**Comment by veluca93** [comment]
Looks like an integer overflow ...
