### ISSUE TITLE
"JXL_ASSERT: frame_rect.IsInside(Rect(0, 0, ppf.info.xsize, ppf.info.ysize))" on attached apng file

### ISSUE THREAD

**Issue by safinaskar** [libjxl/libjxl#1457]
**To Reproduce**
- Get this apng file (it contains multiple frames, it was encoded using ffmpeg):
![tr](https://user-images.githubusercontent.com/859494/170867246-cd19705c-3d6f-4a92-92c2-d55e97f1e81c.png)
- Get static Linux build from here: https://github.com/libjxl/libjxl/actions/runs/2398179621#artifacts , namely this:
https://github.com/libjxl/libjxl/suites/6690650728/artifacts/253925770
- Run this command: `./cjxl --num_threads=2 -d 0 ~/jpeg-xl/tr.png ~/jpeg-xl/out.jxl`
- This is what I saw:
```text
$ ./cjxl --num_threads=2 -d 0 ~/jpeg-xl/tr.png ~/jpeg-xl/out.jxl
JPEG XL encoder v0.7.0 422d09a4 [AVX2,SSE4,SSSE3,Scalar]
./lib/extras/packed_image_convert.cc:130: JXL_ASSERT: frame_rect.IsInside(Rect(0, 0, ppf.info.xsize, ppf.info.ysize))
Illegal instruction
```

**Expected behavior**
File should be encoded

**Environment**
 - OS: Debian Stretch
 - Compiler version: (I used Github artifact)
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.7.0 422d09a4 [AVX2,SSE4,SSSE3,Scalar]

**Comment by mo271** [comment]
In this case just commenting out the assert seems to work.
When printing the dimension of the `frame_rect` (which is created only for the assert, apparently), we get the following:
```
x0: 0, y0: 0, xsize: 1920, ysize: 1080
x0: 1, y0: 627, xsize: 217, ysize: 36
x0: 1, y0: 645, xsize: 1394, ysize: 36
x0: 1, y0: 645, xsize: 1393, ysize: 71
x0: 2, y0: 573, xsize: 1393, ysize: 71
x0: 0, y0: 0, xsize: 1920, ysize: 1078
x0: 426, y0: 1012, xsize: 1135, ysize: 66
x0: 1279, y0: 58, xsize: 10, ysize: 18
**x0: 1279, y0: 58, xsize: 1282, ysize: 30**
x0: 4, y0: 64, xsize: 1282, ysize: 30
x0: 1, y0: 76, xsize: 235, ysize: 36
x0: 0, y0: 0, xsize: 1920, ysize: 1078
x0: 0, y0: 0, xsize: 1920, ysize: 1078
x0: 127, y0: 573, xsize: 10, ysize: 18
x0: 136, y0: 573, xsize: 28, ysize: 18
```
I highlighted the frame where the assert fails.

**Comment by szabadka** [comment]
It turns out that the bug was not in cjxl, but in the way how the apng decoder fills in the FrameInfo structures of the created ppf.
