### ISSUE TITLE
libjxl cannot read extended ISOBMFF box sizes

### ISSUE THREAD

**Issue by thebombzen** [libjxl/libjxl#1478]
**Describe the bug**
A file that has an extended box size fails to be read by either libjxl or djxl.

**To Reproduce**
An extended box size is when an ISOBMFF box has `size == 1`. When this happens, the size field is immediately followed by an 8-byte extended-size field, which contains a 64-bit true size. These are permitted even if the extended size is less than 4G. 

Take any JXL file with an extended box size and attempt to decode it with djxl or libjxl. It will not decode properly.

**Expected behavior**
The file should decode properly.

**Other information**
I believe the fault here is in `decode.cc` line 1768. https://github.com/libjxl/libjxl/blob/ab775e2298b1ef25229e19ad3f4dba4b06000197/lib/jxl/decode.cc#L1768
The extended box size field is read after the box tag field, but it should be *immediately* after the box size field, and before the box tag field. Contrast the existing behavior with the FFmpeg `mov.c` decoder: https://github.com/ffmpeg/FFmpeg/blob/35ec5c819b0f472536eb48e8f3871eb5ca222da6/libavformat/mov.c#L7813

**Comment by thebombzen** [comment]
[lenna-container-extended-size.jxl.gz](https://github.com/libjxl/libjxl/files/8846930/lenna-container-extended-size.jxl.gz)

I've attached a sample. It's gzipped because Github is refusing to let me upload it raw, so just gunzip it before trying.

**Comment by mo271** [comment]
Thanks for this bug report!
Seems like there are two places where we read the box size and type in a wrong way, I fixed both. 

How did you generate the file with the extended container size? 
I might be useful to add an image with trivial image (without copyright, like just black pixels, e.g.) with such a box size to one of our test sets.

**Comment by mo271** [comment]
updated the links in the original post with specific commits, so that they don't go stale...

**Comment by mo271** [comment]
> > How did you generate the file with the extended container size?
> 
> I constructed it manually in a hex editor.
Cool.
> 
> > I might be useful to add an image with trivial image (without copyright, like just black pixels, e.g.) with such a box size to one of our test sets.
> 
> I could do something like that with a piece of JXL Art, since it's easier to visually confirm that the output is rendering correctly. 
I would be happy, if we just had an image like the one attached (8x8 image of black pixels)

![black_square jxl](https://user-images.githubusercontent.com/3491627/172845157-cb12815a-e16a-4e4a-9558-1c5a793135c6.jpg)

Note that the file extension of the image linked here is ".jpg", but it is a JPEG XL file. I only made the file extension "jpg", because otherwise github doesn't allow the upload.

Could you add an appropriate box with the size written in the extended way to this file or a similar one? That would be great!

**Comment by thebombzen** [comment]
Test this image with the patch: [square-extended-size-container.jxl.gz](https://github.com/libjxl/libjxl/files/8872108/square-extended-size-container.jxl.gz)

I prepended the following:
```
00 00 00 0c 4a 58 4c 20  0d 0a 87 0a 00 00 00 14
66 74 79 70 6a 78 6c 20  00 00 00 00 6a 78 6c 20
00 00 00 01 00 00 00 00  00 00 00 48 6a 78 6c 63
```

where `0x48 = 72` and the original image is 56 bytes long, so the size of the jxlc box should be the right size if I'm not mistaken.

**Comment by mo271** [comment]
reopening, in order to add a test

**Comment by mo271** [comment]
Thanks again for bringing up this issue and providing the test image!

**Comment by mo271** [comment]
@Traneptora seems like the order should be 
4 bytes size + 4 bytes type + optional 8 bytes size
and not 
4 bytes size + optional 8 bytes size + 4 bytes type

**Comment by mo271** [comment]
see https://github.com/libjxl/testdata/pull/20

**Comment by Traneptora** [comment]
I just checked the specification, and it appears you are correct and ffmpeg's behavior is incorrect.

```
aligned(8) class Box (unsigned int(32) boxtype,
optional unsigned int(8)[16] extended_type) {
unsigned int(32) size;
unsigned int(32) type = boxtype;
if (size==1) {
unsigned int(64) largesize;
} else if (size==0) {
// box extends to end of file
}
if (boxtype==‘uuid’) {
unsigned int(8)[16] usertype = extended_type;
}
}
```

**Comment by mo271** [comment]
Thanks for checking!
