### ISSUE TITLE
jxl_extra gets built and sits unused if JPEGXL_ENABLE_TOOLS is set to FALSE

### ISSUE THREAD

**Issue by amyspark** [libjxl/libjxl#1483]
**Is your feature request related to a problem? Please describe.**

Currently, libjxl builds the jxl_extras static library even with JPEGXL_ENABLE_TOOLS disabled. In this case, it will look up dependencies such as PNG, GIF, OpenEXR, etc. and build all the associated objects, which will then be left unused.

**Describe the solution you'd like**

jxl_extras should be skipped if no targets use it.

**Describe alternatives you've considered**

At Krita we hotpatch libjxl as follows:

```diff
diff --git a/lib/CMakeLists.txt b/lib/CMakeLists.txt
index a366e51..257f87d 100644
--- a/lib/CMakeLists.txt
+++ b/lib/CMakeLists.txt
@@ -132,7 +132,9 @@ endif()  #!MSVC
 include(jxl.cmake)
 
 # Other libraries outside the core jxl library.
+if(JPEGXL_ENABLE_TOOLS)
 include(jxl_extras.cmake)
+endif()
 include(jxl_threads.cmake)
 
 # Install all the library headers from the source and the generated ones. There

```

**Additional context**

Krita support for libjxl is scheduled for release in 5.1. See [!1363](https://invent.kde.org/graphics/krita/-/merge_requests/1363).

**Comment by mo271** [comment]
Makes sense
