### ISSUE TITLE
Converting DNG to JXL nearly doubles the filesize

### ISSUE THREAD

**Issue by RubenKelevra** [libjxl/libjxl#1492]
**Describe the bug**
I've tried to convert DNG files to JXL via ImageMagick (which I understand uses libjxl).

exiftool shows that the data is in 16 bit depth and RGGB:

<details>

```console
$ exiftool IMG_20220603_144349_0.dng
ExifTool Version Number         : 12.42
File Name                       : IMG_20220603_144349_0.dng
Directory                       : .
File Size                       : 24 MB
File Modification Date/Time     : 2022:06:09 13:14:58+02:00
File Access Date/Time           : 2022:06:09 13:14:58+02:00
File Inode Change Date/Time     : 2022:06:09 22:21:47+02:00
File Permissions                : -rw-r--r--
File Type                       : DNG
File Type Extension             : dng
MIME Type                       : image/x-adobe-dng
Exif Byte Order                 : Little-endian (Intel, II)
Subfile Type                    : Full-resolution image
Image Width                     : 4000
Image Height                    : 3000
Bits Per Sample                 : 16
Compression                     : Uncompressed
Photometric Interpretation      : Color Filter Array
Image Description               : 
Make                            : Xiaomi
Camera Model Name               : M2101K6G
Strip Offsets                   : (Binary data 25621 bytes, use -b option to extract)
Orientation                     : Horizontal (normal)
Samples Per Pixel               : 1
Rows Per Strip                  : 1
Strip Byte Counts               : (Binary data 14999 bytes, use -b option to extract)
X Resolution                    : 72
Y Resolution                    : 72
Planar Configuration            : Chunky
Resolution Unit                 : inches
Software                        : Redmi/sweet_eea/sweet:12/SKQ1.210908.001/V13.0.8.0.SKFEUXM:user/release-keys
Modify Date                     : 2022:06:03 14:43:49
CFA Repeat Pattern Dim          : 2 2
CFA Pattern 2                   : 1 2 0 1
Copyright                       : 
Exposure Time                   : 1/941
F Number                        : 1.9
ISO                             : 50
Date/Time Original              : 2022:06:03 14:43:49
Focal Length                    : 6.0 mm
TIFF-EP Standard ID             : 1 0 0 0
DNG Version                     : 1.4.0.0
DNG Backward Version            : 1.1.0.0
Unique Camera Model             : M2101K6G-Xiaomi-Redmi
CFA Plane Color                 : Red,Green,Blue
CFA Layout                      : Rectangular
Black Level Repeat Dim          : 2 2
Black Level                     : 64 64 64 64
White Level                     : 1023
Default Scale                   : 1 1
Default Crop Origin             : 8 8
Default Crop Size               : 3984 2984
Color Matrix 1                  : 0.6875 -0.09375 -0.0703125 -0.4140625 1.203125 0.171875 -0.0625 0.234375 0.4140625
Color Matrix 2                  : 1.34375 -0.5078125 -0.46875 -0.296875 1.4140625 -0.25 0.0390625 0.1484375 0.5234375
Camera Calibration 1            : 0.6171875 0 0 0 1 0 0 0 0.640625
Camera Calibration 2            : 1 0 0 0 1 0 0 0 1
As Shot Neutral                 : 0.529296875 1 0.5908203125
Baseline Exposure               : 0
Calibration Illuminant 1        : D65
Calibration Illuminant 2        : Standard Light A
Active Area                     : 0 0 3000 4000
Forward Matrix 1                : 0.765625 0.125 0.0703125 0.2734375 0.9296875 -0.203125 -0.0234375 -0.3671875 1.2109375
Forward Matrix 2                : 0.5078125 0.046875 0.40625 0.046875 0.734375 0.21875 -0.1796875 -0.5703125 1.5703125
Opcode List 2                   : GainMap, GainMap, GainMap, GainMap
Noise Profile                   : 9.34903000467e-05 3.209479880749e-07 4.256158549375e-05 2.425648234101e-07 3.40389499548e-05 3.24915177521575e-07
Aperture                        : 1.9
CFA Pattern                     : [Green,Blue][Red,Green]
Image Size                      : 4000x3000
Megapixels                      : 12.0
Shutter Speed                   : 1/941
Focal Length                    : 6.0 mm
Light Value                     : 12.7
```

</details>

So data stored in DNG which gets recompressed to JXL will produce significantly larger files. I think ImageMagick is inflating the DNG file because it does Debayering from 16 bit RGGB to 4 times 16 bit RGB - right?

Is there a "best practice" to convert raw images without any loss in data to JXL? Will cjxl/djxl support DNG import/export eventually?

**To Reproduce**
- Create a DNG
- Convert it with ImageMagick with `-quality 100 -define jxl:effort=7` to jxl
- Get a larger output file than input file

**Expected behavior**
Have a similar or smaller output size than input size and four channel RGGB data

**Screenshots**
Additionally, there seems to be an issue with some information about the raw nature of these pictures getting lost. So Gimp will render them in weird tones instead of doing a raw-import:

Otherwise, the picture looks fine (details retained etc.):

![Screenshot_20220609_223909](https://user-images.githubusercontent.com/614929/172940528-2a73116a-9e6a-490d-9a7d-66a0858f2fc7.jpg)

**Environment**
 - OS: Linux
 - Compiler version: gcc (12.1)
 - CPU type: x86_64
 - cjxl/djxl version string: 

```console
$ cjxl --version
cjxl v0.6.1 a205468b [AVX2,SSE4,SSSE3]
Copyright (c) the JPEG XL Project
$ convert --version
Version: ImageMagick 7.1.0-37 Q16-HDRI x86_64 20104 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (12.1)
```

**Additional context**
File sizes:

```
$ du -h IMG_20220603_144349_0*
23M     IMG_20220603_144349_0.dng
42M     IMG_20220603_144349_0.jxl
27M     IMG_20220603_144349_0_gimp.jxl
```

**Comment by RubenKelevra** [comment]
So with draw I can extract the raw image:

```console
$ dcraw -E -4 IMG_20220603_144349_0.dng
$ du -h IMG_20220603_144349_0.pgm 
23M     IMG_20220603_144349_0.pgm
```

Converting this with ImageMagick or Gimp will give me the following file sizes:

```console
$ convert -quality 100 -define jxl:effort=9 IMG_20220603_144349_0.pgm IMG_20220603_144349_0_draw_imagemagick.jxl
$ du -h *draw*.jxl
700K    IMG_20220603_144349_0_draw_gimp.jxl
4.4M    IMG_20220603_144349_0_draw_imagemagick.jxl

```

So there's a HUGE potential to save DNG files in JXL if there's a way to convert them back for (legacy) software to read. If JXL would save the four layers not as one layer with Bayer pattern but as 4 individual layers for RGGB the compression rate would probably even be higher – or the amount of analyzing to archive the same compression rate significantly lower.

I've attached the jxl files as demo files (not sure why there's such a large difference between them for JXL compression size).

[demo.zip](https://github.com/libjxl/libjxl/files/8874274/demo.zip)

**Comment by RubenKelevra** [comment]
Importing the Image in Gimp, converting it down to 16-bit integer and saving it Lossless in JXL does however take 21 MByte of diskspace. So there would be a huge benefit if the images would be saved in Bayer-RAW instead of debayer them just to save the interpolation results.

**Comment by jonsneyers** [comment]
My idea was to put R, avgG, B in the main image, and G1-G2 in an extra channel. Compression-wise, that should work quite well. The main challenges are:

- preserving the metadata, in particular the Bayer pattern that was used
- making the jxl look like a reasonable preview (it's OK if it's half resolution because no interpolation gets done and G1-G2 gets ignored, but it would be nice if the colors are not completely wrong due to different ranges for R,G,B)
- making tooling that can convert raw to jxl and back

**Comment by RubenKelevra** [comment]
Well, not sure that extra work with the channels is really necessary. Just put each of them in a single layer and have the regular compression figure this out. 🤷‍♂️

Since DNG is pretty well documented I guess the metadata could just be fetched as "binary" and put into the container, which then could just be read like if it's a DNG in case an application what's to read it. 

The metadata do contain the info what kind of Bayer pattern was used (see exif tool dump).

As the file definition itself is just something like "uint16 values" I think the conversation should be fairly easy.

DNG can include a JPG image for preview purposes, which is kinda already "developed".

JXL should ideally store this too, to allow a preview without specialised software.

---

In theory dcraw can easily create "developed" picture in low resolution for preview purposes and JXL could save this in an additional layer for preview :)

**Comment by kmilos** [comment]
IMHO this is a wrong way to go about compressing raw data.

DNG is a relatively nice and well documented raw container already, with decent support across the apps to manage the metadata and color profiles. The metadata problem is bigger than it seems because of undocumented camera vendor MakerNotes that are sometimes not trivial to preserve.

Ideally what you want is to lobby and add JXL as a codec to DNG (just like JPEG, LJPEG92 and deflate are now), not the other way around.

Or just start doing it until it gets wide adoption. GoPro have done this already: .GPR files are nothing but a DNG w/ the VC5 codec inside.

You can try it for independent channels if you really want to keep the raw (and potentially lossless), or after interpolation/demosaicing w/ PhotometricInterpretation of 34892 (LinearRaw) for the best compression I guess.

**Comment by RubenKelevra** [comment]
Hey @kmilos, I really don't want to create yet another raw format - I was just curious about the possibility to compress abitary raw channels with JXL, as @jonsneyers has had thrown around that idea. 

I was curious if ImageMagick would "magically" make this happen. But ImageMagick will just develop the image like for other formats (aka BMP/PNG/JPG) just with higher bit depth, by debayer it - what's not what I wanted. 

Said that, I think there's kind of an advantage to use the same compression technology for "regular pictures" (aka JXL) and raw data, as this would allow manufacturers to create optimized silicon for both tasks.

As shown JXL is pretty great at compressing these kind of data - even with the weird bayer pattern in the image.

I wouldn't really mind if the container keeps beeing DNG - if this makes more sense. :) 

We might want to split the JXL/RAW/DNG/Lossless compression of sensor data into a different ticket. I'll create a dedicated one for this. 

---

@jonsneyers going forward with this topic in general, I think the real issue here is that ImageMagick do not switch to lossless modular when `-quality 100` ks set by the user.

Can you have a look at what ImageMagick outputs when just `-quality 100` and a `.jxl` as output is selected? I suspect that there's a bug there somewhere given the large size differences of the files.

**Comment by kmilos** [comment]
> I was curious if ImageMagick would "magically" make this happen.

Does it make it happen for any other raw -> foo output format conversion? Why would you expect it do something differently for JXL?

AFAIK, when it sees raw data, ImageMagick/GraphicsMagick calls the dcraw delegate, does default (and relatively simplified) processing to sRGB and then feeds it to the output codec. Nothing wrong w/ this, and I don't think exceptions should be introduced. If you want more out of your raw data, use a special purpose app/tool.

Btw, you could try reading existing and createing a new DNG w/ embedded JXL payload prototype perhaps easily in Python w/ excellent `tifffile` + `imagecodecs` packages (the former is for DNG/TIFF support, the former, well for different codecs including all the DNG supported ones, and also JXL as of recently).

**Comment by RubenKelevra** [comment]
@kmilos well, if I don't specify any conversion it's just weird for me that ImageMagick assumes that I want to develop the Digital RAW when converting to a format which – can technically store the same data as DNG.

I mean, if DNG would be supported as "writing", would you expect that if I ask it to convert NEF to DNG that it will do some processing?

My expectation was, that conversions are lossless if the target format is lossless, unless otherwise specified.

**Comment by kmilos** [comment]
> if I don't specify any processing it's just weird for me that ImageMagick assumes that I want to develop the Digital RAW when converting to a format which – can technically store the same data as DNG

I don't feel the original design goal of ImageMagick was to support all possible scenarios and transformations for raw camera data (hence the reliance on external delegates like dcraw and LibRaw as a "best effort" to at least give you some workable RGB image), but that is a conversation you should have over there.

**Comment by TPS** [comment]
> DNG can now be compressed internally by Jpeg-XL, e.g. by this website:
> 
> https://tinydng.com/
> 
> So it would be nice if there's a tool for this where we can do this on the console. Like is that a thing the Jpeg-XL could support on it's own?

Author of site is @qdwang, per @qdwang's, per https://github.com/Beep6581/RawTherapee/issues/7131#issue-2410880064, & site says they're working on a command-line version, so maybe have insight here?

**Comment by RubenKelevra** [comment]
@TPS ah, didn't saw that. That's great news :)

**Comment by TPS** [comment]
TinyDNG CL was released almost 2wa @ https://tinydng.com/, annoyingly only in the site header where the tease was before.

**Comment by RubenKelevra** [comment]
Thanks! Funny enough it's already in the AUR. People using Arch are lit :)

**Comment by RubenKelevra** [comment]
So I guess this can be closed then.

**Comment by TPS** [comment]
> So I guess this can be closed then.

Depends on…

@jonsneyers Is there a plan to have any kind of support of DNG-like files in libjxl?

@RubenKelevra If so, maybe not close.  Else, go for it, imho.

**Comment by RubenKelevra** [comment]
Yeah, makes sense.
