### ISSUE TITLE
djxl: Color Encoding check fails when decoding grayscale animated JXL to APNG

### ISSUE THREAD

**Issue by thebombzen** [libjxl/libjxl#1517]
**Describe the bug**
When decoding a grayscale animated JXL to APNG, `djxl` reports the following line, and then crashes with SIGILL:
```
./lib/jxl/image_bundle.cc:34: JXL_CHECK: metadata_->color_encoding.IsGray() == c_current.IsGray()
Illegal instruction (core dumped)
```
If the same file is decoded but no APNG is created, instead the output is discarded, then djxl exits successfully and gracefully after "Decoded to pixels."

**To Reproduce**
Take the attached JXL file and run `djxl test.jxl test.apng` and compare the output with `djxl test.jxl`. 

**Expected behavior**
djxl should write the animated PNG without crashing.

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: gcc 12.1.0
 - cjxl/djxl version string: `JPEG XL decoder v0.7.0 ec093557 [AVX2]`

**Full Log**
```
$ djxl test.jxl
JPEG XL decoder v0.7.0 ec093557 [AVX2]
Read 79 compressed bytes.
No output file specified.
Decoding will be performed, but the result will be discarded.
Decoded to pixels.
64 x 64, 3.54 MP/s [3.54, 3.54], 1 reps, 4 threads.
Allocations: 413 (max bytes in use: 3.873179E+06)

$ djxl test.jxl test.apng
JPEG XL decoder v0.7.0 ec093557 [AVX2]
Read 79 compressed bytes.
Decoded to pixels.
./lib/jxl/image_bundle.cc:34: JXL_CHECK: metadata_->color_encoding.IsGray() == c_current.IsGray()
Illegal instruction (core dumped)
```

**Sample**
It's attached as a `.jxl.gz` because github doesn't allow `.jxl` file extensions. Just `gunzip` it before testing.
[test.jxl.gz](https://github.com/libjxl/libjxl/files/8933880/test.jxl.gz)

**Comment by mo271** [comment]
TODO: also check with `djxl_ng`

**Comment by thebombzen** [comment]
@mo271 I checked djxl_ng and as it doesn't have the feature to decode to pixels and discard, I couldn't test that. But when I tested it with `djxl_ng test.jxl test.apng` it segfaulted. Here's the valgrind log: https://buzo.us/P.log

**Comment by mo271** [comment]
I played around a bit and right now, `djxl_ng` didn't yet accept the `.apng` extension, but it should already work fine (and actually decode to a animated png) when you run
```
djxl test.jxl test.png
```
#1530 allows compressing with the `apng` extension.
#1529 makes sure that it fails more gracefully when trying to decode to unknown extensions (of which `.apng` should not be one..)

Thanks for reporting this! Let's keep the issue open, so we can look at what the problem with `djxl` (as supposed to `djxl_ng`) is.

**Comment by szabadka** [comment]
We have moved `djxl_ng` to `djxl` now, and I have tested it and it seems to work now. Could you verify that it is fixed?

**Comment by thebombzen** [comment]
It's working now with the new `djxl`.
