### ISSUE TITLE
undefined behavior

### ISSUE THREAD

**Issue by maddin200** [libjxl/libjxl#1520]
/lib/jxl/dec_huffman.cc line 73
Maybe here is a shift of a negative value possible. 
Code:

     old_repeat = repeat;
      if (repeat > 0) {
        repeat -= 2;
        repeat <<= extra_bits; // shift if repeat == -1
      }

**Comment by szabadka** [comment]
The next line is 
```
repeat += (int)br->ReadBits(extra_bits) + 3;
```

```repeat``` can never be 1, or 2, since it starts from 0, then it is at least 3, and from then on it can only increase until it is set to zero again. Note that ```extra_bits``` is at least 2, therefore ```(repeat - 2) << extra_bits``` is greater than ```repeat```.
