### ISSUE TITLE
Build error in MSVC (error C2146: syntax error: missing ';' before identifier 'JxlDecoderStatus')

### ISSUE THREAD

**Issue by jobbautista9** [libjxl/libjxl#1525]
**Describe the bug**
While building [this PR](https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1928) which will include JPEG-XL support to [Pale Moon's](http://www.palemoon.org/) platform, the project owner who is on Windows found that it fails to build with the MSVC compiler, which we use to build Pale Moon on Windows. Here's his output when the error occurred:

    0:32.95 c:\mozdev\obj-pm-x64-unstable\dist\include\jxl/decode.h(861): error C2146: syntax error: missing ';' before ide
    ntifier 'JxlDecoderStatus'
    0:32.95
    0:32.96 In the directory  /c/mozdev/obj-pm-x64-unstable/image
    0:32.96 The following command failed to execute properly:
    0:32.96 c:/mozdev/obj-pm-x64-unstable/_virtualenv/Scripts/python.exe -m mozbuild.action.cl c:/VS2015/VC/BIN/amd64/cl.EX
    E -FoUnified_cpp_image0.obj -c -Ic:/mozdev/obj-pm-x64-unstable/dist/stl_wrappers -DNDEBUG=1 -DTRIMMED=1 -DWIN32_LEAN_AND
    _MEAN -D_WIN32 -DWIN32 -D_CRT_RAND_S -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DOS_WIN=1 -D_UNICODE -DCHROMIUM_BUILD -DU_STATI
    C_IMPLEMENTATION -DUNICODE -D_WINDOWS -D_SECURE_ATL -DCOMPILER_MSVC -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_MOZGLUE -DMOZIL
    LA_INTERNAL_API -DIMPL_LIBXUL -Ic:/mozdev/PaleMoon/platform/image -Ic:/mozdev/obj-pm-x64-unstable/image -Ic:/mozdev/obj-
    pm-x64-unstable/ipc/ipdl/_ipdlheaders -Ic:/mozdev/PaleMoon/platform/ipc/chromium/src -Ic:/mozdev/PaleMoon/platform/ipc/g
    lue -Ic:/mozdev/PaleMoon/platform/dom/base -Ic:/mozdev/PaleMoon/platform/dom/svg -Ic:/mozdev/PaleMoon/platform/gfx/2d -I
    c:/mozdev/PaleMoon/platform/image/decoders -Ic:/mozdev/PaleMoon/platform/layout/svg -Ic:/mozdev/PaleMoon/platform/netwer
    k/base -Ic:/mozdev/PaleMoon/platform/xpcom/threads -Ic:/mozdev/PaleMoon/platform/gfx/skia -Ic:/mozdev/PaleMoon/platform/
    gfx/skia/skia/include/config -Ic:/mozdev/PaleMoon/platform/gfx/skia/skia/include/core -Ic:/mozdev/PaleMoon/platform/gfx/
    skia/skia/include/gpu -Ic:/mozdev/PaleMoon/platform/gfx/skia/skia/include/utils -Ic:/mozdev/obj-pm-x64-unstable/dist/inc
    lude -Ic:/mozdev/obj-pm-x64-unstable/dist/include/nspr -Ic:/mozdev/obj-pm-x64-unstable/dist/include/nss -MD -FI c:/mozde
    v/obj-pm-x64-unstable/mozilla-config.h -DMOZILLA_CLIENT -TP -nologo -wd5026 -wd5027 -Zc:sizedDealloc- -wd4752 -wd4091 -w
    d4577 -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -utf-8 -FS -Gw -wd4251 -wd4244 -wd4267 -wd4345 -wd4351 -wd4800 -wd4595 -we4
    553 -GR- -Zi -O2 -GTs -GS- -favor:AMD64 -Oy -Ic:/mozdev/obj-pm-x64-unstable/dist/include/cairo -Fdgenerated.pdb c:/mozde
    v/obj-pm-x64-unstable/image/Unified_cpp_image0.cpp
    0:32.97 mozmake.EXE[5]: *** [c:/mozdev/PaleMoon/platform/config/rules.mk;886: Unified_cpp_image0.obj] Error 1
    0:32.98 mozmake.EXE[4]: *** [c:/mozdev/PaleMoon/platform/config/recurse.mk;71: image/target] Error 2
    0:32.98 mozmake.EXE[4]: *** Waiting for unfinished jobs....

**To Reproduce**
Refer to [our developer instructions for Windows](http://developer.palemoon.org/build/windows/). But before building: after cloning the UXP platform, pull from [my UXP fork](https://repo.palemoon.org/jobbautista9/UXP) and checkout the `1769-take2` branch. Add `--enable-jxl` to your `.mozconfig` before running `./mach build`.

**Expected behavior**
It should build fine.

**Screenshots**
N/A

**Environment**
 - OS: Windows
 - Compiler version: MSVC 2015
 - CPU type: x86_64
 - cjxl/djxl version string: N/A(?)

**Additional context**
We are building on the tree of commit 192ddd90fdf0c69cd1db1c8d7850db036dd87f4b to match Mozilla's implementation, and (just in case this is important) we're also using 0.17.0 for highway instead of 0.15.0 which Mozilla uses. Also pinging @wolfbeast who's the one who ran into the build issue here.

**Comment by novomesk** [comment]
My static build of libjxl (without tools) using MSVC works:

https://ci.appveyor.com/project/novomesk/qt-jpegxl-image-plugin/builds/43938920

**Comment by wolfbeast** [comment]
The problem seems to be that since #1337, `JXL_DEPRECATED` is being used and defined as:
```C++
#define JXL_DEPRECATED __attribute__((__deprecated__)) 
```
in `types.h`
`__deprecated__` is not defined as an attribute in MSVC 14 which we use (MSVC 2019 might have added this as a compat consideration?), which ultimately causes the error in the initial comment on this issue by having an unknown type definition down the line. It _is_ probably available in gcc. It seems someone else also ran into this issue too with certain versions of clang in #1388 -- using the standard `[[deprecated]]` _does_ seem to solve this for our compiler.

**Comment by mo271** [comment]
So in https://github.com/libjxl/libjxl/blob/b7961e1318634a95c7d689ec340dbad8a42d4ed4/lib/jxl.cmake#L466 
the file `jxl_export.h` is generated and for I guess it is wrongly defined as 
```
#ifndef JXL_DEPRECATED
#  define JXL_DEPRECATED __attribute__ ((__deprecated__))
#endif
```
in MSVC 14. Seems like cmake is working on a fix for this:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7009/diffs#699260029b855a8b79dd6a4b4cf2508017e6006d_0_25

As a workaround, I suggest to make your own definition of  `JXL_DEPRECATED` as something that MSVC understand until cmake has fixed the problem.
Would that work?

**Comment by wolfbeast** [comment]
Apologies, we're actually using MSVC 19, not 14. Note that v19 is VS 2015, not 2019 :P Just to keep things confusing for everyone (thanks, Microsoft)
But yes, `jxl_export.h` is indeed where this is defined wrong. I've attempted to simply define JXL_DEPRECATED in our build system file but it doesn't seem to be picked up by cmake and it simply spit out the same thing again resulting in build failures.
I'm not too familiar with cmake myself; is there a possibility to edit the .cmake files locally in the interim so it avoids this problem?

**Comment by mo271** [comment]
Possibly a solution might be to have your own `libjxl/include/jxl/jxl_export.h` with a content like this:

```
#ifndef JXL_EXPORT_H
#define JXL_EXPORT_H

#define JXL_EXPORT
#define JXL_DEPRECATED [[deprecated]]

#endif /* JXL_EXPORT_H */
```

**Comment by jobbautista9** [comment]
Yeah, that's what we did in our end, and it builds both in GCC 9 and MSVC. Unfortunately we also use Clang for Mac, and if I get a confirmation from the Mac maintainer that it breaks there, I will ifdef it instead in my PR.

**Comment by mo271** [comment]
Let's close this here then and keep #1388 open. 

Thank you for the report!

Re highway trouble: consider opening an issue with the concrete problem at https://github.com/google/highway!
