### ISSUE TITLE
Build error JPEGXL_EMSCRIPTEN=OFF

### ISSUE THREAD

**Issue by shinchiro** [libjxl/libjxl#1564]
Build failed with `-DJPEGXL_EMSCRIPTEN=OFF`. The compiler throw
`x86_64-w64-mingw32/bin/ld: cannot find -ljxl_extras-static: No such file or directory`

when I checked commit fd4028d

https://github.com/libjxl/libjxl/blob/9eaaebf6cd93c6c694811baf38e14f66aa0b1922/tools/CMakeLists.txt#L424-L431

The `else()` block should not compile `jxl_emcc `. Probably copy paste error

**Comment by kleisauke** [comment]
I just opened PR https://github.com/libjxl/libjxl/pull/1565 for this.
