### ISSUE TITLE
libjxl's pkgconfig checks fail on macos, needs  -lstdc++

### ISSUE THREAD

**Issue by Vargol** [libjxl/libjxl#1648]
**Describe the bug**
Attempting to build ffmpeg 5.1 with libjxl support fails during the configuration of ffmpeg
due to failing pkgconfig check for libjxl>=0.7.0, checking the config.log in rebuild it show it actually fails with
unknown symbol errors referring to the standard C++ libraries. 
It might be clang issue rather then a macOS issue.

**It can be fixed by adding  -lstdc++to the Libs.private section of both libjxl.pc and libjxl_threads.pc**

**To Reproduce**
build ffmpeg with libjxl support

libjxl cmake invocation...

  cmake -DCMAKE_INSTALL_PREFIX:PATH=$3 -DINSTALL_PKGCONFIG_DIR=$3/lib/pkgconfig -DENABLE_SHARED=NO -DBUILD_TESTING=OFF -DJPEGXL_STATIC=YES \
        -DJPEGXL_FORCE_SYSTEM_BROTLI=YES -DJPEGXL_FORCE_SYSTEM_HWY=YES -DJPEGXL_FORCE_NEON=YES \
        -DJPEGXL_ENABLE_MANPAGES=NO -DJPEGXL_ENABLE_BENCHMARK=NO -DJPEGXL_ENABLE_BENCHMARK=NO -DJPEGXL_ENABLE_EXAMPLES=NO \
        -DJPEGXL_ENABLE_SJPEG=NO -DJPEGXL_ENABLE_OPENEXR=NO \
        -DJPEGXL_ENABLE_TOOLS=NO \
        -DJPEGXL_ENABLE_VIEWERS=NO \
        -DJPEGXL_ENABLE_SKCMS=NO \
        ../${SOFTWARE}

**Expected behavior**
libjxl pkgconfig checks are successful, and ffmpeg builds successfully

**Screenshots**
I'll attach logs later, but I need to unfix it first and recompile, and transfer them from my build "server"

**Environment**
 - OS: macOS 12.4
 - Compiler version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
 - CPU type: ARM64
 - cjxl/djxl version string: not build the tools, building from main, git clone https://github.com/libjxl/libjxl.git

**Comment by Vargol** [comment]
build error
cat build-ffmpeg.log 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0  8689k      0  0:00:01  0:00:01 --:--:-- 8705k
ERROR: libjxl >= 0.7.0 not found using pkg-config


from config log

gcc -L/Users/davidburnett/SSD/Source/ffmpeg/build-ffmpeg/tool/lib -I/Users/davidburnett/SSD/Source/ffmpeg/build-ffmpeg/tool/include -Wl,-dynamic,-search_paths_first -DHWY_STATIC_DEFINE -I/Users/davidburnett/SSD/Source/ffmpeg/build-ffmpeg/tool/include -L/Users/davidburnett/SSD/Source/ffmpeg/build-ffmpeg/tool/lib -o /var/folders/mq/w85wcgsx58g9xjz_66mj8bk40000gn/T//ffconf.u7vBYTlT/test /var/folders/mq/w85wcgsx58g9xjz_66mj8bk40000gn/T//ffconf.u7vBYTlT/test.o -ljxl -lm -lhwy -lbrotlienc -lbrotlidec -lbrotlicommon -llcms2 -lm -lpthread
Undefined symbols for architecture arm64:
  "std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const", referenced from:
      std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libjxl.a(frame_header.cc.o)
      std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libjxl.a(image_metadata.cc.o)
      std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libjxl.a(modular_image.cc.o)
      std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libjxl.a(dec_modular.cc.o)
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      std::__1::vector<bool, std::__1::allocator<bool> >::__vallocate(unsigned long) in libjxl.a(dec_context_map.cc.o)
  "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
      std::__1::ctype<char> con

**Comment by kleisauke** [comment]
AFAIK (libvips' OSS-Fuzz integration [had a similar issue](https://github.com/google/oss-fuzz/blob/0d7e1b655f92e4d4c1d27a7658b0560d22351607/projects/libvips/build.sh#L163-L164)), this issue only manifests when building static libraries, so a easy workaround is to remove the `-DJPEGXL_STATIC=YES` CMake option.

Note that `-lstdc++` / `libstdc++` is specific to the GNU toolchain, when using Clang, you can optionally use `libc++` instead, in which case the `Libs.private` would contain `-lc++` instead. So, hardcoding the C++ runtime library is not a good option I think.

**Comment by Vargol** [comment]
Hi, my issue with  `-DJPEGXL_STATIC=YES` CMake option is that  I require a static build of libjxl as I'm building a fully static build of ffmpeg.

I'll try -lc++, so whilst I appreciate that maybe which one  shouldn't be hard coded the pkg-config files for libjxl should have an appropriate standard c++ library in when required.

**Comment by mo271** [comment]
> I'll try -lc++, so whilst I appreciate that maybe which one shouldn't be hard coded the pkg-config files for libjxl should have an appropriate standard c++ library in when required.

Did adding `-lc++` work for you?

**Comment by Vargol** [comment]
Ooops, sorry went ofon holiday and totally forgot about this when I came back.

Yes, I've added a line in my build script to sed -lc++ into the *.pc files for libjxl

e.g.

Libs.private: -lm -lc++

and ffmpeg builds correctly.

**Comment by mo271** [comment]
Seems to be fixed, please reopen if the problem is still there
