### ISSUE TITLE
0.6.1: build fails with libhwy > 0.15.0

### ISSUE THREAD

**Issue by ethindp** [libjxl/libjxl#1659]
**Describe the bug**
When building with libhwy > 0.15.0, the build fails with a variety of error messages (.

**To Reproduce**
Just build with libhwy > 0.15.0. GCC will emit a bunch of error messages related to entities not being found (I suspect they've been moved around).

**Expected behavior**
libjxl should build fine.

**Screenshots**
N/A (I have a build log but its insanely huge).

**Environment**
 - OS: NixOS 22.05, but this also occurs on Darwin platforms.
 - Compiler version: GCC 11.3.0 (Apple Clang as well)
 - CPU type: x86_64
 - cjxl/djxl version string: `JPEG XL encoder v0.6.1 [AVX2,SSE4,SSSE3,Scalar]`

**Additional context**

**Comment by thebombzen** [comment]
This can be fixed by building a version of libjxl that is not ancient.

**Comment by ethindp** [comment]
@thebombzen This version is not ancient. According to the releases page, version 0.6.1 is the latest version. And Arch Linux's packages repository also clearly states that version 0.6.1-3 is the latest version. So, if version 0.6.1 is not, in fact, the latest version, where is the latest version, exactly? I would build from master if it weren't for reasons that should be apparent.

**Comment by thebombzen** [comment]
0.6.1 was released almost a year ago and predates highway 0.15.0. If you want to build 0.6.1, then build it against highway 0.15.0, which is also the most recent version packaged in the arch repositories. 

What are you exactly suggesting be done? 0.7 has a release candidate and it builds against highway 1.0.0. What bug are you suggesting be fixed that isn't already fixed?

**Comment by mo271** [comment]
I hope this can be closed when `0.7` is released...

**Comment by mo271** [comment]
I assume this is now working with version 0.7.0
