### ISSUE TITLE
add tags for reasonable `git describe` output

### ISSUE THREAD

**Issue by Optiligence** [libjxl/libjxl#1665]
**Is your feature request related to a problem? Please describe.**
`git describe --tags main` yields `v0.3.7-1197-g40460f72`

**Describe the solution you'd like**
add tags at the branch-off points in master
e.g. tag `20cccbf646158cb128d68db20d12f93d1fb9b6a1` as `v0.6.x`
resulting in `git describe --tags main` yielding `v0.6.x-794-g40460f72`

**Describe alternatives you've considered**
manually traversing the commit tree to find the closest tag
although possible, that seems pretty ridiculous

**Additional context**
generic versioning of devel packages

**Comment by mo271** [comment]
Thanks for the suggestion!
I think it might be a bit confusing to tag the branch-off points with the same name as the branches. Can we avoid having a branch with the name `v0.6.x` and a branch-off point with the? Not sure what good a good name would be for that. How are other projects tagging their branch-off points?


The ridiculous alternative might be something like
```
echo $(git describe --tags $(git rev-list --tags --max-count=1))-$(git rev-list --count $(git merge-base $(git rev-list --tags --max-count=1) HEAD)..HEAD)-g$(git rev-parse --short HEAD)
```
which gives
```
v0.6.1-794-g40460f72
```

**Comment by mo271** [comment]
any ideas, @eustas?

**Comment by eustas** [comment]
The problem grows from our release procedure -- first we make branch, and after this we "release" -- actually add tag.
Thus, no tags are associated with "main" branch.

Current agreement is we use "vA.B.x" as branch name, and "vA.B" as a first release (tag) on that branch.
We could use "vA.B" as a branch-point tag, and "vA.B.0" as first release tag...

**Comment by mo271** [comment]
> 



> The problem grows from our release procedure -- first we make branch, and after this we "release" -- actually add tag. Thus, no tags are associated with "main" branch.
> 
> Current agreement is we use "vA.B.x" as branch name, and "vA.B" as a first release (tag) on that branch. We could use "vA.B" as a branch-point tag, and "vA.B.0" as first release tag...

Might be a bit confusing to have a tag `v0.7` which then might be different from `v0.7.0`

**Comment by eustas** [comment]
Then it could be something like `v0.7-base`

**Comment by mo271** [comment]
Sounds good, I will add those tags then....

**Comment by mo271** [comment]
ok, I checked again and up to `v0.3.7` the history was linear and we don't need to tag the branch off points after I propose to add the branch off points like this:
```
d5ab3c6caef17c1db6fd90c4b00b5845a0ac8339 refs/tags/v0.1
739e6cd1305fdec5acfa47ad414189b3d3ecb6a4 refs/tags/v0.1.1
31c71b0f61123a40789b0b8f54feb70e5995420e refs/tags/v0.2
35ad23dd611199ed63a8c198a7e6a2dab40ec0b8 refs/tags/v0.3
ef3f7a6254e09e6672d2f071b3f4da07c0436dbb refs/tags/v0.3.1
e2b1e60f5fda02f5fb395b0b6113f64d33cbb91d refs/tags/v0.3.2
65825c8629f181dbe8bdd432b15576735af29701 refs/tags/v0.3.3
f2aeba7e3d091314eaccb64748791e1f4e2cf0a6 refs/tags/v0.3.4
f071e6c7d25984df04f4dc629646c3b0cca57de9 refs/tags/v0.3.5
c2d18d95df67fe167e495d22c9876d33438d4055 refs/tags/v0.3.6
9e9bce86164dc4d01c39eeeb3404d6aed85137b2 refs/tags/v0.3.7
c4e0877f93506e880cd922f6c94644d79ae9adff refs/tags/v0.5
0405f91e9480a3ed3aecb061dd40adbe48a21ac2 refs/tags/v0.5-base
25ef9145273eb5fe3db04e196327c77e404308d8 refs/tags/v0.6
20cccbf646158cb128d68db20d12f93d1fb9b6a1 refs/tags/v0.6-base
a205468bc5d3a353fb15dae2398a101dff52f2d3 refs/tags/v0.6.1
```
Basically we only need to add two tags, namely `v0.5-base` and `v0.6-base`. If you approve, @eustas, I will push those to origin.

**Comment by eustas** [comment]
LGTM

**Comment by mo271** [comment]
Done!
Now 
`git describe --tags` on current main gives
```
v0.6-base-784-gf4ae326c
```
I hope this helps, @Optiligence! Please re-open if there still is an issue

**Comment by Optiligence** [comment]
nice, thanks a lot!
