### ISSUE TITLE
New cjxl seems to ignore Exif orientation

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#1667]
Hello,
I encoded following picture using old and new cjxl.
When viewing the JXL output in Google Chrome, the old one has correct orientation but new one is not rotated.
![IMG_20220725_152349](https://user-images.githubusercontent.com/52529860/182201791-2ab098fe-74e5-472f-9dbf-4e694f2a8725.jpg)

Encoded files:
[old.zip](https://github.com/libjxl/libjxl/files/9235787/old.zip)
[new.zip](https://github.com/libjxl/libjxl/files/9235790/new.zip)

**Comment by mo271** [comment]
Thanks for finding this! It really seems like the new cjxl is completely ignoring the exif metadata. I will look into this and plan to fix this this week. 
https://github.com/libjxl/libjxl/blob/79293824dcdb91f1f934244b6f48e83bfed97588/lib/jxl/exif.cc#L52
never gets called.

**Comment by mo271** [comment]
Please let me know if there is still a problem!

**Comment by novomesk** [comment]
Thanks, it works for me.
