### ISSUE TITLE
Spelling mistake in cjxl "modular lossy palette" flag

### ISSUE THREAD

**Issue by TheDecryptor** [libjxl/libjxl#1668]
**Describe the bug**
Small and simple issue, the cjxl flag for enabling the lossy palette is misspelt [here](https://github.com/libjxl/libjxl/blob/79293824dcdb91f1f934244b6f48e83bfed97588/tools/cjxl_main.cc#L353). It's `moular_lossy_palette` instead of `modular_lossy_palette`.

**Comment by mo271** [comment]
Thanks for opening an issue for this!
