### ISSUE TITLE
MSYS2 build fails to detect architecture (and number of threads)

### ISSUE THREAD

**Issue by eustas** [libjxl/libjxl#168]
```
JPEG XL decoder v0.3.7 [AVX2,SSE4,Scalar]
/C/msys64/home/eustas/clients/libjxl/tools/cpu/cpu.cc:415: JXL_FAILURE: Unable to detect processor topology
Failed to choose default num_threads; you can avoid this error by specifying a --num_threads N argument.
```

**Comment by eustas** [comment]
@jan-wassenberg any thoughts what to check?

**Comment by veluca93** [comment]
We could default to `std::thread::hardware_concurrency()` when that happens (or perhaps always)

**Comment by jan-wassenberg** [comment]
Probably SetThreadAffinity failing, breakpoint there?

That will also happen if JXL_DISABLE_PINNING, which is not good.
(To disable pinning, we should remove the call sites of PinThreadToCPU, not the one in cpu.cc)
