### ISSUE TITLE
DjxlFuzzerTestInstantiation/DjxlFuzzerTest.TestOne/ status ?

### ISSUE THREAD

**Issue by malaterre** [libjxl/libjxl#1692]
**Describe the bug**

I'd like to run 'make test' without error. make test return the following:

The following tests FAILED:
	2522 - DjxlFuzzerTestInstantiation/DjxlFuzzerTest.TestOne/4546077333782528 (ILLEGAL)
<snip>
	2563 - DjxlFuzzerTestInstantiation/DjxlFuzzerTest.TestOne/6735607318052864 (ILLEGAL)
	2564 - DjxlFuzzerTestInstantiation/DjxlFuzzerTest.TestOne/6737321070821376 (ILLEGAL)
	2565 - DjxlFuzzerTestInstantiation/DjxlFuzzerTest.TestOne/6748486320652288 (ILLEGAL)

**To Reproduce**

download v0.7rc and build on amd64 using gcc-12.

**Expected behavior**

I'd like to run 'make test' without error.

**Screenshots**

* https://buildd.debian.org/status/fetch.php?pkg=jpeg-xl&arch=amd64&ver=0.7.0%7Egit20220805.980c90f-1&stamp=1660127268&raw=0

**Environment**
 - OS: Linux/Debian/sid
 - Compiler version: gcc-12
 - CPU type: x86_64
 - cjxl/djxl version string: v0.7rc

**Comment by mo271** [comment]
Those failing tests seems to come from https://github.com/libjxl/libjxl/pull/1589

**Comment by malaterre** [comment]
@mo271 if the tests is supposed to always fail, simply mark it so:

```
set_tests_properties(always_failing_test_name PROPERTIES WILL_FAIL TRUE)
```

**Comment by szabadka** [comment]
Could you be using an older version of testdata? It seems that all of those tests fail when attempting to read the fuzzer test case from testdata/oss-fuzz

**Comment by malaterre** [comment]
@szabadka Here is what log reveal:

```
Get:162 https://deb.debian.org/debian unstable/main amd64 libjxl-testdata all 0.0~git20220711.d81acac-1 [24.9 MB]
```

Which seems to be latest git commit:

* https://github.com/libjxl/testdata/commits/main

Also:

```
$ dget -u http://deb.debian.org/debian/pool/main/libj/libjxl-testdata/libjxl-testdata_0.0~git20220711.d81acac-1.dsc
$ cd libjxl-testdata-0.0\~git20220711.d81acac
$ sha1sum ./oss-fuzz/clusterfuzz-testcase-minimized-djxl_fuzzer-5914266367557632
925c24f2809d2109452fcc3d730742589bde32bb  ./oss-fuzz/clusterfuzz-testcase-minimized-djxl_fuzzer-5914266367557632
```

is that ok ?

ref:
* https://buildd.debian.org/status/fetch.php?pkg=jpeg-xl&arch=amd64&ver=0.7.0%7Egit20220805.980c90f-1&stamp=1660127268&raw=0

**Comment by malaterre** [comment]
ouch !

```
Testing oss-fuzz/clusterfuzz-testcase-minimized-djxl_fuzzer-5914266367557632
./lib/jxl/base/file_io.h:81: JXL_FAILURE: Failed to open file for reading: /usr/share/libjxl-testdata/oss-fuzz/clusterfuzz-testcase-minimized-djxl_fuzzer-5914266367557632
./lib/jxl/testdata.h:22: JXL_CHECK: ReadFile(full_path, &data)
```

I did not pay attention that `SIGILL, Illegal instruction.` was a hint to indicate a missing file. Will fix the Debian package ASAP.

Sorry for the noise, will be more careful next time.
