### ISSUE TITLE
Windows static build seems to be dynamic

### ISSUE THREAD

**Issue by A-Conrath** [libjxl/libjxl#1694]
**Describe the bug**
Since 2022-07-18 the automatic builds on "https://artifacts.lucaversari.it/libjxl/libjxl/" for windows static are not executable anymore.
Some not included dll's like brotli are requestet.
Also the file size of the exe is smaler since then.

**To Reproduce**
Start exe on winodws system without any parameter and you get the dll requestes

**Expected behavior**
Like last working version "v0.7.0 9df69ef [AVX2,SSE4,SSSE3,Emu128]"

**Comment by kylxbn** [comment]
I apologize if "me too" is forbidden here. But I have experienced the same problem when I tried to use the v0.7 release candidate Windows builds. Windows complained that `brotlidec.dll` and `brotlienc.dll` were not found and refuses to run `cjxl.exe`, so I guess I can verify that the problem exists.

**Comment by eustas** [comment]
Hello. Thanks for the report. We already know how to fix it, and hopefully will solve the problem on Monday =)

**Comment by suphamster** [comment]
It's strage but for me "brotli*.dll" error was only in x86 (for Windows) version https://github.com/libjxl/libjxl/actions/runs/2847839309 (downloaded it there) but in x64 (for Windows) build encoding and decoding worked fine without 'em.

**Comment by suphamster** [comment]
It wasn't fixed for me, at least this x86 build https://github.com/libjxl/libjxl/actions/runs/2863241551 still asks for "brotli*.dll".

**Comment by eustas** [comment]
Sorry. Indeed, brotli is still not shipped. Investigating.

**Comment by eustas** [comment]
Well, the ongoing fix won't do the build completely static, rather it will ship brotli dlls...
Have to discuss if we want completely static builds...

**Comment by kleisauke** [comment]
Commit https://github.com/google/brotli/commit/641bec0e30bea648b3da1cd90fc6b44deb429f71 ensures that Brotli honors the `BUILD_SHARED_LIBS` option in CMake, allowing it to be statically linked in libjxl.
