### ISSUE TITLE
Big file size with progressive + tortoise.

### ISSUE THREAD

**Issue by bat999** [libjxl/libjxl#17]
Hi
I used a test file from here...
`$ wget http://www.r0k.us/graphics/kodak/kodak/kodim20.png
`
Create a jxl file with speed 9...
`$ cjxl kodim20.png kodim20.jxl -s 9 -d 3
`
Create a progressive jxl file with speed 9...
`$ cjxl kodim20.png prog_kodim20.jxl -s 9 -d 3 -p
`
Compare the file sizes...
`$ ls -l kodim20.jxl | awk '{print $5}' && ls -l prog_kodim20.jxl | awk '{print $5}'
`
**24893
72467**

The progressive file is much larger than the non-progressive file.
I'm using `cjxl v0.3.7-30ea86ab`

**Comment by veluca93** [comment]
One of the recent commits might have fixed this - would you be able to test on main?

**Comment by bat999** [comment]
> ...would you be able to test on main?
No

**Comment by eddiezato** [comment]
```PowerShell
PS > cjxl kodim20.png kodim20.jxl -s 9 -d 3
PS > cjxl kodim20.png prog_kodim20.jxl -s 9 -d 3 -p
PS > ls *.jxl | Format-Table Name,Length

Name             Length
----             ------
kodim20.jxl       24840
prog_kodim20.jxl  71979
```
cjxl v0.3.7-12-g04267a8

**Comment by veluca93** [comment]
Ok, then it's something else. Thank you!

**Comment by eddiezato** [comment]
FYI:
```PowerShell
PS > cjxl kodim20.png kodim20_7.jxl -s 7 -d 3 --quiet
PS > cjxl kodim20.png kodim20_8.jxl -s 8 -d 3 --quiet
PS > cjxl kodim20.png kodim20_7p.jxl -s 7 -d 3 -p --quiet
PS > cjxl kodim20.png kodim20_8p.jxl -s 8 -d 3 -p --quiet
PS > ls *.jxl | Format-Table Name,Length

Name           Length
----           ------
kodim20_7.jxl   26615
kodim20_7p.jxl  27063
kodim20_8.jxl   24751
kodim20_8p.jxl  62302
```

**Comment by veluca93** [comment]
Yep, I'm not surprised that -s 8 has the same behaviour as -s 9 here :) I have a couple of guesses on what is going on, but I don't know when I'll have time to look into it...

**Comment by hohMiyazawa** [comment]
Reproducing in ``v0.3.7 (3068ee0)``, with both lossy and lossless.

```
$ cjxl 0012.png 0012.lossless.jxl -q 100 -e 9
1104509 bytes

$ cjxl 0012.png 0012.lossless_prog.jxl -q 100 -e 9 -p
1810849 bytes

$ cjxl 0012.png 0012.lossy.jxl -d 3 -e 9
42553 bytes

$ cjxl 0012.png 0012.lossy_prog.jxl -d 3 -e 9 -p
85481 bytes
```

[0012.png](https://share.wildbook.me/fNAFlM9DHFhq25lA.png)
[0012.lossless.jxl](https://share.wildbook.me/NXaGmyQF9ZvAus8A.jxl)
[0012.lossless_prog.jxl](https://share.wildbook.me/yd9EkWfF2qkTzZ5j.jxl)
[0012.lossy.jxl](https://share.wildbook.me/d7EBttKNaoukDUhO.jxl)
[0012.lossy_prog.jxl](https://share.wildbook.me/HzTPzfMH0S42DqHy.jxl)

**Comment by veluca93** [comment]
For lossless mode, this is more or less expected - entropy modeling is a lot more difficult with progression...

For lossy, a fix is in #38.

**Comment by eddiezato** [comment]
👌 cjxl v0.3.7-b7edff9
```PowerShell
PS > curl -O http://www.r0k.us/graphics/kodak/kodak/kodim20.png
PS > cjxl kodim20.png kodim20_7.jxl -s 7 -d 3 --quiet
PS > cjxl kodim20.png kodim20_7p.jxl -s 7 -d 3 -p --quiet
PS > cjxl kodim20.png kodim20_8.jxl -s 8 -d 3 --quiet
PS > cjxl kodim20.png kodim20_8p.jxl -s 8 -d 3 -p --quiet
PS > cjxl kodim20.png kodim20_9.jxl -s 9 -d 3 --quiet
PS > cjxl kodim20.png kodim20_9p.jxl -s 9 -d 3 -p --quiet
PS > ls *.jxl | Format-Table Name,Length

Name           Length
----           ------
kodim20_7.jxl   26615
kodim20_7p.jxl  27063
kodim20_8.jxl   24751
kodim20_8p.jxl  24970
kodim20_9.jxl   24840
kodim20_9p.jxl  24918
```

**Comment by bat999** [comment]
Hi
Thanks for fixing this.
Tested OK with cjxl v0.3.7-4dbbdca5

**24893
25031**
