### ISSUE TITLE
Add lib/include/jxl/jxl_version.h

### ISSUE THREAD

**Issue by dlemstra** [libjxl/libjxl#1721]
In the ImageMagick project we would like to have the possibility to add version checks in our code to make it possible to be compatible with multiple versions of the libjxl library. For now we will force people to use the latest version but it would be nice if we could add versions checks in the future

It would be nice if we had the following header file (lib/include/jxl/jxl_version.h):

```c
#ifndef JPEGXL_VERSION_H
#define JPEGXL_VERSION_H

#define JPEGXL_MAJOR_VERSION 0
#define JPEGXL_MINOR_VERSION 7
#define JPEGXL_PATCH_VERSION 0

/* Numeric representation of the version */
#define JPEGXL_NUMERIC_VERSION ((JPEGXL_MAJOR_VERSION <<24) | (JPEGXL_MINOR_VERSION <<16) | (JPEGXL_PATCH_VERSION <<8) | 0)

#endif  /* JPEGXL_VERSION_H */
```

I don't mind opening a pull request to add this to the project.

**Comment by novomesk** [comment]
There is a similar PR already: https://github.com/libjxl/libjxl/pull/834

but so far without success.

I'd like to have version number in the headers too.

**Comment by dlemstra** [comment]
These changes were added in #834.
