### ISSUE TITLE
skcms vs lcms2?

### ISSUE THREAD

**Issue by nobodyatandnothing** [libjxl/libjxl#1734]
what is better to build with?

**Comment by malaterre** [comment]
If you want to build the plugin (JPEGXL_ENABLE_PLUGINS) you must use SKCMS

**Comment by mo271** [comment]
I hope this answers your question.

**Comment by kmilos** [comment]
As mentioned, ideally the plugin should be configurable for this choice as well so there is in theory no dependence on skcms bundling...
