### ISSUE TITLE
cjxl -q 0 fails with "Setting frame distance failed"

### ISSUE THREAD

**Issue by y-guyon** [libjxl/libjxl#1741]
**Describe the bug**
Encoding an image with `cjxl -v -q 0` fails. The error message "Setting frame distance failed" is output.

**To Reproduce**
1. Download [tiger.png](https://user-images.githubusercontent.com/51164219/189933857-4a79b7d3-1168-47bf-a4f3-475b3a817754.png)
2. Build JpegXL at 12902774295fea02aaa19ff41a1ec9941e9b882b
3. Run `./cjxl tiger.png tiger.jxl -v -q 0`

**Expected behavior**
An encoded tiger.jxl is successfully created.

**Environment**
 - OS: Debian
 - Compiler version: GNU 12.1.0
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.8.0 12902774 [AVX2,SSE4,SSSE3,Unknown]

**Comment by mo271** [comment]
Thanks for opening this issue! 
I can confirm the problem! This will trigger for any value for `-q` that is smaller than 
$-5\log_{2.5}(6.25 (25 - 6.4)) + 30 \approx 4.04894058712018289225062637746033...,$
which corresponds to a `-d` of `25.0`.
I think we should update the error message and the help text for quality. 
(And possibly also mention the bounds `0.0` and `25.0` for the distance parameter.)

**Comment by afontenot** [comment]
Couple of notes:

 * I didn't see this issue with 0.6, which I was using prior to the 0.7 release a few days ago. Was the formula for mapping `q` values to `d` values changed, or were low `q` values already invalid with previous versions and that fact is now exposed to the user?
 * The help text for the quality setting actually says it can go down to -infinity, which suggests a very different kind of mapping than a 4-100 range or even 0-100 range.
