### ISSUE TITLE
version discrepancy between tag/tarball and version/library/pkg-config

### ISSUE THREAD

**Issue by tgurr** [libjxl/libjxl#1751]
**Describe the bug**
My assumptions are that the release version will also be tagged as 0.7 like the previous 0.6 release and as can be seen in the current release candidate. The tarball is versioned `0.7rc` but the actual program output of e.g. `djxl --version` is reporting `0.7.0`, the library is also versioned `libjxl.so.0.7.0` and the pkg-config information also reads `Version: 0.7.0`, so it would be nice and consistent if the actual release & tarball could also be tagged & released as `0.7.0` instead of just `0.7`.

**To Reproduce**
* Download & compile 0.7rc
* See version and library and libjxl.pc report 0.7.0 instead of 0.7

**Expected behavior**
* tag/tarball are named 0.7.0 instead of 0.7

**Screenshots**
none

**Environment**
 - OS: Linux
 - Compiler version: GCC 12.2.0
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl/djxl v0.7.0 [AVX2]

**Additional context**
none

**Comment by kmilos** [comment]
AFAIK, the `0.7.0` tag does not exist yet, i.e. it is not released, so there simply is no tarball for it. 

I'd say the issue goes in the other direction: `djxl --version`, pkg-config, etc. should all report `0.7rc` (or something other than `0.7.0`). Just renaming the **_r_**elease **_c_**andidate tarball as final is not the "expected behaviour" here.

**Comment by tgurr** [comment]
> AFAIK, the `0.7.0` tag does not exist yet, i.e. it is not released, so there simply is no tarball for it.

Should've probably more clear, my concern was raised in perspective of the upcomming release for 0.7.0 that it should be tagged as 0.7.0 instead of just 0.7 like it was done for the previous version 0.6.

> Otherwise I agree, ping-ponging between 2 and 3 version numbers is a PITA when it comes to packaging scripts etc., should always be 3 (major.minor.patch).

Indeed that would be very welcomed, thanks for taking it into consideration!

**Comment by mo271** [comment]
I think this has been settled by #1757
