### ISSUE TITLE
Decoding error in gimp when using modular with resampling

### ISSUE THREAD

**Issue by RubenKelevra** [libjxl/libjxl#1758]
**Describe the bug**
While decoding with djxl works fine, gimp shows some weird artifacts when using resampling while encoding.

**To Reproduce**
Encode a file with 

`cjxl -m -e 9 --resampling=2 test.png test.jxl`

**Expected behavior**
Gimp should decode the files the same as djxl

**Screenshots**
![rendering in gimp](https://user-images.githubusercontent.com/614929/190942303-8522ce13-0cba-4081-94ce-10e9bf7f7e13.png)

**Environment**
 - OS: Linux
 - Compiler version: Unknown (Arch Linux binary package)
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.6.1 a205468b [AVX2,SSE4,SSSE3]
 - Gimp version string: GIMP 2.10.32

![test](https://user-images.githubusercontent.com/614929/190942069-1a1e86ee-e35b-4c6f-bfcd-66b78c14ba0a.png)
![test jxl](https://user-images.githubusercontent.com/614929/190942236-a747ac5e-6140-4453-9df4-a66fc3a57e0d.jpg)

**Comment by mo271** [comment]
Thanks for the report! seems like this is related to https://github.com/libjxl/libjxl/issues/1755.

**Comment by mo271** [comment]
Considering #1755, it seems that you have been using an older version of libjxl. Could you try to check if the error persists at the current head?

**Comment by mo271** [comment]
I checked with current head, and it seems that the gimp plugin can decode the image flawlessly. Plesae reopen if this can be reproduced with the most recent version of the GIMP plugin.
