### ISSUE TITLE
No output file produced when converting a JPG file, cjxl exists without error

### ISSUE THREAD

**Issue by perk11** [libjxl/libjxl#1759]
**Describe the bug**
I was converting my library from JPG to JXL and stumbled upon a few files where cjxl would not produce any output, even though it returns with 0 exist codes and shows as if everything is correct

**To Reproduce**
1.Download [this file](https://user-images.githubusercontent.com/1924829/190955641-5fbe7bc6-b2b1-4745-8c68-861c0eab6967.jpg) and rename it to 1.jpg

2. Run `cjxl 1.jpg 1.jxl`

**Expected behavior**
A file with a name 1.jxl is created. 
If the file is not created, at least the returned status code should not be 0.

**Actual behavior**

No file is created.
Returned status code is 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/1924829/190955407-c864e770-d9b2-43b1-aec7-6cdefba8e155.png)

**Environment**
 - OS: Manjaro Linux
 - Compiler version: not sure
 - CPU type: x86_64, AMD Ryzen 7 3700X 8-Core Processor
 - cjxl/djxl version string: cjxl v0.6.1 a205468b [AVX2,SSE4,SSSE3,Scalar]

**Additional context**

**Comment by mo271** [comment]
Thanks for the bug report!
This should be fixed already at the current head; there I could successfully ran
`cjxl 1.jpg 1.jxl`
Could you check that this works for you as well?

**Comment by perk11** [comment]
Compiled the latest master and indeed, this is working.

Thank you. Closing this issue.

**Comment by mo271** [comment]
Thanks for checking!
