### ISSUE TITLE
Add "JXL" text to the file header for future easy identification of extension less files and/or data recovery

### ISSUE THREAD

**Issue by necros2k7** [libjxl/libjxl#1779]
**Is your feature request related to a problem? Please describe.**
Nope
**Describe the solution you'd like**
Add "JXL" text to the file header for future identification of extension less files and/or data recovery

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by jonsneyers** [comment]
It's a bit late in the game to change the bitstream specification :)

If you use the container-based jxl format, you will see ascii "JXL" and "jxl" show up a few times in the initial bytes.

For the 'naked codestream' we kept things as minimal as possible, and even 3 bytes for "JXL" were considered too much. Instead we use the 2 bytes 0xFF0A which uses the FFxx marker syntax as it is used in several JPEG standards (and the combination 0xFF0A is uniquely reserved for "start of jxl codestream").

**Comment by mo271** [comment]
I hope @jonsneyers helps. Closing this as won't fix for the time being.
