### ISSUE TITLE
docker build for windows, can't run exe

### ISSUE THREAD

**Issue by fredprodibi** [libjxl/libjxl#179]
Hello I built cjxl with the command

BUILD_TARGET=x86_64-w64-mingw32 SKIP_TEST=1 CC=clang-7 CXX=clang++-7 ./ci.sh release on docker, 

build worked and I got the cjxl.exe but when I run it with a command line nothing is happening and it returns immediately without doing any thing or sending errors.

What dependencies should I install on windows to run the exe?
How can I modify the build command line so that all the dependencies are imbedded in the exe?

Thank you

**Comment by veluca93** [comment]
@deymo @sboukortt do you know what's up here?

**Comment by deymo** [comment]
At the bottom of the .gitlab-ci.yml there's a recipe for building a static binary on windows which should work. I think with one of the last CLs our test running it under wine64 in the same docker started segfaulting after encoding, so maybe there's some code issue as well.

**Comment by deymo** [comment]
Basically, if you build with `-DJPEGXL_STATIC=ON` it shouldn't require dependencies outside.

**Comment by fredprodibi** [comment]
hello I tried
BUILD_TARGET=x86_64-w64-mingw32 SKIP_TEST=1 CC=clang-7 CXX=clang++-7 ./ci.sh release -DJPEGXL_DEP_LICENSE_DIR=/usr/share/doc -DJPEGXL_STATIC=ON -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_VIEWERS=OFF -DJPEGXL_ENABLE_PLUGINS=OFF -DJPEGXL_ENABLE_OPENEXR=OFF -DJPEGXL_ENABLE_TCMALLOC=OFF -DJPEGXL_ENABLE_FUZZERS=OFF

from the gitlab-ci.yml and it's the same nothing is happening, and no errors
![console1](https://user-images.githubusercontent.com/55511549/122213953-d1d31a80-cea9-11eb-9191-0166177038d1.png)

**Comment by jonsneyers** [comment]
Can you check the exit code?
(do `echo Exit Code is %errorlevel%` just after running cjxl)

**Comment by fredprodibi** [comment]
instead of using powershel I tried in a command prompt and now I have an error

**libjpeg-62.dll was not found**

So that would mean that even with -DJPEGXL_STATIC=ON some dependencies are not embed?

**Comment by deymo** [comment]
when switching to -DJPEGXL_STATIC=ON did you remove the build directory or at least the CMakeCache.txt? I think cmake caches those selections.

**Comment by fredprodibi** [comment]
it works! after deleting the build folder and rebuilding

thanks a lot
