### ISSUE TITLE
fail to reconstruct jpeg from jpeg xl

### ISSUE THREAD

**Issue by gjslkjs** [libjxl/libjxl#1790]
**Describe the bug**
I tried to transcode jpeg image to a jpeg xl image and reconstruct it to jpeg using libjxl API (v0.6.1).
Most jpeg images are successfully transcoded and reconstructed, but som jpeg failed to reconstructing from transcoded jpeg xl.
In my case, failed case has zero padding bits.
I think a padding_spot_limit, variable in jpeg_data.cc, is a reason.
While decoding, value of the padding_spot_limit was not equal to value of the padding_spot_limit while encoding.
And I found it the values of variables in CalculateMcuSize() such as width, height, max_h_samp_factor etc. are not assigned to correctly (It seems not assigned and just have initial values), and it make invalid value for the padding_spot_limit.

**To Reproduce**
Simple pseudo code that i test like below,
```c++
// transcoding jpeg -> jxl
vector<uint8_t> jpg = read("001.jpg");
JxlEncoder* encoder = JxlEncoderCreate(NULL);
JxlEncoderUseContainer(encoder, JXL_TRUE);
JxlEncoderStoreJPEGMetadata(encoder, JXL_TRUE);
JxlEncoderOptions* encoderOptions = JxlEncoderOptionsCreate(encoder, NULL);

// set some encoding options...

JxlEncoderAddJPEGFrame(encoderOptions, jpg->data(), jpg->size());

vector<uint8_t> jxl;
while (true) {
    JxlEncoderStatus status = JxlEncoderProcessOutput(encoder, &nextOut, &availOut);
    if(status == JXL_ENC_SUCCESS) break;
    else if (status == JXL_ENC_ERROR) // handle error
    else if (//.. handle each encoding status
}
JxlEncoderDestroy(encoder);

// reconstruction jpeg xl -> jpeg
JxlDecoder* decoder = JxlDecoderCreate(NULL);
JxlDecoderSubscribeEvents(decoder, JXL_DEC_BASIC_INFO | JXL_DEC_COLOR_ENCODING | JXL_DEC_FULL_IMAGE | JXL_DEC_JPEG_RECONSTRUCTION);
JxlDecoderSetInput(decoder, jxl.data(), jxl.size());

vector<uint8_t> reconJpg;

while (true) {
    JxlDecoderStatus status = JxlDecoderProcessInput(decoder);
    if (status == JXL_DEC_SUCCESS) break;
    else if(status == JXL_DEC_ERROR) // handle error
    else if(//... handle each decoding status
}
JxlDecoderDestroy(decoder);
```

and below is test jpg image that failed reconstructing.
[001](https://user-images.githubusercontent.com/24429565/192573060-12fd2d58-25c4-4f0e-939a-b75efd8268cc.jpg)

**Environment**
 - OS: centos7.4
 - CPU type: x86_64

**Comment by mo271** [comment]
Thank you for the bug report.
Could you check if this problem still occurs with version 0.7.0?

**Comment by gjslkjs** [comment]
Yes, it still occurs with version 0.7.0

**Comment by jendalinda** [comment]
The jpeg file can be fixed using
`jpegtran -copy all`
Then it transcodes without errors.

**Comment by gjslkjs** [comment]
@jendalinda 
Thank you for your advice!
It's a good solution, it works when I copy the image using jpegtran as you commented.
However, I think jpegtran may remove the zero padding datas of the jpeg image.
Actually, I need to transcode and reconstruct the jpeg image without any modifications of the original image.

**Comment by jendalinda** [comment]
Any data outside the JPEG segments are not guaranteed to be preserved.

**Comment by szabadka** [comment]
JPEG XL, just like Brunsli, preserves padding bits and inter marker segment data. This issue was due to a bug in the jpeg xl validation code. I have a PR that will fix it.
