### ISSUE TITLE
Build for windows (advanced) doesn't build

### ISSUE THREAD

**Issue by fredprodibi** [libjxl/libjxl#180]
I followed the build for windows documentation 
![errors](https://user-images.githubusercontent.com/55511549/122160378-1d68d280-ce70-11eb-8404-ba95b01af37d.png)

a lot of errors seems to be in test_util-int.h how can I skip the test build to see if it's work?
or how can I build it for windows?

**Comment by jan-wassenberg** [comment]
@fredprodibi thanks for reporting this. Those lines are:

`const size_t begin = static_cast<size_t>(std::max<intptr_t>(0, lane - 2));
const size_t end = std::min(begin + 7, N);`

I think we are missing an `#include <algorithm>` at the top of the file. Can you add it to confirm that's the issue?

**Comment by fredprodibi** [comment]
Hello thank you for your quick response. 

It seems that the error remains
![sameError](https://user-images.githubusercontent.com/55511549/122177415-e43b5d00-ce85-11eb-9985-d36007104be4.png)

also after reopening the project a new error: Generator: Ninja Does not match the generator used previously: MSYS makefiles
![ninja](https://user-images.githubusercontent.com/55511549/122177413-e3a2c680-ce85-11eb-9e2c-d86c461fd300.png)

**Comment by jan-wassenberg** [comment]
@fredprodibi for the second error, the message includes some advice on how to fix it - deleting CMakeCache.txt seems like a good way.

For the first, another possible cause is that Windows defines min and max macros, which can cause havoc. If that's the cause, then replacing std::min with HWY_MIN and std::max with HWY_MAX should fix it. Would be happy to make that change, but can you again verify that fixes it?

**Comment by fredprodibi** [comment]
Yes I did find and replace for both min/max 

HWY_MAX seems undeclared

![undeclare](https://user-images.githubusercontent.com/55511549/122180249-89efcb80-ce88-11eb-82b3-ee3277a668f4.png)

**Comment by veluca93** [comment]
Can you try `HWY_MAX(0, lane - 2)` instead of `HWY_MAX<intptr_t>(...)`?

Having said that, I don't see a very good reason why std::max shouldn't work...

**Comment by veluca93** [comment]
> Can you try `HWY_MAX(0, lane - 2)` instead of `HWY_MAX<intptr_t>(...)`?
> 
> Having said that, I don't see a very good reason why std::max shouldn't work...

Ah, it seems that the solution for std::min / std::max is to define NOMINMAX when on windows.

**Comment by fredprodibi** [comment]
hello @veluca93 I can try the NOMINMAX 

how can I do that?

**Comment by veluca93** [comment]
It's *probably* enough to add `#define NOMINMAX` at the start of the file, before any other include.

**Comment by jan-wassenberg** [comment]
One issue is that all translation units that potentially include <windows.h> (transitively) would have to arrange for NOMINMAX, so it's probably easier and safer to use HWY_MIN/MAX instead. I'll start on that for Highway.

**Comment by veluca93** [comment]
I don't know if that would solve the issue, as std::min is also used in
other places.
It may be a better option to add the define from the build system itself,
or everywhere windows.h gets included.

**Comment by jan-wassenberg** [comment]
We can do both - other users of Highway could also hit the same issue, so it makes sense to avoid the problem there. I have no objection to adding NOMINMAX to libjxl.

**Comment by fredprodibi** [comment]
hello I have added NOMINMAX at the top of the file and reverted to std:min and the issue persist, when I change to HWY_MIN/MAX the error change HWY_MAX is undeclared

**Comment by meesoft** [comment]
I disabled building the tests to avoid a lot of pain when building for Windows - to do that made two changes compared to the recommended CMakeSettings.json:
Under BUILD_GMOCK I changed the value from True to False, and then I added the section
```
       {
          "name": "BUILD_TESTING",
          "value": "False",
          "type": "BOOL"
        }
```

**Comment by jonsneyers** [comment]
What is the status of this issue? We now have windows builds in the CI, so maybe it has been resolved? Or maybe not?

**Comment by mo271** [comment]
Feel free to re-open if there still is a problem.
