### ISSUE TITLE
How to reduce size of libjxl when targeting Android

### ISSUE THREAD

**Issue by madebr** [libjxl/libjxl#1835]
**Describe the bug**
Android `libjxl.so` libraries are huge. They range from 39MiB for armeabi-v7a to 66MiB for x86_64.

```
-rw-r--r--. 1 maarten maarten 41M 15 okt 16:00 android.arm64-v8a/libjxl.so
-rw-r--r--. 1 maarten maarten 39M 15 okt 16:00 android.armeabi-v7a/libjxl.so
-rw-r--r--. 1 maarten maarten 66M 15 okt 16:00 android.x86_64/libjxl.so
-rw-r--r--. 1 maarten maarten 48M 15 okt 16:00 android.x86/libjxl.so
```
These file sizes exclude libbrotli, which is built separately as a shared library.
Am I misconfiguring libjxl or is this normal?

**To Reproduce**

Use the [simplatex/android-lightweight](https://hub.docker.com/r/simplatex/android-lightweight) docker image:

Start it with:
```
docker run --rm -ti simplatex/android-lightweight /bin/bash
```
Run the following inside the container. It downloads, builds and installs libjxl:
```
git clone https://github.com/libjxl/libjxl.git /src
git -C /src submodule update --recursive --init
apt-get update && apt-get install -y cmake ninja-build
cmake -S /src -B /tmp/build_libjxl -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" -DANDROID_PLATFORM=16 -DANDROID_ABI=x86 -DBUILD_SHARED_LIBS=ON  -GNinja -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_PLUGINS=OFF -DJPEGXL_ENABLE_SKCMS=OFF -DJPEGXL_FORCE_SYSTEM_HWY=OFF  -DCMAKE_INSTALL_PREFIX=/tmp/libjxl_prefix
cmake --build /tmp/build_libjxl --target install
ls -al /tmp/libjxl_prefix/lib/*.so --block-size=M
```
=> output:
```
-rw-r--r--. 1 root root  1M Oct 15 14:20 /tmp/libjxl_prefix/lib/libbrotlicommon.so
-rw-r--r--. 1 root root  1M Oct 15 14:20 /tmp/libjxl_prefix/lib/libbrotlidec.so
-rw-r--r--. 1 root root  2M Oct 15 14:20 /tmp/libjxl_prefix/lib/libbrotlienc.so
-rw-r--r--. 1 root root 34M Oct 15 14:21 /tmp/libjxl_prefix/lib/libjxl.so
-rw-r--r--. 1 root root  2M Oct 15 14:21 /tmp/libjxl_prefix/lib/libjxl_threads.so
```
=> `libjxl.so` for x86@Android is 34 MiB

**Expected behavior**
`libjxl.so` having a more reasonable size.

**Environment**
 - OS: Linux
 - Compiler version: clang
 - CPU type: x86 (but applies to all
 - cjxl/djxl version string: n/a

**Additional context**

I found out about this while creating android prefab archives for SDL_image.

**Comment by jonsneyers** [comment]
Did you try `strip`?

**Comment by madebr** [comment]
No I did not. That reduces the file size hugely: 34M -> 3M.
Thanks for the hint!
