### ISSUE TITLE
cjxl 0.7 seems to produce bigger lossless pictures than 0.6.1

### ISSUE THREAD

**Issue by schrmh** [libjxl/libjxl#1839]
**Describe the bug**
I converted a few PNG screenshots to lossless JXL by using cjxl and noticed that the same screenshots turned into bigger JXL files when I used 0.7.0 compared to 0.6.1 no matter which options I used.

**To Reproduce**
(Example output files in block with file size in front of the names)
0.6.1 `cjxl -q 100 -m -s 9 -E 3 -I 1 $PNG $JXL`
```
652K Bildschirmfoto_2022-09-21_01-05-01.jxl
1,2M Bildschirmfoto_2022-09-21_01-05-08.jxl
705K Bildschirmfoto_2022-09-21_01-05-27.jxl
```
0.7.0 `cjxl -q 100 -m 1 -e 9 -E 3 -I 1 $PNG $JXL`
```
712K Bildschirmfoto_2022-09-21_01-05-01.jxl
1,3M Bildschirmfoto_2022-09-21_01-05-08.jxl
790K Bildschirmfoto_2022-09-21_01-05-27.jxl
```

0.7.0  `cjxl -q 100 -e 9 --brotli_effort 11 -E 3 -I 10 $PNG $JXL`
```
670K Bildschirmfoto_2022-09-21_01-05-01.jxl
1,2M Bildschirmfoto_2022-09-21_01-05-08.jxl
743K Bildschirmfoto_2022-09-21_01-05-27.jxl
```
I also tested dropping -q and -m or using -m 0, etc.

**Expected behavior**
`cjxl -q 100 -m 1 -e 9 -E 3 -I 1` looks like it should create files as small as 0.6.1's `cjxl -q 100 -m -s 9 -E 3 -I 1` since effort is the replacement for speed.
So I expect generated JXL files at least as small as in 0.6.1.

**Screenshots**
Not necessary.

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 14.0.6 / gcc 12.2.0
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.7.0 f95da131 [AVX2,SSE4,SSSE3,Unknown]
 - cjxl/djxl version string (old): cjxl v0.6.1 a205468b [AVX2,SSE4,SSSE3,Scalar]

**Additional context**
I did not compile libjxl myself but used Arch Linux's libjxl package but also tested the static 0.7.0 cjxl from the Release page of this GitHub repo.

**Comment by mo271** [comment]
Thanks for the report!
I suspect there is a misunderstanding: 
`-s 9` would map to `-e 1`. Sorry for the confusion, but a lower effort translates to a faster, i.e. higher, speed. 
Could you try if that solves the issues with size that you are observing?

**Comment by jonsneyers** [comment]
> Thanks for the report! I suspect there is a misunderstanding: `-s 9` would map to `-e 1`. Sorry for the confusion, but a lower effort translates to a faster, i.e. higher, speed. Could you try if that solves the issues with size that you are observing?

I don't think that's true, the old --speed parameter had the same meaning as the current --effort (higher value is slower, like how it is in webp/brotli/gzip), which was confusing so we renamed it to --effort :)

So I suspect something else causes this.

Ah, it's probably the option `-I 1`. That one changed from having a range 0..1 to having range 0..100, so you have to multiply the value by 100 to make it do the same thing.
