### ISSUE TITLE
JXL_FAILURE: Invalid channel range

### ISSUE THREAD

**Issue by Jamaika1** [libjxl/libjxl#184]
cjxl.exe image_21447_24bit.png image_21447_24bit.jxl -v -m -q 100 -s 5 -C 1 --num_threads=4
```
JPEG XL encoder v0.3.7 0.3.7-13649d2b [Scalar]
codec_png.cc:496: PNG: no color_space/icc_pathname given, assuming sRGB
Read 1563x1558 image, 20.7 MP/s
Encoding [Modular, lossless, hare], 4 threads.
transform.cc:70: JXL_FAILURE: Invalid channel range
```
https://github.com/libjxl/libjxl/commit/30dae3b5b0cb70134dd08964a6bb1f247f2ac412

**Comment by jonsneyers** [comment]
Hi, thanks for the report. Using a random image, I cannot reproduce. Could you share the image on which this happens?

**Comment by jonsneyers** [comment]
Nevermind, I found an image on which I can reproduce it.

**Comment by Jamaika1** [comment]
https://www.sendspace.com/file/wx8wam
