### ISSUE TITLE
GIMP plugin fails to load truncated progressive files that `djxl` can understand

### ISSUE THREAD

**Issue by ctrlcctrlv** [libjxl/libjxl#1845]
**Describe the bug**
GIMP plugin fails to load truncated progressive files that `djxl` can understand

**To Reproduce**
Encode an image progressively.
Truncate it.
Try to load it in GIMP.

**Expected behavior**
The image to load in GIMP.

**Environment**
 - OS: GNU/Linux
 - Compiler version: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
 - CPU type: x86_64
 - cjxl/djxl version string: v0.8.0 99b07212 [AVX3,AVX2,SSE4,SSSE3,Unknown]
Copyright (c) the JPEG XL Project

**Comment by novomesk** [comment]
Report it also here:
https://gitlab.gnome.org/GNOME/gimp/-/issues

Please add some truncated JXL there too.

**Comment by ctrlcctrlv** [comment]
I've solved this on my own. Will send a PR.
![Screenshot from 2022-11-05 14-59-52](https://user-images.githubusercontent.com/838783/200136592-91beb133-825b-4a58-ac91-6efb570e51c7.png)
