### ISSUE TITLE
StoreInterleaved: 2 3 4

### ISSUE THREAD

**Issue by sheerluck** [libjxl/libjxl#1852]
**Describe the bug**
in order to compile `main` branch I had to comment out all lines with `StoreInterleaved2` `StoreInterleaved3` `StoreInterleaved4`
(in `dec_group_jpeg.cc` and `stage_write.cc`)

**To Reproduce**
try to compile `main` branch

**Expected behavior**
`main` branch compiles successfully

**Environment**
 - OS: Gentoo Linux
 - Compiler version: gcc-12.2.1
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.8.0  [AVX2]

**Additional context**
`emerge =media-libs/libjxl-9999` with `-DJXL_HWY_DISABLED_TARGETS_FORCED:BOOL=ON`

**Comment by sheerluck** [comment]
so this issue was labeled as **Platform-specific issues**
I wonder where `StoreInterleaved2` `StoreInterleaved3` `StoreInterleaved4` are on other platforms :thinking:

**Comment by mo271** [comment]
The building/portability label was used here because this seems to be a compiling/build issue.

**Comment by sheerluck** [comment]
Sorry, my fault, found all `StoreInterleaved*` in `/usr/include/hwy/ops` after updating `dev-cpp/highway`
