### ISSUE TITLE
JXL_API_ERROR use_original_profile typo

### ISSUE THREAD

**Issue by nigeltao** [libjxl/libjxl#1853]
`lib/jxl/encode.cc` says `"Set use_original_profile=true for lossless encoding"` (inside a `JXL_API_ERROR` invocation), twice, but the field is called `uses_original_profile`.

Note the one versus two `s`s in `use_etc` versus `uses_etc`.

Grepping for `use_original_profile` with only one `s` gives no other hits (other than a `lossy_use_original_profile` function argument in `lib/jxl/encode_test.cc`).

**Comment by mo271** [comment]
Thanks, @nigeltao!
