### ISSUE TITLE
experimental/fast_lossless doesn't anon-namespace its BitWriter

### ISSUE THREAD

**Issue by nigeltao** [libjxl/libjxl#1855]
I can't combine `libjxl/experimental/fast_lossless` and the `github.com/veluca93/fpnge` encoder code in the same program (e.g. to compare the two encoders' speeds), because both fjxl and fpnge declare `struct BitWriter` in the top-level namespace, with the same name (and both have a `Write(uint32_t, uint64_t)` method) but different field layout (see links below). Linking both of them leads to a crash, presumably because the fjxl code mistakenly calls the fpnge BitWriter or vice versa.

- https://github.com/libjxl/libjxl/blob/506714edaa3dd670133b9fe094d5efb94f6d0f6e/experimental/fast_lossless/fast_lossless.cc#L46
- https://github.com/veluca93/fpnge/blob/48020025e197318ab3c695903a4577e3d9565ddb/fpnge.cc#L374

I believe one solution would be to wrap a C++ "anonymous namespace" around all of `fast_lossless.cc` code except for the final `FastLosslessEncode` function.

@veluca93

**Comment by nigeltao** [comment]
Speaking of `fast_lossless.cc`, it also has an unconditional:

```
#pragma omp parallel for
```

When I compile with `g++ -Wall`, this triggers `-Wunknown-pragmas` and `-Wsign-compare` warnings:

```
$ g++ -Wall fast_lossless.cc -o /dev/null
fast_lossless.cc:1300: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
 1300 | #pragma omp parallel for
etc etc etc (several -Wsign-compare warnings)
```

**Comment by veluca93** [comment]
Adding an anonymous namespace SGTM, could you send a PR?
