### ISSUE TITLE
less perceived quality and/or more blurriness at medium bitrates

### ISSUE THREAD

**Issue by fabiorug** [libjxl/libjxl#19]
It's noticeable especially in synthetic images.
for %i in (C:\Users\User\Documents\bn2*.jpg) do cjxl -j -s 6 -q 63.52 --epf=2 -p --gaborish=1 --patches=0 --dots=1 --use_new_heuristics %i %i.jxl
for %i in (C:\Users\User\Documents\dos2\*.png) do cjxl -q 82.33 -s 8 --epf=2 --gaborish=1 %i %i.jxl

build commit 30ea86ab 
seems like some quality like s 9 q 65 not properly tuned. 
So, the issue is what is on the title,  way more blurriness on the commonly used medium bitrate, q 65, q 75.

I'm ok with q 63.52 or q 65 undersaturation as you don't want to make the illusion of more saturated photo, but when I up the quality I prefer that is felt more at least on PNG  source, i know that JPEG will always look upscaled of some sort.
[comparisonjxl.zip](https://github.com/libjxl/libjxl/files/6546759/comparisonjxl.zip)

maybe it needs floating partitioning to improve

**Comment by deymo** [comment]
@jyrkialakuijala could you take a look at this?

**Comment by fabiorug** [comment]
solved with v0.3.7-51-gaf6ece2 sse4 - 2021.06.01 github - eddiezato build.  
looks about visually same as 
for %i in (C:\Users\User\Documents\gww*.png) do cjxl -q 98.23493 -s 8 --epf=1 --faster_decoding=5 %i %i.jxl
in the "I compile cjxl (8304ea44) for windows (non avx2) yesterday commit"

i didn't compiled the build myself but this user on discord said the version is 
solved with v0.3.7-51-gaf6ece2 sse4
Anyway the issue is solved, there is no regressions compared to 12052021 new heuristics
