### ISSUE TITLE
0.7 wasm fails with in JxlDecoderSetPreferredColorProfile

### ISSUE THREAD

**Issue by jimbo2150** [libjxl/libjxl#1902]
**Describe the bug**
Using a 0.7 build of the wasm file, a number of images fail with `JxlDecoderSetPreferredColorProfile failed` when HDR is requested (SDR works).

**To Reproduce**
Compile wasm from version 0.7 and attempt to decode various images.

**Expected behavior**
The error message should not occur and the image decode successfully.

**Environment**
 - OS: Linux
 - Compiler version: clang 15
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.7 | SIMD supported: SSE4,Scalar

**Comment by jimbo2150** [comment]
Submitted a pull request after debugging and finding aoperator that was preventing a function call.
https://github.com/libjxl/libjxl/pull/1900

**Comment by mo271** [comment]
fixed by #1900
