### ISSUE TITLE
Option to not retry with `--pixels_to_jpeg` for `djxl`

### ISSUE THREAD

**Issue by Tokariew** [libjxl/libjxl#1907]
**Is your feature request related to a problem? Please describe.**
When decoding JPEG-XL files to jpeg inside script there is no option to know if image can be reconstructed to jpeg losslessly without saving the output, and then discarding if we want only decode losslessly.

**Describe the solution you'd like**
Add a option to djxl to not to retry with `--pixels_to_jpeg`

**Describe alternatives you've considered**
Some other option to check if jxl was created as losslessly compressed jpeg, without decoding it to file

**Comment by mo271** [comment]
Thanks for the suggestion!
Might the `jxlinfo` be of help here?
It can tell you `JPEG bitstream reconstruction data available` without decoding the file.

**Comment by Tokariew** [comment]
yes, jxlinfo help a lot, thanks for the suggestion
