### ISSUE TITLE
Add Pale Moon to the list of jxl-supporting software (and maybe remove Chrome?)

### ISSUE THREAD

**Issue by wolfbeast** [libjxl/libjxl#1914]
[Pale Moon](https://www.palemoon,org), as of 31.4.0, default-supports (and enables) JPEG-XL. It offers conneg headers to negotiate dynamic image serving by servers that have .jxl images available.
It should be added to the list of supporting software.

Google has also announced it intends to [drop support for it](https://www.cnet.com/tech/computing/chrome-banishes-jpeg-xl-photo-format-that-could-save-phone-space/), so perhaps it should be removed.

**Comment by mo271** [comment]
Happy to add Pale Moon! Let's not remove the Chromium until it actually has been removed.

**Comment by wolfbeast** [comment]
Thanks for that!

> Let's not remove the Chromium until it actually has been removed.

Fair enough! (and a bit off-topic anyways here)

**Comment by wolfbeast** [comment]
Not sure where to report it for the jpegxl.info website but if it could be considered to be listed there as well, that would be awesome.

**Comment by kmilos** [comment]
While we're at it, GraphicsMagick also has seems to have support since v1.3.38: http://www.graphicsmagick.org/NEWS.html#march-26-2022

**Comment by mo271** [comment]
> While we're at it, GraphicsMagick also seems to have support since v1.3.38: http://www.graphicsmagick.org/NEWS.html#march-26-2022

SGTM: https://github.com/libjxl/libjxl/pull/1923
