### ISSUE TITLE
GIMP plugin cannot export to lossless, fails with "could not save image" error

### ISSUE THREAD

**Issue by nekohayo** [libjxl/libjxl#1931]
Initially reported [in the GIMP bug tracker](https://gitlab.gnome.org/GNOME/gimp/-/issues/8905):

---

Open any image (ex: `~/foo.jpg`) and try to export it to "foo.jxl" while the "Lossless Mode" option is checked in the JXL export settings dialog.

It will start, get maybe 1/10th of the way through the progressbar, and then give you this generic error dialog:

> Saving '/home/user/foo.jxl' failed:
> 
> JPEG XL image plug-in could not save image

Exporting without "Lossless Mode" works.

Tested with GIMP 2.10.32 from the Fedora 37 repositories. Turns out the "gimp-jxl-plugin" package was installed on my system, version 0.7.0-3.fc37.

**Comment by mo271** [comment]
Thanks for the bug report!

Possibly relevant might be the work here, at least it might be good to get that merged first and then work on fixing the Lossless Mode issue. https://github.com/libjxl/libjxl/pull/1874

**Comment by thebombzen** [comment]
Fixed by #2188
