### ISSUE TITLE
GDK-pixbuf loader plugin's hard dependency on SKIA / SCMS may hurt adoption in core components of Linux desktop environments and distros

### ISSUE THREAD

**Issue by nekohayo** [libjxl/libjxl#1932]
Here's a fun rabbit hole. I wanted to [request](https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/issues/32) the GNOME Backgrounds (wallpapers) to switch to JPEG XL as their default universal format, to save a lot of space everywhere, because I wanted that to trickle down to Fedora and such, however... the ticket was closed as not being possible at the moment.

So when you dig around from there, you find [this](https://gitlab.gnome.org/GNOME/gnome-backgrounds/-/issues/29) (which doesn't tell us why webp was picked), [this](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/502) which points to [this previous attempt at adding libjxl to GNOME OS' core-deps](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/1622)... which points right back here at issue #865.

However, reading all those, it was still a bit unclear to me what the situation was, so I asked for clarifications in `#gnome-hackers` and here are some answers I got:

> A: "It was a pain to add jpeg-xl support in GNOME OS, [as] it hard depends on skia. Someone would need to figure out how to build skia on our end"

> M: "Hard -1 from me, we should not accept a dependency on skia. Not unless skia decides to become a shared library. It's just too inconsistent with the rest of the platform."
> 
> M: "It looks like libjxl is OK because it can be built with lcms instead of skcms, but the jxl gdk-pixbuf loader that you need for wallpapers really does hard depend on skcms"
> 
> M: "lcms2 is already a dep of GNOME and it is a shared lib, switching to that looks like a good idea"

**Comment by jonsneyers** [comment]
Looks like we should make the gdk-pixbuf loader use lcms2 then...

**Comment by novomesk** [comment]
Similar situation is in Gentoo Linux. Gdk loader is only in live EBUILD, but not in stable package.

I recommend to consider maintainer-friendliness in future decisions. It has impact on many potential users.

**Comment by veluca93** [comment]
Indeed, this should be fixed now.
