### ISSUE TITLE
`allow_partial_input` disabled despite `--allow_partial_files`

### ISSUE THREAD

**Issue by zeroby0** [libjxl/libjxl#1935]
**Describe the bug**

When decoding a truncated progressive .jxl with `djxl --allow_partial_files`, the following warning is printed:

```
JPEG XL decoder v0.7.0 f95da131 [AVX3,AVX2,SSE4,SSSE3,Unknown]
Read 400000 compressed bytes.
Input file is truncated and allow_partial_input was disabled.Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...
Decoded to pixels.
3000 x 4000, 57.92 MP/s [57.92, 57.92], 1 reps, 8 threads.
```

**To Reproduce**

[1935.zip](https://github.com/libjxl/libjxl/files/10123669/1935.zip)

The .zip above has a .jpg file named 1935.jpg

```bash
$bash: cjxl 1935.jpg 1935.jxl -p

# truncate .jxl to first 400kb
$bash: dd if=1935.jxl of=1935t.jxl bs=1 count=400000

# decode to jpg
$bash: djxl 1935t.jxl 1935t.jpg --allow_partial_files

JPEG XL decoder v0.7.0 f95da131 [AVX3,AVX2,SSE4,SSSE3,Unknown]
Read 400000 compressed bytes.
Input file is truncated and allow_partial_input was disabled.Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...
Decoded to pixels.
3000 x 4000, 68.78 MP/s [68.78, 68.78], 1 reps, 8 threads.
```

**Expected behavior**

`allow_partial_input` shouldn't be disabled because ` --allow_partial_files` is set. `allow_partial_input` is also not a cli option for djxl as of 0.7.

**Environment**
 - OS: `Linux 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux`
 - Compiler version: N/A. Using binaries from `jxl-linux-x86_64-static-v0.7.0.tar.gz` of [release 0.7.0](https://github.com/libjxl/libjxl/releases/tag/v0.7.0)
 - CPU type: x86_64
 - cjxl/djxl version string: Encoded with `JPEG XL encoder v0.7.0 f95da131 [AVX3,AVX2,SSE4,SSSE3,Unknown]`, decoded with `JPEG XL decoder v0.7.0 f95da131 [AVX3,AVX2,SSE4,SSSE3,Unknown]`

**Comment by mo271** [comment]
Thanks for the reporting this, @zeroby0!
