### ISSUE TITLE
JxlEncoderAddJPEGFrame() failed

### ISSUE THREAD

**Issue by Queuecumber** [libjxl/libjxl#1973]
**Describe the bug**
I'm transcoding a large (~1.3M) image dataset of JPEGs to JXL using the lossless transcoding. For 864 images I get the following error:

```
JPEG XL encoder v0.8.0 091b60e5 [AVX3,AVX2,SSE4,SSSE3,Unknown]                                                                                                                                                                   
Read JPEG image with 43279 bytes.
Encoding [Container | JPEG, lossless transcode, effort: 7 | JPEG reconstruction data], 
JxlEncoderAddJPEGFrame() failed.
EncodeImageJXL() failed.
```

running in verbose mode does not give any extra information. 

I've attached an example inside a zip file (in case github tries to mess with the image)

[n03476991_52119.zip](https://github.com/libjxl/libjxl/files/10230108/n03476991_52119.zip)

**To Reproduce**

```
cjxl --lossless_jpeg=1 n03476991_52119.JPEG ./test.jxl 
```
should reproduce the failure

**Expected behavior**
A JXL trancoding is produced

**Environment**
 - OS: Linux
 - Compiler version: n/a
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.8.0 091b60e5 [AVX3,AVX2,SSE4,SSSE3,Unknown]

**Comment by mo271** [comment]
Thank you for the bug report, @Queuecumber.

The ICC profile of the image you provide has a weird rendering intent. Those are stored in the bytes with offset 64 to 67 in the ICC profile.

Normally the bytes at offset 64, 65 and 66 should be zero and the byte with offset 67 should be one of 0, 1, 2, or 3. For your image the byte at offset 67 is 0, which should correspond to the rendering intent perceptual, but while the bytes at offset 65 and 66 are zero, the byte at offset 64 is 1. So stricly speaking, I guess this means the ICC profile announces the rendering intent to be $2^{24} = 16777216$, which does not correspond to anything useful. 
In fact checking with exiftool this is just what we see:
```
~/libjxl ((2a95fe4d…))> exiftool n03476991_52119.JPEG | grep Rend
Rendering Intent                : Unknown (16777216)
```
@Queuecumber could you check, e.g. with exiftool, what the Rendering Intent for the other 864 images is? If is is always $2^24$, there might be a problem with a tool generating the ICC profiles... 

I'm not entirely sure what we should do in the case that there is no valid rendering intent; I guess one possibility would be to separate the check we currently have in https://github.com/libjxl/libjxl/blob/2a95fe4d03080ffd82b654d0745f7d9f4e2cda94/lib/jxl/enc_color_management.cc#L892 into two checks:
 - one checking that rendering_intent32 > 3 and failing in this case
 - and one checking that the other three bytes are zero and only printing a warning in this case, showing the non-valid rendering intent.

**Comment by Queuecumber** [comment]
> could you check, e.g. with exiftool, what the Rendering Intent for the other 864 images is?

Yes I'll try to check on this ASAP, the our compute environment is currently having some issues.

These images actually come from the ImageNet dataset as we're evaluating JXL as a replacement for our JPEG based ML datasets, so the images are public (and often they're quite strange)

**Comment by mo271** [comment]
That is cool that you using JXL as replacement for JPEG in the ML dataset, we are happy to help to make that work and are of course interested in the cases where failures occur.

**Comment by Lantern47** [comment]
I've been having this same problem too. Currently using cjxl 0.9.0 and imlib2 1.12.1. I'm getting 

### Input:
`cjxl -v -v --num_threads=4 -e 9 "file.jpg" "file.jxl"`

### Output:
`JPEG XL encoder v0.9.0 [SSE2,Unknown]
Note: Implicit-default for JPEG is lossless-transcoding. To silence this message, set --lossless_jpeg=(1|0).
Read JPEG image with 110977 bytes.
Encoding [Container | JPEG, lossless transcode, effort: 9 | JPEG reconstruction data],
JxlEncoderAddJPEGFrame() failed.
EncodeImageJXL() failed.
`

In batch converting a directory of images I have consisting of pictures I took with my iphone, none could be successfully converted to .jxl except for all the pictures I'd previously mirrored horizontally using ImageMagick.
