### ISSUE TITLE
cjxl can encode XYB JPEG, but djxl fails to decode it

### ISSUE THREAD

**Issue by antermin** [libjxl/libjxl#1986]
**To Reproduce**
1. Download [this PNG](https://github.com/libjxl/conformance/raw/master/testcases/bench_oriented_brg/ref.png) which is taken from the conformance repo
2. Create XYB JPEG from it: `benchmark_xl --input=ref.png --codec=jpeg:libjxl:d1.0 --save_compressed --output_dir=./out`
3. Encode it to JXL, using the default lossless JPEG transcode: `cjxl ref.png.d1.0.libjxl.jpeg ref.png.d1.0.libjxl.jxl`
4. Try to decode it back to original JPEG: `jxl ref.png.d1.0.libjxl.jxl orig.jpg`

**Expected behavior**
djxl outputs an JPEG file which is identical to the original XYB JPEG.

**Actual behavior**
djxl fails with the following message:
```
JPEG XL decoder v0.7.0 f95da131 [AVX2,SSE4,SSSE3,Unknown]
Read 119401 compressed bytes.
Failed to decode image
Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...
Failed to decode image
DecompressJxlToPackedPixelFile failed
```

**Environment**
Arch x86_64 `cjxl`/`djxl` 0.7.0 (Arch Linux package) and `benchmark_xl` 0.8.0 `0a6bafee` (nightly CI artifact)

**Comment by mo271** [comment]
Thanks for the report, @antermin! I can repro the issue. Here a more verbose error message from a debug build:

```
~/libjxl ((2a95fe4d…))> ./build/tools/djxl ref.png.d1.0.libjxl.jxl orig.jpg

JPEG XL decoder v0.8.0 2a95fe4d [AVX3,AVX2,SSE4,SSSE3,Unknown]
Read 119401 compressed bytes.
./lib/jxl/modular/encoding/encoding.cc:566: JXL_FAILURE: Truncated input
./lib/jxl/modular/encoding/encoding.cc:597: JXL_RETURN_IF_ERROR code=1: dec_status
./lib/jxl/dec_modular.cc:413: JXL_FAILURE: Failed to decode modular DC group
./lib/jxl/dec_frame.cc:309: JXL_RETURN_IF_ERROR code=1: modular_frame_decoder_.DecodeVarDCTDC(dc_group_id, br, dec_state_)
./lib/jxl/dec_frame.cc:644: JXL_FAILURE: Error in DC group
./lib/jxl/decode.cc:1138: frame out of bounds
Failed to decode image
Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...
./lib/jxl/modular/encoding/encoding.cc:566: JXL_FAILURE: Truncated input
./lib/jxl/modular/encoding/encoding.cc:597: JXL_RETURN_IF_ERROR code=1: dec_status
./lib/jxl/dec_modular.cc:413: JXL_FAILURE: Failed to decode modular DC group
./lib/jxl/dec_frame.cc:309: JXL_RETURN_IF_ERROR code=1: modular_frame_decoder_.DecodeVarDCTDC(dc_group_id, br, dec_state_)
./lib/jxl/dec_frame.cc:644: JXL_FAILURE: Error in DC group
./lib/jxl/decode.cc:1138: frame out of bounds
Failed to decode image
DecompressJxlToPackedPixelFile failed
```
We should make sure that this doesn't happen...
