### ISSUE TITLE
Save EXIF box Sample Code

### ISSUE THREAD

**Issue by sati32** [libjxl/libjxl#2001]
Hi,

I use the lib not to convert pictures of any format, but to save pictures from an image processing software.
This way I have EXIF data or XMP data and want to save it inside the JPEG XL file.
There is a sample code, how to load the EXIF data, but I could find sample code how to write.
Can you help me?

**Comment by novomesk** [comment]
https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/common/file-jpegxl.c#L1867

**Comment by sati32** [comment]
Thank you very much. I will try it.

**Comment by mo271** [comment]
Closing this, feel free to re-open is concrete questions remain, or ask on [our discord](https://discord.gg/DqkQgDRTFu).
