### ISSUE TITLE
djxl no longer outputs all frames of animations

### ISSUE THREAD

**Issue by marto55555** [libjxl/libjxl#2016]
**Describe the bug**
In `djxl` v0.6.1 and earlier, decoding JXL animations would dump all image frames. Since v0.7.0, it only outputs 1 file and I cannot find a relevant option for it in the manpage.

**To Reproduce**
1. Unzip and use this as the input file - 
[animation.zip](https://github.com/libjxl/libjxl/files/10332992/animation.zip)
2. Run `djxl animated.jxl output.png`
3. Observe that only 1 output file was generated

**Expected behavior**
Because the input is an animation, it should generate multiple image frames: `output-0.png`, `output-1.png`...

**Environment**
 - OS: Windows 10, Ubuntu 20.04
 - CPU type: x86_64
 - cjxl/djxl version string: djxl v0.7.0 [SSE4,SSSE3,Unknown]

**Additional context**
I tried using wildcard (*) in the output filename, which didn't help either.

**Comment by mo271** [comment]
Thanks for the bug report, @marto55555. 

Perhaps something already went wrong during encoding, at least this is what I get for the `animation.jxl` in the file you provide.
```
jxlinfo animated.jxl 
JPEG XL animation, 320x320, (possibly) lossless, 8-bit RGB+Alpha
Color space: RGB, D65, sRGB primaries, sRGB transfer function, rendering intent: Perceptual
layer: full image size, duration: 0.0 ms
layer: 320x269 at position (0,51), duration: 0.0 ms
layer: 320x245 at position (0,68), duration: 0.0 ms
layer: 320x282 at position (0,23), duration: 0.0 ms
layer: 320x310 at position (0,10), duration: 0.0 ms
layer: 320x310 at position (0,10), duration: 0.0 ms
layer: 320x278 at position (0,42), duration: 0.0 ms
layer: 320x247 at position (0,62), duration: 0.0 ms
layer: 320x289 at position (0,31), duration: 0.0 ms
layer: 320x284 at position (0,31), duration: 0.0 ms
Animation length: 0.000 seconds (looping)
```
All those frames are coalesced into one, I suppose since they are of 0 duration.

Trying with another image, like with some from our conformance test
```
djxl ~/conformance/testcases/animation_icos4d/input.jxl out.apng
```
also gives you only one apng (or png) outfile, but that is actually an animation containing all the desired 48 frames.
And those could be decoded e.g. with ffmpeg, like
```
ffmpeg -i out.apng output-%03d.png
```
Does this help for your usecase?

**Comment by Traneptora** [comment]
> Thanks for your help, @mo271. You're right - in the new versions, the single output png is animated. What confused me is that I would specify `out.png` as opposed to `out.apng`, and still get a single animated png file.
> 
> The `ffmpeg` command helped solve my problem and replicate the old behavior.

Do keep in mind that officially, the extension for animated png is `.png` and not `.apng`. I do not know why this was chosen.
