### ISSUE TITLE
failed encoding from jpg with -e10

### ISSUE THREAD

**Issue by multiSnow** [libjxl/libjxl#2034]
**Describe the bug**
failed encoding from jpg with -e10

**To Reproduce**
```shell
cjxl flower.png.im_q85_rgb.jpg out.jxl --effort=10 --verbose
```
(found [flower.png.im_q85_rgb.jpg](https://github.com/libjxl/testdata/blob/81c7e5247c57051bf077b879ee38efd4c309c9e2/jxl/flower/flower.png.im_q85_rgb.jpg) in https://github.com/libjxl/testdata)

**Expected behavior**
exit code 0 with `out.jxl` as output

**Screenshots**
exit code 1
```
JPEG XL encoder v0.8.0 ee70a3ff [AVX2,SSE4,SSSE3,Unknown]
Note: Implicit-default for JPEG is lossless-transcoding. To silence this message, set --lossless_jpeg=(1|0).
Read JPEG image with 1382645 bytes.
Encoding [Container | JPEG, lossless transcode, effort: 10 | JPEG reconstruction data],
JxlEncoderProcessOutput failed.
EncodeImageJXL() failed.
```

**Environment**
 - OS: Linux
 - Compiler version: clang 15.0.6
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.8.0 ee70a3ff [AVX2,SSE4,SSSE3,Unknown]

**Additional context**
encoding with -e9 succeed.

**Comment by lectrode** [comment]
Here's a much smaller example image. This one fails immediately for quicker testing/diagnosis:
![tinier](https://user-images.githubusercontent.com/11493925/212388718-12b8cda7-bfb5-4f6a-95b7-d9c9a75375d6.jpg)

**Comment by lectrode** [comment]
Not strictly on topic for this issue, but in hopes of preventing others who are curious about e10 from needlessly turning their computers into space heaters: here are some stats from testing on one png file. I won't be trying it anymore - it's not worth it past the initial novelty.

Original image:
```
File size       : 1755344 Bytes (~1.7MiB)
MIME type       : image/png
Image size      : 1544 x 1649
```
Lossless, effort 7 (all threads): 7 seconds, 1007649 Bytes (57.40%)
Lossless, effort 8 (1 thread): 14 seconds, 973690 Bytes (55.47%)
Lossless, effort 9 (1 thread): 116 seconds, 904973 Bytes (51.56%)
Lossless, effort 10 (all threads): 22152 seconds (over 6 hours), 860175 Bytes (49.00%)


Time of execution jumped from under 2 minutes (e9) to well over 6 hours (e10). The code isn't lying when it says this method is "very slow".

**Comment by mo271** [comment]
Thanks for the report!

Regarding the last comment:
Meanwhile this flag comes with more of a warning, see
https://github.com/libjxl/libjxl/pull/2041
