### ISSUE TITLE
please update thirdparty/highway to v0.12.1 to unbreak aarch64 and possibly armv7

### ISSUE THREAD

**Issue by stefson** [libjxl/libjxl#21]
hello,

I'm on aarch64 and am trying to build a standalone of jpeg-xl to detect breakages. I have already done this with one of your dependencies called thirdparty/highway: https://github.com/google/highway/issues/93

the fix for aarch64 was published in v0.12.1 ; so can you please pull in the new version with your submodule magic?

thanks :-)

**Comment by stefson** [comment]
here is the build log for you: [neon-desaster.log.gz](https://github.com/libjxl/libjxl/files/6547054/neon-desaster.log.gz)

simply updating the third party highway to v0.12.1 will solve this, thank you

**Comment by deymo** [comment]
@stefson FYI, highway 0.12.1 changed the way the `HWY_COMPILE_ONLY_SCALAR` works in the unittests which we run in the scalar-only build (to make sure scalar-only builds still work). We would need this commit as well: https://github.com/google/highway/commit/69d77eb230cc0d918519110a0e7a8cb40c265e66

**Comment by stefson** [comment]
fair enough, take your time

**Comment by jan-wassenberg** [comment]
Fixed in #61.

**Comment by jan-wassenberg** [comment]
Not quite there yet, we have post-commit gitLab pipeline failures, reverting this and reopening.

**Comment by jan-wassenberg** [comment]
We resolved an issue with JNI in the JPEG XL builder and re-landed the Highway update :)

**Comment by deymo** [comment]
hwy 0.12.2 breaks for debian:buster, it compiles for gcc-8 which hits a compiler bug in the logical_test.cc

**Comment by stefson** [comment]
@deymo can you be so kind to link back the debian issue or bug, please?

**Comment by deymo** [comment]
@stefson This has the repro instructions https://github.com/google/highway/issues/217
