### ISSUE TITLE
image saturation difference between jpg and lossless jxl

### ISSUE THREAD

**Issue by karoberts** [libjxl/libjxl#2105]
**Describe the bug**
I have a jpg that was saved from Photoshop.  I converted it to jxl using `cjxl image.jpg image.jxl`
When viewing the two images in ImageGlass (8.7.11.6), there is a distinct difference in the color output in the jxl vs the jpg.
The good news is that running the opposite `djxl image.jxl image2.jpg` produces an output jpg that is identical to the original.
From my tests, this only seems to happen with images saved from photoshop.  I assume it has something to do with color profiles, but I'm not quite well versed enough in that to understand the difference.

**To Reproduce**
Take jxltest.jpg and run `cjxl jxltest.jpg jxltest.jxl`
compare visually in ImageGlass

**Expected behavior**
I expected the jxl to appear visually identical to the original jpeg.

**Screenshots**
original (crop): 
![jxltest](https://user-images.githubusercontent.com/7482126/214657477-26d784af-5ed5-4eb1-af81-44004b572734.jpg)

jxl:
![jxltest jxl](https://user-images.githubusercontent.com/7482126/214659391-afc84972-5a95-40f7-a2b4-aa470c6adf11.jpg)

viewing both in ImageGlass (I'm not sure why my screencap shows less saturated for both, on my screen the left is identical to the original.  however, you can still see the saturation difference)
![2023-01-25_11h00_26](https://user-images.githubusercontent.com/7482126/214658056-01497b61-c908-41c2-830b-397fd0143c18.png)

**Environment**
 - OS: **Ubuntu 22.04.1 [wsl under Windows 10]**
 - Compiler version: **clang 14.0.0-1ubunut1**
 - CPU type: **x86_64**
 - cjxl/djxl version string: **cjxl v0.9.0 aa99c8d8 [AVX2,SSE4,SSSE3,Unknown]**

**Comment by mo271** [comment]
Thank you for opening an issue about that, @karoberts!

This sounds very similar to the problem described in https://github.com/libjxl/libjxl/issues/2070
In fact, currently the chrome browser I'm using displays the images in the issue:
![libjxl2105](https://user-images.githubusercontent.com/3491627/214793500-433c2891-7c09-4a0a-a188-e3f548e1c5f7.png)
and they look identical.

I suspect that comes from a problem with the image viewer you are using.

**Comment by karoberts** [comment]
@mo271 I see that.  I opened both with IMDisplay (simple viewer that comes with imagemagick), and they appear identical.  I'll submit this to ImageGlass.
