### ISSUE TITLE
build failure on aarch64-linux due to `skcms` triggering GCC internal compiler error

### ISSUE THREAD

**Issue by nh2** [libjxl/libjxl#213]
I packaged `libjxl` for nixpkgs; the `x86_64-linux` build works fine, but the `aarch64-linux` fails because apparently `skcms` triggers a GCC 9.3.0 `internal  compiler error`:

https://github.com/NixOS/nixpkgs/pull/103160#issuecomment-866388610

Since this is just a free-time experiment for me and I don't have time to chase this up to skia or GCC, I'm reporting it here in case you are interested in following up on it.

**Comment by mo271** [comment]
Seems like this is resolved.
