### ISSUE TITLE
Can't seem to find JPEG XL GDK Pixbuf

### ISSUE THREAD

**Issue by lodx-xd** [libjxl/libjxl#2139]
**Describe the bug**
Installation following the https://github.com/libjxl/libjxl/blob/main/README.md does not seem to be compiling/installing JPEG XL GDK Pixbuf (libpixbufloader-jxl.so) neither jxl.thumbnailer.

The libpixbufloader-jxl.so file is also not present in the build folder to be manually copied as described at https://github.com/libjxl/libjxl/tree/main/plugins/gdk-pixbuf#jpeg-xl-gdk-pixbuf.

The jxl.thumbnailer is already present when you clone the project, so is possible to install it manually.

**To Reproduce**
Just follow the installation steps at https://github.com/libjxl/libjxl/blob/main/README.md#compilation

**Expected behavior**
Have the files installed automatically as cited at https://github.com/libjxl/libjxl/tree/main/plugins/gdk-pixbuf#jpeg-xl-gdk-pixbuf or have the same available to be copied manually.

**Environment**
 - OS: Pop!_OS 22.04 LTS
 - Compiler version: clang 1:14.0-55~exp2
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.9.0 4112b8a9 [AVX2,SSE4,SSSE3,Unknown] | JPEG XL decoder v0.9.0 4112b8a9 [AVX2,SSE4,SSSE3,Unknown]

**Additional context**
Personal context, I'm not a new Linux user, but I have very little experience compiling projects.

**Comment by alistair7** [comment]
Try adding `-DJPEGXL_ENABLE_PLUGINS=ON` to your cmake command.  That option could be advertised a little better...

**Comment by kmilos** [comment]
> Try adding `-DJPEGXL_ENABLE_PLUGINS=ON` to your cmake command. That option could be advertised a little better...

This is already enabled by default.

Look at CMake messages regarding gdk-pixbuf...

**Comment by lodx-xd** [comment]
> > Try adding `-DJPEGXL_ENABLE_PLUGINS=ON` to your cmake command. That option could be advertised a little better...
> 
> This is already enabled by default.
> 
> Look at CMake messages regarding gdk-pixbuf...

I don't know if something has changed recently, but in my case it was really the lack of the `-DJPEGXL_ENABLE_PLUGINS=ON` option, after including it both libpixbufloader-jxl.so and jxl.thumbnailer was compiled and installed successfully.

Thank you all for your help.

**Comment by kmilos** [comment]
Ah, sorry, wrong option, so indeed that was it: JPEGXL_ENABLE_PLUGIN_GDKPIXBUF is ON by default, but not effective unless JPEGXL_ENABLE_PLUGINS is set first.

**Comment by mo271** [comment]
Thanks for the report. Let's see how we can improve documentation for that...
