### ISSUE TITLE
Expose APIs for crop coordinates/unblended frames

### ISSUE THREAD

**Issue by ishitatsuyuki** [libjxl/libjxl#217]
**Is your feature request related to a problem? Please describe.**
JPEG XL seems to have several features that allows it to be a PSD replacement, but all the necessary metadata is currently encapsulated in the internal API. The only thing that is possible with the current API is to convert a PSD to JXL (the inverse conversion is not implemented). In any other cases, only the final blended image is accessible.

The feature request aims to make it possible to manipulate layered JXL images in image editor applications. To do that, the API needs to support reading and writing unblended images with their crop coordinates.

**Describe the solution you'd like**
The encoder can already take the input frame by frame. Therefore this could be implemented by allowing additional metadata (crop coordinates, blend mode) when calling `JxlEncoderAddImageFrame`.

The decoder can handle the output frame by frame as well, but the API is currently intended for full-sized frames. I propose to add an decoder option that, when enabled, outputs unblended, cropped frames. The current `JXL_DEC_FRAME` and `JXL_DEC_NEED_IMAGE_OUT_BUFFER` events could be reused to inform the application to resize the buffer when necessary.

**Describe alternatives you've considered**
TBD. The proposal is subject to change.

**Unresolved questions**
- Should we expose internal frames? For PSD-like usecases it's likely not used, but it might be useful for parsing animation files.
- Should we allow the application to have control over reference frames? This could be used control the "preferred final image", where some layers are hidden by default. It could also be used to create images where there's one "base" layer and multiple switchable "patch" layers, and the switchable variants would only depend on the base frame instead of sequentially depending on previous frames.

**Comment by jonsneyers** [comment]
The decode side of this is currently being proposed/discussed here: https://github.com/libjxl/libjxl/pull/831

As for the encode side: I think we should expose at least enough to make it possible to do through the API what cjxl is currently doing with PSD, GIF or APNG input. But imo it's best to first get the decode side done and make the encode api as symmetric as possible to the decode api.

**Comment by mo271** [comment]
This should now be implemented.
