### ISSUE TITLE
2021-08_totocaca.jxl: Failed to decode image 

### ISSUE THREAD

**Issue by guijan** [libjxl/libjxl#2171]
**Describe the bug**
Can't decode [2021-08_totocaca.jxl](https://jpegxl.info/art/2021-08_totocaca.jxl) from https://jpegxl.info/art

**To Reproduce**
libjxl version:
b28f9ffa62a7d469915ab8c37c61ad4e93343812
submodule versions:
 1405a214a8232991c585dc2164b5dec5bd559a33 testdata (1405a21)
 36533a866ed1ca4b75cf049f4521e4ec5fe24727 third_party/brotli (36533a8)
 58d77fa8070e8cec2dc1ed015d66b454c8d78850 third_party/googletest (release-1.12.1)
 58746ca5b9f9444a2a3549704602ecc6239f8f41 third_party/highway (1.0.3)
 65c63bf549d78253c14b30b3d62cb668bbbe612c third_party/lcms (65c63bf)
 a40189cf881e9f0db80511c382292a5604c3c3d1 third_party/libpng (v1.6.37)
 868ab558fad70fcbe8863ba4e85179eeb81cc840 third_party/sjpeg (868ab55)
 b25b07b4b07990811de121c0356155b2ba0f4318 third_party/skcms (b25b07b)
 cacf7f1d4e3d44d871b605da3b647f07d718623f third_party/zlib (v1.2.11)

Compile a checkout of those commit hashes with this command line:
```console
$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_JPEGLI=OFF -DJPEGXL_ENABLE_JNI=OFF -DJPEGXL_ENABLE_TCMALLOC=OFF -B build -G Ninja && cmake --build build
```
Then try decode [2021-08_totocaca.jxl](https://jpegxl.info/art/2021-08_totocaca.jxl) from the jxl art web page:
```console
$ djxl 2021-08_totocaca.jxl test.jpg
```
You will get error output like this:
```plain
JPEG XL decoder v0.9.0 b28f9ffa [AVX2,SSE4,SSSE3,Unknown]
Read 81 compressed bytes.
Warning: could not decode losslessly to JPEG. Retrying with --pixels_to_jpeg...
./lib/extras/enc/encode.cc:135: encoding 10-bit original to 8 bits
./lib/jxl/splines.cc:645: JXL_FAILURE: Too many pixels covered with splines
./lib/jxl/dec_frame.cc:290: JXL_RETURN_IF_ERROR code=1: shared.image_features.splines.InitializeDrawCache( frame_dim_.xsize_upsampled, frame_dim_.ysize_upsampled, dec_state_->shared->cmap)
./lib/jxl/decode.cc:1149: frame processing failed
Failed to decode image
DecompressJxlToPackedPixelFile failed
```
The instructions try to perfectly replicate my setup, but it shouldn't matter, the errors are explicit checks in the code failing.

**Screenshots**
![2023-02-09-121638_1920x210_scrot](https://user-images.githubusercontent.com/25590950/217812138-1caabf61-7e34-4e45-9cb2-1902e48cfa35.png)

**Environment**
 - OS: OpenBSD 7.2 amd64
 - Compiler version: Clang 13.0.0 from the OpenBSD base system
 - CPU type: Intel Core i7 4770, i.e. Haswell
 - cjxl/djxl version string: JPEG XL decoder v0.9.0 b28f9ffa [AVX2,SSE4,SSSE3,Unknown]

**Comment by mo271** [comment]
Thanks for the bug report!

This is probably caused by https://github.com/libjxl/libjxl/pull/2081. 
We introduced spline limits, to avoid that the decoder has to do some work. It is expected that some of the jxl-art images, that heavily rely on the spline feature won't work anymore.

**Comment by jonsneyers** [comment]
> Thanks for the bug report!
> 
> This is probably caused by #2081. We introduced spline limits, to avoid that the decoder has to do some work. It is expected that some of the jxl-art images, that heavily rely on the spline feature won't work anymore.

Didn't we set the limits high enough to make that particular image decode though? I know it didn't decode anymore with the previous spline limits, but with the new spline limits I thought this one was going to decode. But maybe we haven't actually removed the old limits yet, and now we have both?
