### ISSUE TITLE
Installation of plugin mime and thumbnailer files doesn't respect DATAROOTDIR

### ISSUE THREAD

**Issue by kepstin** [libjxl/libjxl#2183]
If the build is done on a Linux distribution where the DATADIR is in a location other than `${CMAKE_INSTALL_PREFIX}/share`, then the data files for plugins - the mime `packages/image-jxl.xml` file, and thumbnailers `jxl.thumbnailer` file in particular - will be installed in the wrong location.

An example is in [Exherbo](https://www.exherbo.org/), where our standard cmake path setup uses `-DCMAKE_INSTALL_PREFIX:PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_INSTALL_DATAROOTDIR:PATH=/usr/share/`. The data files get installed to `/usr/x86_64-pc-linux-gnu/share/` instead of the desired `/usr/share/`.

The fix is that these files should be installed using the [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs) `${CMAKE_INSTALL_DATADIR}` variable instead of a hardcoded `share` path.

**Comment by kmilos** [comment]
In addition, the MIME file should probably be dropped, as image/jxl is already a part of shared-mime- info: https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/data/freedesktop.org.xml.in

**Comment by thebombzen** [comment]
Was this fixed by #2247?
