### ISSUE TITLE
Brotli libraries are not copied to the installation directory

### ISSUE THREAD

**Issue by sincos2854** [libjxl/libjxl#2185]
**Describe the bug**
Brotli libraries(.dll and .lib) are not copied to the installation directory specified by -DCMAKE_INSTALL_PREFIX.
They exist in the build directory, so they are simply not copied.

**To Reproduce**
Execute cmake.

**Expected behavior**
Brotli libraries must be copied into the installation directory.

**Screenshots**
None.

**Environment**
 - OS: Windows 10 Pro x64 22H2 build 19045.2546
 - Compiler version: Microsoft(R) C/C++ Optimizing Compiler Version 19.34.31937 for x64
 - CPU type: Intel x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.9.0 6280645e [AVX2,SSE4,SSSE3,Unknown]

**Additional context**
None.

**Comment by kleisauke** [comment]
PR https://github.com/libjxl/libjxl/pull/2145 would probably fix this.

**Comment by sincos2854** [comment]
I understand.
Thank you very much.

**Comment by mo271** [comment]
Please check that this was fixed by #2145 and reopen if there is still a problem.
