### ISSUE TITLE
Encode effort 10 missing from encoder

### ISSUE THREAD

**Issue by woot000** [libjxl/libjxl#2196]
I just compiled a recent version of cjxl (JPEG XL encoder v0.9.0 ed027ed5 [AVX3], this commit 5e222241cb6a2630fc2f4356b21b448088125bde), and the recently added encode effort level 10 isn't available. Has it been removed? It's still [referenced in the docs](https://github.com/libjxl/libjxl/blob/main/doc/encode_effort.md) as a setting in the encoder.

**Comment by jonsneyers** [comment]
You need to use `cjxl --allow_expert_options -d 0 -e 10`. Be warned: it is very slow.
