### ISSUE TITLE
benchmark_xl fails to encode with jpegli when compiled with `-D_GLIBCXX_ASSERTIONS`

### ISSUE THREAD

**Issue by louie-github** [libjxl/libjxl#2207]
**Describe the bug**
When you compile `benchmark_xl` with `-D_GLIBCXX_ASSERTIONS`, as is done by default on Arch, it often fails to encode with jpegli.
Error is listed as below:
```
❯ ~/dev/libjxl/build/tools/benchmark_xl --input=jpegxl-home.jpg --codec=jpeg:enc-jpegli:xyb:q87 --save_compressed --output_dir=jpegxl-home
benchmark_xl v0.9.0 7566e4c8 [AVX2,SSE4,SSSE3,Unknown]
8 total threads, 1 tasks, 0 threads, 8 inner threads
/usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/stl_vector.h:1123: std::vector::reference std::vector<jpegli::JPEGHuffmanCode>::operator[](std::vector::size_type) [_Tp = jpegli::JPEGHuffmanCode, _Alloc = std::allocator<jpegli::JPEGHuffmanCode>]: Assertion '__n < this->size()' failed.
[1]    11439 IOT instruction  ~/dev/libjxl/build/tools/benchmark_xl --input=jpegxl-home.jpg
```

**To Reproduce**
Use any image, for exact reproduction use the image at https://jpeg.org/images/jpegxl-home.jpg (JPEG XL info page at JPEG website).
Compile `benchmark_xl` with `-D_GLIBCXX_ASSERTIONS`, for example with `-DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS"`.

Try to encode using `benchmark_xl` with codec `jpeg:enc-jpegli:xyb:q87`, changing the quality if you want. Most of the time (but not all the time, for example if you change the quality), the encoding will error out.

**Expected behavior**
`benchmark_xl` encodes successfully whether `_GLIBCXX_ASSERTIONS` is defined or not.

**Environment**
 - OS: Arch on WSL 2
 - Compiler version: clang 15.0.7
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.9.0 7566e4c8 [AVX2,SSE4,SSSE3,Unknown]

**Comment by gianni-rosato** [comment]
I'm experiencing periodic crashing & failure to compress certain images at certain resolutions because of this. It'd be great if this could be resolved soon!

**Comment by szabadka** [comment]
Could you verify that PR #2209 fixed it?

**Comment by louie-github** [comment]
Yes, that seems to have fixed it. Thank you very much!
