### ISSUE TITLE
GIMP plugin fails to open JXLs which were transcoded from JPEG

### ISSUE THREAD

**Issue by cagelight** [libjxl/libjxl#229]
Arch Linux
GCC 11.1.0
JPEG XL encoder v0.3.7 [AVX2,SSE4,Scalar]

I tried to load an assortment of JXL images and there seems to be a bug specifically with JXLs that were transcoded from JPEG, it only seems to happen to the GIMP plugin specifically.

The issue does not occur with lossless JXL, or JXLs encoded with a -q < 100, only JPEG -> JXL

I get a GIMP error: "Opening '...' failed: JPEG XL image plug-in could not open image"
and then the following output in the console:
```
/home/.cache/yay/libjxl-git/src/libjxl/lib/jxl/image_metadata.cc:354: JXL_FAILURE: invalid min 0.001234 vs max 0.001001
/home/.cache/yay/libjxl-git/src/libjxl/lib/jxl/fields.cc:697: JXL_RETURN_IF_ERROR code=1: visitor.Visit(fields, PrintVisitors() ? "-- Read\n" : "")
/home/.cache/yay/libjxl-git/src/libjxl/lib/jxl/dec_file.cc:33: JXL_RETURN_IF_ERROR code=1: ReadImageMetadata(reader, &io->metadata.m)
/home/.cache/yay/libjxl-git/src/libjxl/lib/jxl/dec_file.cc:108: JXL_RETURN_IF_ERROR code=1: DecodeHeaders(&reader, io)
/home/.cache/yay/libjxl-git/src/libjxl/plugins/gimp/file-jxl-load.cc:95: JXL_RETURN_IF_ERROR code=1: DecodeFile(dparams, compressed, &io, &pool)
```

**Comment by ToBeFree** [comment]
Confirmed. I thought I had compiled this incorrectly.

**Comment by ToBeFree** [comment]
Example image (public domain) that can't be opened by the GIMP plugin:
[publicdomain-green-butterfly-2-avatar-scale100px-lossless.zip](https://github.com/libjxl/libjxl/files/6719948/publicdomain-green-butterfly-2-avatar-scale100px-lossless.zip)

Source image:
![publicdomain-green-butterfly-2-avatar-scale100px](https://user-images.githubusercontent.com/66693882/123510229-99d29100-d67a-11eb-9e0e-5b1417be32b4.jpg)

Converted using cjxl [v0.3.7 | SIMD supported: AVX2,SSE4,Scalar] -q 100 -s 8

I don't know how to enable the plugin's debug output, though; GIMP just gives me "GIMP-Error: Opening '/home/tobefree/Bilder/publicdomain-green-butterfly-2-avatar-scale100px-lossless.jxl' failed: JPEG XL image plug-in could not open image" when opening the image by typing "gimp --verbose -c filename.jxl" into bash.

**Comment by BlueSwordM** [comment]
So, this bug seems to be related to 2 things:
1. Lossless JPEG recompression does not work at all with Gimp.
2. With the EXIF profile kept and doing normal varDCT compression, Gimp can't open the picture linked above as well.

**Comment by sboukortt** [comment]
Something that those two cases share is that they use the container format, so the problem may have to do with that.

**Comment by jonsneyers** [comment]
Supposedly fixed, please reopen if needed.
