### ISSUE TITLE
Saved jpg to PNG, then converted to JXL resulting in bigger file size

### ISSUE THREAD

**Issue by gin9980** [libjxl/libjxl#2290]
**Describe the bug**
I saved a 598KB jpg file to a PNG 3.2MB loslessly using photoshop. Then using CJXL I converted the PNG to jxl using --distance 0 --effort 9 and it resulted in a 2.09MB JXL file that is still bigger than the JPG orignal file.

**To Reproduce**
convert jpg to png
convert the png to jxl using --distance 0 --effort 9

**Expected behavior**
expected the jxl file to have a smaller size than the orignal JPG file

**Environment**
 - OS: Windows 10
 - Compiler version: [e.g. clang 11.0.1]
 - CPU type: 13900k
 - cjxl/djxl version string: v0.8.1

**Additional context**
I originally tried to convert the jpg to JXL but it never comes out pixel to pixel lossless and there is always a difference in pixel color using --distance 0 --effort 9

**Comment by jonsneyers** [comment]
Try `cjxl input.jpg output.jxl`. This is lossless and should be smaller than the jpeg. If you don't believe it is lossless, try `djxl output.jxl output.jpg` and then compare the two jpeg files. They should be bit identical.

Getting pixel differences between the result of using one jpeg decoder (say libjpeg-turbo) and another (say libjxl) is perfectly normal. The jpeg format is not fully specified, so there are differences between conforming decoders. In particular, the commonly used libjpeg-turbo is less accurate than libjxl (it prioritizes speed over precision).

**Comment by gin9980** [comment]
> Try `cjxl input.jpg output.jxl`. This is lossless and should be smaller than the jpeg. If you don't believe it is lossless, try `djxl output.jxl output.jpg` and then compare the two jpeg files. They should be bit identical.
> 
> Getting pixel differences between the result of using one jpeg decoder (say libjpeg-turbo) and another (say libjxl) is perfectly normal. The jpeg format is not fully specified, so there are differences between conforming decoders. In particular, the commonly used libjpeg-turbo is less accurate than libjxl (it prioritizes speed over precision).

Thanks it converts back without any loss using djxl.
