### ISSUE TITLE
Fast lossless incorrectly encodes grayscale+alpha image

### ISSUE THREAD

**Issue by etemesi254** [libjxl/libjxl#2331]
**Describe the bug**
When encoding losless images with the fast lossless [encoder](https://github.com/libjxl/libjxl/tree/main/experimental/fast_lossless), the encoder creates images the decoder cannot parse

**To Reproduce**

The below image 
![relax_](https://user-images.githubusercontent.com/24320659/227614354-efc7f745-8640-4228-83ba-7e2a57ff10e5.png)

was used as the test sample

**Expected behavior**
An image encoded to` .jxl` which could be decoded back to the expected input using the fast encoder

 - OS: Manjaro Linux
 - Compiler version:  GCC 12.2.1
 - CPU type: x86_64

**Additional context**
- Removing the alpha channel makes the encoder produce a working image.

- The cjxl encoder generates a decodable image.

the first generated bytes are 
|cjxl|fast_lossless|
|-----|-----------------|
|ff 0a fa 15 e0 3f 58 09  08 08 10 00 84 02 00 00|   ff 0a fa 15 e0 3f 58 14  37 02 08 08 10 00 30 0b|

The only weird behaviour I could note was that jxlinfo interpreted the output as RGB+A

Command
```sh
jxlinfo -v ./a.jxl
```
output was 

```text
JPEG XL image, 512x704, (possibly) lossless, 8-bit RGB+Alpha
num_color_channels: 3
num_extra_channels: 1
extra channel 0:
  type: Alpha
  bits_per_sample: 8
  alpha_premultiplied: 0 (Non-premultiplied)
have_preview: 0
have_animation: 0
Intrinsic dimensions: 512x704
Orientation: 1 (Normal)
Color space: RGB, D65, sRGB primaries, sRGB transfer function, rendering intent: Relative
```

There is also a huge difference in size, when using cjxl and fast encoder, (53k vs 33k), is there something I'm missing?

**sample outputs**
- wrong-image: Output of what I got after encoding with fast lossless encoder
- correct-working-jxl-image: Working image 
- input.ppm.txt: Input image, P7 ppm format in grayscale+alpha

![wrong_image](https://user-images.githubusercontent.com/24320659/227618962-f8c3ef62-7806-4554-83db-f55772432343.jpg)

![correct working jxl image](https://user-images.githubusercontent.com/24320659/227619209-35d72522-e1fb-4685-8783-d4dbb1b8c331.jpg)

[input.ppm.txt](https://github.com/libjxl/libjxl/files/11065827/a.ppm.txt)

**Comment by veluca93** [comment]
Does the issue still happen on github-main? I cannot seem to reproduce it...
Can you give more details on how you compiled and ran fast-lossless?

**Comment by etemesi254** [comment]
> Can you give more details on how you compiled and ran fast-lossless?

I copied enc_fast_lossless.cpp from the repo into a project, and added the main repo which simply calls the PPM reader and writes to a jxl file.

The file was simplified to meet my needs, i.e  a little less template code and removed the intrinsics support for easier debugging.

The enc fast lossless code comes to about 2k LOC , https://gist.github.com/etemesi254/09f66aeab2d38b6b3ef358c3ec9a8a96

**Comment by etemesi254** [comment]
> Does the issue still happen on github-main? I cannot seem to reproduce it...

Yes it does,  attached simple setup I'm using. Use input.ppm as it contains the necessary headers for luma+alpha support, 

[simple_jxl.zip](https://github.com/libjxl/libjxl/files/11115191/simple_jxl.zip)
