### ISSUE TITLE
Lossless JPEG -e 3 smaller than -e 9

### ISSUE THREAD

**Issue by TheHardew** [libjxl/libjxl#235]
**Describe the bug**
`-e 3` produces a smaller file than `-e 9` when losslessly compressing the attached jpg.

**To Reproduce**
```
cjxl -e 3 a.jpg a-3.jxl
cjxl -e 9 a.jpg a-9.jxl
du -b *

JPEG XL encoder v0.3.7 [AVX2]
Read 1200x1000 image, 112.8 MP/s
Encoding [Container | JPEG, lossless transcode, falcon | JPEG reconstruction data], 4 threads.
Compressed to 127967 bytes (0.853 bpp).
1200 x 1000, 30.81 MP/s [30.81, 30.81], 1 reps, 4 threads.
Including container: 128487 bytes (0.857 bpp).
JPEG XL encoder v0.3.7 [AVX2]
Read 1200x1000 image, 104.5 MP/s
Encoding [Container | JPEG, lossless transcode, tortoise | JPEG reconstruction data], 4 threads.
Compressed to 128733 bytes (0.858 bpp).
1200 x 1000, 0.42 MP/s [0.42, 0.42], 1 reps, 4 threads.
Including container: 129253 bytes (0.862 bpp).
128487	a-3.jxl
129253	a-9.jxl
161639	a.jpg
```

**Expected behavior**
`-e 9` should produce the smallest files out of all the presets.

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 12.0.0
 - CPU type: ryzen 3500U x86_64
 - cjxl/djxl version string: f8790509f3588413413682b611cf11f18f4498b1

**Additional context**
Compiled with https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libjxl-git and
```
CFLAGS="-march=native -O3 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fno-plt -pthread -Wno-error -w"
CXXFLAGS="$CFLAGS"
```

https://user-images.githubusercontent.com/7374061/123633993-2cf5fd00-d81a-11eb-8be1-150ac3fbdd95.jpg

**Comment by jonsneyers** [comment]
Interesting. This seems to happen on other JPEG images too. The difference is in the density of the AC encoding. This suggests there is room for improvement at the slower speeds - if they are often worse than falcon speed, they must be doing something not-great for jpeg recompression...

**Comment by jonsneyers** [comment]
Looks like it's the coefficient reordering can be counterproductive in the case of JPEG recompression. At `-e 3` that is disabled (the default zigzag order is used), while at higher effort a reordering is done to move coefficients with more zeroes towards the back for better compression — except it isn't _guaranteed_ to actually give better compression.
