### ISSUE TITLE
Compressing a sample PNG file results in a 4x-sized file

### ISSUE THREAD

**Issue by danielyli** [libjxl/libjxl#2381]
**Describe the bug**

I’ve attached a sample PNG file (3.9 MB) that, when compressed by `cjxl` using defaults, results in a 16 MB jxl file (also attached).

Note that I’ve had to split the output jxl file into two pieces to accommodate GitHub’s file size limits. To reconstruct the output jxl file, `cat` the two pieces together. The SHA-256 is `ae08800074b745a1a2f0faec7ae4ff893f1f5d4279443810371d388804197e91`.

**To Reproduce**

```
$ cjxl reddit-place-2022.png reddit-place-2022.jxl
JPEG XL encoder v0.8.1 0.8.1 [NEON]
Read 6000x6120 image, 4096280 bytes, 358.2 MP/s
Encoding [VarDCT, d1.000, effort: 7],
Compressed to 16288694 bytes (3.549 bpp).
6000 x 6120, 4.69 MP/s [4.69, 4.69], 1 reps, 10 threads.

$ du -sh reddit-place-2022.*
 16M	reddit-place-2022.jxl
3.9M	reddit-place-2022.png
```

**Expected behavior**

Output JXL file should be smaller, or at least same size, as input. Definitely not >4x larger.

**Screenshots**

Please see attached files.

**Environment**
 - OS: macOS 13.2.1
 - Compiler version: Installed via Homebrew formula from tap
 - CPU type: apple arm
 - cjxl/djxl version string: cjxl v0.8.1 0.8.1 [NEON]

![reddit-place-2022-input](https://user-images.githubusercontent.com/1744438/232173534-bc3f6dae-2251-44a7-9bff-d26be9185c8c.png)
![reddit-place-2022-output-part1](https://user-images.githubusercontent.com/1744438/232173703-f73f2d72-6a88-4a42-84b8-a80d9b3c5bdc.jpg)
![reddit-place-2022-output-part2](https://user-images.githubusercontent.com/1744438/232173713-60406a8c-7068-4c55-9b76-4a3e6f2aa5e3.jpg)

**Comment by goodusername123** [comment]
Putting a PNG file directly into cjxl without any other options will result in it using the lossy side of JPEG-XL called "VarDCT". What you want to use for a image like this is the lossless side of JPEG-XL called "Modular" which can be done by adding "-q 100" to the command line which would look something like this: "cjxl -q 100 reddit-place-2022.png reddit-place-2022.jxl"

**Comment by danielyli** [comment]
Didn’t know that about the VarDCT. Appreciate the explanation.

I wonder though, let’s say I do want lossy compression of the file. Is it an expected edge case that JPEG-XL will perform worse than the input PNG for high `-q` values?

**Comment by danielyli** [comment]
I was curious if this performance issue might be related to the peculiar nature of the input file: colors are strictly in blocks of 3x3 pixels. See this zoomed in crop:

![detail](https://user-images.githubusercontent.com/1744438/232175976-7368f589-98f0-47b0-aa0f-5ea734e644a7.png)

I downsampled the input by 3 in both x- and y- and then recompressed using `cjxl` (again, default settings, so didn’t use `-q`). The output was essentially the same size as the input file (both are attached), which makes me suspect it’s the 3x3 blocks that are creating an edge case for `cjxl`.

![downsampled](https://user-images.githubusercontent.com/1744438/232176143-e6f05a80-8034-45ff-bd70-d5498b0fd2b5.png)
![downsampled jxl](https://user-images.githubusercontent.com/1744438/232176146-9b89ce0f-b6a1-4204-83f5-a5e28de8e4c1.jpg)

**Comment by goodusername123** [comment]
`-q` values of anything other then `100` will result in VarDCT being used while using exactly `100` will result in Modular being used.

compressing the full PNG you have posted as a Modular JXL results in final file size going from around 4MB to 1.4MB compared with the giant size that happened with VarDCT (the PNG also went down to 1.4MB when I put it into a lossless PNG optimizer) and this is because there are quite a lot of cases where a lossless compression method will do way better then a lossy one which is not exclusive to JPEG-XL but is something that happens with all image formats such as PNG vs JPEG, WebP lossy vs WebP lossless and other similar comparisons, a general rule of thumb is images that are flat and or have lots of solid repeating colors such as logos, digital art with a flatter style, pixel art and the image you have posted will compress better with a lossless compression method while images that are visually noisy such as photographs from any type of camera would compress better with a lossy compression method.

I even tested to see how a optimized JPEG would do when trying to compress the full PNG and it resulted in a file size that was worse then the VarDCT JXL.

**Comment by goodusername123** [comment]
It would be nice if libjxl/cjxl could automatically try to determine if lossy or lossless compression would be better for a image when you put it in however currently that doesn't happen so you need to manually change `-q` to switch between VarDCT or Modular per image, this is an issue that other encoders for other image formats have had in the past such as for WebP with libwebp/cwebp where you need to manually decide between lossy or lossless for each image.

**Comment by danielyli** [comment]
> there are quite a lot of cases where a lossless compression method will do way better then a lossy one which is not exclusive to JPEG-XL but is something that happens with all image formats such as PNG vs JPEG

Ah you're right, this issue isn't jxl-specific, how did I forget.

I think the confusion came from the mistaken expectation that `cjxl`’s defaults always give a desirable output, as claimed by a [Cloudinary article comparing different image codecs](https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs#fool_proof_default_quality). In the article, they claim “fool-proof default quality” and use an example PNG image (2.6 MB) and show that the output JXL is indistinguishable (53 KB). They write:

> The JPEG XL reference encoder (cjpegxl) produces, by default, a well-compressed image that is indistinguishable from (or, in some cases, identical to) the original.

I think your suggestion of having `cjxl` automatically choose between lossy and lossless would be ideal here. In addition to better default results, it wouldn’t give any erroneous fodder to claims of poor outputs!

**Comment by danielyli** [comment]
Closing this issue, since the underlying feature request is now in a separate ticket.
