### ISSUE TITLE
Decoding seems to have a memory leak

### ISSUE THREAD

**Issue by liuxunfei** [libjxl/libjxl#2386]
![image](https://user-images.githubusercontent.com/41775496/232370086-4896d8e3-2839-4485-afd6-2924ced717bf.png)
After two days of pressure testing and decoding, it leaked over 100 M and used version 0.8.1

**Comment by mo271** [comment]
Thanks for the report!
Can you give some hints to to reproduce the memory leak you mention?

**Comment by eustas** [comment]
Likely https://github.com/libjxl/libjxl/pull/2416
