### ISSUE TITLE
A number of tests fail on ppc32: 69% tests passed, 1077 tests failed out of 3488

### ISSUE THREAD

**Issue by barracuda156** [libjxl/libjxl#2390]
I attach the log, it is huge to quote. (Notice, this is in Rosetta, so if something relies on physical cpu detection instead of compiler-passed settings, it may fail.)

**Environment**
 - OS: macOS 10.6.8 Rosetta
 - Compiler version: gcc 12.2.0
 - CPU type: ppc (emulated)
[libjxl_tests_macOS_ppc.txt](https://github.com/libjxl/libjxl/files/11249767/libjxl_tests_macOS_ppc.txt)

**Comment by mo271** [comment]
Please re-open if this still happens at current head
