### ISSUE TITLE
pfm is not supported with cjxl: Only JXL_BIT_DEPTH_FROM_PIXEL_FORMAT is implemented for float types.

### ISSUE THREAD

**Issue by zhou13** [libjxl/libjxl#2391]
**Describe the bug**

I am trying to reproduce #2363 with cjxl, in which I need to convert a float32 buffer to jxl. Since OpenEXR is not correct supported anymore #1804, I tried pfm.

**To Reproduce**

I am using the following code to generate pfm files:
```
import cv2
import numpy as np

buffer = np.load("1.npy")
cv2.imwrite("1.pfm", buffer)
```

Running cjxl gives
```
$ cjxl 1.pfm 1.jxl
JPEG XL encoder v0.8.1 0.8.1 [AVX2,SSE4,SSSE3]
Read 1536x1536 image, 9437200 bytes, 568.5 MP/s
Encoding [VarDCT, d1.000, effort: 7], 
./lib/jxl/encode.cc:265: Only JXL_BIT_DEPTH_FROM_PIXEL_FORMAT is implemented for float types.
./lib/jxl/encode.cc:1848: Invalid input bit depth
JxlEncoderAddImageFrame() failed.
EncodeImageJXL() failed.
```

Example files are attached here:
[Archive.zip](https://github.com/libjxl/libjxl/files/11255630/Archive.zip)

**Expected behavior**
No Error.

**Environment**
 - OS: MacOS / Homebrew
 - CPU type: x86_64
 - cjxl/djxl version string: `cjxl v0.8.1 0.8.1 [AVX2,SSE4,SSSE3]`

**Additional context**

**Comment by jonsneyers** [comment]
Looks like pfm indeed stopped working as an input format for cjxl.
