### ISSUE TITLE
splines: Decoding error due to high `total_estimated_area_reached` value

### ISSUE THREAD

**Issue by EugeneVert** [libjxl/libjxl#2400]
**Describe the bug**
Most jxl art images are not decodable due to the very high `estimated_area_reached` value

**To Reproduce**
- `djxl art.jxl art.png`
- Failed with JXL_FAILURE("Too large total_estimated_area_reached")

|variable| value| 
|-|-|
| manhattan_distance | 200 |
| width_estimate | 6868597129 |
| total_estimated_area |1373719425800 |

**Expected behavior**
Image successfully decoded

**Additional information**

`manhattan_distance` has an expected value of 200.
As noted by @jonsneyers, "width estimate should be some small number like 16 or something"

png:
![art.png](https://user-images.githubusercontent.com/69643766/232892400-bdb17366-5406-4f8b-9a07-2b2a371c6d92.png)
jxl:
![art.jxl](https://user-images.githubusercontent.com/69643766/232891931-51e183dd-371f-4e09-9b32-8936e956763e.png)

```
Width 200
Height 200
Bitdepth 8
Spline
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
50 50
100 150
150 150
EndSpline
- Set 0
```

**Comment by mo271** [comment]
Thanks for the report!
Sounds like manhattan_distance should indeed be smaller...
