### ISSUE TITLE
Write support for gdk-pixbuf plugin

### ISSUE THREAD

**Issue by schrmh** [libjxl/libjxl#2404]
**Is your feature request related to a problem? Please describe.**
Currently there is no write support which holds back some applications from saving into JXL. Namely xfce4-screenshooter since I opened an issue there previously and got a comment that linked me to https://github.com/libjxl/libjxl/blob/main/plugins/gdk-pixbuf/pixbufloader-jxl.c#L567 in which it is stated that writing support is TODO.

**Describe the solution you'd like**
Make it possible to write JXL files when gdk-pixbuf is used. Doesn't matter that much how but it should be easy enough for other people to adopt it with minimal, if any, code changes necessary.
**However, look at additional context part for something that might be wise to keep in mind.**

**Describe alternatives you've considered**
None.

**Additional context**
Comment from novomesk on the JXL Discord:
> The write support for gdk-pixbuf plugin is not difficult.
The loader needs SKCMS which is not packaged everywhere - that's also a blocker. Would be good to optionally use LCMS2.
Loader loads all frames into memory. That's OK for normal animations but someone create large JXL with many frames, memory gets exhausted quickly.

xfce4-screenshooter issue comment: https://gitlab.xfce.org/apps/xfce4-screenshooter/-/issues/108#note_69652

**Comment by mo271** [comment]
closed by #2410, many thanks at @novomesk!
