### ISSUE TITLE
No stable, trustable version of libjxl

### ISSUE THREAD

**Issue by timtas** [libjxl/libjxl#2439]
Will there be some kind of stable, trustable version of libjxl available anytime soon?

Right now, version 0.8.1 requires me to download at least the following _latest_ git versions of packages:

- third_party/highway
- third_party/sjpeg
- third_party/skcms

Completely unverifiable builds depending on freshly downloaded development versions of obscure packages hardly serve to accelerate the adoption of this library.

Who wants to track down bugs and security issues if it's not even clear where they are coming from?

**Comment by mo271** [comment]
Thanks for opening the issue!

The latest released version [0.8.1](https://github.com/libjxl/libjxl/releases/tag/v0.8.1), depends on the following versions of the packages you mention
 - [highway @ f670ea5](https://github.com/google/highway/tree/f670ea580bb70b4113b63b9cdaa42ba9b10cd13a)
 - [sjpeg @ 868ab55](https://github.com/webmproject/sjpeg/tree/868ab558fad70fcbe8863ba4e85179eeb81cc840)
 - [skcms @ b25b07b](https://skia.googlesource.com/skcms/+/b25b07b)

as can be seen by inspecting the corresponding github submodules in third_party.

Out of those the most essential is highway.
In any case it is a good point to strive to target released versions of our dependencies for our releases, which we also plan to do when we release version 1.0.

**Comment by kmilos** [comment]
> version 0.8.1 requires me

It does not. You're free to build against system provided package of highway through the [`-DJPEGXL_FORCE_SYSTEM_HWY=ON` CMake option](https://github.com/libjxl/libjxl/blob/c27d499263435ac77007174e0f1cf54557cff23a/CMakeLists.txt#L164-L165). Quite a few distros package libjxl this way already (and also disable e.g. sjpeg and skcms in favour of system libjpeg-turbo and lcms2):

Arch: https://github.com/archlinux/svntogit-community/blob/20bd0349291a2fb11d49f6326804aef63a8599c4/trunk/PKGBUILD#L59-L62
Debian/Ubuntu: https://salsa.debian.org/debian-phototools-team/libjxl/-/blob/d5e9a5f19ead9dd70756fc0451a3309eee1cee08/debian/rules#L66-69
Fedora: https://src.fedoraproject.org/rpms/jpegxl/blob/f38/f/jpegxl.spec#_163
MacPorts: https://github.com/macports/macports-ports/blob/3f6602d14eb8b4cb484ace0a4d43e56f540dd8a7/graphics/libjxl/Portfile#L67-L68
MSYS2 MinGW: https://github.com/msys2/MINGW-packages/blob/d839b496700a44e355a1c54e7a190c322b4e6c60/mingw-w64-libjxl/PKGBUILD#L68-L70
openSUSE: https://build.opensuse.org/package/view_file/openSUSE:Leap:15.5:Update/libjxl/libjxl.spec
vcpkg: https://github.com/microsoft/vcpkg/blob/b3e0a1e625a0cc00073efb763e39088e5b75939e/ports/libjxl/portfile.cmake#L31-L33

etc.

**Comment by timtas** [comment]
Thank you very much for your reply! According to the links above, I did now change the cmake line to:

```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=OFF \
      -DJPEGXL_BUNDLE_SKCMS:BOOL=OFF \
      -DJPEGXL_ENABLE_PLUGINS=ON \
      -DJPEGXL_ENABLE_SJPEG:BOOL=OFF \
      -DJPEGXL_ENABLE_SKCMS:BOOL=OFF \
      -DJPEGXL_FORCE_SYSTEM_LCMS2:BOOL=ON \
      ..
```
, applied the patches to the gdk-pixbuf-plugin, and now I only still include highway locally, as it is used nowhere else.
I now seem to have proper jxl support on my linux machines, as gimp, the thumbnailer and gdk-pixbuf work fine like this!
