### ISSUE TITLE
Noise synthesis doesn't match the conformance test reference

### ISSUE THREAD

**Issue by EugeneVert** [libjxl/libjxl#2447]
**Describe the bug**
Conformance test `noise` looks different in the djxl version and doesn't match the `ref.png`

**To Reproduce**
```bash
cd "conformance/testcases/noise/"
djxl input.jxl out.png
```
**Screenshots**
Ref:
![ref](https://user-images.githubusercontent.com/69643766/235508979-b3006faa-c211-4495-a072-5385fee311e6.png)
Djxl version:
![out](https://user-images.githubusercontent.com/69643766/235509059-be5bf896-aa75-4cc5-beb6-1c69f19cf74b.png)

**Environment**
 - OS: Linux 
 - Compiler version: clang version 15.0.6
 - CPU type: x86_64
 - cjxl/djxl version string: `djxl v0.9.0 5ef0a0c [AVX2,SSE4,SSSE3,SSE2]`

**Comment by mo271** [comment]
Thanks for the report!
Could be simply caused by the qt-jpeg-xl-image plugin using an old version? At least the noise synthesized slightly changed at some point:
https://github.com/libjxl/conformance/pull/18

**Comment by sboukortt** [comment]
Could you please double check that this is indeed the case? I just tried to reproduce the issue, and Gwenview displaying `conformance/testcases/noise/input.jxl` did produce the same output as `ref.png` when I linked the Qt JXL plugin to system libjxl (0.7.0), but it showed the same as `djxl.png` when I linked the plugin to a libjxl built from `HEAD` and installed into a temporary prefix (with system libjxl uninstalled to be sure).

**Comment by EugeneVert** [comment]
Ah, yes, sorry. For some reason, qt was using a plugin from kf5-kimageformats, despite `QT_PLUGIN_PATH` being set.

Qt JXL plugin showing the same result as djxl

**Comment by sboukortt** [comment]
Oh, it seems that this is just a case of https://github.com/libjxl/conformance/blob/master/testcases/noise/ref.png not having been updated to match the actual reference data. `ref.png` files are not _actually_ used for reference testing so we did not catch this…

The `djxl` / libjxl output is correct. I have just updated `ref.png` accordingly. Thanks for flagging this.
