### ISSUE TITLE
Fail decoding of truncated JXL file

### ISSUE THREAD

**Issue by Mykhailo418** [libjxl/libjxl#245]
Hello, I got an error when I tried to decode jxl file after trunction it to 1KB. I have attached below PNG image that I encoded. Looks like this issue happens with PNG images that have transparency.
Error message:
```
JPEG XL decoder v0.3.7 [AVX2,SSE4,Scalar]
Read 1024 compressed bytes.
Failed to decompress to pixels.
```
My steps:
1. cjxl <input_png> <output_jxl> -p --distance=15
2. <truncate output jxl file by std::filesystem::file_size in C++>
3. djxl <input_jxl> <output_png> --allow_partial_files --allow_more_progressive_steps

Environment:
 - OS: Windows 10
 - Compiler version: Clang x64, Visual Studio 2019
 - CPU type: x86_64
 - cjxl/djxl version string:  decoder v0.3.7 [AVX2,SSE4,Scalar], encoder v0.3.7 [AVX2,SSE4,Scalar]

Image: 
![Rough1](https://user-images.githubusercontent.com/29024201/123817090-859fc580-d900-11eb-9800-1d10081e1d08.png)

**Comment by eustas** [comment]
Confirmed.
```
JPEG XL decoder v0.3.7 [AVX3,AVX2,SSE4,Scalar]
Read 1024 compressed bytes.
../lib/jxl/dec_modular.cc:436: JXL_FAILURE: Undoing transforms failed
../lib/jxl/dec_frame.cc:821: JXL_RETURN_IF_ERROR code=1: modular_frame_decoder_.FinalizeDecoding(dec_state_, pool_, decoded_)
../lib/jxl/dec_frame.cc:912: JXL_RETURN_IF_ERROR code=1: Flush()
../lib/jxl/dec_frame.cc:230: JXL_RETURN_IF_ERROR code=1: frame_decoder.FinalizeFrame()
../lib/jxl/dec_file.cc:168: JXL_FAILURE: Not enough data.
../lib/jxl/dec_bit_reader.h:259: JXL_FAILURE: Read more bits than available in the bit_reader
Failed to decompress to pixels.
```

**Comment by eustas** [comment]
The first section of encoded file is 2055 bytes; plus few bytes for header.
The question is: what should be the output if there is nothing to present?
(Though if the first section is available, there is still no output; investigating further).

**Comment by IevgeniiChuprun** [comment]
@eustas @jonsneyers @Mykhailo418 Hello guys, any updates on this topic?

**Comment by eustas** [comment]
There is some progress (https://github.com/libjxl/libjxl/pull/259), though there are some problems remaining.

**Comment by ZelenskiyS** [comment]
Hello everyone!
Faced the same problem in decoding. 
Any news? When to expect a fix?

**Comment by Mykhailo418** [comment]
@eustas @jonsneyers Hello guys, are there any changes for this issue?

**Comment by jonsneyers** [comment]
This helps: https://github.com/libjxl/libjxl/pull/592

**Comment by jonsneyers** [comment]
Closing this one, please reopen or open a new issue if it's not solved or if there's another regression in this area.
