### ISSUE TITLE
GDK Pixbuf and GIMP plugins fail to decode valid JXL file

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#2456]
**Describe the bug**
See the attached JPEG XL file. It fails to load with GIMP, Eye of MATE, and ImageMagick. However, djxl, ffmpeg, and jxl-oxide all decode it correctly and report no errors.

**To Reproduce**
```
djxl george-smile4.jxl test.png
mpv george-smile4.jxl
gimp george-smile4.jxl
magick display george-smile4.jxl
eom george-smile4.jxl
```

**Expected behavior**
All libjxl-based decoders should decode the file correctly, as it is a valid file.

**Screenshots**
![george-smile4 jxl](https://user-images.githubusercontent.com/1342577/236212659-2a2c005d-5190-4218-9b65-24ed6b1e2089.jpg)

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: GCC 12.2.1
 - cjxl/djxl version string: JPEG XL decoder v0.9.0 6b1e5b03 [AVX2]

**Comment by novomesk** [comment]
Attempt to open in `eog` on my computer:

```
./lib/jxl/modular/transform/transform.h:99: JXL_FAILURE: Invalid transform RCT type
./lib/jxl/fields.cc:450: JXL_RETURN_IF_ERROR code=1: visitor.Visit(fields)
./lib/jxl/modular/encoding/encoding.cc:458: JXL_RETURN_IF_ERROR code=1: status
./lib/jxl/modular/encoding/encoding.cc:597: JXL_RETURN_IF_ERROR code=1: dec_status
./lib/jxl/dec_modular.cc:413: JXL_FAILURE: Failed to decode modular DC group
./lib/jxl/dec_frame.cc:310: JXL_RETURN_IF_ERROR code=1: modular_frame_decoder_.DecodeVarDCTDC(dc_group_id, br, dec_state_)
./lib/jxl/dec_frame.cc:646: JXL_FAILURE: Error in DC group
./lib/jxl/decode.cc:1146: frame processing failed
```

But GIMP from `flatpak install --user https://flathub.org/beta-repo/appstream/org.gimp.GIMP.flatpakref` works:
![Screenshot_20230504_155707](https://user-images.githubusercontent.com/52529860/236232532-33f64260-25db-4bf5-afe4-65a811c65792.png)

**Comment by Traneptora** [comment]
I wonder if it's somehow related to the TOC permutation?

**Comment by Traneptora** [comment]
Update: GIMP release on windows can read the file fine, but the file-jxl plugin that's used by git main on linux fails, for me. Since the flatpak works as well, it looks like there might be a recent regression.
