### ISSUE TITLE
Unable to decode with coalesce on some lossless layered JXL image

### ISSUE THREAD

**Issue by kampidh** [libjxl/libjxl#2463]
**Describe the bug**
When trying to decode (with coalescing) a layered JXL image that's encoded losslessly, an error sometimes occured:
```
lib\jxl\render_pipeline\stage_blending.cc:40: JXL_FAILURE: Trying to blend XYB reference frame 0 and non-XYB frame
lib\jxl\render_pipeline\render_pipeline.h:81: JXL_RETURN_IF_ERROR code=1: stage->IsInitialized()
lib\jxl\dec_frame.cc:653: JXL_RETURN_IF_ERROR code=1: dec_state_->PreparePipeline(decoded_, pipeline_options)
lib\jxl\decode.cc:1142: frame processing failed
```
However this only occurs when the image is encoded with effort 5 and up, and more interestingly, it only affect some part of the image. When the part is cropped, the error goes away. The error also didn't appear when coalescing is set to false.

**To Reproduce**
A little bit hard to reproduce it perfectly since it's sporadic.
- Encode a layered image losslessly with effort 5 or up, in my case I sent multiple `JxlEncoderAddImageFrame` with name set and each frame duration set to 0, just like the API suggests.
- Decode that image with coalescing on / default, or djxl, or try to open it with other apps.

**Expected behavior**
Image decoded successfully.

**Environment**
- OS: Windows 10
- Compiler version: Clang 15
- CPU type: x86_64
- cjxl/djxl version string: 0.8.1

**Additional context**
Since the errors are sporadic, I attached the following archive with affected JXL images (lossless effort 1-9, and lossy e7) along with the reference PNG:
[jxl-layer-bug.zip](https://github.com/libjxl/libjxl/files/11415615/jxl-layer-bug.zip)

**Comment by alistair7** [comment]
Same issue as #1827 - although my report was slightly off the mark because I'm no longer sure it has anything to do with the first frame specifically.

Encoding with --patches=0 / disabling JXL_ENC_FRAME_SETTING_PATCHES is an effective workaround for efforts >= 5.

**Comment by kampidh** [comment]
> Same issue as #1827 - although my report was slightly off the mark because I'm no longer sure it has anything to do with the first frame specifically.
> 
> Encoding with --patches=0 / disabling JXL_ENC_FRAME_SETTING_PATCHES is an effective workaround for efforts >= 5.

In my case the first layer always at `JXL_BLEND_REPLACE`, and next layer at blend. Anyway can confirm as well it was because of the patches. Disabling it fix the errors.

**Comment by veluca93** [comment]
@kampidh would you be able to test if the issue still reproduces if you encode the image with a libjxl built with this code? https://github.com/veluca93/libjxl/tree/patchframe

**Comment by veluca93** [comment]
I have updated https://github.com/veluca93/libjxl/tree/patchframe with a version of the code that *should* fix the issue, please give it a try when you can!

**Comment by kampidh** [comment]
> I have updated https://github.com/veluca93/libjxl/tree/patchframe with a version of the code that _should_ fix the issue, please give it a try when you can!

That patch seems to work fine! Here's the encoded result for lossless effort 3, 5, 7, and 9:
[jxl-layer-patch.zip](https://github.com/libjxl/libjxl/files/11464465/jxl-layer-patch.zip)

I've confirmed that it decodes fine with other apps / viewer (which uses coalescing by default)!
