### ISSUE TITLE
Decoding to png results in a small black image.

### ISSUE THREAD

**Issue by TheHardew** [libjxl/libjxl#248]
**Describe the bug**
When decoding 003.jxl, which was losslessly transcoded from a jpg, the resulting png file is only 1953 B small and all black, even though djxl didn't throw any errors.
Decoding to the original jpg file is still possible, but only because `--strip` was not used, otherwise it would be impossible to decode this file at all.

**To Reproduce**
(unpack the attached zip file to get 003.jxl)
```
~ $ djxl 003.jxl 003.png
JPEG XL decoder v0.3.7 [AVX2]
Read 274618 compressed bytes.
Decoded to pixels.
752 x 1080, 14.64 MP/s [14.64, 14.64], 1 reps, 8 threads.
Allocations: 476 (max bytes in use: 3.297596E+07)

~ $ djxl 003.jxl 003.jpg
JPEG XL decoder v0.3.7 [AVX2]
Read 274618 compressed bytes.
Reconstructed to JPEG.
752 x 1080, 16.33 MP/s [16.33, 16.33], 6.64 MB/s [6.64, 6.64], 1 reps, 8 threads.
Allocations: 429 (max bytes in use: 3.297534E+07)

~ $ du -b 003.*
330011	003.jpg
274618	003.jxl
1953	003.png
```

**Expected behavior**
It should be possible to decode this file to png.

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 12.0.0
 - CPU type: ryzen 2700x x86_64
 - cjxl/djxl version string: 8193d7b370c36f3df0528f1b22c481c182627aa5

**Additional context**
Compiled with https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libjxl-git and
```
CFLAGS="-march=native -O3 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fno-plt -pthread -Wno-error -w"
CXXFLAGS="$CFLAGS"
```
003.jxl inside a zip file, otherwise github wouldn't accept it.
[003.zip](https://github.com/libjxl/libjxl/files/6736434/003.zip)

**Comment by eustas** [comment]
In gray mode 0-th channel is taken for output instead of 1-st.

**Comment by eustas** [comment]
It is encoder bug =( #250
Hopefully, do data is lost (as it is possible to decode to JPEG again).

**Comment by eustas** [comment]
Should be fixed. Though requires re-encoding of monochrome JPEGs with Adobe RGB ICC.
