### ISSUE TITLE
For emojis, lossless JXL loses to lossless WebP, and even larger than the source

### ISSUE THREAD

**Issue by antermin** [libjxl/libjxl#2508]
**Describe the bug**

When I converted Facebook's emoji PNGs losslessly to JXL and WebP, I found that JXL outputs are larger than WebP outputs and even the source.

(It seems that Facebook uses images instead of actual Unicode emojis in posts.)

**To Reproduce**
1. Download test files, e.g.:
   * https://static.xx.fbcdn.net/images/emoji.php/v9/t80/1/16/1f92a.png
   * https://static.xx.fbcdn.net/images/emoji.php/v9/t6b/1/16/1f971.png
   * https://static.xx.fbcdn.net/images/emoji.php/v9/t25/1/16/1fae1.png
2. Convert them into lossless JXL using `cjxl -d 0`
3. Convert them into lossless WebP using `cwebp -lossless`
4. Observe that JXL always loses (source vs WebP vs JXL):
    * 579 / 528 / 748
    * 586 / 564 / 711
    * 586 / 548 / 696

**Environment**

* Arch Linux x86_64
* `JPEG XL encoder v0.8.1 c27d4992 [AVX2,SSE4,SSSE3,Unknown]`
* libwebp 1.3.0

**Comment by schrmh** [comment]
You can get a bit more down with JXL but yeah, this is the first case I see in which it performs that bad.
`cjxl -q 100 -e 9`:
```
748 1f92a_q100-e9.jxl
711 1f971_q100-e9.jxl
696 1fae1_q100-e9.jxl
```
`cjxl -q 100 -m 1 -e 9 -E 3 -I 100 -g 0`:
```
665 1f92a_q100-m1-e9-E3-I100-g0.jxl
613 1f971_q100-m1-e9-E3-I100-g0.jxl
612 1fae1_q100-m1-e9-E3-I100-g0.jxl
```
`cjxl -q 100 -m 1 -e 9 -E 3 -I 100 -g 3`:
```
665 1f92a_q100-m1-e9-E3-I100-g3.jxl
613 1f971_q100-m1-e9-E3-I100-g3.jxl
612 1fae1_q100-m1-e9-E3-I100-g3.jxl
```
`cjxl --allow_expert_options -q 100 -e 10`:
```
662 1f92a_q100-e10.jxl
613 1f971_q100-e10.jxl
612 1fae1_q100-e10.jxl
```

**Comment by mo271** [comment]
Thanks for the report!
Is there somewhere a larger corpus of those emojis?
