### ISSUE TITLE
Memory leak with djxl

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#2509]
**Describe the bug**
Valgrind reports 167 MB as "possibly lost" when decoding with libjxl. It appears to be system-dependent: I can reproduce it on my desktop but not my laptop, with the same build number.

**To Reproduce**
```
valgrind --leak-check=full djxl ./newton-cradle.jxl --disable_output
```

**Expected behavior**
All Heap Blocks Are Free - No Leaks Are Possible

**Environment**
 - OS: Arch Linux x86_64, Intel i7-6700K
 - Compiler version: GCC 13.1.1
 - cjxl/djxl version string: JPEG XL decoder v0.9.0 c8a4a7aa [AVX2]

**Additional context**
Log file: https://buzo.us/n.log

**Comment by Traneptora** [comment]
Sample: newton-cradle.jxl: https://buzo.us/3.jxl

**Comment by jdpatdiscord** [comment]
Unable to reproduce as of `c8a4a7a`, same as yours. Fedora 38 w. 6 threads, 5900X. With or without `--leak-check=full` is the same. Outputting to a file, no leaks, Only reading with `--disable-output`, no leaks. Also GCC 13.1.1.

**Comment by kkourin** [comment]
Based on the code and the attached log, this leak looks like it occurs when profiling is enabled (e.g. with `-DJPEGXL_ENABLE_PROFILER=true`). Maybe this variable set to true in the CMake cache on your laptop but not your desktop. On my machine, I tested that the leak only occurs with the profiler enabled.

From what I can tell, the memory is allocated and leaked here.
https://github.com/libjxl/libjxl/blob/main/lib/jxl/base/profiler.cc#L493

And I think this comment suggests it is intentionally leaked.
https://github.com/libjxl/libjxl/blob/main/lib/jxl/base/profiler.h#L107

**Comment by mo271** [comment]
Probably best to remove the profiler, I don't think it is used much these days
