### ISSUE TITLE
Modular mode crashes with SIGILL; JXL_DASSERT: n <= 255

### ISSUE THREAD

**Issue by TheHardew** [libjxl/libjxl#251]
**Describe the bug**
Encoding `011.png` with modular mode crashes, lossy and lossless.
It also happens when encoding `.ppm` and `.pgx` files created from the `.png` file.
"Works" after transcoding to `.pfm`, but this changes the image and the resulting `.jxl` is larger than the original `.png`.

**To Reproduce**
```
~ $ cjxl -m 011.png 011.jxl
JPEG XL encoder v0.3.7 [AVX2]
build/libjxl-git/src/libjxl/lib/extras/codec_png.cc:497: PNG: no color_space/icc_pathname given, assuming sRGB
Read 822x1168 image, 38.3 MP/s
Encoding [Modular, lossless, squirrel], 8 threads.
build/libjxl-git/src/libjxl/lib/jxl/enc_ans.cc:220: JXL_DASSERT: n <= 255
fish: Job 1, 'cjxl -m 011.png 011.jxl' terminated by signal SIGILL (Illegal instruction)
```

**Expected behavior**
It should be possible to encode this image in modular mode.

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 12.0.0
 - CPU type: ryzen 2700x x86_64
 - cjxl/djxl version string: 8193d7b370c36f3df0528f1b22c481c182627aa5

**Additional context**
Compiled with https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libjxl-git and
```
CFLAGS="-march=native -O3 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fno-plt -pthread -Wno-error -w"
CXXFLAGS="$CFLAGS"
```
https://user-images.githubusercontent.com/7374061/123955891-707f7100-d9aa-11eb-9ff4-d8af1667466f.png

**Comment by jonsneyers** [comment]
This seems to be a bug in encoder heuristics to make decisions about entropy coding choices. It doesn't lead to incorrect bitstreams (when not using the debug version so the JXL_DASSERT doesn't trigger), but it may lead to suboptimal encoder choices.

**Comment by TheHardew** [comment]
I tried it again now on c914b75 and when encoding with `-q` < 100 it the only error/warning it prints is:
`./lib/extras/color_hints.cc:56: No color_space/icc_pathname given, assuming sRGB`.
When encoding with `-q 100`, any `-d` or just with `-m`, it also outputs `./lib/jxl/enc_ans.cc:220: JXL_DASSERT: n <= 255`.
I don't know if that was also the case before.

I find it strange, that `-q` behaves differently from `-d`.

**Comment by mo271** [comment]
Thanks for the report! Meanwhile on fde214c5, it seems to work flawlessly, without causing any `JXL_DASSERT`, so this is not reproducible at the current. Feel free to re-open if you still have the issue.
