### ISSUE TITLE
libjxl should generate ICC profiles that use CICP tag when appropriate

### ISSUE THREAD

**Issue by leo-barnes** [libjxl/libjxl#2545]
When I last tested in v0.6.1, the ICC profiles returned by `JxlDecoderGetColorAsICCProfile` did not use the CICP tag recently added to the ICC spec for files where `JxlDecoderGetColorAsEncodedProfile` returns CICP values.

I'm guessing this is why the following comment shows up in the headers for v0.8.1:
```
 *    HDR color spaces such as those using PQ and HLG are also potentially
 *    problematic, in that: while ICC profiles can encode a transfer function
 *    that happens to approximate those of PQ and HLG (HLG for only one given
 *    system gamma at a time, and necessitating a 3D LUT if gamma is to be
 *    different from 1), they cannot (before ICCv4.4) semantically signal that
 *    this is the color space that they represent. Therefore, they will
 *    typically not actually be interpreted as representing an HDR color space.
 *    This is especially detrimental to PQ which will then be interpreted as if
 *    the maximum signal value represented SDR white instead of 10000 cd/m^2,
 *    meaning that the image will be displayed two orders of magnitude (5-7 EV)
 *    too dim.
```

While HDR metadata in ICC is still a bit in flux, it seems a good first step would be to at least make use of the CICP tag when appropriate.

**Comment by sboukortt** [comment]
Hi Leo, we should be writing such tags since #1753, and read them from input files since #1883, both of which we think should have made it into the 0.8 and subsequent releases. Do you still encounter the issue with those?

**Comment by leo-barnes** [comment]
Thanks for the info, will have to check.

**Comment by leo-barnes** [comment]
Verified that v0.8.1 does indeed produce ICC profiles with CICP tag. Thanks!
