### ISSUE TITLE
Pixel-to-jpeg is faster than Jpeg reconstruction?

### ISSUE THREAD

**Issue by nnphongphu** [libjxl/libjxl#2572]
I’m looking everywhere on the internet and no one really talks about it. I think most would assume that reconstructing Jpeg would be much faster than decoding the whole thing and re-encoding it. I’m testing it using the latest cjxl release on my machine and having the pixel-to-jpeg flag turned on makes it run twice as fast.

**Comment by jonsneyers** [comment]
There was a performance bug in the way djxl did jpeg reconstruction, see https://github.com/libjxl/libjxl/pull/2534

Should be a lot better now...

**Comment by nnphongphu** [comment]
It is much better now! Thank you.
