### ISSUE TITLE
Wasm performance is much worse

### ISSUE THREAD

**Issue by nnphongphu** [libjxl/libjxl#2574]
I have been experimenting with wasm build from the JPEG XL viewer extension (https://chrome.google.com/webstore/detail/jpeg-xl-viewer/bkhdlfmkaenamnlbpdfplekldlnghchp) and many other wasm build of this lib. The performance recorded on browsers are worst. My 4K image always takes about 4 seconds to decode instead of like 1 seconds when decoding using djxl. I know wasm has some overhead included but 4 times worse is kind of weird. Does anyone else experience this? I'm also experiment using Chrome 104 with jxl flag enabled, and the speed, somehow, was even better than native djxl. I don't know how they achive this... Appreciate it if there're any explanation.

**Comment by jonnyawsom3** [comment]
I could be wrong, but if I recall wasm can only use a single thread, so a 4K image being 4x slower lines up pretty well compared to native

**Comment by nnphongphu** [comment]
After rebuilding my own wasm that supports jpeg recompression decode, the sped is now twice as fast as before. However, I'm still bugged at the fact that decoding jxl in lossy mode (without jpeg recompression) takes so much time. Hmm...

**Comment by nnphongphu** [comment]
> I could be wrong, but if I recall wasm can only use a single thread, so a 4K image being 4x slower lines up pretty well compared to native

Yeah, but I have set --num_threads=1 on native already. Or do I understand it wrong?

**Comment by jonsneyers** [comment]
Perhaps you're not getting good SIMD in wasm? For jpeg reconstruction that doesn't matter that much (it's bottlenecked by entropy decode/encode anyway), but for decoding to pixels the difference between scalar and proper SIMD would be large...

**Comment by eustas** [comment]
WASM can use multithreading. And it providers considerable speedup. It requires some environment support, but works in Chrome (with COOP/COEP) pretty well.

As for performance - modern engines do Just-In-Time compilation. This means that performance gradually improves over first 5-100 decoded images.

**Comment by nnphongphu** [comment]
> Perhaps you're not getting good SIMD in wasm? For jpeg reconstruction that doesn't matter that much (it's bottlenecked by entropy decode/encode anyway), but for decoding to pixels the difference between scalar and proper SIMD would be large...

This! After rebuilding with SIMD, the perf has improved. It can decode 4K images and load them onto the screen in 2 seconds. It is still not as fast as native but yeah, this is much better. At least it is now just 2x slower xD I wonder if it's because WrapPixelsToPng function for encoding pixels to png is slow... I'll try using the jpeg encoder instead to see if it can further improve :D Things are looking good rn ^^Ty

**Comment by jonnyawsom3** [comment]
I know you're waiting on #2595 to try using the jpeg encoder, but I recall when people tested JXL before with PNG as an output format, the PNG encoding was most of the encode time. So I think you're on the right track

**Comment by eustas** [comment]
In our service-worker-demo we use no-compress PNG encoder, so it is quite fast.

**Comment by nnphongphu** [comment]
> In our service-worker-demo we use no-compress PNG encoder, so it is quite fast.

Oh, I see. I kinda figured that out when trying to use JPEG Encoder. But the no-compress PNG encoder output is so large I'm afraid it would take a toll on RAM for large images (4K, 8K, etc...). So I'm just hoping to minimize the file size now :D Can you take a look at #2595 ?

**Comment by eustas** [comment]
Sure, will take a look later today.

**Comment by eustas** [comment]
There is also mixed-ground solution - produce pixels and then use canvas to encode them to PNG/JPG/etc.

**Comment by nnphongphu** [comment]
> There is also mixed-ground solution - produce pixels and then use canvas to encode them to PNG/JPG/etc.

How can I implement this with the wasm-demo? I've seen people return pixels inside an ImageData class, but I don't know how to implement it in the wasm-demo.

**Comment by nnphongphu** [comment]
I found a way to speed it up! Instead of using jxl::extras::DecodeImageJXL for decoding, I use DecodeJpegXlOneShot instead (with some modification to make it work on WASM). Now, the performance is approaching that of djxl's as 4K is decoded in 900ms. It's still a bit slower for 8K images tho.

**Comment by nnphongphu** [comment]
Can somebody explain why DecodeJpegXlOneShot is much faster than jxl::extras::DecodeImageJXL?
