### ISSUE TITLE
cjpegli fails with nondescript error message if input PNG contains alpha

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#2579]
**Describe the bug**
Consider a PNG image that has an alpha channel.
Attempting to encode to encode it with cjpegli fails with `jpegli encoding failed` and no obvious reason why.

**To Reproduce**
Take a PNG with an alpha channel, such as this one: [https://buzo.us/7F.png](https://buzo.us/7F.png)

**Expected behavior**
The alpha channel is entirely max value, i.e. the image is actually opaque. Which means I expect one of three things to happen:
(1) cjpegli should just strip the alpha channel if it's entirely opaque, when encoding from PNG -> JPEG. This will happen, say, if you save a screenshot in Windows with the snipping tool, or use the above image.
(2) cjpegli should refuse to encode it (current behavior) but it should print an error message like "Failed to encode input image because it has an alpha channel." So a user isn't left wondering ??????
(3) Add a `--strip_alpha` option to cjpegli, which causes it to ignore the alpha channel of the input, if present. In my personal opinion, the ideal default would be for `--strip_alpha` to be enabled if the input contains an alpha channel which is perfectly constant and fully opaque, and to refuse to strip it in any other scenario. Perhaps even with a message like "Implicitly stripping fully opaque alpha channel, set `--strip_alpha` to silence this message." An acceptable default would just be to refuse unless explicitly set. However, if set it would save users the trouble of running the image through optipng or other PNG palette reduction features that strip opaque alpha channels.

Personally, I prefer (3) as a long-term solution but at the very least (2) should be implemented in the short-term. 

**Log**
```
$ cjpegli -v -v compass-alpha.png test.jpg
Read 600x600 image, 48699 bytes.
Encoding [YUV d1.000 AQ p2 OPT]
jpegli encoding failed
```

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: GCC 13
 - cjxl/djxl version string: JPEG XL encoder v0.9.0 00935aaa [AVX2]

**Additional context**
cjpegli doesn't print its version string, I had to grab it from cjxl. But that's a separate issue.

**Comment by Firepal** [comment]
Interesting that your proposal does not consider multiplying the RGB channels with the Alpha channel at all.
There isn't always meaningful colors where Alpha = 0.0

**Comment by szabadka** [comment]
This has been fixed a while ago, the behavior is now the same with e.g. imagemagick convert.
