### ISSUE TITLE
Losslessly recompressing JXL turns enum tags into ICC profiles

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#2581]
**Describe the bug**
~~Consider the conformance sample `animation_icos4d.jxl`. (Here, for convenience: [https://buzo.us/H.jxl](https://buzo.us/H.jxl)). 
Attempting to losslessly recompress it using `cjxl -d 0` appears to be taking the 8-bit pixel data from the original and encoding it losslessly as 32-bit float, which inflates the file size pretty dramatically.~~ Fixed by #2591 although the next issue remains, at the moment: 

It also seems to be embedding an ICC profile rather than tagging the new file with an sRGB enum, despite the original being tagged with an sRGB enum.

**To Reproduce**
```
$ cjxl -d 0 animation_icos4d.jxl test.jxl
$ jxlinfo -v animation_icos4.jxl
$ jxlinfo -v test.jxl
```

**Expected behavior**
I expected cjxl to preserve the tagged enum space rather than synthesize an ICC profile and then embed the synthesized profile.

**Log**
[https://buzo.us/D.log](https://buzo.us/D.log)

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: GCC 13
 - cjxl/djxl version string: JPEG XL encoder v0.9.0 00935aaa [AVX2]

**Comment by jonsneyers** [comment]
Ugh, why does github auto-close the issue if I referenced it saying my PR "partially fixes" this issue.

The bitdepth thing should be fixed now, but it will still convert an enum colorspace to a synthesized icc profile...

**Comment by Traneptora** [comment]
Should I open a separate issue for that?

**Comment by Traneptora** [comment]
Updated title and body to reflect the current issue.

**Comment by kmilos** [comment]
> Ugh, why does github auto-close the issue if I referenced it saying my PR "partially fixes" this issue.

@jonsneyers Because of the [keyword "fixes"](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) (and I don't know why they even say "may close" on the side when it seem to do it always when linked). Been there, using "partially addresses" now 😉 (But then it doesn't create the link between the issue and the PR apart from the mentions...)
