### ISSUE TITLE
Trouble linking wasm_demo with jpeg encoder

### ISSUE THREAD

**Issue by nnphongphu** [libjxl/libjxl#2595]
The current wasm_demo (tools/wasm_demo/jxl_decompressor.cc) is using WrapPixelsToPng for encoding pixels to png. Is this a substitute for the actual PNGEncoder because the resulted files are extremely large in size. I want to re-implement it with JPEGEncoder instead, but I'm having trouble linking. I'll really appreciate if anyone can help. I have looked into past commits and use the commit where the wasm-demo used a png decoder instead of WrapPixelsToPng as a reference; I still couldn't build successfully!

Here's my code for jxl_decompressor.cc:
 `
#include "lib/extras/dec/jxl.h"
#include "lib/extras/enc/encode.h"
#include "lib/extras/enc/jpg.h"

...

DecompressorOutput* jxlDecompress(const uint8_t* input, size_t input_size) {
...
  if (!jxl::extras::DecodeImageJXL(input, input_size, dparams, nullptr, &ppf)) {
    return report_error(1, "failed to decode jxl");
  }

  std::unique_ptr<jxl::extras::Encoder> encoder = jxl::extras::GetJPEGEncoder();

  jxl::extras::EncodedImage encoded_image;
  if (!encoder->Encode(ppf, &encoded_image)) {
    return report_error(2, "failed to encode png");
  }

  self->output.size = encoded_image.bitstreams[0].size();
  self->output.data = encoded_image.bitstreams[0].data();
  return self->output;
}
`

The error log kinda looks like this, the full log is attached at the end:
`
[8/249] Building CXX object lib/CMakeFiles/input_suspension_test.dir/jpegli/test_utils.cc.o
FAILED: lib/CMakeFiles/input_suspension_test.dir/jpegli/test_utils.cc.o 
/home/phunp/emsdk/upstream/emscripten/em++  -DHWY_DISABLED_TARGETS="(HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128|HWY_RVV)" -DHWY_STATIC_DEFINE -DTEST_DATA_PATH=\"/home/phunp/libjxl/testdata\" -DTOOLCHAIN_MISS_SYS_AUXV_H -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -I../ -I../third_party/highway -I../lib/include -Ilib/include -isystem ../third_party/googletest/googlemock/include -isystem ../third_party/googletest/googlemock -isystem ../third_party/googletest/googletest/include -isystem ../third_party/googletest/googletest -msimd128 -pthread -fno-rtti -funwind-tables -Xclang -mrelax-all -Xclang -mconstructor-aliases -fno-omit-frame-pointer -O3 -DNDEBUG -O2   -fmacro-prefix-map=/home/phunp/libjxl=. -Wno-builtin-macro-redefined -Wall -Werror -fmerge-all-constants -fno-builtin-fwrite -fno-builtin-fread -Wextra -Wc++11-compat -Warray-bounds -Wformat-security -Wimplicit-fallthrough -Wno-register -Wno-unused-function -Wno-unused-parameter -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -Wdeprecated-increment-bool -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wgnu-redeclared-enum -Winfinite-recursion -Wliteral-conversion -Wno-c++98-compat -Wno-unused-command-line-argument -Wprivate-header -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety-analysis -Wundefined-func-template -Wunreachable-code -Wunused-comparison -fsized-deallocation -fno-exceptions -fmath-errno -fnew-alignment=8 -fno-cxx-exceptions -fno-slp-vectorize -fno-vectorize -disable-free -disable-llvm-verifier -DJPEGXL_ENABLE_SKCMS=1 -DJPEGXL_BUNDLE_SKCMS=1 -DJPEGXL_ENABLE_TRANSCODE_JPEG=1 -DJPEGXL_ENABLE_BOXES=1 -std=c++11 -MD -MT lib/CMakeFiles/input_suspension_test.dir/jpegli/test_utils.cc.o -MF lib/CMakeFiles/input_suspension_test.dir/jpegli/test_utils.cc.o.d -o lib/CMakeFiles/input_suspension_test.dir/jpegli/test_utils.cc.o -c ../lib/jpegli/test_utils.cc
../lib/jpegli/test_utils.cc:487:40: error: assigning to 'boolean' from incompatible type 'const int'
  487 |     cinfo->write_JFIF_header = jparams.override_JFIF;
      |                                ~~~~~~~~^~~~~~~~~~~~~
../lib/jpegli/test_utils.cc:490:41: error: assigning to 'boolean' from incompatible type 'const int'
  490 |     cinfo->write_Adobe_marker = jparams.override_Adobe;
      |                                 ~~~~~~~~^~~~~~~~~~~~~~
../lib/jpegli/test_utils.cc:521:9: error: no matching function for call to 'jpegli_add_quant_table'
  521 |         jpegli_add_quant_table(cinfo, table.slot_idx, &table.basic_table[0],
      |         ^~~~~~~~~~~~~~~~~~~~~~
../lib/jpegli/encode.h:63:6: note: candidate function not viable: no known conversion from 'const bool' to 'boolean' for 5th argument
   63 | void jpegli_add_quant_table(j_compress_ptr cinfo, int which_tbl,
      |      ^
../lib/jpegli/test_utils.cc:538:3: error: no matching function for call to 'jpegli_enable_adaptive_quantization'
  538 |   jpegli_enable_adaptive_quantization(cinfo, jparams.use_adaptive_quantization);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/jpegli/encode.h:146:6: note: candidate function not viable: no known conversion from 'const bool' to 'boolean' for 2nd argument
  146 | void jpegli_enable_adaptive_quantization(j_compress_ptr cinfo, boolean value);
      |      ^
../lib/jpegli/test_utils.cc:547:24: error: assigning to 'boolean' from incompatible type 'bool'
  547 |   cinfo->raw_data_in = !input.raw_data.empty();
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
../lib/jpegli/test_utils.cc:564:5: error: no matching function for call to 'jpegli_start_compress'
  564 |     jpegli_start_compress(cinfo, write_all_tables);
      |     ^~~~~~~~~~~~~~~~~~~~~
../lib/jpegli/encode.h:89:6: note: candidate function not viable: no known conversion from 'bool' to 'boolean' for 2nd argument
   89 | void jpegli_start_compress(j_compress_ptr cinfo, boolean write_all_tables);
      |      ^
../lib/jpegli/test_utils.cc:630:44: error: cannot initialize a parameter of type 'boolean' with an rvalue of type 'bool'
  630 |             comptr, coef_arrays[c], by, 1, true);
      |                                            ^~~~
../lib/jpegli/test_utils.cc:723:39: error: assigning to 'boolean' from incompatible type 'const bool'
  723 |   cinfo->do_block_smoothing = dparams.do_block_smoothing;
      |                               ~~~~~~~~^~~~~~~~~~~~~~~~~~
../lib/jpegli/test_utils.cc:724:40: error: assigning to 'boolean' from incompatible type 'const bool'
  724 |   cinfo->do_fancy_upsampling = dparams.do_fancy_upsampling;
      |                                ~~~~~~~~^~~~~~~~~~~~~~~~~~~
../lib/jpegli/test_utils.cc:736:36: error: assigning to 'boolean' from incompatible type 'const bool'
  736 |   cinfo->quantize_colors = dparams.quantize_colors;
      |                            ~~~~~~~~^~~~~~~~~~~~~~~
../lib/jpegli/test_utils.cc:930:5: error: use of undeclared identifier 'jpeg_crop_scanline'; did you mean 'jpegli_crop_scanline'?
  930 |     jpeg_crop_scanline(cinfo, &xoffset, &xsize_cropped);
      |     ^~~~~~~~~~~~~~~~~~
      |     jpegli_crop_scanline
`
[error_logs.txt](https://github.com/libjxl/libjxl/files/11832769/error_logs.txt)

**Comment by eustas** [comment]
Looks like picky compiler report. Will add proper type conversion and see what's next

**Comment by eustas** [comment]
And the second half is likely fixed with EMCC flag `-s USE_LIBJPEG`

**Comment by nnphongphu** [comment]
I wonder if there's any update on this... has anyone succeeded in building the wasm decoder with jpeg encoder?

**Comment by nnphongphu** [comment]
Never mind. I got it :)
