### ISSUE TITLE
num_threads

### ISSUE THREAD

**Issue by yyyanyy** [libjxl/libjxl#2631]
is the --num_threads really working?
It's alway using only one core.

![image](https://github.com/libjxl/libjxl/assets/100340496/88739644-5777-4df7-8457-f009879f543f)

**Comment by jonsneyers** [comment]
Try with a lower effort or lossy encode. For high-effort (e>3) lossless, most of the encode steps haven't been parallelized yet so you'll indeed see little difference in speed with more threads...

**Comment by yyyanyy** [comment]
oh I see, it works with effor<=3 or lossy
