### ISSUE TITLE
djxl does not report if input file is not found

### ISSUE THREAD

**Issue by eustas** [libjxl/libjxl#265]
**Describe the bug**
I was confused when `djxl` did not report that input file does not exist and just did nothing.

**To Reproduce**
`djxl input-file-name-wtih-a-typo.jxl output-file-name.png`

**Expected behavior**
Report that input file does not exist

**Comment by TheHardew** [comment]
It does return `1` at least.
I think that's the line: https://github.com/libjxl/libjxl/blob/main/tools/djxl_main.cc#L70 ?

**Comment by eustas** [comment]
Yup, status is 1.

**Comment by TheHardew** [comment]
```
~/.c/p/b/l/s/l/tools (makepkg|…) $ diff djxl_main.cc djxl_main-modified.cc
70c70,73
<   if (!jxl::ReadFile(args.file_in, &compressed)) return 1;
---
>   if (!jxl::ReadFile(args.file_in, &compressed)) {
>   	fprintf(stderr, "Failed to read image %s.\n", args.file_in);
>   	return 1;	
>   }
~/.c/p/b/l/s/l/tools (makepkg|…) [1] $ djxl 1.jxl
JPEG XL decoder v0.3.7 [AVX2]
Failed to read image 1.jxl.
~/.c/p/b/l/s/l/tools (makepkg|…) [1] $  
```

If you want that seems to work.
