### ISSUE TITLE
Attempting to create a lossy JXL from a lossless JXL produces a dark image

### ISSUE THREAD

**Issue by cagelight** [libjxl/libjxl#266]
cjxl v0.3.7 [AVX2,SSE4,Scalar]

A few times now, I've wanted to decode a lossless JXL and re-encode it into a lossy JXL. Since cjxl does not allow input of JXL files, I use an intermediary PNG. At some point in the chain however, color information seems to be lost as see here:
![2021-07-01_20-59](https://user-images.githubusercontent.com/3761279/124205579-875bbb80-daaf-11eb-85a3-ccd6a86b2502.png)
1.png: Source PNG
2.jxl: Lossless JXL (`cjxl 1.png 2.jxl -d 0`)
3.png: Intermediary PNG (`djxl 2.jxl 3.png`) (NOTE: Same thing happens with PPM)
4.jxl: Lossy JXL (`cjxl 3.png 4.jxl -d 1`)

If I do step 4 directly with 1.png, the issue does not occur, leading me to believe it is a bug with `djxl`

Images: [img.tar.gz](https://github.com/libjxl/libjxl/files/6751477/img.tar.gz)

**Comment by TheHardew** [comment]
How do you display the files? With `djxl `4.jxl 5.png`, 5.png looks identical to 1.png.

**Comment by cagelight** [comment]
It looks identical for me too with another layer of djxl, but I'm using the Qt plugin to view them. While there could be a bug with the Qt plugin here playing a part, ultimately I strongly feel 1.png and 3.png should have identical color data such that this bug with the Qt plugin shouldn't even be possible.

**Comment by jonsneyers** [comment]
`jxlinfo 2.jxl` gives something that is weird:
```
  transfer_function: 65535
  transfer_function gamma: 0.454550
```

@lvandeve @sboukortt what does that transfer_function mean? that's not a valid value, is that a bug?

**Comment by sboukortt** [comment]
It’s the value that signals a gamma TRC:

https://github.com/libjxl/libjxl/blob/3c54e982df76f46f1162e87a7235342ba592581a/lib/include/jxl/color_encoding.h#L82-L84

**Comment by DavidBuchanan314** [comment]
`3.png` has an ICC colour profile, added by djxl

**Comment by sboukortt** [comment]
With #270 now merged, would you give that another try starting from `djxl 2.jxl 3.png`?

**Comment by cagelight** [comment]
All is well on my end, thank you for the quick fix!
