### ISSUE TITLE
JPEG lossless transcoding resulting JXL images without exif metadata

### ISSUE THREAD

**Issue by dbtsai** [libjxl/libjxl#2666]
**Describe the bug**

I transcoded JPEG images to JXL lossless with `cjxl input.jpg output.jxl --lossless_jpeg=1 -e 9 --brotli_effort=11` using JPEG XL encoder v0.8.2, and the converted JXL images don't contain the proper exif metadata. I can retrieve the exif by transcoding the images back to JPEG, so the exif metadata was stored somewhere in the JXL; however, it can not be directly accessed by exiftool.

**To Reproduce**

```
dbtsai@Mac-mini % exiftool DSCF0170.jxl 
ExifTool Version Number         : 12.60
File Name                       : DSCF0170.jxl
Directory                       : .
File Size                       : 2.5 MB
File Modification Date/Time     : 2023:07:11 02:19:07-07:00
File Access Date/Time           : 2023:07:15 15:02:22-07:00
File Inode Change Date/Time     : 2023:07:15 15:02:17-07:00
File Permissions                : -rw-r--r--
File Type                       : JXL
File Type Extension             : jxl
MIME Type                       : image/jxl
Major Brand                     : JPEG XL Image (.JXL)
Minor Version                   : 0.0.0
Compatible Brands               : jxl
```
```
dbtsai@Mac-mini % djxl DSCF0170.jxl DSCF0170.jpg
JPEG XL decoder v0.8.2 0.8.2 [NEON]
Read 2516883 compressed bytes.
Reconstructed to JPEG.
2848 x 2136, 12.29 MP/s [12.29, 12.29], 6.25 MB/s [6.25, 6.25], 1 reps, 10 threads.

dbtsai@Mac-mini % exiftool DSCF0170.jpg 
ExifTool Version Number         : 12.60
File Name                       : DSCF0170.jpg
Directory                       : .
File Size                       : 3.1 MB
File Modification Date/Time     : 2023:07:15 15:04:46-07:00
File Access Date/Time           : 2023:07:15 15:04:50-07:00
File Inode Change Date/Time     : 2023:07:15 15:04:49-07:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : FUJIFILM
Camera Model Name               : FinePix F31fd
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : Digital Camera FinePix F31fd   Ver1.00
Modify Date                     : 2007:07:08 19:06:28
Y Cb Cr Positioning             : Co-sited
Copyright                       : 
Exposure Time                   : 1/100
F Number                        : 5.0
Exposure Program                : Program AE

```
**Expected behavior**
Lossless transcoded JXL from JPG should contain proper exif metadata.

**Environment**
 - OS: MacOSX Sonoma Public Beta
 - CPU type: ARM64
 - cjxl/djxl version string: JPEG XL encoder v0.8.2 0.8.2 [NEON]

**Comment by goodusername123** [comment]
The version of ExifTool you are using is likely the cause since JXL support was improved in version 12.63 however you are using version 12.60 which lacks the improved support for reading JXL files.
https://exiftool.org/history.html

**Comment by dbtsai** [comment]
Thanks @goodusername123 . How do I disable brotli for metadata compression? After upgrading to exiftool 12.64, I got

```dbtsai@Mac-mini % /usr/local/bin/exiftool DSCF0170.jxl
ExifTool Version Number         : 12.64
File Name                       : DSCF0170.jxl
Directory                       : .
File Size                       : 2.5 MB
File Modification Date/Time     : 2023:07:11 02:19:07-07:00
File Access Date/Time           : 2023:07:15 15:02:22-07:00
File Inode Change Date/Time     : 2023:07:15 15:02:17-07:00
File Permissions                : -rw-r--r--
File Type                       : JXL
File Type Extension             : jxl
MIME Type                       : image/jxl
Major Brand                     : JPEG XL Image (.JXL)
Minor Version                   : 0.0.0
Compatible Brands               : jxl
Image Width                     : 2848
Image Height                    : 2136
Warning                         : Install IO::Uncompress::Brotli to decode Brotli-compressed metadata
Image Size                      : 2848x2136
Megapixels                      : 6.1
```

But I have brotli installed in my system
```dbtsai@Mac-mini % brew info brotli
==> brotli: stable 1.0.9 (bottled), HEAD
Generic-purpose lossless compression algorithm by Google
```

**Comment by goodusername123** [comment]
You should be able to disable metadata compression in cjxl with `--compress_boxes=0` also I think the reason you are getting the error about Brotli in ExifTool despite having Brotli installed is because ExifTool requires a Perl module/wrapper to interface/communicate with Brotli.

**Comment by dbtsai** [comment]
With `sudo perl -MCPAN -e 'install IO::Uncompress::Brotli'`, I can confirm that exiftool 12.64 can properly read brotli compressed exif. 

Look like in MacOSX Sonoma Public Beta, the Preview is not able to read exif for both uncompressed or compressed exif. The image looks correct though.

**Comment by kmilos** [comment]
Note that exiv2 should support brotli compressed boxes since version 0.28 as well.

**Comment by kmilos** [comment]
> however some apps that use exiv2 like gThumb still don't show it

They're probably still linked against the 0.27.x (or older) version, or the distributed 0.28.x version could be built w/o brotli support...

**Comment by sobrus** [comment]
This seems not to be the case, because 
- I'm using stable Manjaro and exiv2 0.28 is the only one available and required by pix/gThumb
- it doesn't have any problems reading exif using command line, so it is probably built with brotli support.
- darktable seems to be using the same exiv2 and shows exif correctly

**Comment by kmilos** [comment]
Re embedded ICC profile: it is stored in the actual code stream and not as metadata. Neither Exiv2 nor exiftool decode the codestream AFIAK. See e.g. https://github.com/Exiv2/exiv2/issues/1506 and https://github.com/exiftool/exiftool/issues/157

**Comment by sobrus** [comment]
> Re embedded ICC profile: it is stored in the actual code stream and not as metadata. Neither Exiv2 nor exiftool decode the codestream AFIAK. See e.g. [Exiv2/exiv2#1506](https://github.com/Exiv2/exiv2/issues/1506) and [exiftool/exiftool#157](https://github.com/exiftool/exiftool/issues/157)

Yes, this is what I also suspect (and exiftool explicity states that it has no ICC support). 
However there are more mysteries regarding ICC and JXL:
- gThumb and GIMP can read ICC profile from lossless JPG conversion, but not from vardct JXL file.
- JXL has currently no support for AdobeRGB color space in vardct mode (gamut cropped to sRGB and invalid transfer function), but works ok with lossless JPG.

**Comment by kmilos** [comment]
Sure, but color management has nothing to do w/ metadata parsing. Those apps access it directly via libjxl.

Re Adobe RGB, when you decode lossy as **_float_**, even though the resulting color space is "unexpected" the data is not lost/clipped, and the app can still recover everything to whatever color space it wants, provided it does color management right. Try darktable for example.

**Comment by sobrus** [comment]
> Sure, but color management has nothing to do w/ metadata parsing. Those apps access ICC directly via libjxl.
> 
> Re Adobe RGB, when you decode lossy as **_float_**, even though the resulting color space is "unexpected" the data is not lost/clipped, and the app can still recover everything to whatever color space it wants, provided it does color management right. Try darktable for example.

No, the vardct AdobeRGB image is not displayed correctly by Darktable and Eye Of Gnome either. The wide gamut information is lost. This is becasue even if you encode and decode AdobeRGB image using cjxl and djxl, you will get RGB_D65_SRG_Rel_Lin colorspace (unless overridden by color space argument).

But AdobeRGB doesn't use linear transfer function nor sRGB color primaries. The decoded image is incorrect, using color management to solve the issue is not a proper way of dealing with it.

**Comment by dbtsai** [comment]
Closing this as I confirm that the brotli compressed metadata can be read from newer version of exiftools.
