### ISSUE TITLE
Test builds with -Werror

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#2670]
Hello,

there is an report from gentoo: https://bugs.gentoo.org/910099 (media-libs/libjxl-0.8.2-r1 adds -Werror flag on its own)

There is a following line in https://github.com/libjxl/libjxl/blob/0e265bfb2f5554d476c7014e43fb927a174b576e/tools/CMakeLists.txt#L386C1-L386C66
`target_compile_options(libjxl_test PRIVATE -Wall -Wextra -Werror)`

Would it be possible to make the -Werror optional?

**Comment by yota-code** [comment]
could be linked to #2669
