### ISSUE TITLE
Images with alpha mess with jpegli using XYB

### ISSUE THREAD

**Issue by Positron832Alt** [libjxl/libjxl#2671]
**Describe the bug**
Encoding an image with jpegli using XYB results in a stretched image with stripes and makes the image almost black and white.

**To Reproduce**
Download 64-bit nightly libjxl for Windows (I used https://artifacts.lucaversari.it/libjxl/libjxl/2023-07-19T08%3A42%3A59Z_0e8f059101cdd6acb4a871bfca22b50691971d17/jxl-x64-windows-static.zip)

Open PowerShell

Convert any PNG image with cjpegli using XYB.

`.\cjpegli ..\input.png ..\output.jpg --xyb`

**Expected behavior**
The image should not be stretched, have stripes, or almost be black and white.

**Screenshots**
Inputs:
![freddy](https://github.com/libjxl/libjxl/assets/114287709/12e11c15-2f14-4308-913e-73b3d21aecbb)
![pattern](https://github.com/libjxl/libjxl/assets/114287709/fd38e79f-46f0-4e23-87da-d2859c847017)
![colors](https://github.com/libjxl/libjxl/assets/114287709/2892a4b7-8b1c-4643-8423-7557057529b5)

Outputs:
![freddy](https://github.com/libjxl/libjxl/assets/114287709/4c7c220b-900a-4881-8d8e-5a98c7f0f070)
![pattern](https://github.com/libjxl/libjxl/assets/114287709/e8cefa79-bc59-4876-adf6-bc3bd8e3ea5e)
Weirdly this doesn't happen here...
![colors](https://github.com/libjxl/libjxl/assets/114287709/46cb79dd-5fdd-4575-9ad7-936f0184b81f)

**Environment**
 - OS: Windows 10 22H2
 - Compiler version: I dunno
 - CPU type: 64-bit
 - cjxl/djxl version string: v0.9.0 1a7931e [AVX2,SSE4,SSSE3,SSE2]
 
**Additoinal info**
I also tested the nightly build from 17th July too which outputs the same result. I think it could be something to do with the colors in the input that causes this.

**Comment by alistair7** [comment]
Reproduced on Linux using 0e265bf. The first two images have an alpha channel. The third one doesn't, but adding one causes the same issue.  See also #2579, #2656.
