### ISSUE TITLE
Bump requirement for highway library

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#2676]
Hello,

When someone builds libjxl using `JPEGXL_FORCE_SYSTEM_HWY`, cmake searches for `find_package(HWY 1.0.0)`.
https://github.com/libjxl/libjxl/blob/06d6570bc5427ec00188e1e5347cb1b184eda476/third_party/CMakeLists.txt#L34C3-L34C26

libjxl from git no longer works with highway 1.0.0 - 1.0.3 because symbol `HWY_AVX3_ZEN4` is used.

I think it would be good to require newer highway version explicitly.

**Comment by mo271** [comment]
not sure if we should also add libhwy-dev (>= 1.0.4) to debian/control, at least once that version of the libhwy-dev is available...
