### ISSUE TITLE
Encode API does not apply selected orientation

### ISSUE THREAD

**Issue by cagelight** [libjxl/libjxl#271]
In my code, I set `m_info.orientation = JXL_ORIENT_FLIP_VERTICAL;` on the JxlBasicInfo that I eventually send to `JxlEncoderSetBasicInfo`, which should create an orientation value of 4 in the output JXL. When I run `jxlinfo` on it however, I read `orientation: 1`. This appears to be the case for all JxlOrientation values.

**Comment by jonsneyers** [comment]
This one was fixed by https://github.com/libjxl/libjxl/pull/535.
