### ISSUE TITLE
Optimize an existing jxl image

### ISSUE THREAD

**Issue by avidseeker** [libjxl/libjxl#2778]
Consider a landscape (4000x3000) `orig.jpg`,

```bash
$ du orig.jpg
1792    orig.jpg
```

and apply two transformations:
1. Rotation then lossy conversion to jxl
2. Lossy conversion to jxl then rotation

```bash
$ convert -rotate 90 orig.jpg rot.jpg
$ cjxl -d 2 --lossless_jpeg=0 rot.jpg rot-jxl.jxl
$ cjxl -d 2 --lossless_jpeg=0 orig.jpg jxl.jxl
$ convert -rotate 90 jxl.jxl jxl-rot.jxl
$ du *
728     jxl-rot.jxl
576     jxl.jxl
1792    orig.jpg
600     rot-jxl.jxl
1752    rot.jpg
```

All tests I tried showed that `jxl-rot.jxl` is always larger than `rot-jxl.jxl`.
I'm no expert in data formats or compression, but I have two possibilities in
mind for this size discrepancy:
1. JPEGXL algorithm is more optimized to portrait images. This is evident by
comparing `jxl.jxl` with `rot-jxl.jxl` or `orig.jpg` with `rot.jpg`. But still,
26% increase in size just because of rotation makes me doubt this is the only
reason.
2. Imagemagick is doing some complex encoding/re-encoding behind the scenes
resulting in unoptimized jxl file.

Is there a way to recompress (optimize) an existing jxl file so that running it
on `jxl-rot.jxl` gives equal or better results than `rot-jxl.jxl`?

## Lossless tests
Curiously, this is the opposite case for lossless conversions.

Rotation then conversion:
```bash
$ convert -rotate 90 orig.jpg rot.jpg
$ du rot.jpg
1752    rot.jpg
$ cjxl rot.jpg rot-jxl.jxl
$ du rot-jxl.jxl
1448    rot-jxl.jxl
```

Conversion then rotation:
```bash
$ cjxl orig.jpg jxl.jxl
$ du jxl.jxl
1448    jxl.jxl
$ convert -rotate 90 jxl.jxl jxl-rot.jxl
$ du jxl-rot.jxl
988     jxl-rot.jxl
```

**Comment by jendalinda** [comment]
convert performs additional lossy compression, so the file size may increase due to increased noise in the picture. Try using png as the intermediate format.
jpegtran can perform lossless rotation of jpeg images. There is no such tool for jxl available at the moment.

**Comment by jonsneyers** [comment]
Yes, what you're effectively comparing is a first generation jpeg with a 2nd generation jpeg. The additional generation loss in your rotated image will in general introduce more artifacts (which are hard for lossless compression) and possibly make it compress slightly better with lossy compression.

Closing this issue now.
