### ISSUE TITLE
Building decoder only now requires lcms

### ISSUE THREAD

**Issue by saschanaz** [libjxl/libjxl#2822]
... after #2782.

Does the decoder now depend on lcms or is it solely a result of refactoring? Can it be split as it was if it does not?

**Comment by mo271** [comment]
cc-ing @eustas

**Comment by saschanaz** [comment]
This doesn't seem to be the case as of 4c23a53dde8840884f424bcca7c60947235fb421, thanks!

**Comment by mo271** [comment]
Thanks for checking @saschanaz!
