### ISSUE TITLE
[question/feature request] Is there a way to read source pixels?

### ISSUE THREAD

**Issue by HappySeaFox** [libjxl/libjxl#2824]
Hi! 🙂

Libjpeg library allows reading source pixels (RGB/Gray in YCbCr color space in most cases) from a jpeg file.

I noticed that the libjxl examples (decode-oneshot) always convert pixels to a specific format. Is there a way to access the original pixels without converting them to a different format?

**Comment by jonsneyers** [comment]
In 'native' lossy mode, the data is in XYB colorspace and if you want it in that space, you can ask for that.
In lossless mode, you can of course get the data in their original colorspace (RGB or CMYK).

So I guess the question is mostly about recompressed JPEGs, where the internal space is YCbCr, sometimes with chroma subsampling.

We could easily add an option to skip the YCbCr to RGB conversion and return the data in YCbCr. It's more complicated to add an option to get yuv420 data though — the current API is hardcoded for interleaved color data (RGB or RGBA).

How important is this feature request? What are the use cases where this would be useful/needed? The API _could_ be extended with an option to skip upsampling and return yuv420 data in some way, but that will take some nontrivial amount of work and I'm not sure if it's worth the effort...

**Comment by HappySeaFox** [comment]
Thanks! I'm currently just experimenting with libjxl and my current goal is to decode a jxl file as fast as possible (preserving the original color space and pixel format) even if I get XYZ pixels not immediately suitable for displaying in an UI app for example.

>In 'native' lossy mode, the data is in XYB colorspace and if you want it in that space, you can ask for that.
In lossless mode, you can of course get the data in their original colorspace (RGB or CMYK).

Could you please demonstrate this with a couple if lines of code, or just name api functions I need to use?

**Comment by jonsneyers** [comment]
To do the least amount of color conversions, you could use `JxlDecoderSetPreferredColorProfile()` with as argument a `JxlColorEncoding` that has `color_space` set to `JXL_COLOR_SPACE_XYB`, in combination with using a `JxlPixelFormat` that has `data_type` set to `JXL_TYPE_FLOAT` and `endianness` set to `JXL_NATIVE_ENDIAN`.
