### ISSUE TITLE
djxl: Netpbm output requires specific file extension for each pixel format

### ISSUE THREAD

**Issue by jendalinda** [libjxl/libjxl#2850]
When decoding to Netpbm image formats, djxl requires user to specify different file extensions for RGB, grayscale and images with alpha. Specifically, .ppm is required for RGB and  .pgm is required for grayscale. Additionally, .pam can only be used for images with alpha channel. 

djxl should allow .pnm file extension to support both RGB and grayscale images. For comparison, .pfm extension can be used for both RGB and graysdcale images.
The behavior when using .pam extension seems to be a bug, .pam should support RGB and grayscale, with or without alpha.

Here are test files for convenience:

[c0.jxl.gz](https://github.com/libjxl/libjxl/files/12835769/c0.jxl.gz) Grayscale, 8-bit
[c2.jxl.gz](https://github.com/libjxl/libjxl/files/12835770/c2.jxl.gz) RGB, 8-bit
[c4.jxl.gz](https://github.com/libjxl/libjxl/files/12835771/c4.jxl.gz) Grayscale+Alpha, 8-bit
[c6.jxl.gz](https://github.com/libjxl/libjxl/files/12835772/c6.jxl.gz) RGB+Alpha, 8-bit

Here are outputs of some tests:

Grayscale image can be decoded using .pgm and .pfm, other file extensions will fail.
```
d:\>djxl c0.jxl c0.ppm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
SelectFormat failed
DecompressJxlToPackedPixelFile failed

d:\>djxl c0.jxl c0.pnm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
can't decode to the file extension '.pnm'

d:\>djxl c0.jxl c0.pam
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
Encode failed

d:\>djxl c0.jxl c0.pgm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
320 x 240, 11.382 MP/s [11.38, 11.38], 1 reps, 4 threads.

d:\>djxl c0.jxl c0.pfm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
320 x 240, 11.120 MP/s [11.12, 11.12], 1 reps, 4 threads.
```
RGB image can be decoded using .ppm and .pfm, but .pnm and .pam will fail.
```
d:\>djxl c2.jxl c2.pnm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
can't decode to the file extension '.pnm'

d:\>djxl c2.jxl c2.pam
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
Encode failed

d:\>djxl c2.jxl c2.ppm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
320 x 240, 8.676 MP/s [8.68, 8.68], 1 reps, 4 threads.

d:\>djxl c2.jxl c2.pfm
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
320 x 240, 8.377 MP/s [8.38, 8.38], 1 reps, 4 threads.
```
.pam file extension works well for images with alpha channel.
```
d:\>djxl c4.jxl c4.pam
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
320 x 240, 9.644 MP/s [9.64, 9.64], 1 reps, 4 threads.

d:\>djxl c6.jxl c6.pam
JPEG XL decoder v0.9.0 136cd81 [SSE4,SSSE3,SSE2]
Decoded to pixels.
320 x 240, 8.812 MP/s [8.81, 8.81], 1 reps, 4 threads.
```

**Comment by mo271** [comment]
Thanks for bringing this up!
After the two changes #2869 and #2878, the following should work:

| File Format |          Without Alpha          |            |           With Alpha            |            |
|-------------|:-------------------------------:|:----------:|:------------------------------:|:----------:|
|             |         Grayscale, 8-bit        |  RGB, 8-bit|    Grayscale+Alpha, 8-bit      | RGB+Alpha, 8-bit |
| png         | ✔                               | ✔          | ✔                             | ✔               |
| apng        | ✔                               | ✔          | ✔                             | ✔               |
| jpeg        | ✔                              | ✔          | ✔                             | ✔               |
| pnm | ✔                              | ✔          | ✔                             | ✔               |
| ppm         | ❌                             | ✔          | ❌                             | ✔               |
| pgm         | ✔                             | ❌          | ✔                             | ❌               |
| pfm         | ✔                             | ✔          | ✔                             | ✔               |
| pam         | ✔                             | ✔          | ✔                             | ✔               |
