### ISSUE TITLE
Failed to read input from stdin

### ISSUE THREAD

**Issue by marcus65001** [libjxl/libjxl#2852]
**Describe the bug**
When I try to convert any input image, cjxl failed to read input from stdin with the error: `Reading image data failed.`

**To Reproduce**
`cjxl - - < in.jpg > out.jxl`

`cat in.jpg | cjxl - - > out.jxl`

**Expected behavior**
cjxl should read in the input from stdin and output into the stdout.

**Environment**
 - OS: Tested on both Windows 11 Home 22621.2283 and Linux 
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.8.2 954b4607 [AVX2,SSE4,SSSE3,SSE2]

**Comment by mo271** [comment]
Thanks for pointing out this issue! Seems like this is working on unix based systems, but still does not work on Windows. As a workaround until we have fixed it using WSL might help.

**Comment by zachpoblete** [comment]
309b637 fixes this.

**Comment by mo271** [comment]
please re-open if the problem is reproducible at current head
