### ISSUE TITLE
Progressive decoding performance drastically decreases with smaller buffer sizes

### ISSUE THREAD

**Issue by HappySeaFox** [libjxl/libjxl#2861]
**Describe the bug**
I use the following image for testing with `decode_progressive.cc`:
[death-gray8.zip](https://github.com/libjxl/libjxl/files/12856745/death-gray8.zip)

I also disabled writing PAM files to measure just decoding and not writing to disk:

```C
        char fname[1024];
        if (snprintf(fname, 1024, "%s-%" PRIu64 ".pam", filename,
                     static_cast<uint64_t>(seen)) >= 1024) {
          fprintf(stderr, "Filename too long\n");
          return false;
        };
        //if (!WritePAM(fname, pixels.data(), xsize, ysize)) {
        //  fprintf(stderr, "Error writing progressive output\n");
        //}

```

 I built `decode_progressive.cc` against vcpkg with libjxl 0.8.2, in "shared" and "release" mode.

People frequently use buffer sizes like `4096` to read from streams/memory.

**To Reproduce**
```
$ time ./decode_progressive F:/images/jpeg-xl/death-gray8-1.jxl out 4096
Flushing after 4096 bytes
<...>
real    0m0.780s
user    0m0.000s
sys     0m0.015s

$ time ./decode_progressive F:/images/jpeg-xl/death-gray8-1.jxl out 100000
Flushing after 100000 bytes
Flushing after 199761 bytes

real    0m0.160s
user    0m0.000s
sys     0m0.015s
```

Buffer = 4096 bytes, decoding time = 780 ms.
Buffer = 100'000 bytes, decoding time = 160 ms.
**Performance decrease = 5x**

**Environment**
 - OS: Windows 7 x64
 - Compiler version: MSVC 2019
 - vcpkg with libjxl 0.8.2: https://github.com/microsoft/vcpkg/tree/master/ports/libjxl, shared release build

**Comment by jonsneyers** [comment]
The user time is very low (0.000s) in both cases, so could it be that the difference is caused by the file output (and/or the terminal output) being slower when output is getting written in many small chunks instead of one big one?

**Comment by HappySeaFox** [comment]
I've just figured out the issue is in flushing chunks into the buffer which is not needed to measure decoding performance. After commenting out the flushing function, performance got back to expected (low fluctuation with different buffer sizes)
