### ISSUE TITLE
oss-fuzz has found an undefined shift (by -5) in libjxl

### ISSUE THREAD

**Issue by jcupitt** [libjxl/libjxl#29]
Hi, this image:

www.rollthepotato.net/~john/clusterfuzz-testcase-minimized-pngsave_buffer_fuzzer-5360982477111296

Produces this error in oss-fuzz:

```
&nbsp; | /src/jpeg-xl/lib/jxl/dec_modular.cc:471:47: runtime error: shift exponent -5 is negative
&nbsp; | #0 0x1434953 in jxl::ModularFrameDecoder::FinalizeDecoding(jxl::PassesDecoderState*, jxl::ThreadPool*, jxl::ImageBundle*) jpeg-xl/lib/jxl/dec_modular.cc:0
&nbsp; | #1 0x1387e5e in jxl::FrameDecoder::Flush() jpeg-xl/lib/jxl/dec_frame.cc:814:3
&nbsp; | #2 0x137f603 in jxl::FrameDecoder::FinalizeFrame() jpeg-xl/lib/jxl/dec_frame.cc:849:3
&nbsp; | #3 0x104eadf in jxl::(anonymous namespace)::JxlDecoderProcessInternal(JxlDecoderStruct*, unsigned char const*, unsigned long) jpeg-xl/lib/jxl/decode.cc:1155:30
&nbsp; | #4 0x104c287 in JxlDecoderProcessInput jpeg-xl/lib/jxl/decode.cc:1668:14
...
```

Not very important, but it should probably be fixed.

**Comment by jonsneyers** [comment]
I wonder how a bitstream managed to get a -5 _there_. Will have a look later.

**Comment by deymo** [comment]
hmm, I tried this from main just now running `djxl` from asan and msan builds and it only gets to `-1` there. Didn't see uninitialized memory in msan run. @jcupitt do you know what version of jxl is that report from?

**Comment by jcupitt** [comment]
I think it's the sync from two weeks ago (current github):

https://gitlab.com/wg1/jpeg-xl/-/compare/040eae8105b61b312a67791213091103f4c0d034...30ea86ab4c1f1b98c21967a2e3d72a51fe77e454

**Comment by jonsneyers** [comment]
It was a weird combination of modular transforms (something the encoder doesn't do) where multi-channel Palette is done after Squeeze, and inverse Palette had a bug where it wouldn't correctly set the `hshift`/`vshift` of the reconstructed channels, causing inverse Squeeze to potentially make them go negative.

https://github.com/libjxl/libjxl/pull/35 should fix it.
