### ISSUE TITLE
JxlEncoderAddImageFrame failed to handle RGBA data

### ISSUE THREAD

**Issue by qdwang** [libjxl/libjxl#2901]
**Describe the bug**
I'm using libjxl in Rust.
When passing the RGBA array(like 2x2 8bit image data: `[255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255]`) to `JxlEncoderAddImageFrame`, it will cause a `0x81 JXL_ENC_ERR_API_USAGE` error.

It has no problem to work with RGB data.

**To Reproduce**
```rust
// already called JxlEncoderSetBasicInfo with no error

let frame_settings = JxlEncoderFrameSettingsCreate(jxl_encoder, core::ptr::null());

let pixel_size = width as usize * height as usize * 4;
let mut img = vec![0u8; pixel_size];
for pixel in img.chunks_exact_mut(4) {
    pixel[0] = 255;
    pixel[3] = 255;
}
let img_ptr = img.as_ptr() as *const c_void;
let pixel_format = JxlPixelFormat {
    num_channels: 4,
    data_type: JxlDataType::JXL_TYPE_UINT16,
    endianness: JxlEndianness::JXL_NATIVE_ENDIAN,
    align: 0,
};
JxlEncoderAddImageFrame(
    frame_settings,
    &pixel_format,
    img_ptr,
    pixel_size * core::mem::size_of::<u8>(),
);
let error = JxlEncoderGetError(jxl_encoder);
```
The `error` is `0x81`.

The complete code is here: https://gist.github.com/qdwang/12304a925f1b0d3c1231a3b2dd0d63a6

**Expected behavior**
The `error` should be `0`

**Environment**
 - OS: MacOS 13.4
 - Compiler version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
 - CPU type: Apple M2
 - cjxl/djxl version string: nightly

**Comment by alistair7** [comment]
Does it work if you set `num_extra_channels: 1`, `alpha_bits: 8` in the `JxlBasicInfo`?  It probably doesn't like adding an RGBA frame to an RGB image.

The code above also has `JxlPixelFormat` `data_type` set to `JXL_TYPE_UINT16` when the data looks like it's actually `JXL_TYPE_UINT8` - but I see the full code is consistently using UINT8s.

**Comment by qdwang** [comment]
Thanks. It works with `num_extra_channels: 1` and `alpha_bits: 8`. 

But is it possible to ignore the alpha channel? My goal is to encode RGBA data to RGB jxl file, the alpha channel data is useless in my case. By setting `num_extra_channels` and `alpha_bits` will also encode the alpha channel data in the final result.

**Comment by alistair7** [comment]
I think with the current API you would have to remove the interleaved alpha from the pixel buffer and pass it as 3 channels only.

There are some TODOs in the `JxlPixelFormat` description hinting at support for different channel ordering etc.  Maybe in the future it will support an "RGBx" format where every fourth sample is ignored... but with the current API, I don't know of any way to ignore it.

**Comment by qdwang** [comment]
Thanks for your reply. Now I get it.
