### ISSUE TITLE
Current 0.10.0 cjxl produces unreadable files w/ lossless jpeg transcoding

### ISSUE THREAD

**Issue by gitoss** [libjxl/libjxl#2995]
**Describe the bug**
I'm using the bleeding edge win binaries for a long time. Recent versions (0.10.0 about-ish, I cannot say which exact commit) produce jxl files that are unreadable in XnViewMP and Chrome (Thorium), I didn't check others. 

Since the bitstream format is fixed, I'm reporting this to be safe - of course the problem might be the compile.

**To Reproduce**
Current 0.10.0 produces unreadable jxl files: downloaded from https://artifacts.lucaversari.it/libjxl/libjxl/latest/jxl-x64-windows-static.zip 

An older 0.9.0 binary works just fine: http://jeremylee.sh/bins/jpegxl.7z

**Expected behavior**
The jxl produced by 0.10.0 should be as readable as from 0.9.0

**Screenshots**
Attached source jpeg, jxl from 0.9.0 and current 0.10.0

**Environment**
 - OS: Windoes
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.10.0 9b82fa1 [SSE4,SSSE3,SSE2]
 
**Additional context**
Trancoding the jxl to original jpeg continues to work fine w/ current 0.10.0
![logo](https://github.com/libjxl/libjxl/assets/10775306/91cfaa21-9edd-48a3-b61f-8e02ccefeceb)
![logo-v010 jxl](https://github.com/libjxl/libjxl/assets/10775306/f90240e6-7c3a-4470-a41e-149e096fb825)
![logo-v090 jxl](https://github.com/libjxl/libjxl/assets/10775306/5a322e2f-bca2-4320-8462-5977ef011b0e)

**Comment by alistair7** [comment]
The v010 file contains a box with an "extended" size, which wasn't correctly handled by the decoder until #1478 was fixed recently.

But the fact that the encoder is using extended box sizes when it isn't necessary seems like a bug.  That's going to cause a problem for all current decoders...

**Comment by gitoss** [comment]
> The v010 file contains a box with an "extended" size, which wasn't correctly handled by the decoder until #1478 was fixed recently.
> 
> But the fact that the encoder is using extended box sizes when it isn't necessary seems like a bug. That's going to cause a problem for all current decoders...

Right, so let's hope app devs will regularly update their decoder libs. That doesn't seem to happen though because the fix in in https://github.com/libjxl/libjxl/issues/1478 is 1.5 years old.

I've added a bug ticket as a reminder for XnViewMP: https://forum.xnview.com/viewtopic.php?f=62&t=46505&sid=bbcad5a65550cef12da89c1080dc114f

For the time being, I'll keep the 0.9.0 encoder close to my heart :-)

**Comment by alistair7** [comment]
> That doesn't seem to happen though because the fix in in https://github.com/libjxl/libjxl/issues/1478 is 1.5 years old.

It's worse than that :).  Although it's not obvious from that bug, it wasn't fully fixed until last week: #2958, so it really is only the bleeding edge decoder that can deal with those files.

**Comment by mo271** [comment]
#3001 should fix this, please re-open if issues remain.
