### ISSUE TITLE
lib/include/jxl/cms_interface.h: mangled Sphinx generated documenation.

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#3008]
**Describe the bug**
I don't think it's supposed to look like this.
![image](https://github.com/libjxl/libjxl/assets/1342577/6bdddac3-32a0-4ae4-8c5a-7102d0f90f66)

**To Reproduce**
See: https://libjxl.readthedocs.io/en/latest/api_color.html#structJxlCmsInterface

**Suggested Fix**
There's probably a typo somewhere, but I'm not familiar enough with the documentation engine to find it.

**Comment by eustas** [comment]
Going to check soon. Thats the on graphviz diagram in generated docs, likely plugin did not work as expected.

**Comment by eustas** [comment]
Not sure why shuffling code in #3015 helped, but now diagram is generated:
<img width="699" alt="Screenshot 2023-12-12 at 12 56 11" src="https://github.com/libjxl/libjxl/assets/203457/9e2c8366-a92e-44ce-a87b-b13b60b04bd1">

**Comment by eustas** [comment]
GH Pages deployment  looks ok: https://libjxl.github.io/libjxl/api_color.html#_CPPv415JxlCmsInterface
