### ISSUE TITLE
Building decoder-only now requires cms again

### ISSUE THREAD

**Issue by saschanaz** [libjxl/libjxl#3009]
Migrating to the latest libjxl commit in Gecko fails with:

```
 0:32.23 D:/gecko/third_party/jpeg-xl/lib/jxl/cms/jxl_cms.cc(38,10): fatal error: 'lcms2.h' file not found
 0:32.23    38 | #include "lcms2.h"
 0:32.23       |          ^~~~~~~~~
```

This is probably done by https://github.com/libjxl/libjxl/pull/2927. Is there still a way to build the decoder without CMS?

**Comment by eustas** [comment]
Hello. Do you want decoder without CMS or without dependency to `lcms`? If the latest, then you should build with `-DJPEGXL_ENABLE_SKCMS=ON`, and `-DJPEGXL_BUNDLE_SKCMS=ON`.

**Comment by saschanaz** [comment]
But that then enables lkcms, when Gecko has its own in the decoder system. Can we skip CMS at all?

**Comment by saschanaz** [comment]
How did it work before the CMS work?

**Comment by eustas** [comment]
Oh, I see the point. I'll check if we can add "no-cms" build option, that will exclude `skcms`/`lcms` parts from `jxl_cms`

**Comment by mo271** [comment]
https://github.com/libjxl/libjxl/pull/3047

**Comment by saschanaz** [comment]
Perfect, thanks!
