### ISSUE TITLE
jxl_cms.h not installed

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#3010]
**Describe the bug**
lib/jxl/cms/jxl_cms.h is not installed, which makes it impossible to use `JxlGetDefaultCms()` and similar functions.

**Expected behavior**
Install the necessary headers.

**Comment by eustas** [comment]
Header is not installed, because it is not in includes/ folder.
@mo271 do we want `JxlGetDefaultCms` to become a part of public API?

**Comment by Traneptora** [comment]
Without it, it's not possible for a decoder to utilize the CMS API without bringing its own CMS to the table, which sort of defeats the purpose of building one into libjxl on decode-side.

**Comment by mo271** [comment]
@eustas yes, I think `JxlGetDefaultCms` should become part of the public API

**Comment by novomesk** [comment]
I'd like to use the JxlGetDefaultCms() too.

**Comment by eustas** [comment]
On it

**Comment by novomesk** [comment]
Will it be backported into `v0.9.x`?

**Comment by mo271** [comment]
Yes

Daniel Novomeský ***@***.***> schrieb am Do., 21. Dez. 2023,
18:27:
