### ISSUE TITLE
Libjxl static build requires -DJPEGXL_ENABLE_SKCMS=false to link

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjxl/libjxl#3021]
**Describe the bug**

Unless -DJPEGXL_ENABLE_SKCMS=false is specified in a static build, a dependent application is not able to link due to unresolved skcms symbols, which appear to be in an uninstalled libskcms.a.  This includes when -DJPEGXL_BUNDLE_SKCMS=true.

**To Reproduce**

With libraries (libpng, libjpeg, liblcms2) built static in advance, this build recipe is used:

```
    cmake \
        -DCMAKE_INSTALL_PREFIX=$WORK \
        -DBUILD_TESTING=off \
        -DBUILD_SHARED_LIBS=false \
        -DCMAKE_BUILD_TYPE=Release \
        -DJPEGXL_ENABLE_BENCHMARK=false \
        -DJPEGXL_ENABLE_EXAMPLES=false \
        -DJPEGXL_ENABLE_FUZZERS=false \
        -DJPEGXL_ENABLE_JPEGLI=false \
        -DJPEGXL_ENABLE_MANPAGES=OFF \
        -DJPEGXL_ENABLE_SJPEG=false \
        -DJPEGXL_ENABLE_TOOLS=false \
        -DJPEGXL_ENABLE_VIEWERS=false \
        -DJPEGXL_ENABLE_JPEGLI=false \
        -DJPEGXL_FORCE_SYSTEM_LCMS2=false \
        -DCMAKE_C_FLAGS="-DHWY_DISABLED_TARGETS=HWY_SSSE3 ${CFLAGS} -fPIC" \
        -DCMAKE_CXX_FLAGS="-DHWY_DISABLED_TARGETS=HWY_SSSE3 ${CXXFLAGS} -fPIC" \
        "${SRC}/libjxl"
```
With the above, a spew of unresolved symbols are produced when performing a static link with a dependent application (GraphicsMagick) for purpose of oss-fuzz testing.  However, this recipe avoids the unresolved symbols:

```
    cmake \
        -DCMAKE_INSTALL_PREFIX=$WORK \
        -DBUILD_TESTING=off \
        -DBUILD_SHARED_LIBS=false \
        -DCMAKE_BUILD_TYPE=Release \
        -DJPEGXL_ENABLE_BENCHMARK=false \
        -DJPEGXL_ENABLE_EXAMPLES=false \
        -DJPEGXL_ENABLE_FUZZERS=false \
        -DJPEGXL_ENABLE_JPEGLI=false \
        -DJPEGXL_ENABLE_MANPAGES=OFF \
        -DJPEGXL_ENABLE_SJPEG=false \
        -DJPEGXL_ENABLE_TOOLS=false \
        -DJPEGXL_ENABLE_VIEWERS=false \
        -DJPEGXL_ENABLE_JPEGLI=false \
        -DJPEGXL_ENABLE_SKCMS=false \
        -DJPEGXL_BUNDLE_SKCMS=false \
        -DJPEGXL_FORCE_SYSTEM_LCMS2=false \
        -DCMAKE_C_FLAGS="-DHWY_DISABLED_TARGETS=HWY_SSSE3 ${CFLAGS} -fPIC" \
        -DCMAKE_CXX_FLAGS="-DHWY_DISABLED_TARGETS=HWY_SSSE3 ${CXXFLAGS} -fPIC" \
        "${SRC}/libjxl"
```

**Expected behavior**

It is expected that when a dependent application links using the linker flags output by 'pkg-config --static libjxl --libs' that linking will be successful.  But this is not possible since the skcms symbols are not included in libjxl.a.

**Environment**
 - OS: Linux
 - Compiler version: clang version 15.0.0
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.10.0 733dfda [AVX3,AVX2,SSE4,SSE2]

**Additional context**
None

**Comment by BtbN** [comment]
For me, it fails to link no matter if it's using lcms or skcms.
It just fails with different missing symbols
```
...
jxl_cms.cc:(.text+0x33a8): undefined reference to `cmsCloseProfile'
...
```
and so on.

As it stands right now, statically linking latest libjxl with build-in l/skcms is impossible.

**Comment by inflation** [comment]
It used to have the option to bundle `skcms` into `libjxl.a`.
