### ISSUE TITLE
OSS Fuzz Issue Issue 64990: graphicsmagick:coder_JXL_fuzzer: Global-buffer-overflow in jxl::Status jxl::DecodeACVarBlock<

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjxl/libjxl#3025]
**Describe the bug**

This issue has appeared due to GraphicsMagick oss-fuzz testing, and JXL is now included in the build.

This is the crash stack-trace:

#0 0xb130e22 in ZeroDensityContext [libjxl/lib/jxl/ac_context.h:78](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/ac_context.h#L78):11
	    #1 0xb130e22 in jxl::Status jxl::(anonymous namespace)::DecodeACVarBlock<(jxl::ACType)1, false>(unsigned int, unsigned int, int*, int const*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, jxl::AcStrategy, unsigned int const*, jxl::BitReader*, jxl::ANSSymbolReader*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, unsigned char const*, int const*, jxl::BlockCtxMap const&, jxl::ACPtr, unsigned int) [libjxl/lib/jxl/dec_group.cc:481](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/dec_group.cc#L481):24
	    #2 0xb12bbc6 in jxl::(anonymous namespace)::GetBlockFromBitstream::LoadBlock(unsigned int, unsigned int, jxl::AcStrategy const&, unsigned int, unsigned int, jxl::ACPtr*, jxl::ACType) [libjxl/lib/jxl/dec_group.cc:548](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/dec_group.cc#L548):9
	    #3 0xb08c892 in jxl::N_SSE4::DecodeGroupImpl(jxl::FrameHeader const&, jxl::GetBlock*, jxl::GroupDecCache*, jxl::PassesDecoderState*, unsigned int, unsigned int, jxl::RenderPipelineInput&, jxl::ImageBundle*, jxl::DrawMode) [libjxl/lib/jxl/dec_group.cc:332](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/dec_group.cc#L332):9
	    #4 0xb0cb204 in jxl::DecodeGroup(jxl::FrameHeader const&, jxl::BitReader* restrict*, unsigned int, unsigned int, jxl::PassesDecoderState*, jxl::GroupDecCache*, unsigned int, jxl::RenderPipelineInput&, jxl::ImageBundle*, unsigned int, bool, bool, bool*) [libjxl/lib/jxl/dec_group.cc:761](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/dec_group.cc#L761):3
	    #5 0xb079be0 in jxl::FrameDecoder::ProcessACGroup(unsigned int, jxl::BitReader* restrict*, unsigned int, unsigned int, bool, bool) [libjxl/lib/jxl/dec_frame.cc:485](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/dec_frame.cc#L485):5
	    #6 0xb0866dd in operator() [libjxl/lib/jxl/dec_frame.cc:698](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/dec_frame.cc#L698):5
	    #7 0xb0866dd in jxl::ThreadPool::RunCallState<jxl::FrameDecoder::ProcessSections(jxl::FrameDecoder::SectionInfo const*, unsigned int, jxl::FrameDecoder::SectionStatus*)::$_1, jxl::FrameDecoder::ProcessSections(jxl::FrameDecoder::SectionInfo const*, unsigned int, jxl::FrameDecoder::SectionStatus*)::$_2>::CallDataFunc(void*, unsigned int, unsigned int) [libjxl/lib/jxl/base/data_parallel.h:94](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/jxl/base/data_parallel.h#L94):14
	    #8 0xb7e9c6d in RunRange [libjxl/lib/threads/thread_parallel_runner_internal.cc:139](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/threads/thread_parallel_runner_internal.cc#L139):7
	    #9 0xb7e9c6d in jpegxl::ThreadParallelRunner::ThreadFunc(jpegxl::ThreadParallelRunner*, int) [libjxl/lib/threads/thread_parallel_runner_internal.cc:169](https://github.com/libjxl/libjxl/blob/581b62dd71384ecadfe539cc173141c73a0748e3/lib/threads/thread_parallel_runner_internal.cc#L169):9
	    #10 0xb7ebdad in __invoke<void (*)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int> /usr/local/include/c++/v1/type_traits:3592:23
	    #11 0xb7ebdad in __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(jpegxl::ThreadParallelRunner *, int), jpegxl::ThreadParallelRunner *, unsigned int, 2U, 3U> /usr/local/include/c++/v1/thread:281:5
	    #12 0xb7ebdad in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(jpegxl::ThreadParallelRunner*, int), jpegxl::ThreadParallelRunner*, unsigned int> >(void*) /usr/local/include/c++/v1/thread:292:5
	    #13 0x8242199 in __asan::AsanThread::ThreadStart(unsigned long long) /src/llvm-project/compiler-rt/lib/asan/asan_thread.cpp:277:25
	    #14 0x821bafe in asan_thread_start(void*) /src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:199:13
	    #15 0xf7e5c609 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
	    #16 0xf7d6bd29 in __clone

**To Reproduce**

A compressed tarball has been provided with the test cases from oss-fuzz.  As far as I am aware, it is only necessary to read the file (possibly a forced read)
[oss-fuzz-64990.tar.gz](https://github.com/libjxl/libjxl/files/13666903/oss-fuzz-64990.tar.gz)
.

**Expected behavior**

Don't crash

**Environment**
 - OS: Ubuntu 20.04 LTS
 - Compiler version: 15.0.0
 - CPU type: i386
 - cjxl/djxl version string: cjxl v0.10.0 961307e [SSE4,SSE2]

**Comment by eustas** [comment]
Will take a look soon.

**Comment by eustas** [comment]
Currently I have 2 guesses:
 - compiler bug (happens quite often on i386 with our project)
 - silent overflow in `if (nzeros + covered_blocks > size) {` check; given size_t is 32 bit i386 arch, that is not impossible

Investigating further.

**Comment by eustas** [comment]
In attached report it is said `is located 2 bytes to the left of global variable 'jxl::kCoeffNumNonzeroContext'`, i.e. `nzeros == size_t(-1)`. `nzeros` is decremented one-by-one and compared to zero before entering the loop. I.e. it had that value initially. That corresponds to guess number 2.

It is easy to fix. Going to try to repro it with oss-fuzz harness and check is suggested fix helps.

**Comment by bobfriesenhahn** [comment]
oss-fuzz reports that this issue is fixed.
