### ISSUE TITLE
djxl: Full file path not working on Windows

### ISSUE THREAD

**Issue by jendalinda** [libjxl/libjxl#3068]
djxl fails to write the output file if the output file name is specified using the full path.
```
d:\0>djxl test.jxl d:\test.png
JPEG XL decoder v0.10.0 ed80bfe [SSE4,SSSE3,SSE2]
can't decode to the file extension '.d'
```
However, it works if drive letter is not used.
```
d:\0>djxl test.jxl \test.png
JPEG XL decoder v0.10.0 ed80bfe [SSE4,SSSE3,SSE2]
Decoded to pixels.
512 x 512, 9.242 MP/s [9.24, 9.24], 1 reps, 4 threads.
```

**Comment by alistair7** [comment]
It's interpreting the `d:` as the requested output format.  e.g., you can prefix the file name with `jpg:`, or `png:` to force a particular format regardless of the file extension.  Slightly annoying for Windows paths (maybe djxl should avoid doing this for single-letter prefixes?), but this should be a workaround:

`djxl test.jxl png:d:\test.png`

**Comment by jendalinda** [comment]
djxl does not support any output format with a single letter file extension, so these should be left as drive letters as this is the generally expected behavior.

**Comment by jonnyawsom3** [comment]
I'd assume using quotations marks might fix the issue?

**Comment by jendalinda** [comment]
Using quotes does not fix the issue.
```
d:\0>djxl test.jxl "d:\test.png"
JPEG XL decoder v0.10.0 ed80bfe [SSE4,SSSE3,SSE2]
can't decode to the file extension '.d'
```
Anyway, using drive letter is allowed for the input file, so the arguments are now behaving inconsistently.
```
d:\>djxl d:\0\test.jxl test.png
JPEG XL decoder v0.10.0 ed80bfe [SSE4,SSSE3,SSE2]
Decoded to pixels.
512 x 512, 8.312 MP/s [8.31, 8.31], 1 reps, 4 threads.
```
