### ISSUE TITLE
deps.sh is failing in 0.9.0

### ISSUE THREAD

**Issue by adityapatadia** [libjxl/libjxl#3070]
Deps.sh file has a bug because of which it's never able to download LIBJPEG_TURBO.

The output while downloading is `Downloading third_party/libjpeg-turbo version TURBO...` which ideally should be `Downloading third_party/libjpeg-turbo version <sha_hash>...`

Because of that, it's impossible to install this library.

**Comment by vtorri** [comment]
deps.h is useless

ask people to install the required packages with their prefered package manage and get rid of this script. simpler and less problems
