### ISSUE TITLE
0.9.0 - Failed to encode with specific (CMYK) ICC

### ISSUE THREAD

**Issue by kampidh** [libjxl/libjxl#3078]
**Describe the bug**
While updating to 0.9.0 in Krita, I got this error when exporting CMYK(A) image:
```
lib\jxl\color_encoding_internal.cc:202: JXL_FAILURE: Empty ICC
lib\jxl\color_encoding_internal.cc:202: JXL_FAILURE: Empty ICC
lib\jxl\color_encoding_internal.cc:202: JXL_FAILURE: Empty ICC
lib\jxl\enc_fields.cc:76: JXL_RETURN_IF_ERROR code=1: Bundle::CanEncode(fields, &extension_bits, &total_bits)
lib\jxl\enc_fields.cc:208: JXL_RETURN_IF_ERROR code=1: WriteImageMetadata(metadata->m, writer, kLayerHeader, aux_out)
lib\jxl\encode.cc:753: Failed to write codestream header
```
Even though the ICC is already set with `JxlEncoderSetICCProfile`. Other (RGB) ICC profiles work fine, only happens with CMYK, both in lossy (both original and XYB) and lossless (original). At first I thought it was because of large size for CMYK ICC, but then I tried to use RGB profile with large LUTs it exported successfully.

This doesn't happen with 0.8.2.

**To Reproduce**
- Set ICC with `JxlEncoderSetICCProfile`
- Prepare for CMYK(A) buffer with `JxlEncoderSetExtraChannelInfo`, `JxlEncoderAddImageFrame` and `JxlEncoderSetExtraChannelBuffer`
- Encode failed during `JxlEncoderProcessOutput` and returns the lines above.

**Expected behavior**
CMYK image exported successfully.

**Environment**
 - OS: Windows 11
 - Compiler version: Clang 15
 - CPU type:  x86_64
 - cjxl/djxl version string: 0.9.0

**Additional context**
Example ICC used for the test:
[cmyk.zip](https://github.com/libjxl/libjxl/files/13769497/cmyk.zip)

**Comment by sboukortt** [comment]
Thank you for reporting this. Given that it appears to be a regression, would you be in a position to bisect this without too much trouble? Alternatively, some minimal (or not so minimal) code to reproduce the issue would probably help with investigating this.

**Comment by kampidh** [comment]
@sboukortt I'll try my best, currently some commits are failing to build with lcms2, which is kind of tricky to bisect..

And as for the complete code, our current implementation is here https://invent.kde.org/graphics/krita/-/blob/master/plugins/impex/jxl/JPEGXLExport.cpp

**Comment by kampidh** [comment]
Alright, I got some findings after bisecting:

- CMYK images failed to encode with above errors after aa41093e1b39c2b6eac77096b8ec43d86a97d5fa , (maybe after ddd8e5841840e0aa0a1b5c0da0fafaf9e9a2273d to be precise, but I was unable to build with lcms2 on that specific commit).
- However before that commit, CMYK images can be encoded successfully but failed to decode, `jxlinfo -v` returns `Color space: JxlDecoderGetICCProfileSize failed` (Example encoded file: [cmyk-mising-icc.zip](https://github.com/libjxl/libjxl/files/13783747/cmyk-mising-icc.zip)). Tracing further back to a36aa48a9f56bb744ee7f49e7463d99d53dcea17 that caused this error. Below that commit, CMYK works just fine.

Hopefully this helps!

**Comment by novomesk** [comment]
I have also problem writing CMYK+A JXL in GIMP 2.99.17 with libjxl 0.9.0

I am getting slightly different message:
```
./lib/jxl/color_encoding_internal.cc:202: JXL_FAILURE: Empty ICC
./lib/jxl/fields.cc:428: JXL_UNREACHABLE: AllDefault should never fail
```
