### ISSUE TITLE
"Error parsing flag -x"

### ISSUE THREAD

**Issue by zinalili** [libjxl/libjxl#3087]
**Describe the bug**
"-x" option is not recognized

**To Reproduce**
From the changelog of 0.9.0
`cjxl can now be used to explicitly add/update/strip Exif/XMP/JUMBF metadata using
the decoder-hints syntax, e.g. cjxl input.ppm -x exif=input.exif output.jxl`

**Expected behavior**
it does not seem to work

**Environment**
 - OS: Windows, Powershell

**Comment by mo271** [comment]
Thanks for your report!

I cannot reproduce the bug you are describing; perhaps you could provide an example of an exif file where this fails?!

**Comment by zinalili** [comment]
I'm trying to convert JPG into JXL without losing EXIF data. Can I do that with this command or I have to have a separate EXIF file that will be imported into JXL?
