### ISSUE TITLE
Link errors while building v0.9.0 on Windows (cannot open file 'RelWithDebInfo\jxl_cms.lib')

### ISSUE THREAD

**Issue by PetrMinar** [libjxl/libjxl#3125]
I have problems with building 0.9.0 on Windows. I always get the following error:
```
LINK : fatal error LNK1104: cannot open file 'RelWithDebInfo\jxl_cms.lib' [C:\Projects\libjxl-build\RelWithDebInfo-x64\
lib\jxl.vcxproj]
```
In past I had no problems building v0.8.2 and I can even build current main branch without errors.

**To Reproduce**
```
cd C:\projects
git clone https://github.com/libjxl/libjxl.git --recursive --shallow-submodules
cd libjxl
git checkout tags/v0.9.0
git submodule init
git submodule update --recursive
mkdir ..\libjxl-build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_TOOLS=0 -S . -B ..\libjxl-build\RelWithDebInfo-Win32 -G "Visual Studio 17 2022" -A Win32
cmake --build ..\libjxl-build\RelWithDebInfo-Win32 --config RelWithDebInfo -j8
```

**Expected behavior**
Should compile and link correctly

**Environment**
 - OS: Windows11
 - Compiler version: Visual Studio 2022 (17.8.3)
 - CPU type: I9-13900K

Perhaps I am doing something incorrectly (I am not sure about the git commands and submodules after checkingout v0.9.0) Thank you for looking into this matter.
Petr Minář

**Comment by kmilos** [comment]
Have you tried the v0.9.x branch? I think this should already have been fixed...

**Comment by mo271** [comment]
Hi thanks for the report!

Can you give the branch `v0.9.x` a try

**Comment by PetrMinar** [comment]
I have tried the v0.9.x branch and the build was successful. Thank you.
That brings another question - Can I use branch v0.9.x in production code or should I wait for release v0.9.1?

**Comment by mo271** [comment]
We plan to release what is currently in v0.9.x as v0.9.1 very soon

**Comment by PetrMinar** [comment]
Thank you once again.

**Comment by mo271** [comment]
fyi @kmilos , we just made the release...

**Comment by kmilos** [comment]
Thanks for the notice!
