### ISSUE TITLE
Document special ISOBMFF boxes

### ISSUE THREAD

**Issue by StefanOltmann** [libjxl/libjxl#3128]
I am the author of Kim, the Kotlin Image Manipulation library, available on https://github.com/Ashampoo/kim

Recently I added general support for ISOBMFF and now I want to parse JPEG XL, too. The information about image size and rotation for example are not covered by the ISOBMFF standard and file formats need to specify their own.

Please document all special JPEG XL BMFF boxes related to metadata, so I can fully support them.

**Comment by StefanOltmann** [comment]
@kmilos Thank you, I will look into that JUMBF box.

Can you tell me where I can find some sample JPEG XL files based on BMFF or even how to create or convert JPEG to JXL?

Most tools I found are always creating the naked byte stream, I want to analyze the container.

**Comment by kmilos** [comment]
> Can you tell me where I can find some sample JPEG XL files based on BMFF or even how to create or convert JPEG to JXL?

`cjxl` will write those boxes AFAIK:
```
 --container=0|1
    0 = Do not encode using container format (strip Exif/XMP/JPEG bitstream reconstruction data).1 = Force using container format
(default: use only if needed).

 --compress_boxes=0|1
    Disable/enable Brotli compression for metadata boxes (not provided = default, 0 = disable, 1 = enable).
```

Other than that, you can e.g. export one w/ (uncompressed) Exif and XMP from [darktable ](https://www.darktable.org/) (assuming it is built w/ libjxl support; Windows and macOS installers are, Linux packages may vary...).

You can also try a sample used in exiv2 unit tests: https://github.com/Exiv2/exiv2/blob/main/test/data/Reagan.jxl (also uncompressed)

**Comment by StefanOltmann** [comment]
Thank you both for your help! :)
I see my question fully answered.
