### ISSUE TITLE
0.9.1 red-room.jxl fails to load with gdk-pixbuf plugin

### ISSUE THREAD

**Issue by oreo639** [libjxl/libjxl#3144]
**Describe the bug**
In jxl 0.8.2, the red-room.jxl test image is able to be loaded in EOG using the gdk-pixbuf plugin.

In jxl 0.9.1 the red-room jxl test image fails to load in EOG.

The test image can be downloaded here:
https://jpegxl.info/test-page/

**To Reproduce**
1. Compile the jxl 0.9.1 release with no patches
2. Download red-room.jxl from here: https://jpegxl.info/test-page/
3. Run `gdk-pixbuf-pixdata red-room.jxl test.pixdata`
4. It outputs `failed to load "red-room.jxl": Failed to load image “red-room.jxl”: JxlDecoderSetImageOutBuffer failed`

The error is due to here: https://github.com/libjxl/libjxl/blob/8e7dc5eff3d3dc92281ce4edbd5ea86e58c8aaf0/lib/jxl/decode.cc#L2443 as, gdb outputs:
```
(gdb) finish
Run till exit from #0  JxlDecoderImageOutBufferSize (
    dec=dec@entry=0x555555581750, format=format@entry=0x55555556dc50, 
    size=size@entry=0x7ffffffee0e0)
    at /builddir/libjxl-0.9.1/libjxl-0.9.1/lib/jxl/decode.cc:2402
JxlDecoderSetImageOutBuffer (dec=0x555555581750, format=0x55555556dc50, 
    buffer=0x7ffff44b0010, size=1351980)
    at /builddir/libjxl-0.9.1/libjxl-0.9.1/lib/jxl/decode.cc:2441
2441	in /builddir/libjxl-0.9.1/libjxl-0.9.1/lib/jxl/decode.cc
Value returned is $1 = JXL_DEC_SUCCESS
(gdb) print min_size
$2 = 1354416
(gdb) print size
$3 = 1351980
```

This became a problem in 0.9.0 due to https://github.com/libjxl/libjxl/commit/2ef999bbaa3e5d03b1894d224b6f44e756b6822e and reverting the commit does work around the issue.

Using `gdk_pixbuf_get_pixels_with_length()`, the length of pixel buffer is `1354413` which is also too small.

**Expected behavior**

The pixdata file is outputted with no errors.

This issue is specific to the gtk-pixbuf plugin.
This image loads fine with gimp and krita.
It also mostly works with djxl, `djxl -v red-room.jxl test.jpeg` outputs the file as expected however `djxl -v red-room.jxl --disable_output` aborts in packed_image.h on line 87. May not be related though.

**Environment**
 - OS: Void Linux
 - Compiler version: Tested with both gcc 12 and gcc 13
 - CPU type: x86_64
 - cjxl/djxl version string: djxl v0.9.1 0.9.1 [AVX2,SSE4,SSE2]

**Comment by Traneptora** [comment]
There appears to be two issues here:
(1) Row Stride isn't being taken into account in the gdk-pixbuf plugin.
(2) Row Stride *is* taken into account in the min_size calculation but it's calculated incorrectly. If the distance between two rows is larger than an exact row of pixels, then the trailing unnecessary data isn't actually needed after the last pixel.
