### ISSUE TITLE
Apple Silicon macOS build of djxl crashes on metadata-only decode

### ISSUE THREAD

**Issue by tirr-c** [libjxl/libjxl#3148]
**Describe the bug**
macOS build of djxl crashes when I try to extract metadata.
```console
$ djxl image.jxl metadata.exif
JPEG XL decoder v0.10.0 8e7dc5ef [NEON]
zsh: trace trap  ./djxl image.jxl metadata.exif
```

**To Reproduce**
Try to extract metadata from an image with djxl. It doesn't need to have any metadata box.
```
djxl image.jxl metadata.exif
```

**Expected behavior**
It extracts metadata or prints an error if metadata doesn't exist, instead of crashing.

**Environment**
OS, CPU type and compiler version:
```
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

djxl version string:
```
JPEG XL decoder v0.10.0 8e7dc5ef [NEON]
```

**Additional context**
djxl was built from sources, but it also happens on Homebrew build (which is on v0.9.1).

**Comment by mo271** [comment]
Thanks for the report!

Does this happen with only one specific image? Are there images where it works?

**Comment by tirr-c** [comment]
It happens with every image I test, couldn't find one that doesn't crash.

**Comment by eustas** [comment]
Will take a look soon.

**Comment by Jerry1144** [comment]
Does not seem to happen with 0.10.2 Homebrew build.

**Comment by mo271** [comment]
ok, thanks for checking, let's close this issue then. Please re-open if the problem appears at 10.2 or newer...
