### ISSUE TITLE
Link failure due to missing DebugString() definitions

### ISSUE THREAD

**Issue by saucecontrol** [libjxl/libjxl#3159]
https://github.com/libjxl/libjxl/pull/2614 made `DebugString` compile conditionally on `JXL_DEBUG_V_LEVEL >= 1`.

When attempting to build v0.9.1 with vcpkg, I got linker errors on those methods under debug config.  I didn't take the time to untangle all the calls to find where they were sneaking in, but I suspect it might be related to `JXL_DEBUG_WARNING` or `JXL_DEBUG_ON_ERROR`, as I was able to fix the build by defaulting `JXL_DEBUG_V_LEVEL` to 1 when `!defined(NDEBUG)`.

I had a second issue on release config using `/LTCG` with MSVC, where it probably wanted to look into those methods despite the fact they should be trimmed away.  I ended up removing the conditions around [several](https://github.com/saucecontrol/PhotoSauce/blob/3a4f092c701b6f0990c1e8b388c535d06ac863e8/build/vcpkg/ports/libjxl/fix-debug-string.patch) `DebugString` definitions and was able to build successfully.

I'd open a PR to revert the above commit, but I figured the maintainers here might have a different preference.

**Environment**
 - OS: Windows
 - Compiler version: MSVC 17.8
 - vcpkg 2024.01.12
 - CPU type: x86_64

**Comment by dlemstra** [comment]
Can you give it another try with the last commit on the main branch? Did my PR resolve your issue?

**Comment by saucecontrol** [comment]
Yep, that did it, thanks!
