### ISSUE TITLE
I ran a local benchmark of JXL vs AVIF

### ISSUE THREAD

**Issue by alexandrehtrb** [libjxl/libjxl#3176]
Hello,

I hope this is the correct place to post this.

I have been reading about JXL and AVIF and I found very interesting these two new image formats, they are very promising.

On most of the blog posts that I read, JXL fared equal or better regarding compression, but, on a local benchmark, AVIF fared better in every scenario, with smaller output sizes; although it took much longer to process.

Could you guys help me see if something is wrong in my tests?

My machine: Windows 7 x64

For JXL, I used libjxl 0.9.1:

```pwsh
if ($inputFile -like "*jpg")
{
    ./cjxl.exe $inputFile $outputFile -q 90 --lossless_jpeg=0
}
else
{
    ./cjxl.exe $inputFile $outputFile -q 90
}
```

For AVIF, I used cavif-rs:

```pwsh
./cavif.exe $inputFile -o $outputFile -Q 90 -f
```

**Comment by alexandrehtrb** [comment]
Update: I realized that I had to pass `--lossless_jpeg=0` to specify quality for JPG, I re-ran the tests and updated the results table above. The results are more consistent now.

**Comment by mo271** [comment]
> Could you guys help me see if something is wrong in my tests?

One thing that might need some consideration is the fact your comparison seems to make the assumption that passing a quality parameter to cjxl and cavif result in comparable quality. However that is not necessarily the case. We write in our api documentation on the topic:

 > Note: the `quality` parameter has no consistent psychovisual meaning
 > across different codecs and libraries. Using the mapping defined by 
 > `JxlEncoderDistanceFromQuality` will result in a visual quality roughly
 > equivalent to what would be obtained with `libjpeg-turbo` with the same
 > `quality` parameter, but that is by no means guaranteed; do not assume that
 > the same quality value will result in similar file sizes and image quality
 > across different codecs.

**Comment by jonsneyers** [comment]
Here are some useful basic guidelines for how to do a meaningful comparison of image codecs: https://kornel.ski/en/faircomparison
(by the cavif author, by the way)

**Comment by alexandrehtrb** [comment]
Thanks!

**Comment by alexandrehtrb** [comment]
I've made a repo for benchmarking JXL vs AVIF:

https://github.com/alexandrehtrb/jxl-avif-simple-benchmark

My analysis, based on the results, is that:

* JXL is faster than AVIF in every scenario;
* JXL offers better compression for high-detail photography;
* AVIF offers better compression for videos and GIFs;
* In one of the tests, `organic_chemistry.png`, the original PNG file was smaller than both JXL and AVIF outputs

I would like to make a blog post about the two formats. It's not a qualitative analysis and not a scientific study.

Do you guys agree with my findings?

**Comment by mo271** [comment]
> * In one of the tests, `organic_chemistry.png`, the original PNG file was smaller than both JXL and AVIF outputs

For this kind of non-photographic content lossless compression can give smaller results than lossy compression. Perhaps try with `cjxl -d 0`.

**Comment by jonnyawsom3** [comment]
There was a heuristic planned to use lossless areas in the image when better compressed than lossy, so it's not unreasonable to do a lossless comparison on that image too
