### ISSUE TITLE
API break by not including version.h in decode.h

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#3177]
**Describe the bug**
version.h is no longer accessible or exported, which means macros like `JPEGXL_COMPUTE_NUMERIC_VERSION` `JPEGXL_NUMERIC_VERSION` are not available to callers anymore. This makes it not possible to get the version at preprocessor-time (or compile-time), which in turn makes `#ifdef`ing header version checks impossible (e.g. you want to use a new function that didn't exist in old versions, so you guard it with an #`ifdef`).

This is an API break (although not an ABI break).

**Additional context**
The culprit is 66b959239355aef5255502ada73c6cde54d00629 when the regression was introduced.

**Comment by eustas** [comment]
Going to fix it soon.

**Comment by eustas** [comment]
Completely agree, that is breaking API change, mea máxima culpa.

On the bright side: `version.h` was exported when it was created, i.e. `v0.7.0`.
This means that when version definitions / macro is used it is safe to add extra include.

Also, on a lucky coincidence, `ffmpeg` also requires libjxl package `>=0.7.0`, which means it is 100% safe to include `version.h`.

I propose to:
 - document the API change
 - add include in `libavcodec/libjxldec.c`

As a temporary measure (before the next release), I could put includes back into `decode.h`/`encode.h`.
@Traneptora WDYT?

**Comment by Traneptora** [comment]
Personally, I think libjxl is at a state in maturity where it shouldn't be breaking the API and require downstream clients to make changes to continue to work with newer library versions.
