### ISSUE TITLE
Question about JPEG XL codestream, embedded icc profiles and its handling in libjxl

### ISSUE THREAD

**Issue by PetrMinar** [libjxl/libjxl#3195]
Hello

I have a question about JPEG XL codestream, embedded icc profiles and its handling in libjxl.

As I have read in ISO 18181-1:2021 specs (I know there is newer edition, but unfortunately I do not have access to it) when `want_icc=1` than icc profile should follow after the `ImageMetadata / CustomTransform` as specified in Annex B. But before writing icc profile the stream should be aligned on byte boundary (`ZeroPadToByte`) - at least it is written in _B.2 Data stream_ ("The bitstream is byte aligned as specified in 6.3.").

I think that libjxl 0.9.1 does not do this aligning (after several hours of debugging). And when I introduce the padding the library refuses to read such a file. Is it a bug in libjxl or am I misreading the standard?

Just to explain why I am messing with codestream - I want to change orientation of the existing JXL and to do this I have to decode the headers. But the orientation is not always encoded in the codestream so I have to add it and rewrite the rest of the bistream (as discussed in [link](https://github.com/libjxl/libjxl/issues/648)). To do so I have to write all the following bits until I hit the first `ZeroPadToByte` and fix the padding. Than I can just blindly copy the rest of the codestream. Until now I thought that the first `ZeroPadToByte` is always right after `ImageMetadata / CustomTransform`. But that does not seem to work...

Thank you for clarification
Petr Minář

**Comment by Traneptora** [comment]
This is not true and it was changed in the more recent version of the spec. If you wish to change any of the header fields you will need to copy all of the remaining bits until you hit a ZeroPadToByte, which is before the first Frame. The bitreader is not zero-aligned before reading the ICC profile stream, if present. This does mean that editing the header values is a massive pain if there's an ICC profile in the stream.

**Comment by PetrMinar** [comment]
Thank you for clarification.

_If you wish to change any of the header fields you will need to copy all of the remaining bits until you hit a ZeroPadToByte, which is just before the first Frame_ To find the ZeroPadToByte after icc profile I have to first determine the bit length of the icc profile itself. For this it is necessary to implement "ANS / Hybrid integer coding"... that looks like a lot of work to be done. Or is there any "shortcut" how to safely find the ZeroPadToByte before first frame?

**Comment by Traneptora** [comment]
There is not. I searched for the solution to this exact problem for quite some time, but in a worst-case scenario, it is not possible to parse a JXL file without implementing its entropy decoder. Even if the ICC profile is not present, each Frame may have a permuted table of contents, and the TOC permutation is entropy-encoded. You can't skip past the TOC permutation without decoding it, which makes it not possible to calculate the length of the Frame.

Something you can do, if you wish to preserve the alignment after the ImageHeader, is to use the Extensions bundle as a way to create padding, since their payload sizes are recorded in bits, not bytes. Ideally there will actually be an extension specified which is required to be all zeroes in its payload for this purpose, but for now you can just pick a bit and use it.

**Comment by Traneptora** [comment]
Do note that the orientation in the codestream is automatically handled by libjxl, but you can tell it not to do that. See: https://libjxl.readthedocs.io/en/latest/api_decoder.html#_CPPv428JxlDecoderSetKeepOrientationP10JxlDecoder8JXL_BOOL

**Comment by Traneptora** [comment]
Another idea is that you can assume that most JXL viewers will handle the orientation properly, since re-orienting the JXL image is the default behavior. In that regard, you can always set the Exif orientation to "Do not rotate." JPEG XL spec requires that the codestream orientation take precedence, so any software that understands both Exif orientation and the one embedded in the codestream will be unaffected. Any software that only understands Exif orientation will have libjxl orient automatically, and zeroing out Exif rotation prevents it from being rotated again.

**Comment by PetrMinar** [comment]
That is unfortunately not going to help. The main problem is that when we rotate the image file (and we can rotate hundreds of files at once) we do not use libjxl at all. This is normally done just by updating the orientation in exif (=fast). Doing image data recompression (using libjxl) is not the way to go - it's slow and lossy(!). And libjxl cannot write a file without recompression, right?

So in case of JXL we have to fix the header in codestream. Until now we did that. But just last week I have encountered an file with binary icc profile... leading to corrupted file. I would say that such files are uncommon because most icc profiles can be replaced by primaries / whitepoint / trc. That is the reason why I have missed it in the first place.

As I see it, there are only four options:
1. Write the entropy decoder / encoder for icc profile and update the codestream 
2. Do slow recompression using libjxl
3. "Break" the rules and only update the exif
4. "Break" the rules, reset the orienation in jxl codestream and update the exif (= would not change the bit offset of icc profile).

Honestly I think most apps will choose the third option and it will became "defacto standard" regardless what the norm says. It wouldn't be the first time something like that has happend. What a shame... and all because of orientation in codestream and one missing padding that can save at most 7 bits. Such things make me really sad.

Right now I am considering the third or the fourth option. I have already written the header decoder / encoder, so I would "break the rules" only when I detect binary icc profile (`want_icc == 1`).

**Comment by Traneptora** [comment]
> Write the entropy decoder / encoder for icc profile and update the codestream

Fwiw, you don't have to write an entropy encoder. A decoder is necessary to determine the length, but once you determine it, you know the alignment, and can just re-use the already-compressed ICC stream that was present in the file.

**Comment by PetrMinar** [comment]
Of course I don't need a encoder. Today I have checked the standard in detail and tried to write the protoype of the decoder so I have better understanding how much work it would be. And it's awful a lot of work given that all I want is just to change 1 bit in the header.  The specs even include parts of IETF RFC 7932:2016 - brotli compression.

That leaves me with question what is the relationship of "brotli compression" and "jxl ANS / Hybrid integer coding". Some parts of libjxl looks like they are copied from directly brotli lib itself. And perhaps if brotli lib could be used instead of writing the decoder itself...

**Comment by veluca93** [comment]
> Of course I don't need a encoder. Today I have checked the standard in detail and tried to write the protoype of the decoder so I have better understanding how much work it would be. And it's awful a lot of work given that all I want is just to change 1 bit in the header. The specs even include parts of IETF RFC 7932:2016 - brotli compression.
> 
> That leaves me with question what is the relationship of "brotli compression" and "jxl ANS / Hybrid integer coding". Some parts of libjxl looks like they are copied from directly brotli lib itself. And perhaps if brotli lib could be used instead of writing the decoder itself...

The common part is the way prefix codes are encoded.

I would recommend using extensions here - we can standardize the usage of some specific extension for padding purposes (with all-0 payloads). @jonsneyers can you describe what you would propose to use here?

**Comment by jonsneyers** [comment]
We could define an extension with `ext_id == 0` (so using the least significant bit of the `extensions` bitfield) which has a payload of variable size and all extension payload bits are zero. We can reserve this extension just for padding purposes, though to be sure, payload values different from all-zeroes are reserved (so if needed we might also use this extension for something else at some point, e.g. where the first bit of the payload is 1).

This extension allows modifying the image header in a way that keeps the byte alignment preserved, so e.g. if you need to insert some bits in the header (because Orientation is not signalled yet), you can then add a number of padding bits needed to get the overall header size change to a multiple of 8, meaning from the ICC profile onwards, it's just byte copying and you don't need to know where the ICC profile ends and the first frame starts.

I propose to define this extension for all three places where we allow extensions (ImageMetadata, FrameHeader, and RestorationFilter) since it could potentially be useful in these other places (e.g. to reserve some space for the TOC in a streaming encoder that writes a huge image directly to disk and then at the end of encoding seeks to write the correct TOC). Another application could be to reserve some space in the FrameHeader to allow later changing the crop coordinates of a frame easily, so reversible cropping can be easily implemented (the frame itself remains the same, but the image dimension and frame's x0,y0 offset could be adjusted to modify how much of the frame is shown in a normal viewer which will clip everything to the image canvas).

For byte-alignment alone, a payload size of at most 7 bits would be enough, but for these "reserve some space" purposes larger payload sizes would be useful so I suggest not to put any limit on the payload size of this extension.

**Comment by PetrMinar** [comment]
@jonsneyers Using padding `extension` is a solution that I can easily use and that would save me a lot of work. Could I start safely using it right now in production code or should I wait until it is published in the standard? Is there a possibility that in the end it would not be in the standard (for example someone voted against it)? I do not want to produce invalid files....

One slightly related question regarding `jxlp `and `jxlc` boxes. When the codestream is divided into multiple `jxlp` boxes, is it always on byte boundary? Can the basic header in codestream be splitted into two `jxlp` boxes?

And just for my curiosity, why was the padding before icc profile removed from standard?

Thank you

**Comment by PetrMinar** [comment]
@jonsneyers  While writing prototype code using the extension to align the codestream I found a possible future problem. As you wrote:
 _... so if needed we might also use this extension for something else at some point, e.g. where the first bit of the payload is 1._ 
How should the application "realign" the stream if it sees `extension` with `ext_id == 0` in the original stream and data in that extension are not all zeroes? Should it just append some more zeroes?

This can happen when bits in ImageMetadata bundle are like:
- `all_default` is 0  - this means that `extensions` is in codestream (and possibly extension with `ext_id == 0`)
- `extra_fields` is 0 - this means that `orientation_minus_1` is not in codestream and we need to add it and realign the stream

**Comment by PetrMinar** [comment]
@jonsneyers  The more I think about that... I don't think it is a good idea to use `ext_id == 0 ` extension for anything else than padding with zeroes. And I would even go as far as to limit the bit length of the  `ext_id == 0 ` to min 1 and max 8 bits in the standard. Just so you understand why I am thinking this way:

Extensions are written using one or more U64s that have variable bit length:
Value 0 are written using 2 bits
Values 1-16 are written using 6 bits
Values 17-272 are written using 10 bits
Values 273-max are written using 15-75 bits (exactly 15, 23, 31, 39, 47, 55, 63, 71, 75)

By introducing the padding we have four possible situations:
1. There were no extensions in the codestream. We have to add 10 bits overhead
- 4 bits for `extensions` - original value 0 used 2bits U64 and new value 1 requires 6bits U64
- 6 bits for `extension_bits[0]` - we need to add at most 8 of padding (cannot have zero length extension?) that fits in 6bit U64
(So when we need to align the codestream by1 bit means 10 bits overhead + 7 bits of actual padding, etc)
2. There were extensions in the codestream but there were no extension `ext_id==0`. We have to add 6 bits overhead.
- 0 bits for `extensions` - U64 bit length does not change while setting the least significant bit (`ext_id==0`), right?
- 6 bits for `extension_bits[0]` - we need to add at most 8 of padding (cannot have zero length extension?) that fits in 6bit U64
3. There were extensions in the codestream and there was extension `ext_id==0` containing all zeroes
- 0 bits for `extensions` - the value does not change at all
- 0 bits for `extension_bits[0]` - that is the reason I would like to make valid bit length only 1 to 8. Because it quickly becomes nightmare to solve all the corner cases.
4. There were extensions in the codestream and there was extension `ext_id==0` not containing only zeroes.
- If this is allowed than we cannot use this extension for padding purpose and can forget about it...

What do you think?

**Comment by veluca93** [comment]
I see your point on only allowing zeros (we can always have a separate extension to contain more extensions).

However, I am not sure about which corner cases you are talking about in case 3 - the property of extension 0 is that it has no meaning, so you can use it to pad to whichever size you need to, independently of whatever it was before, no?

**Comment by PetrMinar** [comment]
What I mean is that I would like to prevent `extension_bits[0]` value to be "variable bit length U64". To make things clear:
`extension_bits[0]` contains value - number of bits in pay load. Let's call it `payload_length`.
`extension_bits[0]` is written using variable length U64. Let's call the lenght `u64_length`
In theory `u64_length` can be one of these values 2, 6, 10, 15, 23, 31, 39, 47, 55, 63, 71, 75. So when altering existing padding in codestream I have 11 combinations to handle. These combinations are useless so why even allow them in the first place?

PS: By "altering existing padding" I mean discarding the old padding altogether regardless of its `payload_length` and replacing it with new 1-8 `payload_length`. I do not see any point in preserving anything longer than 8. But the length itself is an information someone might abuse for whatever usage... I've already seen worse things in source code :-)

**Comment by veluca93** [comment]
I'm sorry, but I still don't see the problem - you still need to parse a u64 to correctly read extensions anyway, so I don't see how you add more cases by allowing this flexibility...

It can be useful to allow for more padding in some cases - for example, for a streaming encoder that emits some data in different order and might want to have additional space to fill up later. This would be relevant i.e. for the FrameHeader padding, and I would have some preference for not having two slightly different extensions that serve very similar purposes.

**Comment by jonsneyers** [comment]
OK, I see the point that if we reuse this extension for anything other than padding, then things get complicated. So let's reserve it only for padding, so the contents of this extension is guaranteed to have no semantic implications and applications are free to add or remove it.

I still think it's useful to allow more than 8 bits of padding for cases where the padding is not just used to achieve byte alignment but also to reserve some space for in-place header-only changes.

The U64() that is used to signal `extension_bits[0]` itself uses a variable-length encoding like this:

2 bits: payload length 0
6 bits: payload length 1-16
10 bits: payload length 17-272
15 bits: payload length 0-4095
24 bits: payload length 0-1048575
33 bits: payload length 0-268435455
...
73 bits: payload length 0-(2^64-1)

So you can't do 1 or 3 to 6 total bits of padding (extension length signalling + padding itself), but starting with 7 bits any total size of padding can be achieved:
For 7-22 total padding bits, you use the 6-bit U64() option
For 23-4110 total padding bits, you use the 15-bit U64() option
(just don't use the 10-bit U64() option, it's not needed if you don't care if the bits go to size signaling or to payload)

I don't think there are really a lot of cases to handle, you just figure out how much total padding bits N you want to write and then the logic to write the extension length + padding itself is something like this:

```
assert (N >= 7)
if (N < 23) {
  write(u(2) with value 1)
  write(u(4) with value N-7)
  write(u(N-6) with value 0)
} else if (N < 4110) {
  write(u(2) with value 3)
  write(u(12) with value N-15)
  write(u(1) with value 0)
  write(u(N-15) with value 0)
} else {
  write(N-73 as a 73-bit U64())
  write(u(N-73) with value 0)
}
```

**Comment by PetrMinar** [comment]
Ok, I was overthinking yesterday and I didn't realize that 
- the 2, 6 and 10 bits U64 variants are not enforced and I can freely choose whatever variant of U64 I want.
- the 15+ bits U64 variant has range starting from 0 (unlike 6 and 10 bits variants).
I have overlooked that ant it makes things simpler.

On the other hand it made me discover one more problem in my implementation. When rewriting the codestream I always use the most bit efficient variant of any U32 / U64 value. But the original creator of the stream is not obliged to do so... so even rewriting the codestream without any changes to actual values can lead to bit missalignment before icc profile.

**Comment by PetrMinar** [comment]
I have the padding code working correctly. Is it safe to use it in production code?

Just for my curiosity, why was the padding before icc profile removed from standard? Today I have obtained the most recent version  of published standard from iso.org and it still says that the icc profile should be padded to the byte boundary.

Otherwise I think we can close this topic.

**Comment by jonsneyers** [comment]
The padding before icc profile was a mistake in the first edition of the spec, it was never implemented like that in libjxl.

With hindsight, we should probably have done such padding, and also an indication of the compressed size of the ICC profile (so it can be skipped without decoding it), and also we should have made the Orientation field unconditional so it can always be updated by just changing two bits, but it's too late for all of those things now, so it is what it is. Sorry about that :)
