### ISSUE TITLE
libjxl fails to decode image with SkipProgressive frames

### ISSUE THREAD

**Issue by Traneptora** [libjxl/libjxl#3197]
**Describe the bug**
Consider the following JXL image (gzipped). It is a valid JXL file with multiple tiled frames tagged as SkipProgressive.
[test.jxl.gz](https://github.com/libjxl/libjxl/files/14057410/test.jxl.gz)

**To Reproduce**
Attempt to decode the file with djxl/libjxl. It will fail upon reading the entropy stream for one of the frame's TOCs, most likely because its bitreader is misaligned.

**Expected behavior**
The valid file should decode to pixels correctly.

**Screenshots**
jxlatte decodes the file correctly, without issues. It's supposed to look like this:
![jxlatte](https://github.com/libjxl/libjxl/assets/1342577/cfd8eba3-5ab9-4d30-9e3f-f81c9c797423)

jxl-oxide also decodes the file without complaint, but a bug in its frame blending logic causes all but the last frame to show up black:
![jxl-oxide](https://github.com/libjxl/libjxl/assets/1342577/1a70498e-1972-41fc-a66c-f818aba0ca7a)

djxl produces the following error message:
```
$ djxl test.jxl libjxl.png
JPEG XL decoder v0.10.0 847e11bc [AVX2]
./lib/jxl/fields.cc:246: Skipping 10-bit extension(s)
./lib/jxl/coeff_order.cc:70: JXL_FAILURE: Invalid ANS stream
./lib/jxl/toc.cc:54: JXL_RETURN_IF_ERROR code=1: DecodePermutation( 0, toc_entries, permutation->data(), reader)
./lib/jxl/dec_frame.cc:172: JXL_RETURN_IF_ERROR code=1: ReadToc(toc_entries, br, &sizes, &permutation)
./lib/jxl/decode.cc:1257: invalid frame header
Failed to decode image
DecompressJxlToPackedPixelFile failed
```

Here's the frame layout for the file, in order:
```
Frame Info:
    Encoding: VarDCT
    Type: Skip Progressive
    Size: 2048x112
    Origin: (0, 2048)
    YCbCr: false
Frame Info:
    Encoding: VarDCT
    Type: Skip Progressive
    Size: 1792x112
    Origin: (2048, 2048)
    YCbCr: false
Frame Info:
    Encoding: VarDCT
    Type: Skip Progressive
    Size: 2048x2048
    Origin: (0, 0)
    YCbCr: false
Frame Info:
    Encoding: VarDCT
    Type: Skip Progressive
    Size: 1792x2048
    Origin: (2048, 0)
    YCbCr: false
```

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: gcc version 13.2.1 20230801 (GCC)
 - JPEG XL decoder v0.10.0 847e11bc [AVX2]

**Comment by Traneptora** [comment]
Update: the problem is on line 372 of `frame_header.cc`

```cpp
    if (visitor->Conditional(frame_type == FrameType::kRegularFrame ||
                           frame_type == FrameType::kSkipProgressive)) {
    // ...
    JXL_QUIET_RETURN_IF_ERROR(visitor->Bool(true, &is_last));
  }
  if (frame_type != FrameType::kRegularFrame) {
    is_last = false;
  }
  ```

It reads the `is_last` field but then it immediately overwrites the value, regardless of what is signaled. The incorrect `is_last` value then causes the rest of the frame header to be misaligned as it changes signalling conditions for `save_as_reference`.

**Comment by Traneptora** [comment]
Note that the spec *does* permit `kSkipProgressive` frames to have `is_last = true`.

**Comment by mo271** [comment]
Thanks for reporting this!
