### ISSUE TITLE
cjxl: Lossless jpg transcoding silently ignores -x strip=exif

### ISSUE THREAD

**Issue by pkrause1980** [libjxl/libjxl#3206]
cjxl -x strip=exif Input_With_Exif.jpg out.jxl
silently ignores the -x strip=exif.
Similar cases with strip=xmp, xmp=external_xmp_file.bin, and so on.

**Expected behavior**
1) Do what the user asks for, even if the input cannot be reconstructed.
2) Fail with an error.
3) Print at least a warning.

Bonus: Only warn/error if there is actual metadata to strip.

Thanks!

**Environment**
 - cjxl v0.9

**Comment by mo271** [comment]
A proposed fix is in #3224: It goes for option 2. in your list above with being able to do 1. optionally by passing `allow_jpeg_reconstruction=0`
