### ISSUE TITLE
[Discussion] What is the range for 10-bit BT.2020/BT.2100 encoding?

### ISSUE THREAD

**Issue by aluo-x** [libjxl/libjxl#3207]
I'm putting this down as a discussion since I don't see a discussion board for this repo. Please feel free to close the issue if it is an obvious question or inappropriate for this github. I skimmed over the code but couldn't see anything that jumped out at me. 

I'm curious about the correct bit depth for 10 bit BT.2020/BT.2100 content.
Here is the BT.2020 parameters: [itu url](https://www.itu.int/rec/R-REC-BT.2020-2-201510-I/en)
Here is the BT.2100 parameters: [itu url](https://www.itu.int/rec/R-REC-BT.2100-2-201807-I/en)

1. On the last page of the BT.2020 parameter english PDF, it gives the range for luma to be 64-940 and chroma to be 64-960
2. On page 10 (as written in the PDF) of the BT.2100 parameter english PDF, it allows for both limited and full range encodings to be defined, along with the new ICtCp color space. 
3. As far as I can tell, both the ICtCp color space, and the full range encoding are new in BT.2100 relative to BT.2020.

So my questions are:
1. Is there a way for jxl to distinguish (in the format or encoding) if the limited range or full range encoding is used? I guess if encoding to Rec.2020 it has to be limited range, while in Rec.2100 there should be a flag somewhere?
3. Does the decoder correctly recognize if limited/full range is used? 
4. Is the new ICtCp colorspace supported?

**Comment by Traneptora** [comment]
JPEG XL as an image format only supports full range, full stop. If you pass it limited range, it will interpret as though it were full range. You may need to do the range change yourself, or via a library like libplacebo or libzimg.

JPEG XL only supports pixel data using RGB colorsystems (or raw XYB, in theory). A color system which is not based on tristimulus RGB (such as dolby vision or CIE XYZ, etc.) will need to be converted to RGB before being passed to libjxl.

**Comment by aluo-x** [comment]
Thanks! 

I'll leave this discussion open for 5 more days in case anyone wants to comment, but will close it after that.
