### ISSUE TITLE
JXL box order: Where does metadata belong?

### ISSUE THREAD

**Issue by StefanOltmann** [libjxl/libjxl#3220]
Here's the jxl file structure w/ metadata (Exif and XMP boxes) as exported from darktable:
```
$ exiv2 -pS foo.jxl
Exiv2::BmffImage::boxHandler: JXL         0->12
Exiv2::BmffImage::boxHandler: ftyp       12->20 brand: jxl
Exiv2::BmffImage::boxHandler: jxlc       32->974078
Exiv2::BmffImage::boxHandler: Exif   974110->644
Exiv2::BmffImage::boxHandler: xml    974754->6212
```

_Originally posted by @kmilos in https://github.com/libjxl/libjxl/issues/3193#issuecomment-1914260115_

I want to understand why darktable puts the metadata at the end and not at the beginning like cjxl does.

To read metadata faster and to prevent downloading whole files from a cloud source to parse metadata I have [logic in place](https://github.com/Ashampoo/kim/blob/8b7ddd49ebc18ab283f2f6d89e93c94bcc539cdb/src/commonMain/kotlin/com/ashampoo/kim/format/bmff/BoxReader.kt#L86) to stop after reading metadata.

Was this their decision or is this a default for JXL?
Does the spec say something about that?

@jonsneyers Can you comment on that?

**Comment by kmilos** [comment]
dt doesn't do this explicitly AFAIK... Feel free to check the implementation: https://github.com/darktable-org/darktable/blob/71652d9db414a670d7eccdc23201abdaeff54632/src/imageio/format/jxl.c#L105

**Comment by StefanOltmann** [comment]
They call to add the image frame first. This may decide the order. 🤔

https://github.com/darktable-org/darktable/blob/71652d9db414a670d7eccdc23201abdaeff54632/src/imageio/format/jxl.c#L315

**Comment by kmilos** [comment]
After moving the metadata adding block before the frame, it is indeed written in different order. However, instead of a single `jxlc` box, there are two `jxlp` boxes now, the first one being tiny:
```
Exiv2::BmffImage::boxHandler: JXL         0->12
Exiv2::BmffImage::boxHandler: ftyp       12->20 brand: jxl
Exiv2::BmffImage::boxHandler: jxlp       32->22
Exiv2::BmffImage::boxHandler: Exif       54->24038
Exiv2::BmffImage::boxHandler: xml     24092->6375
Exiv2::BmffImage::boxHandler: jxlp    30467->307099
```

**Comment by StefanOltmann** [comment]
Now it looks exactly like a JPG converted using cjxl. 👍

I hope we can add a word to the spec or docs to make this the recommended default box order.

**Comment by novomesk** [comment]
Some people want to download picture first. So from their point of view it is better to put metadata at the end.

**Comment by veluca93** [comment]
> Some people want to download picture first. So from their point of view it is better to put metadata at the end.

FWIW a few web specs forbid the browsers from (or allow them not to?) reading exif data that arrives after picture data: https://github.com/w3c/csswg-drafts/issues/4929

**Comment by kmilos** [comment]
> FWIW a few web specs forbid the browsers from (or allow them not to?) reading exif data that arrives after picture data

... which is why WebP is considered to be fundamentally broken by some.

**Comment by StefanOltmann** [comment]
> ... which is why WebP is considered to be fundamentally broken by some.

Including me. 😄

The PNG spec makes no statements where the metadata chunk should come, but some browser decided to read only metadata before the first IDAT. So writers changed this behavior. I remember a discussion in the ExifTool forum where Phil ranted about that, because writing metadata at the end was reported as a ExifTool bug even it was legal to do so. Ultimately ExifTool was changed to be compatible with browsers again.

> Some people want to download picture first. So from their point of view it is better to put metadata at the end.

I assume that there may be reasons for that, yes.

If it’s for a website like Instagram they strip the metadata anyway. So it only makes a difference for downloading the original file from OneDrive, Dropbox & co. Even if they show you a preview it does not contain metadata.

I believe if it’s a original file that includes metadata (and you want the whole file anyway) reading the 50 kb metadata (most of the times it’s way less!) first don’t hurt.

**Comment by StefanOltmann** [comment]
@jonsneyers 

To resolve this issue can we add a (strong) recommendation to the spec that metadata should come before the pixel data?

In the best case we would even require that.

For efficient metadata parsing of many files this is essential. Especially for cloud files.

**Comment by StefanOltmann** [comment]
@jonsneyers 

> In some cases metadata can get quite bulky and then putting it at the end seems like a better idea.

Exif data typically remains below 30 kB, and for JPEG, its maximum size is 65 kB. Therefore, it is unlikely to pose a significant burden. Even in the future.

> try using Range Requests

While this is a sound approach in general, its universal support is unfortunately not guaranteed. Additionally, its implementation necessitates more intricate logic.

> another thing you might want to do with cloud-stored images is view them, and then you'd want to get image data asap

Cloud services like OneDrive and Dropbox currently display smaller image previews rather than the original files. I anticipate that, in the future, these services may offer a naked JXL codestream for rapid rendering. The original files, containing metadata in an ISO BMFF format, will be downloaded upon selecting "download original“. I don’t expect this to change.

Given the availability of a JXL naked codestream for swift web rendering, it is advisable to consider a Box layout recommendation for archival purposes (original files).

This approach would prevent complications similar to those encountered with HEIC, where uncertainty about metadata location and support for range requests really hampers cloud compatibility.

For a photo organizer app like Ashampoo Photos, expeditious scanning of extensive file collections is imperative.

So, yes, there are different use cases, but I think the more common use case for the container format will benefit from having metadata coming first.

Please give this topic another thought.

**Comment by jonsneyers** [comment]
Regardless of what the spec says, of course applications that anticipate use cases like the one you describe are free to adopt a convention to put metadata at or near the start of the file. I agree that for large photo originals this makes sense, at least if the metadata is reasonably small.

I have seen "metadata" blobs that are very substantial, such as entire Photoshop edit histories or Illustrator files that are included as "metadata" in a rasterization. So I am not convinced that as a general rule all metadata should be in the beginning. But yes, if it's just a few dozen kilobytes in a multi-megabyte image file, putting it in the beginning makes sense.

But what makes sense depends on use cases and their requirements, and I think it is best to leave room to applications to decide what makes the most sense for them. For darktable I think it does make sense to put the metadata in the beginning, so they should probably change their encoding order. But for web delivery of images (where metadata is sometimes not stripped because some copyright/provenance info may need to be preserved), metadata at the end can make sense too.

Note also that jxl boxes can be reordered (within some constraints, e.g. jxlp boxes need to remain in the same relative order, and the header boxes should stay in the front), so I could e.g. imagine a service that moves Exif boxes to the front on ingress, to ensure they can be retrieved easily later on.

**Comment by StefanOltmann** [comment]
I am optimistic that, in the end, most apps will indeed adopt this convention.

I understand your decision not to incorporate it into the specification.

It's advantageous that JPEG files converted with cjxl currently prioritize placing metadata at the beginning, and I hope this practice continues. I assume that the majority of JXL files during the initial adoption years will be converted from JPG.

Darktable used to position its metadata at the end, but this has been fixed now for future versions.

If, at the very least, all major applications prioritize writing metadata first, it may not be a big issue in the end.

Seeing my questions answered I will now close this issue.
