### ISSUE TITLE
Failed converting huge PNG

### ISSUE THREAD

**Issue by clairem-sl** [libjxl/libjxl#3223]
**=== Update ===**
I just realized that I used the wrong flag, `-d` instead of `-q`, but even using the right `-q` flag -- plus trying out `-e 3` -- the conversion still fails. Check the comments following this issue, [specifically this one](https://github.com/libjxl/libjxl/issues/3223#issuecomment-1916752239), for the details.

-----

_Original issue follows:_

-----

**Describe the bug**
I tried converting a huge PNG file (19_968 x 24_576 pixels, with transparency, size on disk is 328 MiB), but `cjxl` keeps failing with error `Setting frame distance failed.`

**To Reproduce**

1. Grab this file: [Bellisseria_ALL.composited.png](https://drive.google.com/file/d/1lO0WQCS6nIFqHsys9zP5vkoNH_f-LJRc/view?usp=sharing) (WARNING! HUGE!)
2. Use one of these pre-built `cjxl` binaries:
   * [Jeremy Lee's](https://jeremylee.sh/bins/)
   * [7700291642 artefact](https://github.com/libjxl/libjxl/actions/runs/7700291642/job/20984507647)
3. Convert using the following:

> ```
> cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -d 80
> ```

**Expected behavior**

I expect it to just work.

**Screenshots**

Using `cjxl` from Jeremy Lee:

```
PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> C:\Progs\jpegxl\cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -d 80
JPEG XL encoder v0.9.0 eaf12cc1 [AVX2,SSE4,SSE2]
Encoding [VarDCT, d80.000, effort: 7]
Setting frame distance failed.
EncodeImageJXL() failed.
```

Using `cjxl` from [latest artefact](https://github.com/libjxl/libjxl/actions/runs/7700291642/job/20984507647):

```
PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> C:\Progs\jpegxl\cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -d 80
JPEG XL encoder v0.10.0 07203da [AVX2,SSE4,SSSE3,SSE2]
Encoding [VarDCT, d80.000, effort: 7]
Setting frame distance failed.
EncodeImageJXL() failed.
```

**Environment**
 - OS: Windows 10 Pro
 - Compiler version: N/A (I'm using prebuilt binaries)
 - CPU type: x86_64 (AMD Ryzen 3700U)
 - RAM available: 7GB
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]]
   - `v0.9.0 eaf12cc1 [AVX2,SSE4,SSE2]`
   - `v0.10.0 07203da [AVX2,SSE4,SSSE3,SSE2]`

**Additional context**

I created the huge PNG image myself, and it is released under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/). So feel free if you want to use it as a test case.

**Comment by mo271** [comment]
Using the very recent streaming mode it is possible to convert this image, when it is converted to ppm beforehand:
```bash
> convert Bellisseria_ALL.composited.png Bellisseria_ALL.composited.ppm
> cjxl --streaming_input --streaming_output Bellisseria_ALL.composited.ppm Bellisseria_ALL.composited.jxl
JPEG XL encoder v0.10.0 07203da0 [AVX2,SSE4,SSE2]
Encoding [VarDCT, d1.000, effort: 7]
Compressed to 40072.2 kB (0.653 bpp).
19968 x 24576, 14.821 MP/s [14.82, 14.82], 1 reps, 96 threads.
> ls -sh Bel*
 39M Bellisseria_ALL.composited.jxl  328M Bellisseria_ALL.composited.png  1.4G Bellisseria_ALL.composited.ppm
```
First the `convert` command was giving an `cache resources exhausted` error, which I fixed by editing `/etc/ImageMagick-6/policy.xml` multiplying all relevant limits by 10.

**Comment by clairem-sl** [comment]
@mo271 Ah thanks for the tip!

btw I only realized that I made a mistake of using `-d` instead of `-q` when what I wanted was `-q`.

Using `-q` still resulted in a crash, though.

With Jeremy Lee's binary:

```
PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> C:\Progs\jpegxl\cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -q 80

JPEG XL encoder v0.9.0 eaf12cc1 [AVX2,SSE4,SSE2]
Encoding [VarDCT, d1.900, effort: 7]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> C:\Progs\jpegxl\cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -q 80 -e 3

JPEG XL encoder v0.9.0 eaf12cc1 [AVX2,SSE4,SSE2]
Encoding [VarDCT, d1.900, effort: 3]
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

With latest artefact, it just crashed silently, not producing any output:

```
PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> C:\Progs\jpegxl\cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -q 80

JPEG XL encoder v0.10.0 07203da [AVX2,SSE4,SSSE3,SSE2]
Encoding [VarDCT, d1.900, effort: 7]

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> dir *.jxl

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> dir

	Directory: C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024-01-21    16:09         140763 2024-01-21_160417.jpg
-a---          2024-01-21    16:09         276538 2024-01-21_160513.jpg
-a---          2024-01-21    16:10         186626 2024-01-21_160830.jpg
-a---          2024-01-21    20:53         398926 2024-01-21_205230.jpg
-a---          2024-01-21    20:58         496377 2024-01-21_205742.jpg
-a---          2024-01-21    21:02         269871 2024-01-21_210210.jpg
-a---          2024-01-23    01:17         124721 2024-01-23_011716.jpg
-a---          2024-01-28    22:23          76668 2024-01-28_222204.jpg
-a---          2024-01-28    22:40         108382 2024-01-28_224038.jpg
-a---          2024-01-28    23:24          42299 2024-01-28_232453.jpg
-a---          2024-01-29    00:06          70906 2024-01-29_000602.jpg
-a---          2024-01-29    01:09         103136 2024-01-29_010933.jpg
-a---          2024-01-21    12:28       17457231 Bellisseria_ALL.annotated.transp.kra
-a---          2024-01-21    12:29        7144268 Bellisseria_ALL.annotated.transp.png
-a---          2024-01-21    01:08      298521056 Bellisseria_ALL.composited.HIDE.png
-a---          2024-01-30    12:45      343910090 Bellisseria_ALL.composited.png
-a---          2024-01-21    22:15        5134434 Bellisseria_ALL.lattice-overlay.png
-a---          2024-01-21    22:14      337242150 Bellisseria_ALL.png
-a---          2024-01-21    22:15          64737 Bellisseria_ALL.regions.txt

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL>

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> C:\Progs\jpegxl\cjxl.exe .\Bellisseria_ALL.composited.png .\Bellisseria_ALL.composited.jxl -q 80 -e 3

JPEG XL encoder v0.10.0 07203da [AVX2,SSE4,SSSE3,SSE2]
Encoding [VarDCT, d1.900, effort: 3]

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> dir *.jxl

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> dir

	Directory: C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024-01-21    16:09         140763 2024-01-21_160417.jpg
-a---          2024-01-21    16:09         276538 2024-01-21_160513.jpg
-a---          2024-01-21    16:10         186626 2024-01-21_160830.jpg
-a---          2024-01-21    20:53         398926 2024-01-21_205230.jpg
-a---          2024-01-21    20:58         496377 2024-01-21_205742.jpg
-a---          2024-01-21    21:02         269871 2024-01-21_210210.jpg
-a---          2024-01-23    01:17         124721 2024-01-23_011716.jpg
-a---          2024-01-28    22:23          76668 2024-01-28_222204.jpg
-a---          2024-01-28    22:40         108382 2024-01-28_224038.jpg
-a---          2024-01-28    23:24          42299 2024-01-28_232453.jpg
-a---          2024-01-29    00:06          70906 2024-01-29_000602.jpg
-a---          2024-01-29    01:09         103136 2024-01-29_010933.jpg
-a---          2024-01-21    12:28       17457231 Bellisseria_ALL.annotated.transp.kra
-a---          2024-01-21    12:29        7144268 Bellisseria_ALL.annotated.transp.png
-a---          2024-01-21    01:08      298521056 Bellisseria_ALL.composited.HIDE.png
-a---          2024-01-30    12:45      343910090 Bellisseria_ALL.composited.png
-a---          2024-01-21    22:15        5134434 Bellisseria_ALL.lattice-overlay.png
-a---          2024-01-21    22:14      337242150 Bellisseria_ALL.png
-a---          2024-01-21    22:15          64737 Bellisseria_ALL.regions.txt

PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL>
```

I'm gonna try your suggestion after this.

**Comment by clairem-sl** [comment]
> ```shell
> > convert Bellisseria_ALL.composited.png Bellisseria_ALL.composited.ppm
> > cjxl --streaming_input --streaming_output Bellisseria_ALL.composited.ppm Bellisseria_ALL.composited.jxl
> JPEG XL encoder v0.10.0 07203da0 [AVX2,SSE4,SSE2]
> ```

I tried your suggestion, but I encountered a different error:

```
PS > convert Bellisseria_ALL.composited.png Bellisseria_ALL.composited.ppm

PS > C:\Progs\jpegxl\cjxl --streaming_input --streaming_output Bellisseria_ALL.composited.ppm Bellisseria_ALL.composited.jxl

JPEG XL encoder v0.10.0 07203da [AVX2,SSE4,SSSE3,SSE2]
PNM decoding failed.
PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> dir *.ppm

    Directory: C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024-01-30    19:37     1472200749 Bellisseria_ALL.composited.ppm
```

**Comment by mo271** [comment]
Since this is working on my machine and not on yours, it might be useful to have more info an what machine your are running this, like OS, CPU type, how much RAM you have etc. 
Also perhaps a debug build would give more useful error messages here?!
Can you see if it works with a smaller ppm file?
btw for me the ppm output by `convert` is 1472200723 and it begins like this:
```bash
> hexdump -C Bellisseria_ALL.composited.ppm | head
00000000  50 36 0a 31 39 39 36 38  20 32 34 35 37 36 0a 32  |P6.19968 24576.2|
00000010  35 35 0a 00 00 00 00 00  00 00 00 00 00 00 00 00  |55..............|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000310  00 00 00 aa ac ab aa ac  ab aa ac ab aa ac ab aa  |................|
00000320  ac ab aa ac ab aa ac ab  aa ac ab aa ac ab aa ac  |................|
00000330  ab aa ac ab aa ac ab aa  ac ab aa ac ab aa ac ab  |................|
00000340  aa ac ab aa ac ab aa ac  ab aa ac ab aa ac ab aa  |................|
00000350  ac ab aa ac ab aa ac ab  aa ac ab aa ac ab aa ac  |................|
00000360  ab aa ac ab aa ac ab aa  ac ab aa ac ab aa ac ab  |................|
```
Yours seem to be of length 1472200749, so very slightly different, perhaps this is already the reason why it doesn't work for you?!

**Comment by veluca93** [comment]
> > ```shell
> > > convert Bellisseria_ALL.composited.png Bellisseria_ALL.composited.ppm
> > > cjxl --streaming_input --streaming_output Bellisseria_ALL.composited.ppm Bellisseria_ALL.composited.jxl
> > JPEG XL encoder v0.10.0 07203da0 [AVX2,SSE4,SSE2]
> > ```
> 
> I tried your suggestion, but I encountered a different error:
> 
> ```
> PS > convert Bellisseria_ALL.composited.png Bellisseria_ALL.composited.ppm
> 
> PS > C:\Progs\jpegxl\cjxl --streaming_input --streaming_output Bellisseria_ALL.composited.ppm Bellisseria_ALL.composited.jxl
> 
> JPEG XL encoder v0.10.0 07203da [AVX2,SSE4,SSSE3,SSE2]
> PNM decoding failed.
> 
> PS C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL> dir *.ppm
> 
>     Directory: C:\Cache\SL-Carto\AreaMaps\Bellisseria_ALL
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a---          2024-01-30    19:37     1472200749 Bellisseria_ALL.composited.ppm
> ```
> 
> Didn't encounter `cache resources exhausted`, but `cjxl` just bailed out with `PNM decoding failed`.

Should be fixed now!
