### ISSUE TITLE
Question about jxlp boxes in the jxl file

### ISSUE THREAD

**Issue by PetrMinar** [libjxl/libjxl#3237]
Hello,

The standard (9.10 JPEG XL partial codestream box) says the the full codestream is produced by concatenation of all partial codestream. Does it mean, that the codestream can be split safely only on byte boundaries? If not, how should the bit paddings handles?

As an example there is written in the standard:
_Splitting the codestream into multiple parts allows placing the first part of the codestream (e.g. the header and preview) early in the file, followed by possible metadata boxes, followed by the main part of the codestream._
But the header does not need to end on byte boundary (as I have encountered in https://github.com/libjxl/libjxl/issues/3195). 

And also is there some sort of guarantee that the whole header will in the first jxlp box? Probably not, right?

Thank you for clarification

**Comment by jonsneyers** [comment]
The spec is not explicit about it (we should probably fix that), but `jxlp` boxes are supposed to be byte-aligned, so the codestream can only be split on byte boundaries, and there is no bit padding to consider.

The "header" in the sense of "anything before the first frame header" does end on a byte boundary. IIRC this is how libjxl does it.

There is no guarantee that the whole header will be in the first jxlp box.

**Comment by PetrMinar** [comment]
Thank you for the clarification.
