### ISSUE TITLE
build error : cannot convert 'const bool' to 'boolean' for two_pass_quantize

### ISSUE THREAD

**Issue by ssinno** [libjxl/libjxl#3245]
Build fails roughly halfway through with the following error, using GCC13.   This happens with both release libjxl-0.9.1 and master git version

cmake  -DJXL_HWY_DISABLED_TARGETS_FORCED=OFF -DCXX_FUZZERS_SUPPORTED=NO -DJPEGXL_ENABLE_FUZZERS=NO ..
make
......
Consolidate compiler generated dependencies of target jxl_extras_core-obj
[ 43%] Building CXX object lib/CMakeFiles/jxl_extras_core-obj.dir/extras/dec/jpg.cc.o
/discover/nobackup/ssinno/dl/cespit-1.2/src/libjxl-0.9.1/lib/extras/dec/jpg.cc: In lambda function:
/discover/nobackup/ssinno/dl/cespit-1.2/src/libjxl-0.9.1/lib/extras/dec/jpg.cc:281:42: error: cannot convert ‘const bool’ to ‘boolean’ in assignment
  281 |       cinfo.two_pass_quantize = dparams->two_pass_quant;
      |                                 ~~~~~~~~~^~~~~~~~~~~~~~
      |                                          |
      |                                          const bool
make[2]: *** [lib/CMakeFiles/jxl_extras_core-obj.dir/build.make:244: lib/CMakeFiles/jxl_extras_core-obj.dir/extras/dec/jpg.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1866: lib/CMakeFiles/jxl_extras_core-obj.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
(cespit-1.7b) [ssinno@discover22 build]gcc --version
gcc (GCC) 13.1.0

**Comment by mo271** [comment]
Thanks for the report! Is this the only place where the error `cannot convert ‘const bool’ to ‘boolean’ in assignment` appears in your setup?

**Comment by ssinno** [comment]
And thank you for the inquiry!  That is the only place, though I'm only making it about 50% through the build process, possible another lies deeper in the build.  Note that I've hit this error on both CentOS-7 and SLES12-SP3 systems, as detailed below.  

[ssinno@discover22 ~]cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

[ssinno@login1 generic]cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by mo271** [comment]
let's see if this fixes it or if more explicit casts are needed

**Comment by ssinno** [comment]
Looks like just one more, build 100% completed  & installed by adding this cast   

lib/extras/enc/jpg.cc:295:  cinfo.optimize_coding = (boolean)params.optimize_coding;
