### ISSUE TITLE
Progressive Decode

### ISSUE THREAD

**Issue by yongjianbao** [libjxl/libjxl#329]
I'm trying to apply progressive encoding and decoding features. There seems no command line option for djxl to instruct it which quality level it stops to decode an image. I have to truncate the jxl code stream and simply apply djxl. It works to some degree, but djxl uses all information in the truncated compression code stream and resultant image looks with different quality details in the top area (where I guess more information available in the truncated code stream) and in the bottom area. Is there option for djxl to stop when further information is not available for the entire image?

**Comment by jonsneyers** [comment]
There's the option `djxl -s {2, 4, 8}` that you can use to stop when enough data has been decoded for an effective 1:2, 1:4 or 1:8 image. It's a bit limited since in principle you can have more progressive passes than that, but it may be good enough.

**Comment by yongjianbao** [comment]
-s option is down sampling , similar to resolution based progression like JPEG 2000. What I tried is to expand the image with the original, full resolution but use only received data covering the entire image. As i understand, the code stream in jxl is arranged DC first, and then increased precision AC data follows. Can decoder do this? If djxl does not, does library API support to expand images of full resolution with, say, only 5% of the code stream . With options --allow_partial_files and --allow_more_progressive_steps, djxl seems like do this, but it seems like apply all data available, the resultant distance (pixelwise) of the expand and the original is uneven across the entire image: smaller distance in the first portion and then increased distance. I asked if there is a way to ask decoder to stop at a point of the available data, if not the entire image is covered.

**Comment by deymo** [comment]
The API has a `JxlDecoderFlushImage()` function that would try to render as much as possible with the input buffer provided so far, so you can do that. The output is the full resolution image.

There's probably a bug that hits an assert if the chunk is too small (#245) but after the DC is parsed it should be ok.

**Comment by jonsneyers** [comment]
I think this one can be closed now, feel free to reopen if there are any further questions.
