### ISSUE TITLE
Encoding does not work with the `--resampling' option and speed/effort higher than 7

### ISSUE THREAD

**Issue by ScopeBurst** [libjxl/libjxl#330]
Encoding does not work with the `--resampling' option and speed/effort higher than 7

`-s 8 -q 30 --resampling=2`

```
JPEG XL encoder v0.3.7 [AVX2]
Read 1473x820 image, 47.2 MP/s
Encoding [VarDCT, d6.400, kitten], 8 threads.
../lib/jxl/image_bundle.cc:62: JXL_CHECK: ec.xsize() == xs
```

Sometimes without error messages

**Comment by mo271** [comment]
We should ideally fix that or at least forbid that combination as a temporary fix.

**Comment by Fraetor** [comment]
It appears that larger (with respect to dimentions) images are not effected by this issue. I have attached two test images for which one encodes fine, and the other does not. I used `cjxl -e 9 -d 25`

[test_images.zip](https://github.com/libjxl/libjxl/files/8695433/test_images.zip)

**Comment by szabadka** [comment]
I verified that with the latest changes -e9 --resampling 2 and -e9 -d25 works.
