### ISSUE TITLE
Streaming input PPM decoding fails on Windows

### ISSUE THREAD

**Issue by jonnyawsom3** [libjxl/libjxl#3303]
**Describe the bug**
Trying to use a PPM input file  with --streaming_input results in "PNM decoding failed."
```
cjxl.exe Doggo.ppm Doggo.jxl -d 0 --streaming_input --streaming_output
JPEG XL encoder v0.10.0 a070f82 [AVX2,SSE2]
PNM decoding failed.
```

**To Reproduce**
cjxl.exe Doggo.ppm Doggo.jxl -d 0 --streaming_input --streaming_output

**Expected behavior**
The file should be readable

**Environment**
 - OS: Windows 10
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.10.0 a070f82 [AVX2,SSE2]
 
 Source file
![Doggo](https://github.com/libjxl/libjxl/assets/51539240/c71389e2-fb84-419a-a3a8-e0555e275894)
PPM file made with ffmpeg (With .png appended for upload)
![Doggo ppm](https://github.com/libjxl/libjxl/assets/51539240/6b71d3a7-9155-421f-bd21-d2fbff7d58ff)

**Comment by mo271** [comment]
Thanks! I can't repro this on my linux box. Seems like this is possibly a duplicate of #3223.

**Comment by jonnyawsom3** [comment]
I made this as a separate issue since PPM failing wasn't the original problem there (Even if it would fix both)

**Comment by veluca93** [comment]
Should be fixed now!

**Comment by jonnyawsom3** [comment]
Can confirm it's working now
