### ISSUE TITLE
v0.9.2 static Linux binary is broken

### ISSUE THREAD

**Issue by kuro68k** [libjxl/libjxl#3309]
**Describe the bug**
I downloaded [jxl-linux-x86_64-static-v0.9.2.tar.gz](https://github.com/libjxl/libjxl/releases/download/v0.9.2/jxl-linux-x86_64-static-v0.9.2.tar.gz). When I run cjxl, I get 

```
cjxl: error while loading shared libraries: libjxl_extras_codec.so.0.9: cannot open shared object file: No such file or directory
```

**To Reproduce**
Download on a system without that library pre-installed, and try to use cjxl to convert a JPEG to JXL losslessly. It may be possible to produce it other ways, that's the only one I tried.

**Expected behavior**
Statically linked binary is self contained.

**Environment**
 - OS: Ubuntu 24 via WSL
 - cjxl/djxl version string: `JPEG XL encoder v0.9.2 41b8cda [AVX2,SSE4,SSE2]`

**Comment by mo271** [comment]
Thanks for the report!
We tried to repro this and couldn't. Are you sure you are the `./tools/cjxl` from that tar file?
