### ISSUE TITLE
cap `-E`/`--modular_nb_prev_channels` to the number of channels of the image

### ISSUE THREAD

**Issue by TheHardew** [libjxl/libjxl#3324]
**Describe the bug**
`-E` increases the encoding time if the value of the argument is larger than the number of channels in the image.
As far as I understand, `-E` describes how many channels in the image will be looked at at a time in the input image.
It does not make sens for it to do more work when `-E` exceeds the number of input channels of the image.  

The outputs produced with different `-E` options are identical.

**To Reproduce**
```
time cjxl img.png -e 9 -d 0 --patches 1 --disable_output
JPEG XL encoder v0.10.0 bf2b7655 [AVX2]
Encoding [Modular, lossless, effort: 9]
Compressed to 2340.7 kB (2.774 bpp).
3000 x 2250, 0.106 MP/s [0.11, 0.11], 1 reps, 16 threads.
66.56user 0.89system 1:03.93elapsed 105%CPU (0avgtext+0avgdata 587916maxresident)k
0inputs+0outputs (0major+67501minor)pagefaults 0swaps

time cjxl img.png -e 9 -d 0 -E 3 --patches 1 --disable_output
JPEG XL encoder v0.10.0 bf2b7655 [AVX2]
Encoding [Modular, lossless, effort: 9]
Compressed to 2340.7 kB (2.774 bpp).
3000 x 2250, 0.076 MP/s [0.08, 0.08], 1 reps, 16 threads.
91.80user 1.07system 1:29.41elapsed 103%CPU (0avgtext+0avgdata 607396maxresident)k
0inputs+0outputs (0major+74815minor)pagefaults 0swaps

time cjxl img.png -e 9 -d 0 -E 11 --patches 1 --disable_output
JPEG XL encoder v0.10.0 bf2b7655 [AVX2]
Encoding [Modular, lossless, effort: 9]
Compressed to 2340.7 kB (2.774 bpp).
3000 x 2250, 0.040 MP/s [0.04, 0.04], 1 reps, 16 threads.
172.36user 0.86system 2:49.79elapsed 102%CPU (0avgtext+0avgdata 781596maxresident)k
0inputs+0outputs (0major+98965minor)pagefaults 0swaps
```
**Expected behavior**
`-E` should be capped to the number of channels in the input image so that it takes the same amount of time if it's larger

**Screenshots**
grayscale image, 1 channel: 
![img](https://github.com/libjxl/libjxl/assets/7374061/868f41fb-7539-47f6-9612-2d04cfdb12af)

**Environment**
 - OS: Arch Linux
 - Compiler version: clang version 16.0.6
 - CPU type: x86_64 Ryzen 2700x
 - cjxl/djxl version string: cjxl v0.10.0 bf2b7655 [AVX2]

**Comment by TheHardew** [comment]
Jon said on discord that it "Makes sense to cap it to the number of prev channels that actually exist"
I guess the MA trees are computed for each channel?

**Comment by TheHardew** [comment]
I built c82bdfb.
It's better but I think still not perfect?

Both the encoded image and the source image have 1 color channel:
```
jxlinfo -v img.jxl
JPEG XL image, 3000x2250, (possibly) lossless, 8-bit Grayscale
num_color_channels: 1
num_extra_channels: 0
have_preview: 0
have_animation: 0
Intrinsic dimensions: 3000x2250
Orientation: 1 (Normal)
Color space: Grayscale, D65, sRGB transfer function, rendering intent: Relative
```

Times:

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `cjxl -e 5 -d 0 --patches 1` | 1.630 ± 0.035 | 1.603 | 1.720 | 1.00 |
| `cjxl -e 5 -d 0 -E 1 --patches 1` | 1.759 ± 0.020 | 1.725 | 1.785 | 1.08 ± 0.03 |
| `cjxl -e 5 -d 0 -E 2 --patches 1` | 1.838 ± 0.016 | 1.807 | 1.862 | 1.13 ± 0.03 |
| `cjxl -e 5 -d 0 -E 3 --patches 1` | 1.850 ± 0.017 | 1.821 | 1.869 | 1.14 ± 0.03 |
| `cjxl -e 5 -d 0 -E 4 --patches 1` | 1.851 ± 0.025 | 1.805 | 1.879 | 1.14 ± 0.03 |
| `cjxl -e 5 -d 0 -E 11 --patches 1` | 1.868 ± 0.023 | 1.836 | 1.909 | 1.15 ± 0.03 |

**Comment by veluca93** [comment]
Yes, gray-scale images would still have some unnecessary work here, but I'm
not sure the difference is *that* relevant...

**Comment by TheHardew** [comment]
On another image, 3000x4500 `-e10`, it's a difference between 90 s and 140 s. I understand if it's a wontfix, however.
