### ISSUE TITLE
Windows file zip clarification.

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [libjxl/libjxl#3327]
**Is your feature request related to a problem? Please describe.**
On the release page, for Windows, there is 2 zip file options which is Windows-static and another one with the Static. I'm confused which one should I download and why there is 2 options for Windows?

This is not about x64 or x86.

**Describe the solution you'd like**
An explanation the difference between windows-static and non windows-static zip file. 

**Describe alternatives you've considered**
1 zip file for Windows which is either static only or non static. 

**Additional context**
![Screenshot_2024-02-25-18-07-06-854_com.github.android-edit.jpg](https://github.com/libjxl/libjxl/assets/27284123/122c4d33-4339-4ef2-af11-7b47219ae00d)

**Comment by jonnyawsom3** [comment]
Static has larger size, but everything inside will work on its own. The other is smaller, but requires all the files to be in the same folder

**Comment by Ahmad-Amsyar** [comment]
> Static has larger size, but everything inside will work on its own. The other is smaller, but requires all the files to be in the same folder 

Understandable. Thank you for explaining the difference.
