### ISSUE TITLE
Can cjxl read JXL files?

### ISSUE THREAD

**Issue by Yay295** [libjxl/libjxl#3349]
The readme file doesn't list `.jxl` as a file type that can be read.

https://github.com/libjxl/libjxl/blob/cae805d8b68f973fcac3b4235029b82366f02a8b/README.md?plain=1#L76-L77

Just wondering if `cjxl` can recompress a JXL image.

**Comment by TheHardew** [comment]
Yes.
Run cjxl without any arguments. It will tell you what file types it supports.

At least 0.9.2 does support it, I'm not sure when it was added.

**Comment by Traneptora** [comment]
cjxl can read JXL files. The `--help` states the following: `the input can be PNG, APNG, GIF, JPEG, EXR, PPM, PFM, PAM, PGX, or JXL`
