### ISSUE TITLE
Clarification on "Speed" parameters.

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [libjxl/libjxl#3354]
**Is your feature request related to a problem? Please describe.**
I'm confused about the difference between "Effort" parameters and "Speed" parameters. 

**Describe the solution you'd like**
- Explanation what the value for the parameter mean.
- What the parameter do?
- What is the difference between using "Effort" parameters and "Speed" Parameters?

**Comment by jonnyawsom3** [comment]
Speed was the old term before effort, but the system was changed so that higher effort took longer, rather than higher speed taking longer

**Comment by Ahmad-Amsyar** [comment]
> Speed was the old term before effort, but the system was changed so that higher effort took longer, rather than higher speed taking longer 

I assume that means speed is working like effort parameters but its a legacy option?

**Comment by jonnyawsom3** [comment]
Yes, as far as I'm aware

**Comment by Ahmad-Amsyar** [comment]
Got it, thank you for explaining it to me.
