### ISSUE TITLE
jpegli XYB encode fails on grayscale image

### ISSUE THREAD

**Issue by Firepal** [libjxl/libjxl#3355]
**Describe the bug**
cjpegli prints `jpegli encoding failed` and quits when trying to encode a particular file.
This file is a PNG with grayscale colors.

**To Reproduce**
Encode the following image with `--xyb` option:
![cover](https://github.com/libjxl/libjxl/assets/29317321/cdf2a180-f807-4f07-aa27-e0449943d401)

**Expected behavior**
The image is encoded and `cjpegli` does not halt with an error message.

**Screenshots**
```
PS C:\Users\Firepal\Pictures> cjpegli -d 1 --xyb c.png c.jpg
Read 150x150 image, 5853 bytes.
Encoding [XYB d1.000 AQ p2 OPT]
jpegli encoding failed
```

**Environment**
 - OS: Windows 10
 - Compiler version: (0.10.1 build downloaded from Github)
 - CPU type: x64

**Comment by Firepal** [comment]
The plot thickens.

Applying a `magick mogrify PNG24:c.png` to transform the grayscale PNG to a color PNG allows cjpegli to ingest the image.

Color PNG: 
![c](https://github.com/libjxl/libjxl/assets/29317321/f1a9f460-b6cc-43cd-9c23-ba9c4ad9c354)

The associated result from cjpegli of using this converted PNG:
```
PS C:\Users\Firepal\Pictures> cjpegli -d 1 --xyb .\c.png c.jpg
Read 150x150 image, 11972 bytes.
Encoding [XYB d1.000 AQ p2 OPT]
Compressed to 4403 bytes (1.566 bpp).
150 x 150, 14.474 MP/s [14.47, 14.47], 1 reps, 1 threads.
```
And it outputs the XYB JPEG :)
![c](https://github.com/libjxl/libjxl/assets/29317321/27436b7f-9ad7-493a-801f-20b9eb2af59d)

**Comment by Firepal** [comment]
This is mostly a curiosity at best. JPEG has a grayscale mode

**Comment by Traneptora** [comment]
`--xyb` does not work at the moment for anything that isn't RGB. This includes RGBA. See Also: #2671

Not necessarily the same bug, but possibly related.

**Comment by Firepal** [comment]
I assume the referenced commit has fixed this problem.
