### ISSUE TITLE
Lossless encode/decode is not lossless

### ISSUE THREAD

**Issue by palemieux** [libjxl/libjxl#3357]
**Describe the bug**
Lossless encode/decode of [qoi_benchmark_suite/images/textures_pk/pkw_wall02bf.png](https://qoiformat.org/benchmark/) is not lossless

**To Reproduce**
See encoder/decoder code at https://github.com/sandflow/libench/blob/ff5ec6959ee27b24a5185cc78c972ccc52f07a16/src/main/cpp/jxl_codec.cpp

**Expected behavior**
Lossless encode/decode should be lossless.

**Environment**
 - OS: Ubuntu 20
 - Compiler version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
 - CPU type: x86_64
 - cjxl/djxl version string: [libjxl @ 5f67ebc](https://github.com/libjxl/libjxl/tree/5f67ebced96df5c0696ec7d1822bdd3e4e11a1a1)

**Comment by Traneptora** [comment]
It is actually lossless. The problem here is that the original PNG uses a PLTE palette, so comparing it to the round-trip, which produces RGB24, won't produce identical IDAT pixel buffers.

If you compare the round-trip to what you would get if you coerce the original into rgb24, it does line up.

```
$ ffmpeg -v quiet -i pkw_wall02bf.png -c rawvideo -f hash -
SHA256=7e1ccff73a5cac9f6b6e4f91917f5c4d73a35d66ceb4806a948711e16bf71622
$ cjxl -d 0 pkw_wall02bf.png test.jxl
JPEG XL encoder v0.10.0 6d041617 [AVX2]
Encoding [Modular, lossless, effort: 7]
Compressed to 63894 bytes (7.800 bpp).
256 x 256, 0.879 MP/s [0.88, 0.88], 1 reps, 8 threads.
$ djxl test.jxl test.png
JPEG XL decoder v0.10.0 6d041617 [AVX2]
Decoded to pixels.
256 x 256, 6.966 MP/s [6.97, 6.97], 1 reps, 8 threads.
$ ffmpeg -v quiet -i test.png -c rawvideo -f hash -
SHA256=149acdc1db062826218e75bb98c84e7ab06a90d21cf68dece1f720176bbe873d
$ ffmpeg -v quiet -i pkw_wall02bf.png -pix_fmt rgb24 -c rawvideo -f hash -
SHA256=149acdc1db062826218e75bb98c84e7ab06a90d21cf68dece1f720176bbe873d
```

**Comment by palemieux** [comment]
Ok it used to work with the JXL accelerated lossless encoder circa 2022.

**Comment by Traneptora** [comment]
I'm not sure, but I can say that if you decode the original PNG you'll get a PNG that uses 8-bit indexed color, so comparing the pixel arrays directly will not work. You'll have to convert the original to standard 24-bit RGB. If you do that, the pixel arrays will agree with each other.

**Comment by palemieux** [comment]
> You'll have to convert the original to standard 24-bit RGB

This is what the code does.

> If you do that, the pixel arrays will agree with each other.

They do not for this specific image, but do for others.

Did you use Effort 1, which uses the fast path?

**Comment by Traneptora** [comment]
I tested this with default effort, which is 7. If I use `-e 1` I do indeed get different pixel data. Very notably different pixel data. It does indeed trigger only on fast lossless though.
![pkw_wall02bf](https://github.com/libjxl/libjxl/assets/1342577/0164b1f7-549e-4ea9-9762-f0d93a5d0f05)
![test](https://github.com/libjxl/libjxl/assets/1342577/5817f4a8-fab3-4910-89bd-c0d4f13d1eb2)

**Comment by jonsneyers** [comment]
Thanks for finding this, @palemieux !
Bug is fixed.
