### ISSUE TITLE
JXL file generated by the latest v0.10..1 cannot be opened by Image Viewer in GNOME 42.5 on Ubuntu-based PopOS 22.04

### ISSUE THREAD

**Issue by g4x86** [libjxl/libjxl#3358]
**Describe the bug**
Just what the title described, the JXL file generated by the latest v0.10..1 cannot be opened by Image Viewer (eog) in GNOME 42.5 on Ubuntu-based PopOS 22.04. All five DEB packages contained in the downloaded tar.gz were installed correctly. Actually, all those JXL files generated by v0.9.x that used to work with Image Viewer now just stop working (interestingly, GIMP can still open the file). So I guess there's probably something wrong with libjxl-gdk-pixbuf.

**To Reproduce**
Just download the official tar.gz file for Ubuntu 22.04 from GitHub

**Expected behavior**
Image Viewer (eog) in GNOME should be able to open and view JXL file correctly, as all previous versions of libjxl do.

**Screenshots**

**Environment**
 - OS: Pop_OS (Ubuntu-based) 22.04
 - CPU type: x86_64
 - cjxl/djxl version v0.10.1

**Additional context**

**Comment by Traneptora** [comment]
Can you provide a sample JXL file?

**Comment by g4x86** [comment]
[JXL-Samples.zip](https://github.com/libjxl/libjxl/files/14482868/JXL-Samples.zip)

![EOG-Screenshot](https://github.com/libjxl/libjxl/assets/5235335/29450b56-a7e5-490e-bf63-d15b53166f9f)

Here you are:

1) A ZIP file containing: a source PNG file, one JXL file generated before, and one JXL generated by v0.10.1.
2) A screenshot of the error occurring when Image Viewer (eog) tries to open either JXL files.

**Comment by g4x86** [comment]
By the way, both JXL files can be previewed in Finder and opened by Preview on macOS Sonoma 14.3 correctly (macOS Sonoma natively support JXL format)

**Comment by nhoudelot** [comment]
same on Linux mint 21.3
Xviewer can't open any of those (with same error)
no thumbnail generated
so i guess it related to libjxl-gdk-pixbuf

**Comment by mo271** [comment]
Thanks for the report. I'm not able to repro this problem.
Is the mime-type correctly detected?
Could you check this by running one of the following:
```bash
xdg-mime query filetype sample-v0.9.jxl 
file --mime-type  sample-v0.9.jxl
```
Perhaps we can get a more informative error when running
```
gdk-pixbuf-thumbnailer sample-v0.9.jxl out.png
```
?

**Comment by nhoudelot** [comment]
here are the results for me :
```
$ xdg-mime query filetype sample-v0.9.jxl
application/octet-stream

$ file --mime-type  sample-v0.9.jxl
sample-v0.9.jxl: image/jxl

$ gdk-pixbuf-thumbnailer sample-v0.9.jxl out.png
** (gdk-pixbuf-thumbnailer:182702): WARNING **: 11:32:01.540: Could not thumbnail 'sample-v0.9.jxl': Couldn't recognize the image file format for file "/home/nicolas/JXL-Samples/sample-v0.9.jxl "
```

**Comment by mo271** [comment]
Ok, that explains it!
Seems like this is caused by
https://github.com/libjxl/libjxl/pull/2259
Running
```
sudo xdg-mime install --novendor image-jxl.xml
```
with the file https://github.com/libjxl/libjxl/blob/main/plugins/mime/image-jxl.xml might fix it manually, but I suppose we better revert https://github.com/libjxl/libjxl/pull/2259 to fix it globally.

**Comment by nhoudelot** [comment]
I confirm. 
Running `sudo xdg-mime install --novendor image-jxl.xml` fixed the problem
Now I can see thumbnails in nemo, and I can see the samples in Xviewer
:)

**Comment by mo271** [comment]
Thanks for reporting this, @g4x86 and thanks for helping out tracking down what is the problem here, @nhoudelot!

**Comment by g4x86** [comment]
Glad to see the bug is caught quickly! Congratulations everyone!
