### ISSUE TITLE
After Update to extra/libjxl 0.10.1-1  extra/telegram-desktop 4.15.0-1 won't work

### ISSUE THREAD

**Issue by wasundwarum** [libjxl/libjxl#3372]
After Update to extra/libjxl 0.10.1-1 telegram-desktop will not work correctly. A Downgrade to libjxl-0.9.2-1
all works fine

**Comment by mo271** [comment]
Likely related to the libjxl-gdk-pixbuf issue: https://github.com/libjxl/libjxl/issues/3358
