### ISSUE TITLE
The output size is different when inputting optimized PNG image or unoptimized it

### ISSUE THREAD

**Issue by sorairolake** [libjxl/libjxl#3413]
This is unoptimized image (752,757 B):
![unoptimized Krita 5.0 splash art](https://cdn.kde.org/krita/marketing/kiki/electrichearts_20201224A_kiki_c1-1024x512.png)

This is optimized image (653,559 B):
![optimized Krita 5.0 splash art](https://github.com/libjxl/libjxl/assets/48999343/029c7886-a486-4e03-8a41-ecbbb27e3c85)

The optimization method is as follows:
```sh
oxipng -o max electrichearts_20201224A_kiki_c1-1024x512.png
zopflipng -my electrichearts_20201224A_kiki_c1-1024x512.png electrichearts_20201224A_kiki_c1-1024x512.png
```

Also, these images are completely identical:
```text
$ compare -metric AE unoptimized.png optimized.png /dev/null
0
```

I compressed these images losslessly:
```sh
cjxl -q 100 electrichearts_20201224A_kiki_c1-1024x512.png electrichearts_20201224A_kiki_c1-1024x512.jxl
```

The output sizes are as follows:
- 458,778 B (unoptimized)
- 458,631 B (optimized)

I expected the output size to be the same, but it was not. Is this the expected behavior?

## Environment

- OS: Arch Linux on Docker on openSUSE Leap 15.5
- CPU type: x86_64
- cjxl/djxl version string: cjxl v0.10.2 e1489592 [AVX2,SSE4,SSE2]

**Comment by sorairolake** [comment]
The following images had the same result.

Unoptimized image (4,955 B):
![unoptimized image](https://github.com/libjxl/libjxl/assets/48999343/e843545f-3c80-46de-bb6d-b5ad5666dc16)

Optimized image (204 B):
![optimized image](https://github.com/libjxl/libjxl/assets/48999343/cfee0d83-a923-4ba0-a364-4b72392738f3)

In addition, when using `cwebp`, all output sizes were the same (including the images in the first comment).

Example:
```sh
cwebp -lossless QR_code.png -o QR_code.webp
```

`cwebp -version` output:
```text
1.3.2
libsharpyuv: 0.2.1
```

**Comment by goodusername123** [comment]
Krita seemingly outputs/exports all it's files with alpha channels for some reason and oxipng strips blank alpha channels while cjxl/libjxl does not so the final JXL files are different because one has an alpha channel and the other doesn't.
Also oxipng has zopfli built-in and you can use it with `-Z` so you don't need to use two different programs/tools.


As for the second image you posted of the QR code, The unoptimized version is RGB+Alpha like the first image however since it's black and white oxipng optimizes it to a 1-bit grayscale PNG with the blank Alpha removed and cjxl ends up keeping the same channels and bit-depth.

**Comment by sorairolake** [comment]
> Also oxipng has zopfli built-in and you can use it with `-Z` so you don't need to use two different programs/tools.

I know about that. I personally prefer using `zopflipng` instead of `-Z`, so I did that.

`cwebp` seems to be optimizing the alpha (if unnecessary) and color depth. I don't know if it's intentional to keep these, but personally, I think it would be more useful to optimize these in `cjxl` as well.

**Comment by sorairolake** [comment]
Should I file a feature request?

**Comment by sorairolake** [comment]
I submitted a feature request, so I close this issue.
