### ISSUE TITLE
JXL back to GIF issue

### ISSUE THREAD

**Issue by hellomynameisleo** [libjxl/libjxl#3428]
**Describe the bug**
When using CJXL to convert a JXL back to GIF file it doesn't convert the animated jxl back to a gif, it just makes a copy

**To Reproduce**
cjxl image.gif image.jxl
cjxl image.jxl image2.gif

**Expected behavior**
should be able to convert back the processed jxl back to the gif original file like it does with jpg image files.

**Comment by jonnyawsom3** [comment]
You want to use djxl

**Comment by hellomynameisleo** [comment]
> You want to use djxl

I get an error saying the below using "djxl image.jxl image.gif"

JPEG XL decoder v0.10.1 5f67ebc [AVX2,SSE2]
can't decode to the file extension '.gif'.

**Comment by jonnyawsom3** [comment]
Ah, right, I forgot APNG is the only animated option due to how bad GIF is...

**Comment by jendalinda** [comment]
JXL does not support bit exact compression of gif files. Gifs are converted from indexed color to RGB+alpha before encoding to jxl. Conversion from jxl to gif is not trivial so it is not supported by djxl.

**Comment by mo271** [comment]
Thanks for the report. There are no plans to add a gif encoder.
