### ISSUE TITLE
Apng encoding: `IDAT chunk after fcTL chunk` error when using apng created with imagemagick and ffmpeg

### ISSUE THREAD

**Issue by EugeneVert** [libjxl/libjxl#3430]
**Describe the bug**
Both `fcTL->IDAT->fcTL` and `IDAT->fcTL` chunks ordering seems to be [spec-conforming](https://wiki.mozilla.org/APNG_Specification#Chunk_Sequence_Numbers) ways to encode apng.

But neither ffmpeg, imagemagick, nor apngasm produces a cjxl acceptable apng with `IDAT->fcTL` ordering
* `ffmpeg -f concat -i ./concat_demuxer -plays 0 -c:v apng out.apng`
* `magick convert *.png APNG:out.apng`
* `apngasm *.png`

**To Reproduce**
```bash
convert -size 512x512 canvas:white '1.png'
convert -size 512x512 canvas:gray '2.png'
convert -delay 10 '1.png' '2.png' 'anim.apng'
cjxl 'anim.apng' 'out.jxl'
```
```log
JPEG XL encoder v0.10.0 b49cdd5 [AVX2,SSE4,SSE2]
./lib/extras/dec/apng.cc:739: JXL_FAILURE: IDAT chunk after fcTL chunk
./lib/extras/dec/decode.cc:142: JXL_FAILURE: Codecs failed to decode
Getting pixel data failed.
```

**Additional context**
Related commit: https://github.com/libjxl/libjxl/commit/4a9aaa83ad3c7b9d28140aa9a0b3be8d96548d74

**Comment by jonnyawsom3** [comment]
Do we actually know of any apng encoders that are compatible with cjxl currently?
[apngasm](https://apngasm.sourceforge.net/) is also affected
