### ISSUE TITLE
djxl silently failed to reconstruct some JPEG files

### ISSUE THREAD

**Issue by URenko** [libjxl/libjxl#3455]
**Describe the bug**
I use cjxl to recompress some JPEG files to JXL.
Then I use djxl to reconstruct them to JPEG, but it silently failed (no files were produced).
But I can successfully decode the JXL files into PNG files.

**To Reproduce**
JPEG file sample: [1c94fa30eea811e597bc25dc24f9c26c.zip](https://github.com/libjxl/libjxl/files/14865227/1c94fa30eea811e597bc25dc24f9c26c.zip)
```
$ cjxl 1c94fa30eea811e597bc25dc24f9c26c.jpg 1.jxl
JPEG XL encoder v0.10.2 e148959 [AVX2,SSE2]
Note: Implicit-default for JPEG is lossless-transcoding. To silence this message, set --lossless_jpeg=(1|0).
Encoding [JPEG, lossless transcode, effort: 7]
Compressed to 2746.1 kB including container
```
```
$ djxl 1.jxl 2.jpg
JPEG XL decoder v0.10.2 e148959 [AVX2,SSE2]
3677 x 5549,  282.590 MP/s [282.59, 282.59], , 1 reps, 16 threads.
```
The return code is 0, but nothing is produced.

```
$ djxl 1.jxl 2.png
JPEG XL decoder v0.10.2 e148959 [AVX2,SSE2]
Decoded to pixels.
3677 x 5549,  280.952 MP/s [280.95, 280.95], , 1 reps, 16 threads.
```
The content of 2.png is the same as the original JPEG.

**Environment**
 - OS: tested on Debian and Windows
 - Compiler version: all download from GitHub releases, so I guess clang
 - CPU type: x86_64
 - cjxl/djxl version string: see command line output above

**Comment by mo271** [comment]
Thanks for the report, I can reproduce it at current head.
