### ISSUE TITLE
cjxl silently fails when losslessly transcoding a jpg

### ISSUE THREAD

**Issue by TheHardew** [libjxl/libjxl#346]
**Describe the bug**
Encoding `1.jpg` appears to work, but no file is created.
`cjxl` output omits the `Including container: [size] bytes ([bpp] bpp).` message.
If the flags `-j` or `--strip` are used however, it does work.

**To Reproduce**
```
~/P/test $ ls
1.jpg
~/P/test $ cjxl 1.jpg 1.jxl
JPEG XL encoder v0.5.0 [AVX2]
Read 1024x768 image, 116.5 MP/s
Encoding [Container | JPEG, lossless transcode, squirrel | JPEG reconstruction data | 38973-byte Exif], 8 threads.
Compressed to 129617 bytes (1.319 bpp).
1024 x 768, 14.23 MP/s [14.23, 14.23], 1 reps, 8 threads.
~/P/test $ ls
1.jpg
```

**Expected behavior**
It should be possible to transcode this image or `cjxl` should output an error message and a non-zero exit status if the transcoding is not possible.

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 12.0.1
 - CPU type: ryzen 2700x x86_64
 - cjxl/djxl version string: 31d3ba750c9a705689490cc57159ebf898b6d64c

**Additional context**
Compiled with https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libjxl-git and
```
CFLAGS="-march=native -O3 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fno-plt -pthread -Wno-error -w"
CXXFLAGS="$CFLAGS"
```
The image:
![1](https://user-images.githubusercontent.com/7374061/126671020-0d292ffe-dbb1-44cf-b47c-c431ad987d70.jpg)

**Comment by TheHardew** [comment]
It seems running `jpegtran -copy all -outfile 2.jpg 1.jpg` makes it, so that the file can be transcoded.

**Comment by jonsneyers** [comment]
I get the following errors on this image, indicating that there's something strange about the original jpeg (it has 3 quantization tables but only uses 2 of them):
```
./lib/jxl/jpeg/jpeg_data.cc:200: JXL_FAILURE: Not all quant tables are used (3 tables, 3 used table mask)
../lib/jxl/fields.cc:711: JXL_RETURN_IF_ERROR code=1: CanEncode(fields, &extension_bits, &total_bits)
../lib/jxl/jpeg/enc_jpeg_data.cc:234: JXL_RETURN_IF_ERROR code=1: Bundle::Write(jpeg_data, &writer, 0, nullptr)
../tools/cjxl_main.cc:97: JXL_RETURN_IF_ERROR code=1: EncodeJPEGData(data_in, &jpeg_data)
```

@veluca93 does this mean we cannot make a `jbrd` that can reconstruct the original JPEG?

In cases like this, where the image data can be losslessly recompressed but the jpeg bitstream cannot, what would be the preferred behavior?

1. encode the image (and also any exif/xmp metadata) but not the `jbrd`, show a warning
2. encode the image including a 'best-effort' `jbrd` that will produce a slightly different jpeg bitstream than the original one (e.g. without the redundant unused quantization table), show a warning
3. throw an error

**Comment by veluca93** [comment]
Indeed it means that you can't make a jbrd box.

I vote for either 1 or 3.

**Comment by TheHardew** [comment]
This image was taken with a Nikon COOLPIX S7c. I've also seen images from Olympus C160/D395 and I think 1 more camera behave this way, and that's just the files I had on my disk, who knows how many cameras might have a similar problem. There might be a lot of images like this and that's why I think it would be nice if `cjxl` could work with them.

I'd like to be able to decode jxl to jpg without decoding to pixels first, so if jbrd is required for that I'd vote for 2, otherwise either 1 or 2.

Only maybe such behaviour should be behind a flag and an error should be thrown otherwise? By default I'd expect the jpg transcodes to be reversible in a bit perfect manner.
On the other hand, if such jpg files are not standard-compliant, maybe by default it should transcode them and a flag could be used to throw the error?

**Comment by TheHardew** [comment]
When I try to decode jxl created with `--strip` to jpg, `cjxl` outputs `Cannot decode to JPEG without a JPEG reconstruction box`.
So I think maybe 2 could be the defualt and 1 could be forced with `--strip`?

**Comment by jonsneyers** [comment]
> When I try to decode a jxl file created with `--strip` to jpg, `cjxl` outputs `Cannot decode to JPEG without a JPEG reconstruction box`.
> So I think maybe 2 could be the defualt and 1 could be forced with `--strip`?

We don't currently have a jpeg reconstruction procedure without `jbrd`, but all the image data is actually in the jxl codestream even when created with `--strip`, so it can in principle actually be decoded to a JPEG that will be different from the original JPEG file but contain exactly the same image data (basically like the result of `jpegtran` — the DCT coefficients are identical, but the file itself is created from scratch).

**Comment by jonsneyers** [comment]
The pull request https://github.com/libjxl/libjxl/pull/358 implements a combination of 1 and 3, in the sense that when jpeg bitstream reconstruction data cannot be created for whatever reason, it returns an error code but it still also produces a jxl output (that contains all the image data but not the jpeg reconstruction data).

The pull request https://github.com/libjxl/libjxl/pull/359 changes the behavior of `jbrd` specifically for this case (redundantly duplicated quantization tables), interpreting the part 2 spec in such a way that we can actually represent jpeg bitstreams like this example, as long as the redundant quant table is a copy of the previous one. That way we can just do actual full lossless recompression of these jpegs, including the jpeg bitstream reconstruction data.

**Comment by TheHardew** [comment]
Thank you very much, works great. (although this 1 image is all that I have now left for testing, sadly)

**Comment by ziemek99** [comment]
@jonsneyers I can confirm that I've got the **exact** same issue with JPGs from my Coolpix P900. I'm waiting for the PRs mentioned above to be merged...

![DSCN0276](https://user-images.githubusercontent.com/15923635/129740824-03f489b4-7e71-46ee-bede-3cb068da9249.jpg)

**Comment by jloqfjgk** [comment]
Related:
[Cannot convert 360 photos from Nikon KeyMission 360](https://gitlab.com/wg1/jpeg-xl/-/issues/212) (Reported by @GilDev)
['Failed to compress to JPEG.' ](https://gitlab.com/wg1/jpeg-xl/-/issues/176)

**Comment by orange47** [comment]
> I'd like to be able to decode jxl to jpg without decoding to pixels first, so if jbrd is required for that I'd vote for 2, otherwise either 1

as I understood, cjxl does not transcode, you don't lose any quality. the 'final' jpg is not the same but pixels are identical.

**Comment by ziemek99** [comment]
Merging "`allow redundant quant table in jbrd`" fixed the issue for me. Thanks, devs! 😃
