### ISSUE TITLE
jpegli reduces noise in images

### ISSUE THREAD

**Issue by zygoballus** [libjxl/libjxl#3461]
Some photographers (like me) intentionally [use digital noise in their images for effect](https://www.quora.com/Does-anyone-intentionally-use-digital-noise-in-their-photography). Reducing noise should be a function of my image editing program, not my file compression algorithm. I realize that sacrificing image fidelity for compression is nothing new, but doing so in a way that makes specific aesthetic choices (i.e. ["to make the internet faster and more beautiful"](https://opensource.googleblog.com/2024/04/introducing-jpegli-new-jpeg-coding-library.html)) is crossing the line into image manipulation. Between this and all the AI enhancement my cell phone camera does, we'll soon be living in a world where it is literally impossible to create a photo that isn't "beautiful".

**Comment by jonnyawsom3** [comment]
What about with higher quality settings?

**Comment by mxdpeep** [comment]
I think that's the purpose of compression

Jpegli works by using a number of new techniques to reduce noise and improve image quality.

**Comment by Waccoon** [comment]
> I think that's the purpose of compression

Reducing noise is the purpose of filtering and other pre-processing, which can aid compression down the line.  It may be a necessary evil to improve compression results, but it does indeed change the aesthetic nature of the images.

I would certainly hope that the library scales noise reduction along with the compression level.  There are a lot of paint programs out there that will do chroma sample reduction on JPEGs regardless of how high a quality setting you choose.  I hate when they do that.

**Comment by niutech** [comment]
@zygoballus If you want to preserve the artificial noise, why don't you use lossless WebP or JXL?

**Comment by jonnyawsom3** [comment]
Once the support is more widespread, I'd recommend looking into lossy JXL's ISO noise setting. Then you can set the amount of noise you want in the image without making it any harder to compress
