### ISSUE TITLE
Lossy cjxl with Alpha channel not using --keep_invisible=0 as default

### ISSUE THREAD

**Issue by Bustycat** [libjxl/libjxl#3514]
**Describe the bug**
When using `cjxl` to encode an image with the Alpha channel to a lossy JPEG XL file, the default value for `keep_invisible` should be 0. The results show a possible default as 1 instead.

```
--keep_invisible=0|1
disable/enable preserving color of invisible pixels (default: 1 if lossless, 0 if lossy).
```

**To Reproduce**
```
cjxl file.png file.jxl -d 1
cjxl file.png file.jxl -d 1 --keep_invisible=0
```

**Expected behavior**
The default value of `keep_invisible` for lossy JPEG XL images should be 0.

**Screenshots**
<img width="431" alt="截圖 2024-04-20 23 18 17" src="https://github.com/libjxl/libjxl/assets/161316/75c34982-d9ee-4e99-b155-a80fce8b6c0f">

**Environment**
 - OS: macOS Sonoma 14.4.1 (23E224)
 - Compiler version: Apple clang version 15.0.0 (clang-1500.3.9.4)
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.10.2 0.10.2 [AVX2,SSE4,SSE2]

**Comment by zond** [comment]
Hey @Bustycat,

I have been trying to reproduce the problem you describe, but I suspect the PNGs I'm trying it with are missing something.

Could you perhaps share the PNG you used to create this report?

**Comment by Bustycat** [comment]
> Hey @Bustycat,
> 
> I have been trying to reproduce the problem you describe, but I suspect the PNGs I'm trying it with are missing something.
> 
> Could you perhaps share the PNG you used to create this report?

[Original.zip](https://github.com/libjxl/libjxl/files/15223586/Original.zip)

I used a ZIP archive to preserve the original status, and avoided some disputes.

**Comment by mo271** [comment]
fixed by #3562

**Comment by zond** [comment]
> > Hey @Bustycat,
> > I have been trying to reproduce the problem you describe, but I suspect the PNGs I'm trying it with are missing something.
> > Could you perhaps share the PNG you used to create this report?
> 
> [Original.zip](https://github.com/libjxl/libjxl/files/15223586/Original.zip)
> 
> I used a ZIP archive to preserve the original status, and avoided some disputes.

Thanks, should be fixed now!

**Comment by MasterInQuestion** [comment]
"-d 1.0 --keep_invisible=0.jxl": 686 KB
    "-d 1.0 -a 1.0 --keep_invisible=0.jxl": 683 KB
    .
    Why would "-a" matter for "--keep_invisible=0" this case..?
