### ISSUE TITLE
The effort documentation is outdated

### ISSUE THREAD

**Issue by Galaxy4594** [libjxl/libjxl#3517]
Encode_effort.md is not accurate anymore with the release of libjxl 0.10.x. Outside of the "brute force" effort now being 11, does VarDCT e10 do anything special? Or does it simply do more Butteraugli iterations? What about e9 vs e10 lossless? I think it should also mention which efforts use the new streaming mode by default in 0.10.x. Jon Sneyers in the JXL discord [mentioned](https://discord.com/channels/794206087879852103/794206170445119489/1215017451931045948) that e10 disables streaming by default.

I should also mention that for benchmarking.md, "glacier" is equivalent to e10, so what is e11? _Edit: Apparently e11 is called "tectonic plate"._ And finally the target bitrate command `-r` is depreciated.

**Comment by MasterInQuestion** [comment]
Discord seems to require login for read access now.
    Would you transcript the relevant info?

**Comment by Galaxy4594** [comment]
Here's a snippet, Jon Sneyers is \_wb\_, the topic is about lossless encoding. I recommend joining the sever, lots of good information in there.
```
afed — 3/6/2024 11:22 AM
because streaming sometimes gets better results than non-streaming

JendaLinda — 3/6/2024 11:24 AM
I kept the default streaming settings.

_wb_ — 3/6/2024 11:25 AM
It's basically greedy local optimization vs greedy global optimization. Cannot say which will be best.

_wb_ — 3/6/2024 11:25 AM
Default is to use streaming up to e9, no streaming at e10

JendaLinda — 3/6/2024 11:26 AM
So that explains it. -e 9 also seems to better utilize CPU threads.

Orum — 3/6/2024 11:38 AM
yeah, but you can force streaming with e 10 (which is the only way it's remotely practical IMHO)

JendaLinda — 3/6/2024 11:52 AM
What is the actual difference between streaming and not streaming?
Is that the streaming mode better uses the available resources?

afed — 3/6/2024 11:55 AM
streaming is encoding in independent blocks, non-streaming is the whole image

JendaLinda — 3/6/2024 11:57 AM
So in non-streaming mode, the encoder has access to more information to work with, right?

afed — 3/6/2024 11:59 AM
yeah
```

**Comment by MasterInQuestion** [comment]
Thanks for suggestion.
    But somewhat troublesome for me. (the access management trouble)

    "afed - 3/6/2024 11:22 AM"
    Is it CE 2024-03-06 11:22 -07:00? (or -03:00?)
    (I'll add refactored content later)

**Comment by MasterInQuestion** [comment]
Is it?
    “"--streaming_output"
    Enable incremental writing of the output file.”

    I tried but appears no-op with "-e 11 -d 0"?

**Comment by Galaxy4594** [comment]
> "afed - 3/6/2024 11:22 AM". Is it CE 2024-03-06 11:22 -07:00? (or -03:00?)

The format is MM/DD/YYYY, UTC -8.

>  “--streaming_output Enable incremental writing of the output file.” I tried but appears no-op with "-e 11 -d 0"?

First of all, you should be using `--streaming_input` not `--streaming_output`.

Streamed encoding can only be used on images larger than 2048x2048. So if your images are under these dimensions it will ignore `--streaming_input`.

**Comment by MasterInQuestion** [comment]
“"--streaming_input"
    Enable streaming processing of the input file (works only for PPM and PGM input files).”

    "only for PPM and PGM input files"?

**Comment by Galaxy4594** [comment]
That's what it says, but according to my testing it seems to work with non-interlaced PNGs as well.

**Comment by MasterInQuestion** [comment]
So my \`ffmpeg` pipe [ [ https://github.com/libjxl/libjxl/issues/3921#issue-2639083059](https://github.com/libjxl/libjxl/issues/3921#issue-2639083059) ] there shall also work..?
    May try later.

    What about JXL (lossless) input?

**Comment by Galaxy4594** [comment]
Lossless JXL input also seems to work. Maybe the documentation is old.
