### ISSUE TITLE
Typos in color_encoding.h

### ISSUE THREAD

**Issue by ledoge** [libjxl/libjxl#3553]
1. [Here](https://github.com/libjxl/libjxl/blob/9d5477dc7c2604c596980de1bca072489d4b5aed/lib/include/jxl/color_encoding.h#L100), `Rendering` is misspelled as `Renderig`.

2. There seems to be a copy-paste error [here](https://github.com/libjxl/libjxl/blob/9d5477dc7c2604c596980de1bca072489d4b5aed/lib/include/jxl/color_encoding.h#L81), as the enum constant is called `JXL_TRANSFER_FUNCTION_709`, but the comment refers to `SMPTE RP 431-2` instead of `ITU-R BT.709-6`.

**Comment by mo271** [comment]
Thanks!
