### ISSUE TITLE
a2x Syntax Error with .asdf/PyEnv

### ISSUE THREAD

**Issue by Patterner** [libjxl/libjxl#3564]
**Describe the bug**
```
[  0%] Generating cjxl.1
  File "/home/p/.asdf/shims/a2x", line 3
    exec /home/p/.asdf/bin/asdf exec "a2x" "$@" # asdf_allow: ' asdf '
SyntaxError: invalid syntax
```
**To Reproduce**
```
which a2x
    /home/p/.asdf/shims/a2x
mkdir build
cd build
cmake ..
cmake --build .
```
**Expected behavior**
```
[  0%] Generating cjxl.1
[  0%] Generating djxl.1
[  0%] Built target manpages
```
**Environment**
 - OS: WSL2
 - Compiler version: Debian clang 17.0.6
 - CPU type: x86_64
 - cjxl/djxl version string: v0.10.2 661fec1b [AVX2,SSE4,SSE2]

**Additional context**

Line 435f of CMakeLists.txt:
```
    file(STRINGS "${ASCIIDOC}" ASCIIDOC_SHEBANG LIMIT_COUNT 1)
    if(ASCIIDOC_SHEBANG MATCHES "/sh|/bash" OR MINGW)
```
.asdf/shims/a2x
```
#!/usr/bin/env bash
exec /home/p/.asdf/bin/asdf exec "a2x" "$@" # asdf_allow: ' asdf '
```
I think the problem is the SheBang line which has "/usr/bin/env bash",
so it isn't recognized as a Shell script.

**Comment by mo271** [comment]
Thanks for the report, can you check if #3565 fixes your problem?
