### ISSUE TITLE
compressed exif/xmp is not yet implemented

### ISSUE THREAD

**Issue by jonsneyers** [libjxl/libjxl#357]
At the file format level, we have defined brotli-compressed boxes (`brob`), but this hasn't been implemented yet.

**Comment by mo271** [comment]
Does this closes the issue? 
https://github.com/libjxl/libjxl/pull/902

**Comment by jonsneyers** [comment]
Once https://github.com/libjxl/libjxl/pull/1350 merges, it should be fine, except cjxl_ng still needs to be wired up to preserve exif/xmp (compressed or uncompressed is less important, but it currently silently strips it), and probably djxl_ng is also not looking for metadata to add when decoding to png.
But as far as this issue is concerned, I think it can be closed.

**Comment by kmilos** [comment]
Btw, I don't understand the need for the 4 extra (zero?) bytes prepended to the Exif buffer [here](https://github.com/libjxl/libjxl/blob/a444260ba2519499f82497358348ee9d38f52ba4/lib/jxl/encode.cc#L1398)? Usually both APP1 payload and any TIFF raw data just starts w/ "II"/"MM", I don't understand where this "tiff offset" comes from?

**Comment by jonsneyers** [comment]
This is how it is specified in the ISOBMF `Exif` box, so we do it in the same way. I assume they defined it that way to allow people to put some arbitrary extra stuff in the Exif box, and the "tiff offset" would then tell you where the actual Exif data starts.

**Comment by kmilos** [comment]
Thanks... I guess the idea was to perhaps try to record the original offset of the pre-existing Exif and/or Makernote IFDs in case they use original TIFF container absolute addresses instead of relative ones...

Can you please share a link, I can't find a spec for this `Exif` box anywhere (i.e. [the only publicly available version](https://mpeg.chiariglione.org/standards/mpeg-4/iso-base-media-file-format/text-isoiec-14496-12-5th-edition)  does not mention Exif it at all...)?

**Comment by kmilos** [comment]
Thanks. I guess the spec is the spec if you decided to follow JPEG XS/HEIF.

However, I still don't get their rationale given the below, but I guess that's out of scope here, and I don't expect further clarification. Sorry for taking your time.

> exif_tiff_header_offset is an offset in bytes from the first byte of exif_payload to the first byte of the TIFF Header of the Exif metadata, as specified in JEITA CP-3451B.

No mention of any such offset in the latest JEITA CP-3451E (Exif 2.32) spec - the payload always starts w/ the TIFF header AFAICT.

> (e.g. exif_payload is formatted as specified for the DCF thumbnail file in JEITA CP-3461B)

Again, no mention of any such offset in JEITA CP-3461B either, the payload is as specified in JEITA CP-3451E previously, i.e. always starts w/ the TIFF header...

> exif_payload is a variable sized array of bytes holding the Exif compliant metadata to be parsed by the reader. This is compliant with JEITA CP-3451B or JEITA CP-3461B and shall have as part of it a TIFF Header with referenced Image File Directories (IFDs). There may be additional bytes before or after this Exif data...

It's compliant in a way that is contains a valid Exif payload somewhere (i.e. neither JEITA CP-3451E nor JEITA CP-3461B mention any offsets to it), but the before/after part seems completely arbitrary/unnecessary...

**Comment by jonsneyers** [comment]
Yeah I'm also not quite sure what the rationale is, but we decided to follow what others already did instead of defining our own 'Exif' box (which would need to have a different name then if it is defined in a different way).

I can only assume there might be use cases where besides the Exif itself, you also want to preserve extra stuff that came before or after the Exif data itself. I don't know what those use cases are. Perhaps it's something that they anticipated to be useful for something but then it turned out to be not useful. In any case, these four 'wasted' zero bytes didn't seem to be worth haggling about, especially since we can put an `Exif` box inside a `brob` box which will probably deal quite well with such zero bytes.

**Comment by jonsneyers** [comment]
Yeah, originally we had an `exif` box (no capital letter) which was just an exif blob, but then I think some Japanese members of JPEG said we should call it `Exif` and use the same definition that was already used in JPEG XS and HEIF, so we did that :)

**Comment by mo271** [comment]
> Once #1350 merges, it should be fine, except cjxl_ng still needs to be wired up to preserve exif/xmp (compressed or uncompressed is less important, but it currently silently strips it), and probably djxl_ng is also not looking for metadata to add when decoding to png. But as far as this issue is concerned, I think it can be closed.

Let's close it then...
