### ISSUE TITLE
Undefined symbols for x86_64: `___cpu_model`

### ISSUE THREAD

**Issue by Blonteractor** [libjxl/libjxl#3599]
**Describe the bug**
I am cross compiling for Intel Mac from my M1 mac and I am getting this error while linking. I am using the vcpkg port, `libjxl:x64-osx`.
```
 Undefined symbols for architecture x86_64:
            "___cpu_model", referenced from:
                _JxlFastLosslessPrepareFrame in libjxl.a[21](enc_fast_lossless.cc.o)
                _JxlFastLosslessProcessFrame in libjxl.a[21](enc_fast_lossless.cc.o)
          ld: symbol(s) not found for architecture x86_64
```

**To Reproduce**
Use the vcpkg port, `libjxl:x64-osx` to cross compile from M1 to intel mac.

**Expected behavior**
It should link just fine.

**Environment**
 - OS: MacOS 14.4.1
 - Compiler version: clang 15.0.0
 - HOST CPU type: aarch64
 - TARGET CPU type: x86_64

**Additional Context**
- I am on the latest version of vcpkg, on the master branch 
- I got this to link by disabling AVX2 support but that's not ideal.
- If I use the cmake lists `find_package` it also works, as its automatically pulling all the correct flags and stuff for the target, I am probably missing a flag or two.

**Comment by Blonteractor** [comment]
@eustas got anything yet? I think its happens on a native apple x86 build too

**Comment by veluca93** [comment]
Can you check that #3658 fixes this?

**Comment by Blonteractor** [comment]
This is still present in `0.11`
