### ISSUE TITLE
jfif support

### ISSUE THREAD

**Issue by joskezelensky** [libjxl/libjxl#3638]
**Is your feature request related to a problem? Please describe.**
i want to be able to encode jfif files
**Describe the solution you'd like**
implement jfif encoding
**Describe alternatives you've considered**
i have not tried alternatives
**Additional context**
i'm trying to encode [this](https://cyfrowe-cdn.mnw.art.pl/upload/multimedia/46/5e/465e5e3e24a24ccdbe76af4186170bc0.jpg) image, which is mislabeled as a jpg file

**Comment by jonsneyers** [comment]
What exactly is the problem you're encountering?
This file recompresses just fine when I try it:
```
bash-3.2$ cjxl 465e5e3e24a24ccdbe76af4186170bc0.jpg 465e5e3e24a24ccdbe76af4186170bc0.jpg.jxl
JPEG XL encoder v0.10.2 0.10.2 [NEON]
Note: Implicit-default for JPEG is lossless-transcoding. To silence this message, set --lossless_jpeg=(1|0).
Encoding [JPEG, lossless transcode, effort: 7]
Compressed to 2213.4 kB including container 

bash-3.2$ djxl 465e5e3e24a24ccdbe76af4186170bc0.jpg.jxl 465e5e3e24a24ccdbe76af4186170bc0.jpg.jxl.jpg
JPEG XL decoder v0.10.2 0.10.2 [NEON]
Reconstructed to JPEG.
3499 x 4228,  209.197 MP/s [209.20, 209.20],  37.457 MB/s [37.46, 37.46], 1 reps, 12 threads.

bash-3.2$ sha512sum 465e5e3e24a24ccdbe76af4186170bc0.jpg 465e5e3e24a24ccdbe76af4186170bc0.jpg.jxl.jpg
0ad9257da0a71dd756e967d94308249551f3fa3cff06840b3e0633d3ad44c0b95ea627466b04f6a10badb6424af573018bd75ef71f8f768ddbe4ae790db7ffa0  465e5e3e24a24ccdbe76af4186170bc0.jpg
0ad9257da0a71dd756e967d94308249551f3fa3cff06840b3e0633d3ad44c0b95ea627466b04f6a10badb6424af573018bd75ef71f8f768ddbe4ae790db7ffa0  465e5e3e24a24ccdbe76af4186170bc0.jpg.jxl.jpg
```

Note that jfif and jpg are basically the same thing.

**Comment by joskezelensky** [comment]
> What exactly is the problem you're encountering? This file recompresses just fine when I try it
> 
> Note that jfif and jpg are basically the same thing.


```
cjxl in.jfif out.jxl
JPEG XL encoder v0.10.2 cdb6a66 [AVX2,SSE2]
Reading image data failed.
```

**Comment by jonsneyers** [comment]
I cannot reproduce this problem. Are you sure we are using the same input file?
The link in your original message is broken, I used this one instead: https://cyfrowe-cdn.mnw.art.pl/upload/multimedia/46/5e/465e5e3e24a24ccdbe76af4186170bc0.jpg

**Comment by joskezelensky** [comment]
> I cannot reproduce this problem. Are you sure we are using the same input file? The link in your original message is broken, I used this one instead: [cyfrowe-cdn.mnw.art.pl/upload/multimedia/46/5e/465e5e3e24a24ccdbe76af4186170bc0.jpg](https://cyfrowe-cdn.mnw.art.pl/upload/multimedia/46/5e/465e5e3e24a24ccdbe76af4186170bc0.jpg)

i was using an older version when the issue existed, i updated my version to latest git master and the issue doesn't exist anymore
thx
