### ISSUE TITLE
FindHWY.cmake no longer works with the latest version of highway

### ISSUE THREAD

**Issue by dlemstra** [libjxl/libjxl#3641]
**Describe the bug**
The `FindHWY.cmake` file uses the `hwy/highway.h` header file to determine the version when `pkgconfig` is not available but this moved to the file `hwy/base.h` and now the version cannot be found anymore.

**To Reproduce**
Build this project somewhere where `pkgconfig` is not available and the latest (`1.2.0`) highway library is installed on the system.

cc @jan-wassenberg

**Comment by mo271** [comment]
@dlemstra could you check that #3642 fixes the problem for you?
