### ISSUE TITLE
old encoded image jxl cannot decode by new version

### ISSUE THREAD

**Issue by doanquocnam** [libjxl/libjxl#3659]
**Describe the bug**
I have along time to use this image format. The version I started using for my application is v0.6.x.  So I had a problem, what I cant  resolve. Please help me to fix it.

A received an report that there was an image jxl cannot be decoded, so that I tried to decode by chrome old version (supported jxl), firefox trunk, ... so I put  to the sample decode_oneshot, it failed to decompress this file (what I upload for this report),
I tried all version 0.7.x, 0.8.x, ... 0.10.x .. and the main git version but the image wasnt able to decode.

I tried the version 0.6.x and the image could be decoded. So that please fix for this case. Thanks!
![image](https://github.com/libjxl/libjxl/assets/41658839/fd187718-821e-4f94-bc6b-69d6ff3a8f4d)

![c56f50ec47dfe481bdce jxl](https://github.com/libjxl/libjxl/assets/41658839/2e7d4168-09ad-4218-aa02-47e5f11d9295)

**Environment**
 - OS: [e.g. Windows, Android, Linux, iOS]
 - Compiler version: [e.g. clang 11.0.1]
 - CPU type: [e.g. x86_64, ARM64, ARM32]
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]]

**Comment by mo271** [comment]
Bisecting suggests that this started happening at https://github.com/libjxl/libjxl/pull/1046. Any thoughts, @jonsneyers?

**Comment by mo271** [comment]
Thanks for the report, @doanquocnam!

**Comment by jonsneyers** [comment]
Could you share the jxl file that no longer decodes?

**Comment by mo271** [comment]
@jonsneyers it is linked above

**Comment by doanquocnam** [comment]
> Could you share the jxl file that no longer decodes?

Didnt you see that link of jxl image what I've uploaded.?
![image](https://github.com/libjxl/libjxl/assets/41658839/f78f39af-4baf-4d5b-bcbd-790c0af5aa14)

You can download it here: https://b-f67-zpg-r.zdn.vn/jxl/7220520585340013593/c56f50ec47dfe481bdce.jxl

**Comment by jonsneyers** [comment]
Oh, interesting, on my browser (Thorium) I didn't see a broken image icon and a filename but an empty area the size of that image :)
(so it doesn't decode but it does know the image dimensions, it just doesn't paint any pixels)

Thanks for finding this regression!
