### ISSUE TITLE
0.8.3 release has a version of number of 0.10.2

### ISSUE THREAD

**Issue by mgorny** [libjxl/libjxl#3680]
**Describe the bug**
The v0.8.3 tag contains a library with a version number of 0.10.2.

**To Reproduce**
https://github.com/libjxl/libjxl/blob/a7e04be87bd060884cfcc5c3125e6e770f7d1e16/lib/CMakeLists.txt#L7-L8

**Expected behavior**
Version 0.8.3 :-).

**Comment by mo271** [comment]
This was a mistake, the correct v0.8.3 will come soon.
Thanks for the notice!

**Comment by mo271** [comment]
should be fixed now, v0.8.3 tag points to https://github.com/libjxl/libjxl/commit/20374fdd040dec80f28ee35a30aa882a1be54bd6

**Comment by mgorny** [comment]
Thanks.
