### ISSUE TITLE
tracking_memory_manager.cc(41,35): error C2672: 'std::max': no matching overloaded function

### ISSUE THREAD

**Issue by dbyoung720** [libjxl/libjxl#3694]
tracking_memory_manager.cc(41,35): error C2672: 'std::max': no matching overloaded function

Windows10X64+VS2022

**Comment by eustas** [comment]
Will be fixed by https://github.com/libjxl/libjxl/pull/3693

**Comment by mo271** [comment]
should be fixed now, please re-open if the issue persists
