### ISSUE TITLE
2k²~ image encoded in lossless mode has color artifact above effort 4

### ISSUE THREAD

**Issue by Firepal** [libjxl/libjxl#3717]
**Describe the bug**
When using `cjxl` to encode a particular 2096x2088 PNG image to lossless JPEG XL, a reddish 48x40 rectangle appears at the bottom-right corner of the encoded JXL.

**To Reproduce**
Encode this image using `cjxl -d 0 -e 5`
<img width="512" src="https://github.com/user-attachments/assets/4dcfec20-9f3b-448a-9f75-af03db2086e1"></img>

**Expected behavior**
The encoded JXL should contain all pixels of the PNG unaltered.

**Screenshots**
This is a 512x512 crop of the bottom-right corner of the encoded JXL
![image](https://github.com/user-attachments/assets/d1cbc9c9-f79f-4d42-8710-650786c652e3)

**Environment**
 - OS: Windows 10
 - Compiler version: Unknown (downloaded from GitHub releases)
 - CPU type: x86_64
 - cjxl/djxl version string: `JPEG XL encoder v0.10.2 e148959 [AVX2,SSE2]`

**Additional context**
The image I had this issue on was the [cover art for femtanyl's "CHASER" EP](https://musicbrainz.org/release/ada3880b-7522-47cc-b526-81d2aadb5a4a/cover-art) at original size, which is **slightly graphic.**
This would be rather distracting, so the provided test image is that cover art with the graphic part blacked out. 
It exhibits the same problem as the source image.

**Comment by Firepal** [comment]
Someone on the discord inspired me to check whether this was a regression:
* 0.9.3 encodes and does not exhibit this problem at all
* 0.10.0 and 0.10.1 crash when attempting to encode the image
* 0.10.2 and 0.10.3 encode the image with this bug.

**Comment by yota-code** [comment]
I can confirm with `JPEG XL encoder v0.10.2 7b9701eb`

**Comment by yota-code** [comment]
bug confirmed today with the last commit of master: `cjxl v0.10.2 7b9701eb`

**Comment by yota-code** [comment]
The static release 0.8.2 seems to also have the bug, and the static release 0.10.2 gives a green square instead of red :D https://discord.com/channels/794206087879852103/848189884614705192/1265570789046882315

**Comment by jonsneyers** [comment]
@veluca93 any idea what could cause this?

It seems to happen only when using multiple threads and when using streaming encode. The problem region is aligned with DC groups and corresponds to a DC group that is very small. Some kind of race condition maybe?

This is a high-priority bug imo.
