### ISSUE TITLE
14bit grayscale image cannot be correctly compressed in lossless mode

### ISSUE THREAD

**Issue by qdwang** [libjxl/libjxl#3718]
**Describe the bug**
For 16bit grayscale PGM(with 65535 in header), everything works fine, the `idenfity` result is identical for src and target.
But for 14bit grayscale PGM(with 16383 in header), this issue happens.

**To Reproduce**
I have a 14-bit grayscale PGM `src.pgm`, and I converted it to lossless JXL by using `cjxl -d 0 src.pgm target.jxl`.

The problem is the brightness of these two are slightly different.
By using `identify -verbose`, I get the Channel statistics:

**src.pgm**
```
  Channel statistics:
    Pixels: 24337152
    Gray:
      min: 0  (0)
      max: 15871 (0.968748)
      mean: 642.471 (0.0392157)
      median: 229 (0.0139779)
      standard deviation: 1242.43 (0.0758363)
      kurtosis: 15.1143
      skewness: 3.73396
      entropy: 0.759787
```

**target.jxl**
```
  Channel statistics:
    Pixels: 24337152
    Gray:
      min: 0  (0)
      max: 15871 (0.96875)
      mean: 642.457 (0.0392148)
      median: 228.99 (0.0139773)
      standard deviation: 1242.42 (0.0758362)
      kurtosis: 15.1143
      skewness: 3.73397
      entropy: 0.759787
```

One more thing, I also decode the compressed jxl file to `decoded.pgm`.  
The pixel values in `decoded.pgm` are **not identical** to `src.pgm`.

**Expected behavior**
It should like the 16bit grayscale image, the two statistics from `identify` should be identical.

**Environment**
 - OS: MacOS
 - Compiler version: Apple clang version 15.0.0
 - CPU type: M2
 - cjxl/djxl version string: Both v0.10.2 and main

**Comment by balping** [comment]
For anyone running into this issue:, you need to specify the buffer bit depth for both the encoder and decoder in order to perfectly reconstruct the original image:

```c++
const JxlBitDepth bit_depth = {JXL_BIT_DEPTH_FROM_CODESTREAM};
JxlEncoderSetFrameBitDepth(frame_settings, &bit_depth);
```


```c++
const JxlBitDepth bit_depth = {JXL_BIT_DEPTH_FROM_CODESTREAM};
JxlDecoderSetImageOutBitDepth(dec.get(), &bit_depth);
```
