### ISSUE TITLE
BUG - Can't create a JPEG XL file from animated PNGs

### ISSUE THREAD

**Issue by TacoCake** [libjxl/libjxl#3745]
**Describe the bug**
trying to run this command to convert an APNG file to an animated JPEG XL doesn't work:
```bash
cjxl '/home/redacted/Downloads/alexey-fedorov.png' '/home/redacted/Downloads/alexey-fedorov-apng-input.jxl'
```
This is what it returns:
```bash
JPEG XL encoder v0.10.3 [AVX2,SSE4,SSE2]
Getting pixel data failed.
```

**To Reproduce**
I've tried with two files, both from different places. Basically, take any APNG and try to convert it to JPEG XL.
This is one of the APNG I tried to convert:
![alexey-fedorov](https://github.com/user-attachments/assets/4fd0eca3-dd18-413d-9901-0dc9fc118de5)

**Expected behavior**
Creates an animated JPEG XL file.

**Additional context**
I'm using the pre-packaged binaries directly from the openSUSE Tumbleweed repositories.

I have also tried building from source with the debug symbols turned on.
This is the output, the above command gave me, after building from source.

```bash
JPEG XL encoder v0.11.0 e10fb685 [AVX2,SSE4,SSE2]
./lib/extras/dec/apng.cc:899: JXL_FAILURE: Malformed chunk
./lib/extras/dec/exr.cc:29: JXL_FAILURE: EXR is not supported
./lib/extras/dec/decode.cc:151: JXL_FAILURE: Codecs failed to decode
Getting pixel data failed.
```

From what I understand, my input APNG is being flagged as malformed. However, I have **multiple programs that can read the APNG correctly.**

**Environment**
 - OS: openSUSE Tumbleweed
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.10.3 [AVX2,SSE4,SSE2]
 
 **Edit**
 I also tried changing the extension to `.apng`, that did nothing.

**Comment by jonnyawsom3** [comment]
Just to test... Did you try giving it the .apng file extension?

**Comment by 0fbcb238c0** [comment]
The 0.10.3 release still has the issue with encoding from apng. Compile from source for it to work. Or wait until 0.11 releases in a few weks(?).

**Comment by TacoCake** [comment]
> Just to test... Did you try giving it the .apng file extension?

Ah yes, I did. I forgot to add that...

**Comment by TacoCake** [comment]
> The 0.10.3 release still has the issue with encoding from apng. Compile from source for it to work. Or wait until 0.11 releases in a few weks(?).

I tried though. I said in my issue that I even tried it when compiled straight from source.

**Comment by 0fbcb238c0** [comment]
Sorry, I must have overread that.

**Comment by 0fbcb238c0** [comment]
This seems to be a problem with the APNG, not with cjxl.
I was unable to open the APNG in an image viewer due to `libpng error: Read Error`
ffprobe shows `[apng @ 0x5fbd96f94980] Packet corrupt (stream = 0, dts = NOPTS).`
and even Imagemagick threw an error while reading the file `identify: Read Exception`

**Comment by TacoCake** [comment]
That seems plausible, though why does Firefox display it correctly?

**Comment by 0fbcb238c0** [comment]
MPV also plays the APNG, though showing an error message.
Looking into Firefox's devtools, i was not able to find an error message like FFmpeg has shown.
FFmpeg is able to transcode the APNG, although I have not compared the resulting file.
If I reencode the APNG using FFmpeg, cjxl will work on the new APNG file.

**Comment by jendalinda** [comment]
The file is truncated, IEND is missing.

**Comment by TacoCake** [comment]
According to the wording on this page: https://exiftool.org/TagNames/PNG.html

> According to the specification, a PNG file should end at the IEND chunk, however ExifTool will preserve any data found after this

It seems that it would be *possible* that a PNG file doesn't end with a IEND chunk, and have it still considered as a valid PNG file.

Though according to the section 4.1.4. of the PNG 1.2 spec (http://www.libpng.org/pub/png/spec/1.2/png-1.2-pdg.html) a PNG file **must** end with an IEND chunk.

> The IEND chunk must appear LAST. It marks the end of the PNG datastream. The chunk's data field is empty.

**Comment by TacoCake** [comment]
Though, even if it would be out of spec, the APNG that I provided was created from a GIF using this site: https://ezgif.com/gif-to-apng

So I assume this issue could be encountered by other people.

> FFmpeg is able to transcode the APNG

Could you share the full command you used?

**Comment by 0fbcb238c0** [comment]
> Could you share the full command you used?

`ffmpeg -i 356832947-4fd0eca3-dd18-413d-9901-0dc9fc118de5.png test.apng`
As I said before, I have not compared the transcoded file to your uploaded file. I simply did this for testing.
It may have something missing, who knows.

> Though, even if it would be out of spec, the APNG that I provided was created from a GIF using this site: https://ezgif.com/gif-to-apng

Can you not simply convert to GIF to APNG using ffmpeg directly?

**Comment by TacoCake** [comment]
Sorry for the multiple comments in a row, but I also found the APNG spec.

From reading the section on Error Handling in this document, https://wiki.mozilla.org/APNG_Specification.

It states: 
> APNG is designed to allow incremental display of frames before the entire image has been read.

So I guess Firefox & FFMPEG could simply be ignoring the missing IEND chunk, since APNGs are designed to be read chunks at a time ? They could simply be interpreting the lack of more data as the end of the file.

Pure speculation btw.

**Comment by TacoCake** [comment]
> Can you not simply convert to GIF to APNG using ffmpeg directly?

That is not something I tried, I guess I could. Though, I assume I wouldn't be the only one trying to use an online tool for conversion, so other people might encounter this issue.

---

I just tried converting it from GIF to APNG with FFMPEG, and it does in fact contain the `IEND` chunk at the end of the file.
![Screenshot_20240811_102111](https://github.com/user-attachments/assets/dab46229-44ea-4b10-976d-21221a76ed86)

As [jendalinda](https://github.com/jendalinda) said, the original file I sent (the one converted from https://ezgif.com/gif-to-apng) doesn't contain the IEND.

**Comment by 0fbcb238c0** [comment]
May I ask why you are taking the APNG route?
ezgif.com does have https://ezgif.com/gif-to-jxl
And cjxl also directly supports GIF input.

**Comment by TacoCake** [comment]
> May I ask why you are taking the APNG route?

I have already some GIFs that I converted to APNG before JPEG XL was as big as it is. For some of my APNG files, I don't have the original GIF file for.

Would love to simply be able to all convert them to JPEG XL, instead of having to hunt down the original GIF files.

The one I included in the issue I do have the original for, which helps with debugging.

**Comment by 0fbcb238c0** [comment]
Could you try converting the original GIF to APNG using ffmpeg and check if it then has the same issue?
Or better yet, attach the original GIF so others can have a look as well.

**Comment by TacoCake** [comment]
> Could you try converting the original GIF to APNG using ffmpeg and check if it then has the same issue? Or better yet, attach the original GIF so others can have a look as well.

Yes, that's what I detailed in this comment: https://github.com/libjxl/libjxl/issues/3745#issuecomment-2282779693

Though here is the original: 
![alexey-fedorov-gif-400](https://github.com/user-attachments/assets/9f0ea58e-210f-472f-a948-ebf5395f7c3c)

**Comment by 0fbcb238c0** [comment]
Is the APNG you attached modified? I notice that the GIF has 180 frames, yet the originally attached APNG only has 35 frames.

Passing the GIF to cjxl via
`ffmpeg -i 356885171-9f0ea58e-210f-472f-a948-ebf5395f7c3c.gif -f apng - | cjxl - test.jxl`
works as expected.

Converting the GIF to APNG using ezgif also shows 180 frames and converts to jxl as expected.

**Comment by jendalinda** [comment]
The file is simply truncated. IEND does not exist at all and the last fdAT chunk has incorrect size.

**Comment by TacoCake** [comment]
> Is the APNG you attached modified?  I notice that the GIF has 180 frames, yet the originally attached APNG only has 35 frames.

Not that I know of, perhaps it didn't convert to APNG correctly.

> Converting the GIF to APNG using ezgif also shows 180 frames and converts to jxl as expected.

>The file is simply truncated. IEND does not exist at all and the last fdAT chunk has incorrect size.

Hmm, well that confirms it, if you managed to correctly convert it using ezgif I guess this issue is a user error on my end.

Thanks for the help, everyone, I apologize for wasting your time.

It seems the true solution was this the whole time: https://github.com/libjxl/libjxl/issues/3745#issuecomment-2282272691

**Comment by 0fbcb238c0** [comment]
> Hmm, well that confirms it, if you managed to correctly convert it using ezgif I guess this issue is a user error on my end.

Do you have a backup to confirm the validity of the file?
I do not think a broken file like this is necessarily user error. A file being broken like this may stem from many reasons.

> It seems the true solution was this the whole time: [#3745 (comment)](https://github.com/libjxl/libjxl/issues/3745#issuecomment-2282272691)

No, if the APNG is broken then a newer release will very likely not fix this issue.
Although I do not know if re-converting to JXL is even worth it if the source file is not intact.

**Comment by TacoCake** [comment]
> Do you have a backup to confirm the validity of the file?

I only have the original GIF for this one file, don't know if the others I have are broken.

> No, if the APNG is broken then a newer release will very likely not fix this issue.

Some of the APNG files I have convert successfully with the build straight from source. Which means this is most likely an issue that I will only have with this file, because it is broken.

> Although I do not know if re-converting to JXL is even worth it if the source file is not intact.

This is a very valid point, might be worth it to hunt down the originals then.

Anyway, as for me, this issue can be considered closed.

**Comment by jonnyawsom3** [comment]
I somehow missed this issue, but you were close with the missing IEND meaning end of file. 
Browsers are meant to do progressive decoding, so they're made to handle partial and truncated files until the rest downloads. Most software just tries to load it all at once, and can fail or error when it tries to load the non-existent end.
I'm honestly surprised ffmpeg didn't complain, but usually truncated PNGs can load fine, just with the missing data shown as black, or in this case it could be the previous frame through transparency so no actual data is missing.

I was going to say maybe EzGIF tried to optimize the file by removing duplicate frames, but the download got interrupted... Not sure, could be anything.

I'll finish off by saying, GIF > APNG > JXL could actually be better than GIF > JXL, because APNG optimizers/makers will use the transparency and variable frame sizes which JXL can take advantage of. Currently cjxl does very basic animated encoding, just copying whatever the input was frame by frame, in the future it will do the tricks of [APNGopt](https://sourceforge.net/projects/apng/files/APNG_Optimizer/) and more.
