### ISSUE TITLE
Failure to build tools/benchmark/benchmark_codec_avif.cc under Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by bobfriesenhahn** [libjxl/libjxl#3753]
**Describe the bug**

Libjxl and submodules are updated to the latest as of August 15, 2024.  The tools/benchmark/benchmark_codec_avif.cc source file fails to compile due to some incompatibility with libavif.  Libjxl was previously compiled successfully on July 14, 2024.

**To Reproduce**

The build is done in a 'build' subdirectory using

```
cmake -DCMAKE_INSTALL_RPATH=/usr/local/lib -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF ..
```

**Expected behavior**

I expect the software to compile (as it used to do).

**Screenshots**

```
[ 97%] Building CXX object tools/CMakeFiles/benchmark_xl.dir/benchmark/benchmark_codec_avif.cc.o
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc: In function ‘jxl::Status jpegxl::tools::{anonymous}::SetUpAvifColor(const jxl::ColorEncoding&, bool, avifImage*)’:
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc:129:31: error: void value not ignored as it ought to be
  129 |         avifImageSetProfileICC(image, color.ICC().data(), color.ICC().size()));
      |                               ^
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc:23:51: note: in definition of macro ‘JXL_RETURN_IF_AVIF_ERROR’
   23 |     avifResult jxl_return_if_avif_error_result = (result);                     \
      |                                                   ^~~~~~
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc: In member function ‘jxl::Status jpegxl::tools::AvifCodec::Compress(const string&, const jxl::CodecInOut*, jxl::ThreadPool*, std::vector<unsigned char>*, jpegxl::tools::SpeedStats*)’:
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc:313:60: error: void value not ignored as it ought to be
  313 |         JXL_RETURN_IF_AVIF_ERROR(avifRGBImageAllocatePixels(&rgb_image));
      |                                                            ^
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc:23:51: note: in definition of macro ‘JXL_RETURN_IF_AVIF_ERROR’
   23 |     avifResult jxl_return_if_avif_error_result = (result);                     \
      |                                                   ^~~~~~
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc: In member function ‘jxl::Status jpegxl::tools::AvifCodec::Decompress(const string&, jxl::Span<const unsigned char>, jxl::ThreadPool*, jxl::CodecInOut*, jpegxl::tools::SpeedStats*)’:
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc:382:60: error: void value not ignored as it ought to be
  382 |         JXL_RETURN_IF_AVIF_ERROR(avifRGBImageAllocatePixels(&rgb_image));
      |                                                            ^
/home/bfriesen/src/libjxl/tools/benchmark/benchmark_codec_avif.cc:23:51: note: in definition of macro ‘JXL_RETURN_IF_AVIF_ERROR’
   23 |     avifResult jxl_return_if_avif_error_result = (result);                     \
      |                                                   ^~~~~~
```

**Environment**
 - OS: Ubuntu 22.04 LTS
 - Compiler version: GCC 11.4.0
 - CPU type: x86_64
 - cjxl/djxl version string: Unknown

**Additional context**

Installed Libavif version is 0.9.3-3

**Comment by Traneptora** [comment]
libavif 1.0.0 is ABI-incompatible with versions prior to 1.0.0, which was released August 2023, and promises more stability going forward:

https://groups.google.com/a/aomedia.org/g/av1-discuss/c/wZZPG5b-BgA

**Comment by bobfriesenhahn** [comment]
> libavif 1.0.0 is ABI-incompatible with versions prior to 1.0.0, which was released August 2023, and promises more stability going forward:

That is interesting.  Has a policy decision been made to no longer support the libraries distributed with major Linux distributions (requiring building several/many libraries from source code), or will this glitch be repaired?

Cmake says that the build is 97% complete and this seems to be just a test program.  The level of completion suggests that libjxl itself still compiles.

**Comment by bobfriesenhahn** [comment]
I was able to avoid the issue by adding this CMake option:

```
-DJPEGXL_ENABLE_BENCHMARK=OFF
```

**Comment by mo271** [comment]
I suppose we should specify more precisely which version we require for building the benchmark

**Comment by Traneptora** [comment]
This is a side effect of 5df155d975bd8ecf091f2b808d41cdd1f37e09b8. I could add an #ifdef guard for this, if necessary.

**Comment by mo271** [comment]
> This is a side effect of [5df155d](https://github.com/libjxl/libjxl/commit/5df155d975bd8ecf091f2b808d41cdd1f37e09b8). I could add an #ifdef guard for this, if necessary.

yes, please! Thanks for looking into it.
