### ISSUE TITLE
Windows Static Releases Aren't Static

### ISSUE THREAD

**Issue by jonnyawsom3** [libjxl/libjxl#3755]
0.8, 0.7 and 0.6 releases only have dynamically linked builds mislabelled as static, with the most recent 0.8.3 and 0.9.3 releases missing binaries entirely

0.8.2 'Static' release contains DLLs and cjxl fails to run without them
![image](https://github.com/user-attachments/assets/ac5f9ae9-c91b-4688-a731-83c6dc7761c7)

**Comment by kleisauke** [comment]
This was fixed with commit 21013f4d2877b681b43d822735347fda16530beb, but I'm unsure if it justifies a backport.

**Comment by mo271** [comment]
new versions will have static releases
