### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ronnie187212** [libjxl/libjxl#3764]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or example input/output images to help explain your problem.

**Environment**
 - OS: [e.g. Windows]
 - Compiler version: [e.g. clang 11.0.1]
 - CPU type: [e.g. x86_64]
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]]

**Additional context**

**Comment by CrushedAsian255** [comment]
What? Was this a mistake?

**Comment by CrushedAsian255** [comment]
what

**Comment by CrushedAsian255** [comment]
fair
