### ISSUE TITLE
Inquiry Regarding 16-bit RGB Image Compression Using JPEG-XL

### ISSUE THREAD

**Issue by VincentChandelier** [libjxl/libjxl#3787]
I am currently working on a comparative analysis of JPEG-XL and other image compression software. As part of my project, I need to save a 10-bit RGB image to a PNG file and then compress it using JPEG-XL. At present, I am saving the 10-bit RGB image as a 16-bit RGB PNG image and then encoding it using the following command:

```bash
cjxl -e 10 -q 98 input.png output.jxl
```

Subsequently, I am decoding the compressed file with:

```bash
djxl output.jxl dec.png
```

However, I have encountered an issue wherein the decoded file is being encoded as an 8-bit PNG image, resulting in incorrect output. 

Could you please advise on the correct procedure to use JPEG-XL for compressing and decoding 16-bit RGB images? Your expertise in this matter would be greatly appreciated, as it is crucial for the accurate completion of my project.

Thank you for your time and assistance.

**Comment by 0fbcb238c0** [comment]
Try 
```
--bits_per_sample=N
    Sets the output bit depth. The value 0 (default for PNM) means the original (input) bit depth.
    The value -1 (default for other codecs) means it depends on the output format capabilities
    and the input bit depth (e.g. decoding a 12-bit image to PNG will produce a 16-bit PNG).
```

**Comment by jonsneyers** [comment]
Can you paste the output of `identify input.png` and `jxlinfo output.jxl`?

Normally if the input is a 16-bit png, cjxl should produce a jxl file tagged accordingly, and djxl should decode it to a 16-bit png again. So this is either a bug in cjxl/djxl, or your input image is not actually 16-bit to begin with...

Also note that if you do lossy compression, you have to make sure that the input is encoded correctly, i.e. tagged with the correct color space, and in case of PNG, when storing 10-bit images, the padding should be in the lsb, not in the msb (that is, you still need to use the full range of 0 to 65535). If the PNG does not look correct when viewed in, say, a web browser, then you're doing something wrong.

**Comment by VincentChandelier** [comment]
I use 16 bit data https://imgsaver.com/images/2023/10/03/16bit.png for JPEG XL encoding and decoding, which can be run successfully, and the decoded image can also be displayed normally. This shows that JPEG XL is able to correctly encode and decode 16-bit PNG files.

Because JPEG XL does not support YUV 420 bit image data input, I manually converted the 8192x6192 YUV420 10bit file into BT 601 full range RGB data. I want to save RGB data as PNG image for JPEG XL compression.

I get the RGB data using the following command
```
# img_rgb_data [8192, 6192, 3] range [0, 1023]
img_rgb_data = img_rgb_data.astype(np.uint16)
cv2.imwrite(outputPath, img_rgb_data[...,::-1])
```
I used Windows Resource Viewer to view it, and it showed that the image bit depth is 48bit. But this image cannot be compressed properly by JPEG XL 16bit.

My problem can be easily reproduced using the following code.
```
import cv2
import numpy as np

height, width = 256, 256
rgb_16bit = np.random.randint(0, 1023, (height, width, 3), dtype=np.uint16)
rgb_16bit = rgb_16bit << 6 
cv2.imwrite('output_image.png', rgb_16bit)
```
I understand that "output_image.png" is an RGB image, but this image cannot be correctly encoded and decoded by the JPEG XL reference software for Windows.

**Comment by VincentChandelier** [comment]
> Try
> 
> ```
> --bits_per_sample=N
>     Sets the output bit depth. The value 0 (default for PNM) means the original (input) bit depth.
>     The value -1 (default for other codecs) means it depends on the output format capabilities
>     and the input bit depth (e.g. decoding a 12-bit image to PNG will produce a 16-bit PNG).
> ```

Thank you so much~
Howerver, this command does not work in Windows.

**Comment by VincentChandelier** [comment]
I sincerely ask, does JPEG XL support YUV 420 10bit input? 
When I look at JPEG white paper https://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf , JPEG XL only supports RGB data format.
If it is not supported, do you know how to use YUV 420 10-bit data for JPEG XL compression? 
This is bothering me a lot.

**Comment by VincentChandelier** [comment]
> Can you paste the output of `identify input.png` and `jxlinfo output.jxl`?
> 
> Normally if the input is a 16-bit png, cjxl should produce a jxl file tagged accordingly, and djxl should decode it to a 16-bit png again. So this is either a bug in cjxl/djxl, or your input image is not actually 16-bit to begin with...
> 
> Also note that if you do lossy compression, you have to make sure that the input is encoded correctly, i.e. tagged with the correct color space, and in case of PNG, when storing 10-bit images, the padding should be in the lsb, not in the msb (that is, you still need to use the full range of 0 to 65535). If the PNG does not look correct when viewed in, say, a web browser, then you're doing something wrong.


You are correct; I have attempted three solutions with a quality level of 99 in lossy compression mode:

Solution 1: A 10-bit file is padded with six zero bits in the MSB to extend it to 16 bits and saved as a PNG file. This file is then encoded and decoded using the JPEG XL codec. The reconstructed image is significantly different from the original input.

Solution 2: A 10-bit file is padded with six zero bits in the  LSB to extend it to 16 bits and stored as a PNG. After encoding and decoding with the JPEG XL codec, some differences are observed in the reconstruction results. **Specifically, there are noticeable discrepancies in the blue (B) channel, which I suspect are due to truncation in JPEG XL's internal color conversion process**.

Solution 3: A 10-bit file is scaled by a factor of 65535/1023 to utilize the full range of 16-bit data. However, after encoding and decoding with the JPEG XL codec, unacceptable coding errors occur between the input and the reconstruction.

**Therefore, it is recommended to pad 10-bit files with zeros in the LSB to extend them to 16 bits before encoding with JPEG XL. Nonetheless, this approach may introduce significant errors. I hope that this issue will be resolved soon.**

Thank you all for your responses.

**Comment by jonsneyers** [comment]
In solution 1 you are basically creating a semantically incorrect PNG file that is way too dark (it is only using the range from 0 to 0.0156 instead of using the range from 0 to 1). Doing lossy compression on that with cjxl will remove a lot of information, since the encoder will assume that you cannot see most of the image details anyway in an image that dark.

Getting more error in the B channel than in the R and G channels is expected. It is a consequence of doing perceptual encoding.

I don't really understand why solution 3 doesn't work for you — that's basically the same thing as solution 2 except you're not incorrectly rounding things down by adding zeroes in the lsb (which maps 1023 to 65472 instead of 65535). Solution 3 is the correct way of doing it.

If your input data is 10-bit yuv420, probably the best thing to do is to first convert it to 16-bit rgb (that's a step that should introduce very little precision loss, if done correctly) and then encode it to jxl from there.

**Comment by jonnyawsom3** [comment]
There are a few more things to try too.
You could try using the lossless mode, since it may perform better than extremely high qualities. `-q 100` or `-d 0`
You could try using modular mode `-m 1` with decimal quality levels or distance values `-q 99.99` or `-d 0.1`
You could set `--intensity_target=65504` to make the image brighter to the heuristics. Related issue #1763 
In more recent versions there is also `--disable_perceptual_optimizations` although I'm not sure if it's full implemented yet

**Comment by VincentChandelier** [comment]
Please forgive my oversight and carelessness, Solution2 and solution3 should get similar results.

Judging from the subjective results, the impact of the distortion of the B channel on the results is negligible.

In summary, it is recommended to pad 10-bit files with zeros in the LSB or scale to 65535 to extend them to 16 bits before encoding with JPEG XL.

**Comment by jonnyawsom3** [comment]
Going to link 16-bit padding issues as duplicates, to make finding info easier and avoid repeating info.
