### ISSUE TITLE
check realloc

### ISSUE THREAD

**Issue by maddin200** [libjxl/libjxl#3788]
File:
/libjxl-main/tools/jxlinfo.c: line 389
Code:
  box_index += chunk_size - remaining;
  box_data = realloc(box_data, box_size); // <-- check realloc

**Comment by CrushedAsian255** [comment]
Use pull requests if you want to propose changes to the code base, this is a bug reporting page.

**Comment by mo271** [comment]
Thanks for the proposed changes, @maddin200!
