### ISSUE TITLE
Package also for Ubuntu 24.04

### ISSUE THREAD

**Issue by cmahnke** [libjxl/libjxl#3829]
There are binary releases for Ubuntu 22.04 and 20.04 (like [jxl-debs-amd64-ubuntu-22.04-v0.11.0.tar.gz](https://github.com/libjxl/libjxl/releases/download/v0.11.0/jxl-debs-amd64-ubuntu-22.04-v0.11.0.tar.gz)) but not 24.04.
I know that packaging this isn't your primary fucus and it's expected to be done by vendors, but since you already provide for older versions, this might be added.

**Comment by mo271** [comment]
Thanks for the report!

Fixed by #3831
