### ISSUE TITLE
An incorrect MSVC option is applied in a debug build with static linking

### ISSUE THREAD

**Issue by sincos2854** [libjxl/libjxl#3834]
**Describe the bug**
The `/MT` option is applied instead of the `/MTd` option in a statically linked debug build with Visual Studio.
There is an issue with commit b5cb2464c6d42c3688b4f51e5101adf2ae291bfd(#3803).

**To Reproduce**
Build with the `-DCMAKE_BUILD_TYPE=Debug` option and the `-DJPEGXL_STATIC=ON` option.

**Expected behavior**
The `/MTd` option is applied.

**Environment**
 - OS: Windows 11 23H2
 - Compiler version: cl.exe Version 19.41.34120 for x64
 - CPU type: x86_64

**Additional context**
I have two proposals for a fix.
- Proposal 1
    Replace the following code in `CMakeLists.txt`:

    ```cmake
    set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
    ```

    with:

    ```cmake
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    ```
- Proposal 2
    1. Remove the following code in `CMakeLists.txt`:

        ```cmake
        set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
        ```

    2. Add the `-DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"` option to cmake.exe.

I would prefer Proposal 2 for general purpose.

**Reference**
[CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html)

**Comment by sboukortt** [comment]
Thank you for reporting this. This is deliberate, as it is my understanding that the licencing for the MSVC runtime doesn’t allow redistribution of the debug versions, therefore it was made unconditional to avoid any risk. It was deemed an acceptable compromise given that this only applies to static builds.

Does the use of `/MT` instead of `/MTd` have any other adverse consequences than less debugging information?

**Comment by sincos2854** [comment]
When using the `/MTd` option in a debug build of a project that statically links libjxl, [Linker Tools Error LNK2038](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2038?view=msvc-170) occurs. And the build fails.  

I need to unify all projects to either the `/MT` option or the `/MTd` option.

**Comment by sboukortt** [comment]
Thanks, what do you think of #3837?

**Comment by sincos2854** [comment]
Thanks for your pull request. I tested that code, but it produced the same result as the previous code.  

So, I tested the following code.

```cmake
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded CACHE STRING "")
```

The above code works well for me. This is because by adding the `-DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"` option to cmake.exe, I can override the `CMAKE_MSVC_RUNTIME_LIBRARY` variable.  

How about it?

**Comment by sincos2854** [comment]
The term "overwrite" was an inappropriate expression. When the `-D` option is passed to cmake, a cache entry is created, so the `set` command using `CACHE` does not overwrite it. Therefore, it is convenient for me that the `CMAKE_MSVC_RUNTIME_LIBRARY` variable is a cache entry.

**Comment by sincos2854** [comment]
Thank you very much.
