### ISSUE TITLE
Incomplete manpage for cjxl

### ISSUE THREAD

**Issue by Artoria2e5** [libjxl/libjxl#384]
**Describe the bug**
`doc/man/cjxl.txt` seems to be missing several of the options described in `tools/cjxl.cc`'s `AddCommandLineOptions` function. I noticed this problem when looking for how to use `--resampling`.

I am used to thinking a manpage should show all options and provide more explanation on them than `--help`.

**To Reproduce**
Run `cjxl -v --help`. I suppose the verbosity-gate is what caused the original man-writer to omit these options. I guess the gate can be reflected in the man by putting them in an "Advanced Options" section.

Wait, `cjxl -v -v --help` reveals more? Time for a "Professional options" section.   

**Environment**
It's not useful here, but I'll do it.

 - OS: macOS
 - Compiler version: Apple clang version 12.0.5 (clang-1205.0.22.11)
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl [v0.3.7 | SIMD supported: AVX2,SSE4]

**Additional context**
None for now.

**Comment by Artoria2e5** [comment]
I will try and handle this myself. (Copy-and-pasting documentation should be relaxing, right?) If you don't hear from me in two weeks, feel free to take over.

**Comment by fabiorug** [comment]
are photon noise and how to use/force 8, 10 bits written in the manpage?

**Comment by Artoria2e5** [comment]
Not currently, no. `--override_bitdepth=8` is a thing, so it will be added. From what I can tell it is per-channel

**Comment by fabiorug** [comment]
and whatever iulia comsa added to delta, i don't think there are instructions how to use l 1 p 0 s 1    that short of thing, which parameter are needed, which you can avoid and what are the best to combine.

**Comment by jonsneyers** [comment]
One of the reasons we didn't put many of the encode options in the manpage is that they are still experimental and subject to change. For example for the delta palette approach to near lossless: it is still evolving, including possibly the command line syntax for it. There might also be options that will disappear once we make cjxl libjxl-based (internally using the encode api, instead of directly calling encode functions), since some experimental things will not be worth exposing to the api if we have good enough defaults/heuristics for them.

**Comment by Artoria2e5** [comment]
@jonsneyers, is it okay to put the "verbose" `-v` thing in only instead? That set feels generally less experimental and more useful. Or we can wait till PR time to figure that out.

**Comment by jonsneyers** [comment]
Yes, makes sense to start with the options in the default help screen and the -v one, and wait with the -v -v ones...

**Comment by ValZapod** [comment]
Interesting what -E 3 does and why it is effective. 
https://github.com/libjxl/libjxl/blob/2f872a190f79390ba27a66b2ecb14d51114c12ef/tools/cjxl.cc#L441-L443

**Comment by mo271** [comment]
I think we have now all stuff with `-v -v -v -v`, please reopen if something is missing..
