### ISSUE TITLE
Lossy encoding file size is bigger than lossless

### ISSUE THREAD

**Issue by A-Conrath** [libjxl/libjxl#386]
**Describe the bug**
If I encode a specific file once lossless and once lossy but high quality the resulting lossy file is bigger.

**To Reproduce**
Using this [Picture](https://nilesjohnson.net/images/tiling-overlays.png)
Lossless: cjxl tiling-overlays.png tiling-overlays.d0.0.jxl -d 0.0
Lossy: cjxl tiling-overlays.png tiling-overlays.d0.167.jxl -d 0.167

**Expected behavior**
The lossless file should be bigger because of better quality. But the lossless file size is about 3.05M and the lossy has 4.15M during my tests.

**Environment**
 - OS: Windows 10
 - cjxl version string: JPEG XL encoder v0.5.0 [Scalar] [Link](https://jeremylee.sh/data/bin/jpegxl.7z)

**Additional context**
To get a file with almost same (lossless) size you have to choose -d 0.325
I chose -d 0.167 because this is the value I have found for fractals to be visible lossless, even when I zoom in.

Next scary thing is playing with the encoding effort using same picture.
Default Effort: cjxl tiling-overlays.png tiling-overlays.e7.jxl -d 0.325 -e 7
High Effort: cjxl tiling-overlays.png tiling-overlays.e9.jxl -d 0.325 -e 9

Higher effort should result in smaller file size. But e7 results in 3.05M and e9 in 3.61M. This is weird.
Using lossless, higher effort results in smaller files (as expected).

**Comment by raysar** [comment]
It's not a bug, it's a feature, really :D

Jpeg xl is special, it can use 2 compressions system, varDCT for lossy encoding, and Modular for lossless (and lossy too).
Modular encoding for some picture is VERY good and can be smaller than high quality lossy varDCT. (It is also the same effect in lossy modular, file size can be bigger :D)

If you want a smaller lossy file you can't anticipate it with the encoder for now.
The only solution is to encode in lossless and lossy and choose the smaller with a script.

**Comment by BlueSwordM** [comment]
That is to be expected, especially for this kind of image.

There's an inflexion point at which lossy VARDCT and lossless modular get a similar size.

That is why the limit for -d is 0.1: there's no point going any lower as you will make lossy images bigger than lossless ones.

**Comment by fabiorug** [comment]
it can happen with the some weird images such neurodiverse faces and Roman Empire kings the file at lower distance can get too big because of vardct block selection especially if you aren't using a lossless source.

**Comment by A-Conrath** [comment]
> It's not a bug, it's a feature, really :D
> 
> Jpeg xl is special, it can use 2 compressions system, varDCT for lossy encoding, and Modular for lossless (and lossy too).
> Modular encoding for some picture is VERY good and can be smaller than high quality lossy varDCT. (It is also the same effect in lossy modular, file size can be bigger :D)
> 
> If you want a smaller lossy file you can't anticipate it with the encoder for now.
> The only solution is to encode in lossless and lossy and choose the smaller with a script.

Thank you for the explanation.

**Comment by A-Conrath** [comment]
> That is to be expected, especially for this kind of image.
> 
> There's an inflexion point at which lossy VARDCT and lossless modular get a similar size.
> 
> That is why the limit for -d is 0.1: there's no point going any lower as you will make lossy images bigger than lossless ones.
> 
> This type of image is one of the strongest type of images lossless encoding can deal with as well.

Indeed. I tried converting PNG to BMP and use a 'simple' (ZPAQ) packer and got a even smaller file. (Also faster)

**Comment by A-Conrath** [comment]
> it can happen with the some weird images such neurodiverse faces and Roman Empire kings the file at lower distance can get too big because of vardct block selection especially if you aren't using a lossless source. You can use delta options with the commit Iulia comsa did recently, 2 days ago. The file size will have a bigger size, but that's a compromise. And probably delta don't use block selection or Vardct but is a lossless quantization of residuals so it's done in modular mode.

I wonder what this format (jpegXL) can do in future. Up to now it seems to become a gracefully successor of JPG ;-)

**Comment by A-Conrath** [comment]
May I missed somewhat but I still eager to know why higher effort of compression results in bigger file using the mentioned picture in varDCT-Mode.

**Comment by jonsneyers** [comment]
> May I missed somewhat but I still eager to know why higher effort of compression results in bigger file using the mentioned picture in varDCT-Mode.

Higher effort in lossy mode means two things: more effort spent on entropy coding etc (making files smaller), and more effort spent on perceptual accuracy (making images actually achieve the perceptual distance target that was specified, as opposed to using heuristics and hoping for the best). The latter can lead to smaller or larger files — it's not optimizing for size only, but for quality/size, and for consistency of results. More effort should give more consistent results and also a better bitrate/distortion curve, but it doesn't necessarily give smaller results than faster speeds. Faster speeds get some of their speed from being less perceptually consistent, i.e. closer to what most other encoders like e.g. libjpeg-turbo do (you set a quantizer target but you don't really know how it will look, on some images q70 might be fine while on others it is horrible).

**Comment by A-Conrath** [comment]
> > May I missed somewhat but I still eager to know why higher effort of compression results in bigger file using the mentioned picture in varDCT-Mode.
> 
> Higher effort in lossy mode means two things: more effort spent on entropy coding etc (making files smaller), and more effort spent on perceptual accuracy (making images actually achieve the perceptual distance target that was specified, as opposed to using heuristics and hoping for the best). The latter can lead to smaller or larger files — it's not optimizing for size only, but for quality/size, and for consistency of results. More effort should give more consistent results and also a better bitrate/distortion curve, but it doesn't necessarily give smaller results than faster speeds. Faster speeds get some of their speed from being less perceptually consistent, i.e. closer to what most other encoders like e.g. libjpeg-turbo do (you set a quantizer target but you don't really know how it will look, on some images q70 might be fine while on others it is horrible).

Thx a lot for clarification.
