### ISSUE TITLE
Lossless JPEG transcode is not lossless?

### ISSUE THREAD

**Issue by The0x539** [libjxl/libjxl#3875]
**Describe the bug**
As far as I'm able to observe, output images from lossless JPEG transcode do not exactly match the input. High-frequency areas are covered in slight discrepancies.

**To Reproduce**
```
the0x539@scale $ ls
original.jpg

the0x539@scale $ cjxl original.jpg transcoded.jxl
JPEG XL encoder v0.11.0 4df1e9ec [AVX2,SSE4,SSE2]
Note: Implicit-default for JPEG is lossless-transcoding. To silence this message, set --lossless_jpeg=(1|0).
Encoding [JPEG, lossless transcode, effort: 7]
Compressed to 11509 bytes including container

the0x539@scale $ djxl transcoded.jxl decoded.png
JPEG XL decoder v0.11.0 4df1e9ec [AVX2,SSE4,SSE2]
Decoded to pixels.
800 x 600,  171.103 MP/s [171.10, 171.10], , 1 reps, 32 threads.

the0x539@scale $ imgcmp original.jpg decoded.png
original.jpg and decoded.png differ
```

**Expected behavior**
`original.jpg and decoded.png are identical`.
My testing methodology, including minor variations on it not shared here, behaves as expected for PNG inputs.

**Environment**
 - OS: Windows 11 / WSL 2 / Arch
 - Compiler version: ?
 - CPU type: x86_64
 - cjxl/djxl version string: `cjxl v0.11.0 4df1e9ec [AVX2,SSE4,SSE2]` (see above)

**Additional context**
- I authored `original.jpg` by drawing on a blank canvas in Paint.NET and saving as .jpg - nothing special.
- I first observed this at `-e 10`, but also observe it at levels 1, 5, and 7.
- [original.jpg, transcoded.jxl, and decoded.png](https://github.com/user-attachments/files/17267213/test.image.zip)
- [Source code for `imgcmp`](https://gist.github.com/The0x539/0cf290f30386c846a729285a21c41b4f)

**Comment by 0fbcb238c0** [comment]
The transcoding to JXL is indeed lossless. You can verify it yourself by reconstructing the original JPEG from the JXL using `djxl`. The reconstructed JPEG will be identical to the source JPEG.

**Comment by The0x539** [comment]
Fascinating, thank you. Any clue what's gone awry with my testing methodology? I've also tried decoding the JXL directly using the `jpegxl_rs` crate, which wraps `libjxl`, with similar results.

**Comment by 0fbcb238c0** [comment]
According to the FAQ on the [community page](https://jpegxl.info/resources/faqs.html):
```
Is Lossless JPEG Transcoding really bit-for-bit accurate?

Converting a JPEG to JPEG XL using cjxl and then back to JPEG with djxl results in a bit-identical copy of the original JPEG image. However, it’s important to note JPEG standard leaves room for some interpretation, leading to potential minor variations between different decoders.
```
