### ISSUE TITLE
JxlDecoderSetImageOutBuffer should accept output buffer stride (dstStride) in bytes

### ISSUE THREAD

**Issue by dzeitlin** [libjxl/libjxl#388]
It's very convenient when working with 2D buffer **always accept and support destination STRIDE** everywhere possible.
Example: when decoding two JXL images (let's say 2 map tiles), by using *dstStride* one can stich them together into one output buffer. No redundant copies needed in order to reorg pixels. Of course JxlDecoderSetImageOutBuffer should support `dstStride == 0`, stride was not given and calculate it as it does now, otherwise check `dstStride < minDstStride`, should return `JXL_DEC_ERROR dstStride is too small`. 
Internally `dec_external_image.cc::ConvertToExternal` should accept/support `dstStride` as well for that.

**Comment by deymo** [comment]
You should be able to achieve that by passing the stride in the `align` parameter in `JxlPixelFormat`. It doesn't fail if the "stride" is too small for the xsize, but you can check that `JxlDecoderImageOutBufferSize` returns the expected value if you want to check for strides that are too small.

**Comment by dzeitlin** [comment]
yes you right this code works
```
if (format->align > 1)
    row_size = jxl::DivCeil(row_size, format->align) * format->align;
```
it was confusing, **pixel-format->align** sounds more like stride within the pixel itself (for example decode and embed rgb24 into given rgba32, so called pixel-stride) and not scan line, line stride.
thanks

**Comment by jonsneyers** [comment]
Closing since it seems to be resolved.
