### ISSUE TITLE
docs/encode_effort.md needs updating

### ISSUE THREAD

**Issue by CrushedAsian255** [libjxl/libjxl#3904]
**Is your feature request related to a problem? Please describe.**
The encode_effort.md file has not been updated to take into account the changes to the effort scale in 0.10 (?).

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
Effort 11 requires the allow_expert_options, maybe mention it's not a good idea to use in production (3min+ for 64x64 icons).

**Comment by Galaxy4594** [comment]
I already made an issue here #3517. But it's still annoying how this simple problem hasn't been fixed. 😔
