### ISSUE TITLE
cjxl: apng input "Failed to read image"

### ISSUE THREAD

**Issue by EugeneVert** [libjxl/libjxl#392]
**Describe the bug**

Attempt to encode apng to jxl animation fails with an error

**To Reproduce**
- input (using ImageMagick convert)
```bash
convert -size 1x1 canvas:white 1.png
convert -size 1x1 canvas:black 2.png
convert -delay 10 *.png anim.apng
cjxl anim.apng out.jxl
```
- output
```
JPEG XL encoder v0.5.0 [AVX2,SSE4,Scalar]
libjxl/lib/extras/codec_png.cc:252: JXL_RETURN_IF_ERROR code=1: Decode(bytes, &io->blobs)
libjxl/lib/extras/codec_png.cc:810: JXL_RETURN_IF_ERROR code=1: reader(bytes, is_gray, io)
libjxl/lib/extras/codec_exr.cc:146: JXL_FAILURE: OpenEXR failed to parse input
libjxl/lib/extras/codec.cc:124: JXL_FAILURE: Codecs failed to decode
libjxl/lib/extras/codec.cc:137: JXL_RETURN_IF_ERROR code=1: SetFromBytes(Span<const uint8_t>(encoded), io, pool, orig_codec)
Failed to read image anim.apng.
```

**Environment**
 - OS: Debian 11 (bullseye)
 - Compiler version: Clang 11.0.1
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.5.0 [AVX2,SSE4,Scalar]  https://github.com/libjxl/libjxl/commit/b07df8aa7be4baa19372367aca4f2f59a3d23c01

**Additional context**
- cjxl -h
```
JPEG XL encoder v0.5.0 [AVX2,SSE4,Scalar]
Usage: cjxl INPUT OUTPUT [OPTIONS...]
 INPUT
    the input can be PNG, APNG, GIF, JPEG, EXR, PPM, PFM, or PGX
```
- ldd /usr/bin/cjxl | rg png
```
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f8f82227000)
```

**Comment by raysar** [comment]
That's the same for me with docker for windows:
Works with commit 8f81c4c1 26/06/2021
And did not works with commit a64f5768 09/07/2021

`JPEG XL encoder v0.3.7 [SSE4,Scalar]
Failed to read image ...`

**Comment by EugeneVert** [comment]
Seems to work after #404
