### ISSUE TITLE
Publish binary versions package

### ISSUE THREAD

**Issue by nucliweb** [libjxl/libjxl#395]
With the idea to use it into a `npm` wrapper, like in `image-min` plugins.

There are plans to publish a binary version package for OSX, Windows and Linux in each release?

**Comment by deymo** [comment]
Yes, eventually we want to attach various binary versions to the releases, but we don't have that set up yet.
I've created this for linux-static and Debian packages to start: https://github.com/libjxl/libjxl/pull/406

**Comment by nucliweb** [comment]
Great, I would like to test in in my current environment, Mac OSX

**Comment by eustas** [comment]
You could try https://github.com/eustas/libjxl/suites/3329261054/artifacts/78036931
It is mostly-static linked cjxl/djxl; it is not signed though, so OSX will complain about that.

**Comment by eustas** [comment]
Also I've tried running statically linked linux binaries in scratch docker image. It works and might be easier to run (as OSX does not worry about binaries inside containers, once Docker is setup).

**Comment by nucliweb** [comment]
Hi @eustas 

## Solution

I can run the command removing the `quarentine` attribute.

```bash
xattr -d com.apple.quarantine cjxl
xattr -d com.apple.quarantine djxl
```

## Demo

<img width="1237" alt="Screen Shot 2021-08-13 at 00 52 04" src="https://user-images.githubusercontent.com/1307927/129280110-2c4d718d-5907-46d2-99a6-715ee56f6b0c.png">

## Next steps

I will test to convert some images and play with the settings.

**Comment by joppuyo** [comment]
I released static cjxl and djxl Mac binaries for v0.5.0 [here](https://github.com/joppuyo/jpeg-xl-static-mac/releases/tag/v0.5.0-static-2). I had to make a few changes to make the static compilation for Mac work:

1. Remove `-static -static-libgcc -static-libstdc++` from the linker flags like @eustas did
2. Uninstall Mono before compilation. With Mono installed the compiler was picking up some really old libjpeg version, the problem was the same as [described here](https://github.com/openMVG/openMVG/issues/1349).

**Comment by shvchk** [comment]
I've created a [PPA with packages for Ubuntu](https://launchpad.net/~shevchuk/+archive/ubuntu/jpeg-xl) (Focal and Hirsute for now). Debian packaging is basically copypaste from upstream (this repo).

To install jpeg-xl on Ubuntu using this PPA:
- Add PPA: `sudo add-apt-repository ppa:shevchuk/jpeg-xl`
- Update package info: `sudo apt update`
- Install jpeg-xl: `sudo apt install jxl`

**Comment by joppuyo** [comment]
Looks like the [latest release v0.6.1](https://github.com/libjxl/libjxl/releases/tag/v0.6.1) contains static binaries for Linux and Windows. For some reason, they were missing in v6.0.0.

Hopefully, we'll get a Mac build at some point in the future 🙂

**Comment by deymo** [comment]
there was a config issue in the action runners for v0.6 that made them fail to upload the artifacts to the release. I can re-run those but now that people should use v0.6.1 instead it doesn't make sense.

We don't have a mac build yet, but that could be added to github actions afaik.

**Comment by mo271** [comment]
We have windows and linux binaries. Having signed macOS binaries seems out of scope.

**Comment by eugenesvk** [comment]
Can you add unsigned macOS binaries?

**Comment by gingerbeardman** [comment]
unsigned static macos binaries would be ideal.
