### ISSUE TITLE
Scanlines order request

### ISSUE THREAD

**Issue by Sora1551** [libjxl/libjxl#3974]
Here:
https://github.com/libjxl/libjxl/blob/b9e1c0897e75390f07f0a103fe0cc79ee0789f41/doc/format_overview.md?plain=1#L219
indicate that we can permut scanlines order. I wander know how to modify the order? (e.g. left to right, top to bottom)
 Thanks.

**Comment by Traneptora** [comment]
This is the order of the groups, not the order of the scanlines. Groups are 256x256 (usually) tiles that typically go in raster order, but you can have the groups be sent in any order.

To do this using the CLI, you can use the `--progressive` flag, which causes it to go from center-out in a spiral. With the API, you can do this with [JXL_ENC_FRAME_SETTING_GROUP_ORDER](https://libjxl.readthedocs.io/en/latest/api_encoder.html#_CPPv4N24JxlEncoderFrameSettingId33JXL_ENC_FRAME_SETTING_GROUP_ORDERE) as a Frame Setting flag. 

The library currently doesn't support declaring arbitrary group order, just these two modes. The formats supports any permutation of the the groups (i.e. any order) but there's no way at the moment to make libjxl encode it. If you really need this feature you can use [libhydrium](https://github.com/Traneptora/hydrium/) but it's not a mature library yet.

**Comment by Sora1551** [comment]
@Traneptora got it thank you.
