### ISSUE TITLE
libjxl_dec.so.0 => not found

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#399]
Hello,

I tried to install latest main branch on Gentoo Linux and I have got following warning:
```
 * QA Notice: Unresolved soname dependencies:
 *
 *      /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jxl.so: libjxl_dec.so.0
 *
```

eog cannot open JXL images (it used gdk-pixbuf plugins).

The plugin expect some libjxl_dec.so.0 file which is missing.
```
ldd /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jxl.so
        linux-vdso.so.1 (0x00007ffff79f8000)
        libjxl_dec.so.0 => not found
```

**Comment by deymo** [comment]
oooh, right, we don't install `libjxl_dec.so`. We need to use libjxl.so there instead.
