### ISSUE TITLE
Lossless images are not actually lossless

### ISSUE THREAD

**Issue by CrushedAsian255** [libjxl/libjxl#4026]
**Describe the bug**
Lossless encoding using `-d 0 -e 1` sometimes generates artifacts and sometimes generates a completely corrupted file. 

**To Reproduce**
Download and extract the below ZIP and encode the PNG files using `cjxl -d 0 -e 1`, `glitched_image.png` will encode but will have an odd artifact and `corrupted_image.png` will encode into a completely corrupted image. Encodes using `JPEG XL encoder v0.12.0 24e12baf [NEON,NEON_WITHOUT_AES]` are given in the ZIP. 

**Expected behavior**
The images get lossless converted

**Screenshots**
[Archive.zip](https://github.com/user-attachments/files/18223978/Archive.zip)

**Environment**
 - OS: [e.g. Windows] `OrbStack Ubuntu VM on MacOS`
 - Compiler version: [e.g. clang 11.0.1] `clang version 19.1.1 (1ubuntu1)` 
 - CPU type: [e.g. x86_64] `aarch64`
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]] `JPEG XL encoder v0.12.0 24e12baf [NEON,NEON_WITHOUT_AES]`

**Comment by CrushedAsian255** [comment]
Found by @maynguene_banana on discord

**Comment by Orum** [comment]
I originally found the problematic image/settings, and though I don't have much to add, I can confirm it occurs on older libjxl versions and other architectures.  I'm currently on: `cjxl v0.10.3 4a3b22d2 [AVX2,SSE4,SSE2]`
