### ISSUE TITLE
Crash during encode/write when the input is a png image created by the Qt/C++ API

### ISSUE THREAD

**Issue by dbermond** [libjxl/libjxl#405]
**Describe the bug**
jxl encode/write crashes on the `cjxl` command when the input is a png image that was generated by the Qt/C++ screenshot API. No output image is produced.

**To Reproduce**
1) take a screenshot with the Qt/C++ API and save it as a png image:
```C++
// Qt/C++: grab a screenshot (X11) and save it to png format
QPixmap pixmap(qApp->primaryScreen()->grabWindow(0).copy());
pixmap.save("screenshot.png", "PNG");
```

2) encode/write the taken screenshot with the `cjxl` command:
```
$ cjxl screenshot.png screenshot.jxl 
JPEG XL encoder v0.5.0 [AVX2,SSE4,SSSE3]
/build/libjxl-git/src/libjxl/lib/extras/codec_png.cc:520: PNG: no color_space/icc_pathname given, assuming sRGB
Read 1920x1200 image, 57.4 MP/s
Encoding [VarDCT, d1.000, squirrel], 4 threads.
/build/libjxl-git/src/libjxl/lib/jxl/enc_ac_strategy.h:52: JXL_DASSERT: masking_field_row[by * masking_field_stride + bx] > 0
Illegal instruction (core dumped)
```

**Expected behavior**
I expected the `cjxl` command to encode/write a jxl image from the png input image that was created with the Qt/C++ API without any crash.

**Screenshots**
Not applicable.

**Environment**
 - OS: Arch Linux x86_64
 - Compiler version: gcc 11.1.0
 - CPU type: x86_64
 - cjxl/djxl version string: JPEG XL encoder v0.5.0 [AVX2,SSE4,SSSE3] (also tested with latest git master commit a812d5c361d43ca7f48647513da07cc28643a655 with the same result)
 - Qt: tested with both Qt5 and Qt6 with the same result (versions 5.15.2+kde+r211 and 6.1.2 respectively)

**Additional context**
This was discovered using [qt-jpegxl-image-plugin](https://github.com/novomesk/qt-jpegxl-image-plugin). When using the plugin to directly write the jxl image on the Qt/C++ API, the encode/writing crashes:

```C++
// Qt/C++: grab a screenshot (X11) and save it directly to jxl format through the plugin
QPixmap pixmap(qApp->primaryScreen()->grabWindow(0).copy());
pixmap.save("screenshot.jxl", "JXL"); // crash
```

Console output:
```
/build/libjxl/src/libjxl/lib/jxl/enc_ac_strategy.h:52: JXL_DASSERT: masking_field_row[by * masking_field_stride + bx] > 0
Illegal instruction (core dumped)
```

So, maybe the png format is not relevant here as an input.

Please see the [reference issue there](https://github.com/novomesk/qt-jpegxl-image-plugin/issues/17).

**Comment by dbermond** [comment]
Here is an [attached image](https://user-images.githubusercontent.com/16004942/128092708-0546e907-0b83-4304-b100-126a274c59e4.png) that can be used reproduce the `cjxl` crash:

Generated by Qt/C++ API like in the example above.

**Comment by TheHardew** [comment]
It seems to work if you compile in Release mode, similarly to #251, but I'm not sure if the images created this way are valid. I can decode them fwiw.

**Comment by dbermond** [comment]
@TheHardew True, thank you. Building with the `Release` CMake build type eliminates the issue, so it looks like to be a flags problem. The Arch package is built with the `None` CMake build type.

By investigating further, the cause seems be related to the `NDEBUG` definition (`-DNDEBUG` is added by default by the `Release` CMake build type). I've added this to the Arch packages and everything seems fine.

As a suggestion to the developers, I think that it would be good if this could be detected by the tests, since all the 1300+ tests passes without any problems. And if possible, it would also be good to allow any CMake build type to be free of issues like this :)

**Comment by veluca93** [comment]
Using NDEBUG only disables the assertion and doesn't fix the underlying cause, so I think we should still look into this.

**Comment by dbermond** [comment]
Thank you for investigating this :)

**Comment by fabiorug** [comment]
I have a problem with files that have written at in the filename but only with the .png file type? It seems. I Have windows 7.
Settings: 
for %i in (D:\BDS\pngdesktop\*.png) do cjxl -s 2 -d 1.238 --use_new_heuristics --gaborish=0 --epf=2 --patches=0 --dots=1 %i %i.jxl
I have standard 0.5.0 compiled by others, an user Raysar on Discord, I got.
So I don't know if is a PNG bug file or a cmd Windows 7 and probably older bug.
On linux nobody ever reported this problem. (Neither with older builds 0.3.7 and lower).

**Comment by sboukortt** [comment]
Preliminary investigation: for that screenshot image, when `AdaptiveQuantizationImpl::ComputeTile` is called with `rect = 8×8+0+24`, for `y = 0` and `x = 0`, we have `aq_map_row[x]` equal to infinity here:

https://github.com/libjxl/libjxl/blob/f99f3395c197b00726dc1c1d4a64d81d9f704c9c/lib/jxl/enc_adaptive_quantization.cc#L565-L571

And from there, `ComputeMaskForAcStrategyUse(inf) = 0`. Now going to search where the infinite value is coming from.

@fabiorug Maybe it is simpler if we only discuss one issue at once. Could you perhaps open a separate issue for the filename problem? Thanks.
