### ISSUE TITLE
cjxl illegal instruction when using vardct with extra options

### ISSUE THREAD

**Issue by Sci3ntia** [libjxl/libjxl#407]
**Describe the bug**
when compressing a png with `cjxl -E 3 -s 9 -e 9 "DNA_Structure+Key+Labelled.pn_NoBB.png" "DNA_Structure+Key+Labelled.pn_NoBB.jxl"` encoding proceeds as normal but soon after produces this output
`/build/yay/libjxl-git/src/libjxl/lib/jxl/enc_ac_strategy.h:52: JXL_DASSERT: masking_field_row[by * masking_field_stride + bx] > 0
Illegal instruction (core dumped)`

**To Reproduce**
install and compile libjxl-git with yay (may not be needed but that's how I did my compilation and may be relevant)
download https://cdn.discordapp.com/attachments/806898911091753051/872287538717552740/DNA_StructureKeyLabelled.pn_NoBB.png to the current dir
run `cjxl -E 3 -s 9 -e 9 "DNA_Structure+Key+Labelled.pn_NoBB.png" "DNA_Structure+Key+Labelled.pn_NoBB.jxl"`

**Expected behavior**
cjxl outputs a jxl file

**Screenshots**
![image](https://user-images.githubusercontent.com/46354004/128107111-6e3fcc4d-7199-425b-a59c-882a5ab3c40d.png)

**Environment**
 - OS: linux (arch)
 - Compiler version: clang version 12.0.1 Target: x86_64-pc-linux-gnu Thread model: posix
 - CPU type: x86_64 zen+
 - cjxl/djxl version string: JPEG XL encoder v0.5.0 [AVX2,SSE4,SSSE3,Scalar]

**Additional context**
this build was compiled with the yay aur helper for arch linux, this may or may not be topical

**Comment by Sci3ntia** [comment]
Important extra info: only happens on vardct, seemingly not modular, only happens on vardct at speeds 7 and up, only happens on this particular image and not any others I have tried so far.

**Comment by TheHardew** [comment]
#405, change PKGBUILD to compile in Release mode or add `-DNDEBUG`.

**Comment by TheHardew** [comment]
Btw, `--speed` was changed to `--effort`, so `-e 9` is sufficient and `-I` is used in modular encoding only.

**Comment by Sci3ntia** [comment]
thanks so much, recompiling now

**Comment by Sci3ntia** [comment]
recompiled and it works fine, closing

**Comment by jonsneyers** [comment]
Reopening since hitting a debug assert is still a bug.
Building in release mode will hide the error message but it still needs to be investigated why the assert fails.

**Comment by jyrkialakuijala** [comment]
https://github.com/libjxl/libjxl/pull/412 has a fix

**Comment by sboukortt** [comment]
@jyrkialakuijala I can confirm that #412 resolves part of the problem, however there remains another part in that this code seems to read in-buffer but uninitialized values from `diff_buffer`:

https://github.com/libjxl/libjxl/blob/f99f3395c197b00726dc1c1d4a64d81d9f704c9c/lib/jxl/enc_adaptive_quantization.cc#L553-L560

Initializing `diff_buffer` to zero in `PrepareBuffers` seems to solve this. Does that seem like an appropriate thing to do?

**Comment by veluca93** [comment]
> @jyrkialakuijala I can confirm that #412 resolves part of the problem, however there remains another part in that this code seems to read in-buffer but uninitialized values from `diff_buffer`:
> 
> https://github.com/libjxl/libjxl/blob/f99f3395c197b00726dc1c1d4a64d81d9f704c9c/lib/jxl/enc_adaptive_quantization.cc#L553-L560
> 
> Initializing `diff_buffer` to zero in `PrepareBuffers` seems to solve this. Does that seem like an appropriate thing to do?

Mhh, I don't think so...

**Comment by jyrkialakuijala** [comment]
I don't want to zero-initialize because it increases memory bandwidth use. Memory bandwidth use tends to impact system performance even when it is not a big factor in a single threaded benchmark. Please file a new bug for the uninitialized read along with instructions on how to reproduce/test.

**Comment by veluca93** [comment]
Zero initializing wouldn't be an issue as the diff_buffer is pretty small. Having said that, I don't think we should zero initialize because that doesn't really fix the issue.
