### ISSUE TITLE
uninitialized read in masking estimation

### ISSUE THREAD

**Issue by jyrkialakuijala** [libjxl/libjxl#413]
uninitialized read in masking estimation

```
 if (y % 4 == 3) { 
   float* row_dout = pre_erosion[thread].Row((y - y_start) / 4); 
   for (size_t x = 0; x < (x1 - x0) / 4; x++) { 
     row_dout[x] = (row_out[x * 4] + row_out[x * 4 + 1] + 
                    row_out[x * 4 + 2] + row_out[x * 4 + 3]) * 
                   0.25f; 
   } 
 } 
```

Sami to add steps to reproduce the behavior -- after which assign back to me, I'm comfortable working on this part of the code.

Would be great to find out when was this introduced if easily possible.

**Comment by sboukortt** [comment]
My bad, it seems that it was a false alarm due to an indexing bug in the code I used to detect this itself. There is no such issue after all.
