### ISSUE TITLE
GIMP file-jxl plugin: image imported incorrectly

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#417]
Hello,

when I open [jpegxl-logo.jxl](https://github.com/novomesk/qt-jpegxl-image-plugin/blob/main/testfiles/jpegxl-logo.jxl) image in GIMP 2.10.24, the image looks too transparent:
![gimp1](https://user-images.githubusercontent.com/52529860/128533673-8a397be2-b7b3-49e8-839d-2d79556d7136.png)

When converted to png via djxl, it looks this way:
![gimp2](https://user-images.githubusercontent.com/52529860/128533788-3ed8ed8d-045f-4c78-aae6-8e949e36664f.png)

**Comment by novomesk** [comment]
Possibly related issue: https://gitlab.com/wg1/jpeg-xl/-/issues/234

**Comment by jonsneyers** [comment]
Supposedly fixed, please reopen if needed.

**Comment by rubyFeedback** [comment]
Is there an educated guess when gimp will allow us to use jxl? Right now it all seems to be "it is beta", almost since 2 years by now at this point.

**Comment by novomesk** [comment]
You can use GIMP 2.99.10 today where JXL works out of box in Windows build or in Linux flatpak.
It is called Beta but it works.

Or you can use the old GIMP 2.10.x and manually install file-jxl plug-in afterwards.
