### ISSUE TITLE
Accept JPEG XL files as input to cjxl

### ISSUE THREAD

**Issue by Fraetor** [libjxl/libjxl#430]
**Is your feature request related to a problem? Please describe.**
As JPEG XL supports bunch of stuff that makes it a great intermediate format, it would make sense if it was supported by cjxl for recompression. This would be especially useful for testing different compression levels, and particularly for testing generation loss.

**Describe the solution you'd like**
cjxl able to read in .jxl files. I think it would have to be read in as pixels for the lossy compression, but I may well be incorrect there, and something fancy (as is done for JPEG) could be done to make recompression quicker.

**Describe alternatives you've considered**
They can currently be converted to png by djxl then used in cjxl. While this works, it doesn't support images above the capabilities of PNG (multi layer / animated), and adds an extra step.

**Additional context**
It seems a bit silly that the encoder's own format isn't supported, especially if you are trying to encourage other programs to include JPEG XL support.

Fixed by #2444

**Comment by Joachim-Otahal** [comment]
I second that request! After running cjxl on large collections (-d 0 -e 8) it sometimes depends whether -P 0 and / or -g 3 was included. If I could run it on already encoded .jxl files to check whether it could improve with those options it would save me getting the old original .gif etc back from the snapshot to rerun for optimization tests.
IMO somewhat related to https://github.com/libjxl/libjxl/issues/727 and https://github.com/libjxl/libjxl/issues/426

**Comment by mo271** [comment]
also see https://github.com/libjxl/libjxl/issues/871
