### ISSUE TITLE
Allow explicit targeting to psnr/ssim/etc.

### ISSUE THREAD

**Issue by DamonHD** [libjxl/libjxl#436]
**Is your feature request related to a problem? Please describe.**
As well as targeting size/bpp, it would also be useful to target a specified fidelity type and value.

**Describe the solution you'd like**
Would like a  --target_((psnr)|(ssim)|...)=X option to help slot in to static (Web site) image generation.
cwebp has an option that works nicely for me right now, see
https://www.earth.org.uk/note-on-site-technicals-51.html#2021-08-12

**Describe alternatives you've considered**
Writing my own script loop (again) around one of the other --target_XXXs.

**Additional context**
https://www.earth.org.uk/note-on-site-technicals-51.html#2021-08-12

**Comment by BlueSwordM** [comment]
I mean, you don't really need to target psnr and ssim, since they are not very good metric psycho visually speaking.

Butteraugli distance(-d) already serves the purposes you want while being much more accurate to human perception.

**Comment by jloqfjgk** [comment]
PSNR is not a good metric for image compression. As mentioned by the above comment, you can use the `-d` parameter, which uses Butteraugli:
```
 -d maxError, --distance=maxError
    Max. butteraugli distance, lower = higher quality. Range: 0 .. 15.
    0.0 = mathematically lossless. Default for already-lossy input (JPEG/GIF).
    1.0 = visually lossless. Default for other input.
    Recommended range: 0.5 .. 3.0.
```

P.S. This is how @jonsneyers (co-creator of JPEG XL) describe PSNR (on [JPEG XL Discord server](https://discord.gg/DqkQgDRTFu)):
> PSNR correlates with human perception like the weight of a painting in kilograms correlates to its artistic value.
> It reflects the amount of paint that went into the painting, but it doesn't care about where what color went. Pretty accurate analogy.

**Comment by DamonHD** [comment]
I hear you, but where existing systems have PSNR available and not others, eg on older distros, and they work, then it can be best to continue with what there is.

**Comment by BlueSwordM** [comment]
Uhhh, `-d X` is literally a JXL command.
If you have CJXL installed, you instantly have it available.

In fact, `-d` as said before is literally a target-quality mode, similar to "target psnr/ssim", but a lot better.

**Comment by DamonHD** [comment]
OK, thanks, good point.

For me that does mean finding or bulding a butteraugli distance tool on older systems for non-JXL inputs, but it may be do-able.

**Comment by jonsneyers** [comment]
If you build libjxl from sources, it will automatically build the standalone `butteraugli_main` tool.

**Comment by DamonHD** [comment]
OK, sounds promising.

**Comment by sboukortt** [comment]
Note that `butteraugli_main` is built only if `-DJPEGXL_ENABLE_DEVTOOLS=YES` is passed to CMake (or edited in `CMakeCache.txt`):

https://github.com/libjxl/libjxl/blob/3f663b602625e7f6595b1a3e7a18a87e618d05e3/tools/CMakeLists.txt#L161-L171

`ssimulacra_main` implements another metric, namely [SSIMULACRA](https://github.com/cloudinary/ssimulacra) (as you probably guessed), which you might also be interested in.

**Comment by DamonHD** [comment]
Incidentally (still learning the tools here) when I try and use --target_size from a .jpg it seems to actually ignore the --target_size in effect:

```
% cjxl -v -s 9 --target_size=8200 img/RPiServer/RPi-in-box-800w.jpg
JPEG XL encoder v0.5.0 [AVX2,SSE4]
No output file specified.
Encoding will be performed, but the result will be discarded.
Butteraugli distance 4.054 yields  14311 bytes, 0.594 bpp.
Butteraugli distance 7.076 yields  14311 bytes, 0.594 bpp.
Butteraugli distance 12.349 yields  14311 bytes, 0.594 bpp.
Butteraugli distance 16.000 yields  14311 bytes, 0.594 bpp.
Butteraugli distance 16.000 yields  14311 bytes, 0.594 bpp.
Butteraugli distance 16.000 yields  14311 bytes, 0.594 bpp.
Butteraugli distance 16.000 yields  14311 bytes, 0.594 bpp.
Read 800x241 image, 26.9 MP/s
Encoding [Container | JPEG, lossless transcode, tortoise | JPEG reconstruction data], 2 threads.
Compressed to 14311 bytes (0.594 bpp).
```

If I first convert the source jpg to a png then use otherwise the same argument, all is as I expect:

```
% convert img/RPiServer/RPi-in-box-800w.jpg ~/tmp/test.png 
% cjxl -v -s 9 --target_size 8200 ~/tmp/test.png ~/tmp/test.jxl
JPEG XL encoder v0.5.0 [AVX2,SSE4]
Butteraugli distance 4.054 yields   8159 bytes, 0.339 bpp.
Butteraugli distance 4.034 yields   8172 bytes, 0.339 bpp.
Butteraugli distance 4.020 yields   9046 bytes, 0.375 bpp.
Butteraugli distance 4.435 yields   8356 bytes, 0.347 bpp.
Butteraugli distance 4.519 yields   6949 bytes, 0.288 bpp.
Butteraugli distance 3.830 yields   8514 bytes, 0.353 bpp.
Butteraugli distance 3.976 yields   9063 bytes, 0.376 bpp.
Read 800x241 image, 10.4 MP/s
Encoding [VarDCT, d4.034, tortoise], 2 threads.
Compressed to 8172 bytes (0.339 bpp).
```

So maybe I'm misunderstanding even more than I thought...

**Comment by veluca93** [comment]
That's a bug of our command line - we should fix it, but in the meantime, you could pass `-j` to fix the issue.

**Comment by DamonHD** [comment]
Thanks!

**Comment by veluca93** [comment]
> Thanks!

https://github.com/libjxl/libjxl/pull/442

This should do it...

**Comment by jonsneyers** [comment]
Since we already have `--distance` which does encode to a specified perceptual target, I think that is enough.

We _could_ add different metrics to optimize for, but I don't think we want to focus on that, especially since we don't really have a metric available that will work better (psnr/ssim will not). So I'm closing this one for now.

**Comment by eugenesvk** [comment]
> since we don't really have a metric available that will work better

Now that you have such a metric ([ssimulacra2](https://github.com/cloudinary/ssimulacra2)), would it make sense reopening and maybe think about adding this as a second option to `-d`?

**Comment by DamonHD** [comment]
I'd vote for that, strongly!

Rgds

Damon
