### ISSUE TITLE
enc_modular.cc:506: JXL_ASSERT: !fp

### ISSUE THREAD

**Issue by dlemstra** [libjxl/libjxl#447]
**Describe the bug**
When encoding a lossless image with the `C API` the following assert is being raised: `enc_modular.cc:506: JXL_ASSERT: !fp`.

**To Reproduce**
We are getting this exception inside @ImageMagick and it suspect that it is happening because we are doing this:

```c
basic_info.bits_per_sample=32;
basic_info.exponent_bits_per_sample=8;
JxlEncoderSetBasicInfo(encoder,&basic_info)
```
This will set `enc->metadata.m.xyb_encoded` to `true` because we did not set `info->uses_original_profile` to `JXL_TRUE` because we did not include a color profile.

Then we call the method `JxlEncoderOptionsSetLossless` that sets `options->values.lossless` to `JXL_TRUE`. The next method we call is `JxlEncoderAddImageFrame` and this is happening inside here:

```c
if (options->values.lossless) {
  queued_frame->option_values.cparams.SetLossless();
}
```

And that does this:

```c
void SetLossless() {
  modular_mode = true;
  quality_pair.first = 100;
  quality_pair.second = 100;
  color_transform = jxl::ColorTransform::kNone;
}
```

At this point the `color_transform` is set to `kNone` as it should be.

Then we start to call `JxlEncoderProcessOutput` that at some point calls the method `RefillOutputByteQueue` that does the following:

```C
  if (metadata.m.xyb_encoded) {
    input_frame->option_values.cparams.color_transform =
        jxl::ColorTransform::kXYB;
  } else {
    // TODO(zond): Figure out when to use kYCbCr instead.
    input_frame->option_values.cparams.color_transform =
        jxl::ColorTransform::kNone;
  }
```

Because the value `metadata.m.xyb_encoded` is set to true the `color_transform` is incorrectly changed to `kXYB`.

**Environment**
 - OS: Windows
 - Compiler version: Visual Studio 2019
 - CPU type: x86_64
 - cjxl/djxl version string: v0.5

**Comment by jonsneyers** [comment]
I suggest we make `xyb_encoded` an Override instead of a bool, and initialize it to a default value that will be interpreted as false if lossless frames are added and true if lossy frames are added. WDYT, @lvandeve ?

**Comment by jonsneyers** [comment]
https://github.com/libjxl/libjxl/pull/562 makes modular float + XYB work, but I think we still need to better document the encode API and make it more clear that

1) uses_original_profile == FALSE implies XYB which implies lossy
2) you can pass image data with float buffers (e.g. useful for IM7) but in case of lossless compression, that doesn't necessarily mean you want to actually store them as float values. If the original data has 8-bit integer samples, it will be far more effective to store the data as 8-bit integers than to store them as 32-bit floats in jxl. It is fine to set basic info to 8-bit while using float buffers to pass the image (32-bit float has 24 mantissa bits so anything up to 24-bit integers can be losslessly represented in it).

See also https://github.com/libjxl/libjxl/pull/873

Closing this one now.
