### ISSUE TITLE
Add more artifacts to builds

### ISSUE THREAD

**Issue by petrdiblik** [libjxl/libjxl#454]
**Is your feature request related to a problem? Please describe.**
Although building now works (https://github.com/libjxl/libjxl/actions/runs/1106694153), some useful binaries are missing.

**Describe the solution you'd like**
Please change the building process to build also the GIMP plugin which I think is the most useful for common users who want to try jxl. Other binaries to add include `jxlinfo` and `jxl_from_tree`.

**Describe alternatives you've considered**
Look for builds elsewhere but that's not as convenient and there might be issues with trustworthiness.

**Comment by mo271** [comment]
The gimp plugin is included in the artifacts by now. Please re-open if anything else is missing.
