### ISSUE TITLE
Resampled images are being decoded partially (top-left) by libjxl

### ISSUE THREAD

**Issue by ziemek99** [libjxl/libjxl#459]
**Describe the bug**
Images that use `--resampling=2` (other resampling factors weren't tested) are being shown partially (just the top-left part) in libjxl-dependent apps, e.g. Chrome Canary, Firefox Nightly, nomacs etc.

**To Reproduce**
1. Encode an image with `--resampling=2` option.
2. Decode JXL with `djxl`.
3. Load JXL file to an app that uses libjxl.

**Expected behavior**
Both images, no matter if decoded with `djxl` or shown by libjxl-dependent app, should be shown in full.

**Screenshots**
Expected result (PNG file from `djxl`):
![after](https://user-images.githubusercontent.com/15923635/129734542-a45f45c4-4c6c-4b73-a589-1b8cf665b01e.png)
Chrome Canary (buggy):
![chrome](https://user-images.githubusercontent.com/15923635/129734859-e893d79b-dede-4ce7-9cb0-754fb3369e51.png)
Firefox Nightly (buggy):
![firefox](https://user-images.githubusercontent.com/15923635/129734979-c28b8dbb-3827-48bc-b921-f6b7a7edff76.png)

nomacs (buggy) (different image, submitted by @ScopeBurst on Discord):
![nomacs](https://user-images.githubusercontent.com/15923635/129735326-fb0433af-feb1-4290-b38c-78d0dbd765dc.png)

**Environment**
 - OS: Windows
 - Compiler version: msvc+vcpkg (GitHub artifacts)
 - CPU type: x86_64
 - cjxl/djxl version string: v0.6.0 7193782 [SSE4,Scalar]

**Comment by xiota** [comment]
I see the same behavior with an older commit: 2ebc6ec

**Comment by jonsneyers** [comment]
Looks like a bug in upsampling that depends on decoding config - maybe it works when decoding to full float buffer, but not when decoding with the pixel callback or uint8 output?

**Comment by ziemek99** [comment]
> Looks like a bug in upsampling that depends on decoding config - maybe it works when decoding to full float buffer, but not when decoding with the pixel callback or uint8 output?

That might be correct, I've just loaded the image into GIMP (via `file-jxl.exe` plugin) and it worked perfectly!
![gimp-jxl-resampling-correct](https://user-images.githubusercontent.com/15923635/135104650-d6ef817c-c05d-491e-8682-321529bb3ecd.png)

**Comment by jonsneyers** [comment]
This one should indeed be fixed now (by https://github.com/libjxl/libjxl/pull/825).

Please reopen if it's not the case.

**Comment by ziemek99** [comment]
> This one should indeed be fixed now (by #825).
> 
> Please reopen if it's not the case.

I though about linking both this issue and that PR so GitHub knows explicitly that this PR fixes that particular issue. And yes, it's fixed 😃
