### ISSUE TITLE
Failed to read certain JPGs

### ISSUE THREAD

**Issue by Fraetor** [libjxl/libjxl#468]
**Describe the bug**
cjxl is not able to read certain JPGs. The files open successfully in my image viewer (Eye of GNOME), and Firefox

**To Reproduce**
Steps to reproduce the behaviour: Try and encode the JPG files in the attached archive: [[Non readable JPEGs.zip](https://github.com/libjxl/libjxl/files/7010747/Non.readable.JPEGs.zip)]

**Expected behaviour**
The files to be read successfully, then encoded.

**Screenshots**
```
$ cjxl 04.jpg 04.jxl
JPEG XL encoder v0.5.0 c98f133 [AVX2,SSE4,Scalar]
Failed to read image 04.jpg.
```

**Environment**
 - OS: Debian 11 Bullseye
 - Compiler version: gcc (Debian 10.2.1-6) 10.2.1 20210110
 - CPU type: x86_64
 - cjxl/djxl version string: cjxl v0.5.0 c98f133 [AVX2,SSE4,Scalar]

**Additional context**
Here is the output of the `file` command, with newlines added for clarity:
```
$ file *
04.jpg:   JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS5.1 Windows, datetime=2012:12:20 17:27:02], baseline, precision 8, 1200x1680, components 4

19-2.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS6 (Windows), datetime=2014:05:13 12:01:10], baseline, precision 8, 1100x1600, components 4

19.jpg:   JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS6 (Windows), datetime=2014:08:31 15:09:20], progressive, precision 8, 1100x1600, components 4

23.jpg:   JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=12, height=1518, bps=0, PhotometricIntepretation=CMYK, orientation=upper-left, width=1076], baseline, precision 8, 1076x1518, components 4

39.jpg:   JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS5.1 Windows, datetime=2012:12:20 17:26:58], baseline, precision 8, 1200x1680, components 4

40.jpg:   JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS5.1 Windows, datetime=2012:12:20 17:26:59], baseline, precision 8, 1200x1680, components 4
```
I suspect from this that they may not be true JPEGs, but rather TIFF files in a JPG container. Are these valid JPGs, or are they something weird and non-standard, and thus not meant to be supported?

**Comment by xiota** [comment]
The files all look like they have some Adobe specific APP14 marker.  A few have "Non-standard header for APP1 XMP segment."  A couple have multiple ICC profiles attached.  The file size of several drop by over 50% when run through jpegoptim.  I of wonder if they're intended to run malicious code.

**Comment by jloqfjgk** [comment]
`identify -verbose` on all the files in the ZIP archive reveals that all the files have `Colorspace: CMYK`, so maybe it is related to this issue?
[CJXL 0.2.0-945ad0ce crashes on specific JPEG image](https://gitlab.com/wg1/jpeg-xl/-/issues/122)

**Comment by jonsneyers** [comment]
What is needed here is better error reporting so cases that cannot be handled (CMYK JPEGs in this case) show a more useful error to the user than just "Failed to read".

**Comment by jonsneyers** [comment]
I think this should be improved by #480 .
CMYK jpegs cannot be losslessly recompressed in jxl, that's a limitation of the jxl bitstream, not much that can be done about that...
