### ISSUE TITLE
Possible reduction in the maximum number of patches

### ISSUE THREAD

**Issue by lovell** [libjxl/libjxl#476]
The following 73 byte image, found via fuzz testing, claims to contain a patch dictionary with 491521 entries.
 
https://github.com/libjxl/libjxl/files/7023786/patch-491521.txt

This is less than the 1<<24 `kMaxPatches` limit enforced in `PatchDictionary::Decode`

https://github.com/libjxl/libjxl/blob/e00ac5788b769b14af8a543d6572aee615513649/lib/jxl/dec_patch_dictionary.cc#L55-L56

Attempting to process this image takes many minutes and the `PatchPosition` vector it builds gradually consumes all available memory.

Is 16777216 (1<<24) an appropriate maximum? Perhaps significantly reducing this to something like 4096 (1<<12) might be sufficient?

**Comment by jonsneyers** [comment]
We can reduce it to something smaller, but I wonder why a not incredibly huge number of patches causes trouble already.

**Comment by lovell** [comment]
Thanks, yes, it did seem a bit strange. The bottleneck appears to be the use of `push_back` here:

https://github.com/libjxl/libjxl/blob/e00ac5788b769b14af8a543d6572aee615513649/lib/jxl/dec_patch_dictionary.cc#L141
