### ISSUE TITLE
problem to encode with grayscale ICC profile

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#484]
I am trying to encode JXL file using C API.

I set basic info `uses_original_profile = JXL_TRUE;` and to set grayscale ICC profile via `JxlEncoderSetICCProfile` but I get following error during the process:

```
lib/jxl/enc_external_image.cc:113: JXL_FAILURE: Buffer size is too small
lib/jxl/enc_external_image.cc:328: JXL_RETURN_IF_ERROR code=1: ConvertFromExternal( jxl::Span<const uint8_t>(static_cast<const uint8_t*>(buffer), size), xsize, ysize, c_current, pixel_format.num_channels == 2 || pixel_format.num_channels == 4, false, bitdepth, pixel_format.endianness, false, pool, ib, float_in)
```

I used `num_color_channels = 1;` and pixel format `num_channels = 1;` and `bits_per_sample = 16;` and `data_type = JXL_TYPE_UINT16;`

Similar code with `uses_original_profile = JXL_FALSE;` and `JxlEncoderSetColorEncoding` works with grayscale images so I believe I calculate buffer size correctly.

When I want to save RGB ICC profile, everything works but my attempts to save grayscale ICC lead to failure.

The grayscale ICC profile is generated by GIMP.

**Comment by xiota** [comment]
What ICC profile are you using?  Is it one of the default GIMP profiles or one you actually have a file for?

**Comment by novomesk** [comment]
The default non-linear gray profile. But also with the gray linear.

I understand that only one of JxlEncoderSetColorEncoding and JxlEncoderSetICCProfile can be used.

**Comment by xiota** [comment]
If it's the default gray profile from GIMP, you can call JxlColorEncodingSetToLinearSRGB(&color_encoding, gray) or JxlColorEncodingSetToSRGB(&color_encoding, gray) instead of attaching the ICC profile.

**Comment by xiota** [comment]
Would you show the code you use to calculate the buffer size?

It looks like libjxl doesn't translate translate ICC profiles into the internal color encoding, so it doesn't know that the ICC profile is grayscale.  As a result, [checks in `image_bundle.cc` fail](https://github.com/libjxl/libjxl/blob/2681dc2f4d0a028a38d8cb1d48c38a24cce9e14a/lib/jxl/image_bundle.cc#L41).  Unfortunately, the workaround is to not use the ICC profile on grayscale images.

**Comment by novomesk** [comment]
My code to calculate buffer size with 16bit depth is:
`buffer_size = 2 * pixel_format.num_channels * (size_t) output_info.xsize * (size_t) output_info.ysize;`

**Comment by xiota** [comment]
I don't get the buffer size error on my machine...  Have you tried increasing the multiplier from 2 to 4 to see if it makes a difference?

**Comment by novomesk** [comment]
I think you allocate more than necessary because you multiply with **bits_per_sample** but the buffer is in bytes.
> I don't get the buffer size error on my machine... Have you tried increasing the multiplier from 2 to 4 to see if it makes a difference?
```
  size_t buffer_size = jxl_save_opts.basic_info.xsize *
                       jxl_save_opts.basic_info.ysize *
                       jxl_save_opts.pixel_format.num_channels *
                       jxl_save_opts.basic_info.bits_per_sample;
```

**Comment by xiota** [comment]
Yes.  I have plenty of RAM on this machine.  I have to be a bit wasteful to get swap usage up.  90% of the time, it's stuck at zero.

**Comment by novomesk** [comment]
I observed that increasing buffer helps encoding to pass but saved JXL file looks weird. It is decodable via C API but djxl will fail to decode.

**Comment by xiota** [comment]
When you decode with the API, does it show as three small versions of the image next to each other?  That's because with the ICC profile, libjxl is treating it as RGB.  That's also why the buffer needs to be 3x the size.

**Comment by jonsneyers** [comment]
Question is if the "increasing buffer" workaround causes the encoder to produce an invalid bitstream, or if it produces a valid bitstream and djxl has a bug.

Either way it's a bit strange to have something that decodes via the api but not with djxl. Could you share an example of such a bitstream?

**Comment by novomesk** [comment]
> Either way it's a bit strange to have something that decodes via the api but not with djxl. Could you share an example of such a bitstream?

Examples: [Invalid_channel_range.zip](https://github.com/libjxl/libjxl/files/7045207/Invalid_channel_range.zip)
```
djxl graya1.jxl output1.png
JPEG XL decoder v0.6.0 405a126 [AVX2]
Read 163609 compressed bytes.
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/transform.cc:80: JXL_FAILURE: Invalid channel range: 4..4 (there are only 4 channels)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/palette.h:289: JXL_RETURN_IF_ERROR code=1: CheckEqualChannels(input, begin_c, end_c)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/encoding/encoding.cc:394: JXL_RETURN_IF_ERROR code=1: transform.MetaApply(image)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/encoding/encoding.cc:507: JXL_RETURN_IF_ERROR code=1: dec_status
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_modular.cc:223: JXL_RETURN_IF_ERROR code=1: dec_status
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_frame.cc:208: JXL_RETURN_IF_ERROR code=1: frame_decoder.ProcessSections( section_info.data(), section_info.size(), section_status.data())
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_file.cc:155: JXL_RETURN_IF_ERROR code=1: dec_ok
Failed to decompress to pixels.
```
```
djxl gray1.jxl output2.png
JPEG XL decoder v0.6.0 405a126 [AVX2]
Read 108804 compressed bytes.
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/transform.cc:80: JXL_FAILURE: Invalid channel range: 2..2 (there are only 2 channels)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/transform/palette.h:289: JXL_RETURN_IF_ERROR code=1: CheckEqualChannels(input, begin_c, end_c)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/encoding/encoding.cc:394: JXL_RETURN_IF_ERROR code=1: transform.MetaApply(image)
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/modular/encoding/encoding.cc:507: JXL_RETURN_IF_ERROR code=1: dec_status
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_modular.cc:223: JXL_RETURN_IF_ERROR code=1: dec_status
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_frame.cc:208: JXL_RETURN_IF_ERROR code=1: frame_decoder.ProcessSections( section_info.data(), section_info.size(), section_status.data())
/var/tmp/portage/media-libs/libjxl-9999/work/libjxl-9999/lib/jxl/dec_file.cc:155: JXL_RETURN_IF_ERROR code=1: dec_ok
Failed to decompress to pixels.
```

**Comment by xiota** [comment]
@jonsneyers  The libjxl GIMP plugin prevents ICC profiles from being attached to avoid this problem.  When I undo the patch, I get different errors those that @novomesk reports.  With `uses_original_profile=false`, no file is generated.  The error is:

    ../lib/jxl/image_bundle.cc:33: JXL_CHECK: metadata_->color_encoding.IsGray() == c_current.IsGray()

The problem seems to be that `JxlEncoderSetICCProfile` in [`encode.cc`](https://github.com/libjxl/libjxl/blob/ea6639fb88f75305f3b3e6a80edffbd5e190ca1b/lib/jxl/encode.cc#L145) uses `SetICCRaw` from [`color_encoding_internal.h`](https://github.com/libjxl/libjxl/blob/ea6639fb88f75305f3b3e6a80edffbd5e190ca1b/lib/jxl/color_encoding_internal.h#L272-L279).  This function doesn't do any ICC parsing at all.  Since `JxlEncoderSetICCProfile` and `JxlEncoderSetColorEncoding` cannot be used together, a default color encoding is used, which is RGB.  This causes the check to fail.

With `uses_original_profile=true`, the attached files are generated ([jpegxl-logo-gray-1.zip](https://github.com/libjxl/libjxl/files/7046444/jpegxl-logo-gray-1.zip)).  I get the following errors from `djxl`:

    ../lib/jxl/enc_color_management.cc:657: JXL_RETURN_IF_ERROR code=1: skcms_Parse(icc_.data(), icc_.size(), &profile)
    ../lib/jxl/dec_file.cc:116: JXL_RETURN_IF_ERROR code=1: io->metadata.m.color_encoding.SetICC(std::move(icc))
    Failed to decompress to pixels.

This seems to be caused by `skcms` being unable to parse the ICC profile.

When loaded with into GIMP with the plugin, which uses the API, multiple copies of the image are shown side-by-side.  I believe this is related to encoder treating it as RGB when saving, but being treated by monochrome when being loaded.

![screenshot1](https://user-images.githubusercontent.com/8353098/130779907-6ac1cbfa-2339-4fce-a442-7eceeb48ff6e.png)
![screenshot2](https://user-images.githubusercontent.com/8353098/130779911-3c767836-ce35-4265-bcf6-a73256f7d0c8.png)

**Comment by xiota** [comment]
@novomesk Can you check whether #498 prevents creation of the bad jxl files?

**Comment by novomesk** [comment]
@xiota Thanks, it seems to work now.
