### ISSUE TITLE
Error: APNG with dispose-to-0 is not supported for non-full or blended frames

### ISSUE THREAD

**Issue by petrich** [libjxl/libjxl#486]
**Describe the bug**
`cjxl` generate following error from some animated pngs (`apng`) 
```
../lib/extras/codec_png.cc:252: JXL_RETURN_IF_ERROR code=1: Decode(bytes, &io->blobs)
../lib/extras/codec_png.cc:810: JXL_RETURN_IF_ERROR code=1: reader(bytes, is_gray, io)
../lib/extras/codec_apng.cc:280: JXL_FAILURE: APNG with dispose-to-0 is not supported for non-full or blended frames
../lib/extras/codec_exr.cc:146: JXL_FAILURE: OpenEXR failed to parse input
../lib/extras/codec.cc:124: JXL_FAILURE: Codecs failed to decode
../lib/extras/codec.cc:137: JXL_RETURN_IF_ERROR code=1: SetFromBytes(Span<const uint8_t>(encoded), io, pool, orig_codec)
Failed to read image Animated_PNG_example_bouncing_beach_ball.png.

```

**To Reproduce**
```bash
wget https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png
cjxl Animated_PNG_example_bouncing_beach_ball.png out.jxl
```

**Expected behavior**
Would be great if no error happens.

**Environment**
 - OS: `Linux (Ubuntu)`
 - Compiler version: c`lang 11`
 - CPU type: `x86_64`
 - cjxl/djxl version string: `JPEG XL encoder v0.6.0 e00ac57 [SSE4,Scalar]`

**Additional context**
Is there any way to avoid this error?

**Comment by mo271** [comment]
In the meantime, this seems to have been fixed. At least on b5cec6f81ae1bb5096b51e1181fe7387296ee595 I can't repro the issue and the png compresses just fine. 
Closing this, if you still get the error please re-open.

**Comment by petrich** [comment]
Great... Works now... Thank You @mo271
