### ISSUE TITLE
djxl fails to decode image because unable to parse ICC profile

### ISSUE THREAD

**Issue by xiota** [libjxl/libjxl#492]
**Describe the bug**
When an image contains an ICC profile that skcms is unable to parse, `djxl` fails to decode the image.  The following error is displayed:

    ../lib/jxl/enc_color_management.cc:657: JXL_RETURN_IF_ERROR code=1: skcms_Parse(icc_.data(), icc_.size(), &profile)
    ../lib/jxl/dec_file.cc:116: JXL_RETURN_IF_ERROR code=1: io->metadata.m.color_encoding.SetICC(std::move(icc))
    Failed to decompress to pixels.

The API is able to process these images, presumably because it does not attempt to parse the attached ICC profile.

**To Reproduce**
Use `djxl` to process one of the `*Oyra*` files in the attached file [GrayRGB-Test-Cases.zip](https://github.com/libjxl/libjxl/files/7051926/GrayRGB-Test-Cases.zip).

**Expected behavior**
* Since the inability to decode an image is a potential data-loss issue for users, perhaps decompression could be attempted without the ICC profile?
* Compare this with the behavior of `cjxl`, which displays the same skcms_Parse error (when processing a `png` with the Oyra profile), but discards the profile and continues with encoding.

**Environment**
 - OS: Ubuntu 20.04.  Linux 5.11.—
 - Compiler version: gcc 10.3.0
 - CPU type: x86_64
 - cjxl/djxl version string: djxl v0.6.0 f9b3191 [AVX2,SSE4,Scalar] (from a local git branch)

**Additional context**
* The ICC profile is "Gray CIE*L".  
* The images were generated with a modified version of the libjxl GIMP plugin.  The plugin currently in the repository is specifically patched to avoid attaching ICC profiles to grayscale images to avoid this and other compatibility issues.  (See also #484.)
* Info from `jxlinfo`:
```
original color profile:
  format: ICC profile
  ICC profile size: 424
  CMM type: "Oyra"
  color space: "GRAY"
  rendering intent: 0
data color profile:
  format: JPEG XL encoded color profile
  color_space: 1
  white_point: 1
  white_point XY: 0.312700 0.329000
  transfer_function: 8
  rendering_intent: 1
```

**Comment by mo271** [comment]
> My thoughts:
> 
> * if djxl refuses to decode jxl files with an invalid ICC profile, then cjxl should refuse to encode them. There shouldn't be a situation where cjxl can produce something that the same version of djxl cannot decode.
> * cjxl should not encode in XYB if it doesn't understand the ICC profile (because it's likely not encoding correctly then)
Completely agreed and we should make sure that cjxl_ng and djxl_ng behave in this way.

**Comment by mo271** [comment]
I just tested with this with the image `GrayRGB-Test-Cases/Gray-Oyra-uop.jxl` and by now the error does not cause a failure but only prints a warning and pixels are written
(The warning currently does not include a newline, which I will fix)

```
> ./build/tools/djxl GrayRGB-Test-Cases/Gray-Oyra-uop.jxl test.png
JPEG XL decoder v0.7.0 52ff3e87 [AVX3,AVX2,SSE4,SSSE3,Emu128]
Read 24916 compressed bytes.
Decoded to pixels.
./lib/jxl/enc_color_management.cc:823: JXL_RETURN_IF_ERROR code=1: skcms_Parse(icc_.data(), icc_.size(), &profile)
Warning: error setting ICC profile, assuming SRGB911 x 1149, 55.01 MP/s [55.01, 55.01], 1 reps, 96 threads.
```
So togehter with https://github.com/libjxl/libjxl/pull/498, I think everyting should work as intended now, feel free to re-open is there still is a problem.
