### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by maddin200** [libjxl/libjxl#515]
/libjxl-main/tools/jxl_emcc.cc line 40 

Code:
 return result;
  return nullptr; // <- unreachable

**Comment by ziemek99** [comment]
I'd wait with any PRs. Maybe there's more unreachable code that could be detected with an automated tool. Your example should be kept as a benchmark until that moment – if a tool being tested doesn't detect *known* unreachable code, we can't be sure that it'll reliably detect *unknown* unreachable code, so a better tool should be found.
