### ISSUE TITLE
To support kThunder and kLightning in the JxlEncoderOptionsSetEffort function

### ISSUE THREAD

**Issue by sim9108** [libjxl/libjxl#522]
Coding modifications are required to support kThunder and kLightning in the JxlEncoderOptionsSetEffort function.

			kThunder = 2,
			kLightning = 1

JxlEncoderStatus JxlEncoderOptionsSetEffort(JxlEncoderOptions* options,
                                            const int effort) {
  if (effort < 3 || effort > 9) {  //==> if (effort <1 || effort > 9)
    return JXL_ENC_ERROR;
  }
  options->values.cparams.speed_tier = static_cast<jxl::SpeedTier>(10 - effort);
  return JXL_ENC_SUCCESS;
}

**Screenshots**
If applicable, add screenshots or example input/output images to help explain your problem.

**Environment**
 - OS: [e.g. Windows]
 - Compiler version: [e.g. clang 11.0.1]
 - CPU type: [e.g. x86_64]
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]]

**Additional context**

**Comment by jonsneyers** [comment]
Thanks for the catch, should be fixed as soon as the CI bots are done processing stuff.
