### ISSUE TITLE
Decoding 1x1 image consumes 5.2GB RAM

### ISSUE THREAD

**Issue by lovell** [libjxl/libjxl#528]
Hello, the following 1x1 JPEG-XL image, found via fuzz testing, contains a 8163x2954 3-channel frame.

[fuzz-37679.txt](https://github.com/libjxl/libjxl/files/7085929/fuzz-37679.txt)

When decoding the tree in `DecodeGlobalInfo`, the `tree_size_limit` for this frame is calculated as 72341530 here:

https://github.com/libjxl/libjxl/blob/9d03bfe8111f49210e2d096688dd4db303654270/lib/jxl/dec_modular.cc#L163-L164

then clipped to 67108864 (1 << 26) here:

https://github.com/libjxl/libjxl/blob/9d03bfe8111f49210e2d096688dd4db303654270/lib/jxl/modular/encoding/dec_ma.cc#L100

The size of the `DecodeTree` eventually trips the  `tree_size_limit` check, but consumes 5.2GB of RAM at that point, and takes about 4 seconds to get there.

https://github.com/libjxl/libjxl/blob/9d03bfe8111f49210e2d096688dd4db303654270/lib/jxl/modular/encoding/dec_ma.cc#L43-L45

I suspect this rapid memory growth from a "small" image isn't desired.

Perhaps there could be an earlier sanity check on frame dimensions, or maybe the tree limit should be dependent on target dimensions rather than frame dimensions? I'm sure there are lots of other options too.

**Comment by jonsneyers** [comment]
Lovely example.

Not sure what makes sense in terms of frame dimension restrictions. Having frames that are significantly larger than the image canvas can be useful for reversible cropping (in authoring workflow use cases, not web delivery). A 1x1 crop from a 24 MP image is of course a bit ridiculous, but I wouldn't know what kind of limit would be safe. I don't think it should be disallowed to do a reversible crop of one face from a group picture, for example, even if that could mean having a 100x100 image containing a 6000x4000 frame.

A somewhat stricter tree_size_limit would make sense though imo. Presumably, if we set the limit to 1<<22, the time and memory roughly divide by 16, which seems more reasonable. That limits MA trees to 4 million nodes, which seems not very limiting. WDYT, @veluca93 ?

**Comment by veluca93** [comment]
Reducing the tree_size_limit would make sense. We could also reduce the per-pixel limit by another factor of 16 or so, which IIRC would allow something like one tree node per 16 pixels... probably enough :)

**Comment by jonsneyers** [comment]
Let's do both.
Only reducing the per-pixel limit will not help against malicious cases like this (you'd just need larger frame dimensions).
