### ISSUE TITLE
clang-7 not available in Debian Bullseye

### ISSUE THREAD

**Issue by varnav** [libjxl/libjxl#530]
**Describe the bug**
Readme recommends recent compiler like clang 7, but clang 7 is actually too old to be included as part of Debian bullseye, and oldest they have is clang-9 while current version is clang-12. So `sudo apt install clang-7` command from readme will fail on recent Linux versions like Debian bullseye.

I think readme must be changed to reflect this. Probably recommending clang-9 or newer will make more sense.

**Comment by jonsneyers** [comment]
I think we should recommend using the newest clang, and while we should specify the minimum version needed to get it compiled, we shouldn't put command lines in the readme that mention a specific version if the default version is most likely newer. So I'd change it to just `sudo apt install clang`. WDYT, @deymo ?

**Comment by xiota** [comment]
I've edited the readme in #517 to state "at least version 6" and to remove the specific version number from the command.  Older versions of clang are still available in Ubuntu 18.04.  #28 suggests using clang-5 for some test builds.

**Comment by xiota** [comment]
Does the change to README.md in #517 address this?

**Comment by deymo** [comment]
mozilla firefox uses clang-5 for some of their test builds, so there's some work to make sure it complies in clang-5 (there are some compiler bugs that need to be avoided in clang-5).

**Comment by mo271** [comment]
> @jonsneyers Does the change to README.md in #517 address this? Although clang-7 or newer is still recommended, the suggested command is version agnostic.

Yes, Let's close the issue.
