### ISSUE TITLE
Build error using MSVC

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#568]
![build_error](https://user-images.githubusercontent.com/52529860/132824781-841dcd9a-bcfb-47dd-8e43-5457b4e7303f.png)

Steps to reproduce:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DJPEGXL_ENABLE_PLUGINS=OFF -DBUILD_TESTING=OFF -DJPEGXL_WARNINGS_AS_ERRORS=OFF -DJPEGXL_ENABLE_SJPEG=OFF ..
nmake
```

Error message:
`C:\Devel\libjxl\third_party\skcms\skcms.cc: fatal error C1083: Cannot open include file: '"C:/Devel/libjxl/lib/jxl/enc_jxl_skcms.h"': No such file or directory`

File `C:\Devel\libjxl\lib\jxl\enc_jxl_skcms.h` exists.

**Comment by deymo** [comment]
Is it maybe the issue that it is quoted? Could you try removing the `"` around the filename in third_party/skcms.cmake:35?

**Comment by novomesk** [comment]
When I removed the quotes it started to work.
