### ISSUE TITLE
More speed for lossless decoding

### ISSUE THREAD

**Issue by fabiorug** [libjxl/libjxl#57]
Modular lossless like one month and half ago I got 1,6 mpx, 3,0 mpx/s.
Could you add in some speeds a faster decoding variant?
It would be great.

**Comment by jonsneyers** [comment]
You can try `--faster_decoding`.

Also when encoding at `-e 2` or `-e 1`, decoding should be quite fast, I get ~50 MP/s on my laptop. It's of course not a very dense way to do lossless compression, at that speed, but it should still typically be better than PNG, especially for HDR where PNG has a bit of a problem.

**Comment by jonsneyers** [comment]
Closing this issue - of course further encoder/decoder speedups are always nice to have but we don't really need an open issue to remind us of that.
