### ISSUE TITLE
splines: possible memory exhaustion in ComputeSegments

### ISSUE THREAD

**Issue by lovell** [libjxl/libjxl#576]
The following image 12x8 JPEG-XL image, found via fuzz testing, quickly exhausts memory when decompressed.

[fuzz-35213.txt](https://github.com/libjxl/libjxl/files/7148580/fuzz-35213.txt)

It seems to be due to the `segments_by_y` vector, which reaches almost 300 million entries before the out-of-memory killer terminates the process, but for this image could contain over 2 billion entries given enough RAM.

https://github.com/libjxl/libjxl/blob/08dcb04eb2bed2a9f6875859b4bb9a4080a2d7ec/lib/jxl/splines.cc#L133-L135

Perhaps there should be a maximum size for `segments_by_y`, or maybe this could be caught sooner based on the size of `points_to_draw` in `SegmentsFromPoints`? I'm sure there will be other options.

**Comment by jonsneyers** [comment]
At the moment, in the spec (profile and levels amendment) we only limit the number of splines to min(2^24, W*H/4). However you could have a single spline with lots of control points, or with a huge arclength, or with huge values for sigma, which could all be things that lead to performance and/or memory issues.

I suggest we add some sanity checks / limits in the code first, and then we can see if they can be formulated in a way that is not too implementation-specific. It might be a bit tricky to define limits that are not too limiting, but that also avoid problems. Maybe something along the lines of "every pixel gets updated at most N times by the spline drawing procedure", where N should be large enough to allow large-sigma and/or overlapping splines, but small enough to ensure reasonable memory consumption. @veluca93 @sboukortt any opinions?

**Comment by lovell** [comment]
Variants of this are appearing relatively frequently in fuzz testing.

Another example is the 480 byte, 16x16 image [fuzz-40657.txt](https://github.com/libjxl/libjxl/files/7481636/fuzz-40657.txt), which generates a `segments_by_y` vector containing 116 million entries that takes ~12 seconds to sort.

https://github.com/libjxl/libjxl/blob/6ef17f0ee17ac01a2b632cf423aacb7f94b042c3/lib/jxl/splines.cc#L536

**Comment by kleisauke** [comment]
It looks like PR https://github.com/libjxl/libjxl/pull/905 has resolved a lot of these fuzzer issues, including the one mentioned above.

**Comment by lovell** [comment]
Yes, thank you @eustas for your great work on this, I think we can close this now.

There is one remaining libvips OSS-Fuzz issue labelled `Bug-Security` that relates to a possible problem in libjxl. I won't link to it here as you should already have access, but please do let me know if you can't find it.
