### ISSUE TITLE
TARGET_DATA ICC profile do not match encoded profile

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#580]
I noticed colorspace problems when I started to use `JxlDecoderSetPreferredColorProfile` function.

Pixel data were correctly converted to the preferred colorspace and the `JxlDecoderGetColorAsEncodedProfile` (with JXL_COLOR_PROFILE_TARGET_DATA parameter correctly matches the data and the preferred profile.

However, `JxlDecoderGetICCProfileSize`+`JxlDecoderGetColorAsICCProfile` (with JXL_COLOR_PROFILE_TARGET_DATA parameter) no longer matches the returned pixel data. It returns previous ICC profile which would be correct if JxlDecoderSetPreferredColorProfile was not called before.

I guess that libjxl forgot to generate new ICC profile if image gets converted after JxlDecoderSetPreferredColorProfile call.

**Comment by lvandeve** [comment]
Thanks for reporting, good find. I believe this should fix it: https://github.com/libjxl/libjxl/pull/589, if not feel free to re-open
