### ISSUE TITLE
cjxl - temp JPEG files remain

### ISSUE THREAD

**Issue by eddiezato** [libjxl/libjxl#6]
If the input files are JPEGs, `cjxl` creates `jpe????.tmp` files in the system `%temp%` folder and doesn't delete them after the encoding is finished.

_Windows 10 20H2 x64, cjxl v0.3.7-12-g04267a8_

**Comment by jonsneyers** [comment]
I wonder what is creating these temp files. I don't think jxl itself does that; perhaps libjpeg does it for some reason?

Scope on discord pointed to https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/example.txt#L208 which might be an explanation.

**Comment by JamesPous** [comment]
I recognized the same problem with jpe*.tmp files with the cjxl.exe (JPEG XL encoder 0.3.7) under Windows 10 64bit (lastest updates).

**Comment by eustas** [comment]
"On some systems you may need to set up a signal handler to ensure that temporary files are deleted if the program is interrupted. See libjpeg.txt."

**Comment by eustas** [comment]
But: "NOTE: Unless you develop your own memory manager back end, then temporary files
will never be used.  The back end provided in libjpeg-turbo (jmemnobs.c) simply
malloc()s and free()s virtual arrays, and an error occurs if the required
memory exceeds the limit specified in cinfo->mem->max_memory_to_use."

**Comment by eddiezato** [comment]
> It's best to use the memory manager jmemnobs.c if you can (ie, if you have enough real or virtual main memory).  If not, at least make sure that max_memory_to_use is set as high as possible.  If the JPEG memory manager has to use a temporary file, you will probably see a lot of disk traffic and poor performance.

Probably `max_memory_to_use` isn't used and defaults to 0. This forces the encoder to create temp files every time.
I even tried 1-pixel jpeg. Same thing.

**Comment by eustas** [comment]
So, it is easily reproducible? Good! Does it create file even if processing was successful?
(going to try to reproduce myself, but will bother you further if won't succeed).

**Comment by eddiezato** [comment]
Even a simple `cjxl 0.jpg` will create a temp file that's just a copy of the input jpeg. On Windows at least.

**Comment by eustas** [comment]
Spent some time trying to build project on windows, with limited success (got binary that does not support JPEG).
(Hmm, we have to improve that story - vcpkg and chocolatey is a must).

Next, built binaries via cross-compilation in docker container. Those, however work fine and does not create temporay files.

@eddiezato could you share your experience, how you build / obtain the cjxl / djxl binaries, please.

**Comment by eddiezato** [comment]
I build with mingw64/msys2 myself.
Share them here https://eddiezato.github.io/bin/

**Comment by eddiezato** [comment]
I haven't thought about it. But it could be a problem with the mingw package for libjpeg-turbo. If it turns out that the problem occurs only on mingw builds.

**Comment by eustas** [comment]
At last, succeeded with MSYS2 /  mingw-w64-x86_64-clang.
Can't reproduce =(

**Comment by eustas** [comment]
(oh, but perhaps I have no libjpeg-turbo installed)

**Comment by eustas** [comment]
Was able to reproduce: https://github.com/eustas/libjxl-msys2/runs/3001986608?check_suite_focus=true#step:4:26

**Comment by eustas** [comment]
Tried building without libjpeg-turbo... same result.

**Comment by eddiezato** [comment]
This also happens if the input jpeg is not valid, not even jpg. 😀
```Powershell
PS > ls -Path $Env:temp\jpe*.tmp
PS > Rename-Item cjxl.exe cjxl.jpg
PS > cjxl cjxl.jpg
JPEG XL encoder v0.3.7 [SSE4]
Failed to read image cjxl.jpg.
PS > ls -Path $Env:temp\jpe*.tmp

    Directory: Z:\Temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2021.07.07     8:55        6641152 jpeD8F3.tmp
```

**Comment by eustas** [comment]
Pinpointed the problem. It is: 🤦 🙀 
Will fix soon.

**Comment by eustas** [comment]
(and it have nothing to do with JPEG)

**Comment by eddiezato** [comment]
@eustas I checked #300 , no temp files. Thanks 👍
