### ISSUE TITLE
Predictor value 14/15 Best/Variable not allowed through CLI

### ISSUE THREAD

**Issue by adamburgess** [libjxl/libjxl#611]
**Describe the bug**
CLI says you can use predictor 14/15:
<pre>
 -P K, --predictor=K
    [modular encoding] predictor(s) to use: 0=zero, 1=left, 2=top, 3=avg0, 4=select, 5=gradient, 6=weighted,
    7=topright, 8=topleft, 9=leftleft, 10=avg1, 11=avg2, 12=avg3, 13=toptop predictive average
    <b>14=mix 5 and 6, 15=mix everything.</b> Default 14, at slowest speed default 15
</pre>

**To Reproduce**
```
$ cjxl image.png out.jxl -P 14
Invalid predictor value 14, must be less than 14.
Error parsing flag -P
Use 'cjxl -h' for more information

$ cjxl image.png out.jxl -P 15
Invalid predictor value 15, must be less than 14.
Error parsing flag -P
Use 'cjxl -h' for more information
```

**Expected behavior**
You can use it, or the CLI help be changed.

**Relevant code**
https://github.com/libjxl/libjxl/blob/95cb570e421c25396c222c932ebf8d5d199e8120/tools/args.h#L122-L126

https://github.com/libjxl/libjxl/blob/95cb570e421c25396c222c932ebf8d5d199e8120/lib/jxl/modular/options.h#L35-L38

https://github.com/libjxl/libjxl/blob/95cb570e421c25396c222c932ebf8d5d199e8120/lib/jxl/modular/options.h#L99

**Comment by DamonHD** [comment]
FWIW, I found this confusing too.
