### ISSUE TITLE
JXL_DEPRECATED is implicitly defined by CMake?

### ISSUE THREAD

**Issue by saschanaz** [libjxl/libjxl#623]
It seems the header is not entirely self-contained because of that macro. Should it be defined somehow?

**Comment by deymo** [comment]
JXL_DEPRECATED and JXL_EXPORT are defined in `jxl_export.h` which is generated by CMake. If you are building in some other environment and not running cmake at all you can define them as empty, but for the build workflow with cmake we generated and install that file.

**Comment by saschanaz** [comment]
Oh, I missed that the file now also includes that. Thanks!
