### ISSUE TITLE
Support some "raw" image format in cjxl/djxl

### ISSUE THREAD

**Issue by LeviPesin** [libjxl/libjxl#625]
**Is your feature request related to a problem? Please describe.**
I want to use cjxl to compress raw RGB images (e.g. obtained from JavaScript ImageData) to JPEG XL.

**Describe the solution you'd like**
It is very easy and fast to convert RGB image data to some raw image format (like TIFF, BMP, or MIFF, i.e. which is not compressed). I want that cjxl can encode at least one of them.

**Describe alternatives you've considered**
It is possible to convert TIFF image to, for example, PNG, and then to JPEG XL. But an intermediate compression makes it much slower than directly converting a raw image to JPEG XL.

**Additional context**
No additional context.

**Comment by deymo** [comment]
I believe `.pnm` would be easiest solution here. It has a text header with the x/y size and format, you can specify binary format so the file would be a concatenation of this header plus the raw RGB data. This is already supported by `cjxl`. A "raw" image format requires somehow to pass the image size, color space, bits per pixel. etc; so I don't think something simpler than this would be possible in the `cjxl` command line.

**Comment by LeviPesin** [comment]
Thank you! I will use it.

**Comment by jonsneyers** [comment]
That reminds me, it would be useful to extend the pnm reader/writer to pam, which is basically the same thing but it can also do alpha (and in principle any number of extra channels, but likely most software that supports pam only understands rgba).

**Comment by megapro17** [comment]
bmp is much more common than ppm, it will be great if it supported

**Comment by jonsneyers** [comment]
Bmp is also a rather hairy format with lots of weird features that are not so easy to implement (it's basically memdumps of whatever bizarre internal structs the internal microsoft image apis have been using over the decades). Do not recommend.

**Comment by megapro17** [comment]
What about piping stdout from decoder lol

**Comment by MasterInQuestion** [comment]
Exactly such:
    [ https://github.com/libjxl/libjxl/issues/3921#issue-2639083059](https://github.com/libjxl/libjxl/issues/3921#issue-2639083059)
