### ISSUE TITLE
butteraugli library

### ISSUE THREAD

**Issue by mnb21** [libjxl/libjxl#643]
It seems butteraugli cannot be used as standalone library like [this version](https://github.com/google/butteraugli). Or at least I cannot get only the butteraugli library that I can use for example for [the vapoursynth plugin](https://github.com/fdar0536/VapourSynth-butteraugli).

Can you make it standalone or tell me how can I get only butteraugli library?

**Comment by mnb21** [comment]
Can [this](https://github.com/libjxl/libjxl/blob/main/lib/jxl/butteraugli_test.cc) be used as example for the api usage?

**Comment by deymo** [comment]
Yes, if you are using C++ you can also use the unique_ptr wrappers used there.

**Comment by mnb21** [comment]
Thanks for the info.

**Comment by mnb21** [comment]
@deymo, can you confirm that butteraugli doesn't benefit from multi threading? I'm have same results when using one thread and few threads.

Also I have same results when having environment with avx2 and environment without any SIMD (scalar).
