### ISSUE TITLE
potential build problem under MSYS2

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#646]
Hello,

When I use following configuration, I encounter error to build skcms:

`cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_ENABLE_PLUGINS=ON -DJPEGXL_ENABLE_SJPEG=OFF -DJPEGXL_ENABLE_SKCMS=ON -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_HWY=ON -DCMAKE_CXX_FLAGS="-DHWY_COMPILE_ONLY_SCALAR" ../libjxl/`

```
$ make skcms
[  0%] Building CXX object third_party/CMakeFiles/skcms-obj.dir/skcms/skcms.cc.obj
cc1plus.exe: fatal error: C:C:/msys64/msys64/home/daniel/libjxl/lib/jxl/enc_jxl_skcms.h: Invalid argument
compilation terminated.
make[3]: *** [third_party/CMakeFiles/skcms-obj.dir/build.make:77: third_party/CMakeFiles/skcms-obj.dir/skcms/skcms.cc.obj] Error 1
make[2]: *** [CMakeFiles/Makefile2:326: third_party/CMakeFiles/skcms-obj.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:307: third_party/CMakeFiles/skcms.dir/rule] Error 2
make: *** [Makefile:192: skcms] Error 2
```

After editing `build\third_party\CMakeFiles\skcms-obj.dir\flags.make` to remove **c:** it works well.

When I use **cmake -G Ninja** there is no problem at all.

I just wanted to let you known. It is good to explicitly recommend to use **Ninja** generator under MSYS2 to avoid build problems. Or is possible to make it to work with the `Unix Makefiles` generator too?

**Comment by kmilos** [comment]
Did you try w/ "MSYS Makefiles" just in case (though I expect little would change)?

**Comment by novomesk** [comment]
Same problem with `MSYS Makefiles`

**Comment by kmilos** [comment]
Well, was worth a punt... In any case should be preferred over "Unix Makefiles" in MSYS2 shell as it defines extra variables like `MSYS`...

**Comment by novomesk** [comment]
This is a problematic part of the cmake script, there was similar problem in the past too: https://github.com/libjxl/libjxl/issues/568

**Comment by vtorri** [comment]
MSYS Makefiles is for apps/lib needed in msys2 dev, it should not be used for"native" compilation

i've cloned git today, run deps.sh, and it compiled; I can paste my compilation script is you want

best regards

**Comment by novomesk** [comment]
After commit https://github.com/libjxl/libjxl/commit/8917d6afbcd98e29f85e81c0e8596f94a5c1d4aa the error slightly changed.
`cc1plus.exe: fatal error: C:C:/msys64/msys64/home/daniel/libjxl/third_party/../lib/jxl/enc_jxl_skcms.h: Invalid argument`

@vtorri 
Yes, you can share your scripts. I am just curious, maybe I'll learn something new.

**Comment by vtorri** [comment]
@novomesk  in third_party/skcms.cmake line 38, add a space between -include and ${CMAKE_CURRENT_SOURCE_DIR}

it works for me

that's for such crazy problems (and so much nicer syntax) that i prefer meson over cmake

**Comment by novomesk** [comment]
Thanks, it works.
