### ISSUE TITLE
Image orientation in codestream, exif and xmp - clarification

### ISSUE THREAD

**Issue by PetrMinar** [libjxl/libjxl#648]
Is this information correct?
_If the optional Exif (or XMP) metadata says something that conflicts with what the codestream says, then a decoder has to ignore the Exif/XMP_
Source - https://github.com/w3c/csswg-drafts/issues/4929#issuecomment-718849793

If that is the case than how should one implement lossless rotation (without image re-compression to update orientation in codestream)? For formats like jpeg, png, tiff all that is needed to be done is updating exif/xmp orientation. But that would not work for JPEG XL as one should also fix the value in codestream. Considering the complexity of codestream, that is not an easy task.

Are there plans for libjxl to implement such operations on codestream directly?

Thank you for clarification.

BTW heif and avif image formats have similar problem. Luckily the orientation there is not stored inside compressed bitstream but it is accessible through transformative properties in isobmff container itself.

**Comment by jonsneyers** [comment]
That information is correct, yes.

The orientation is part of the image header in the codestream, which is not _that_ complicated — you certainly don't need to implement a full encoder/decoder if you only want to change that field.

But yes, it's not super trivial and it would be useful if at some point libjxl would offer basic functionality for doing image header manipulations like that one. Orientation, intrinsic size, adding or removing a preview frame, tweaking ToneMapping info, stripping or changing an informative ICC profile or changing the nominal bit depth in case of xyb_encoded are some of the things that can be done just at the level of the image header (without any reencoding of pixel data), and I imagine they can all be useful. If we also allow frame header manipulations (without changing the actual frame data), even more things are possible, like reversible cropping, mild sharpening/blurring by adjusting gaborish weights, changing names of layers, changing durations or timecodes of frames.

We'll have to see to what extent it is sensible to have such functionality in libjxl, as opposed to a separate `jxltran` tool that does such things. @deymo / @lvandeve / @veluca93 opinions on whether e.g. changing image orientation is something that libjxl should do or not?

**Comment by PetrMinar** [comment]
Thank you for clarification. Unfortunately I haven't found any traces of jxltran. Is it something to be developed in the future? I don't have a problem with having such a functionality in another library.

I have checked the codestream structure and to change orientation one must parse whole "Annex A Headers" and rewrite it from scratch. 
Although "orientation_minus_1" occurs fairly early:
- it is not always in the same bit offset because bit size of "SizeHeader" is variable
- it is optional thanks to "extra_fields" / "all_default"
- when "extra_fields" or "all_default" is 0 than to introduce "orientation_minus_1" one must also introduce some additional stuff after it in the ImageMetadata bundle

I do not say that it is some major obstacle. But I am bit worried if such a functionality is not easily available (in libjxl/jxltran) others (while integrating jxl ) might just give up and update the EXIF only. In the end the real word jxl will not be standard compliant. Rotating an image is one of the most basic operations users will do on files...

**Comment by PetrMinar** [comment]
@jonsneyers May I ask for one more thing? I have already written the whole codestream headers decoding / reencoding. But it just didn't work. After two days of experimenting I probably found the reason. I have used ISO/IEC FDIS 18181-1:2021(E)  as a source of information about a codestream structure and I think there is an error in _Table A.16 - ImageMetadata bundle_. The **default_transform** that causes the decoder to read **opsin_inverse_matrix** and **cw_mask** is in my opinion described wrongly and the conditions should contain **!default_transform** instead of **default_transform**.

Is that so?

**Comment by jonsneyers** [comment]
Opened https://github.com/libjxl/libjxl/issues/871

I think the concerns from this issue are reflected in that one, so we can continue discussion there. Closing this one.
