### ISSUE TITLE
Noise generation doesn't work with lossy Modular

### ISSUE THREAD

**Issue by ziemek99** [libjxl/libjxl#665]
**Describe the bug**
Command-line options `--noise` and `--photon_noise` have no effect on output file when used in conjunction with lossy Modular.

**To Reproduce**
`cjxl -m -q 30 --noise=1` or `cjxl -m -q 30 --photon_noise=ISO25600`

**Expected behavior**
Noise is generated because JPEG XL bitstream doesn't disallow it.

**Environment**
 - OS: Windows
 - Compiler version: msvc+vcpkg (GitHub artifacts)
 - CPU type: x86_64
 - cjxl/djxl version string: v0.7.0 233db00 [SSE4,Scalar]

**Additional context**
~~I'd ***really*** like it to make it into v0.6 if it's possible~~ **\[EDIT: ...[whatever](https://github.com/libjxl/libjxl/releases/tag/v0.6).\]** because GoogleChromeLabs/squoosh#1136 depends on this issue.

**Comment by ziemek99** [comment]
I hope @sboukortt won't get annoyed about a ping... isn't noise generation your field? :wink:

**Comment by mo271** [comment]
Now photon noise works for modular mode. Not sure if `--noise` will be kept in `cjxl_ng`, so closing. Thanks for the contribution!
