### ISSUE TITLE
EXIF import functions missing

### ISSUE THREAD

**Issue by sati32** [libjxl/libjxl#666]
Just tried the last version of lib. There is an example to get EXIF data. But there is no function JxlDecoderSetBoxBuffer, JxlDecoderReleaseBoxBuffer and JxlDecoderGetBoxType. Did I miss something?

**Comment by deymo** [comment]
These functions were recently added (~last week) and are a work in progress.

**Comment by jonsneyers** [comment]
The encode API for boxes like Exif is being added now: see e.g. https://github.com/libjxl/libjxl/pull/815

Closing this issue since it is (being) resolved. Of course if there's an issue with the encode/decode API for Exif or other boxes, feel free to reopen this issue or start a new one.
