### ISSUE TITLE
Bad progressive decode of transcoded jpeg.

### ISSUE THREAD

**Issue by wwww-wwww** [libjxl/libjxl#673]
**Describe the bug**
Progressive decode of a lossless transcode of chroma subsampled jpeg does not render correctly.
LQIP is gray, MQIP's chroma is at its original subsampled size.

**To Reproduce**
Progressively load attached files:
4:2:0
<img src="https://user-images.githubusercontent.com/19401176/135532520-75b67b82-eb2d-4f84-8d5e-a23fe3a97b22.jpg"  width="200" height="200" />
4:2:2
<img src="https://user-images.githubusercontent.com/19401176/135532577-96aaf9b4-5c77-4fb1-acaf-d47dd49575ca.jpg"  width="200" height="200" />
(renamed to .jpg to upload to github)

**Expected behavior**
Image used here is a transcode of 4:4:4 jpeg
<img src="https://user-images.githubusercontent.com/19401176/135532806-587ffcec-97b7-4448-9889-61855e1faeef.png"  width="400" height="400" />

**Screenshots**
4:2:0 at 50/384 kb
<img src="https://user-images.githubusercontent.com/19401176/135533186-56a736c3-ef37-4b1a-b8d9-b2b304357c36.png"  width="400" height="400" />
4:2:2 at 50/381 kb
<img src="https://user-images.githubusercontent.com/19401176/135533198-c425bd8e-d787-4259-8953-06b15a8b3f79.png"  width="400" height="400" />

**Environment**
Patched Firefox on libjxl commit [702cd54420513b754edb60e33b9a4438f7e9ca00](https://github.com/libjxl/libjxl/commit/702cd54420513b754edb60e33b9a4438f7e9ca00)

**Comment by TheDecryptor** [comment]
I can also see this using the resampling option in djxl

Using [this image](https://github.com/libjxl/libjxl/blob/c2266c4bacaf355f3e8fe63c8d3a63f83b3cecfe/third_party/testdata/imagecompression.info/flower_foveon.png.im_q85_420.jpg) as a source with these options: `djxl.exe .\flower_foveon.png.im_q85_420.jxl -s 8 .\flower_foveon.png.im_q85_420.jxl.png` results in this output.

![flower_foveon png im_q85_420 jxl](https://user-images.githubusercontent.com/1516741/135592598-5b175c6e-072b-440e-9373-a441e49599d1.png)
