### ISSUE TITLE
Please include .TIF (24 bit and 48 bit) as possible input.

### ISSUE THREAD

**Issue by Joachim-Otahal** [libjxl/libjxl#680]
Hello JXL developers!

Situation: The nice 48 bit full-size original tif(s) at: https://noirlab.edu/public/images/iotw2135a/
Target: .jxl it.
But I can't. .TIF input is not supported. But most space related sites use .TIF in 24 or 48 bit.

Current workaround: Using Affinity Photo to convert it to 48 bit .PNG, and then use cjxl.exe.

BTW: I love the transcoding-jpeg-lossless feature.

kind regards,

Joachim Otahal

**Comment by jonsneyers** [comment]
The problem with TIFF is that it is nearly impossible to write a complete TIFF decoder. The reason for that is that TIFF is a catch-all container format that can basically contain just about any payload codec that ever existed since the 1980s.

We could add support for a limited subset of TIFF (e.g. only uncompressed and non-tiled), but then again, I don't think it's a big problem to convert your input to PPM or PNG before giving it to cjxl. Alternatively, you can use more general-purpose image tools like ImageMagick or libvips to do conversions between arbitrary image formats and jxl.

**Comment by Joachim-Otahal** [comment]
So there is no an existing "libtif" to "simply" include. As far as ImageMagic and libvips is concerned: I'd have to test whether they preserve 48 bit or not. Quite a number of those tools silently convert to 24 bit.
Thanks for the fast reply!

**Comment by jonsneyers** [comment]
libtiff does exist, I don't know how complete it is though. But so far, our motivation for adding new input formats has been that we wanted to test some new kind of input that we couldn't input in any already-supported format.

ImageMagick by default gets compiled to use 16-bit buffers internally (per channel, so 48 or 64 bits per pixel), and can also be compiled to use 32-bit float samples internally. So it should preserve the precision just fine.

**Comment by kmilos** [comment]
libtiff can certainly help with avoiding rewriting a parser and it's pretty feature complete, but it's still up to apps using it to check what the actual payload is...

AFAIK both ImageMagick and GraphicsMagick will happily deal/convert 48bit TIFFs if compiled as Q16 (or better, like HDRI); you can even make sure of that using e.g. [-depth 16](https://imagemagick.org/script/command-line-options.php#depth). You can even use ImageMagick entirely for the one step conversion as it could [leverage libjxl already](https://imagemagick.org/script/formats.php) (ships w/ Windows binary for example, or imagemagick-full-git on Arch Linux)...

**Comment by jonsneyers** [comment]
Closing this one as a `wontfix`. I'm in principle not opposed to adding tiff input/output support, and I'll happily review a pull request that implements it, but it's not a priority and it's not the goal of cjxl/djxl to support all possible input/output formats (there are other tools for that). In the end, cjxl/djxl will eventually be just _example_ applications of libjxl, and just like most people are not using cjpeg/djpeg to encode/decode JPEG files, the same will (hopefully) happen here.
