### ISSUE TITLE
Decode API: clarify color space of returned pixels

### ISSUE THREAD

**Issue by tbsmark86** [libjxl/libjxl#70]
From reading JxlDecoderSetPreviewOutBuffer() in decode.h it's not clear which color space the resulting buffer will have.

My first guess was that's the same as encode srgb for JXL_TYPE_UINT8 and linear-srgb for JXL_TYPE_FLOAT. But it seems to be JxlDecoderGetColorAsEncodedProfile()
=> Could please add some pointers for the user?

Moved this from gitlab https://gitlab.com/wg1/jpeg-xl/-/issues/243 as suggested.

If at all possible it would be nice to have a simple output-color-space option reducing all these possibilities of  JxlDecoderGetColorAsEncodedProfile() return value to something easy-to-use.

**Comment by veluca93** [comment]
What you can easily do today is to use `skcms` on the returned pixels to convert everything to whatever your display space will be - either way, we'd end up doing the same thing :)

You can also do it with float output and the output callback for better performance - I don't know if we have an example of it except [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/image-decoders/jxl/jxl_image_decoder.cc;l=306?q=jxl_image_d&ss=chromium) though...

**Comment by tbsmark86** [comment]
I appreciate your example but sadly I simply can't wrap my head around it.

This is probably just a temporary problem until the developers of all the image processing tools adapt jxl. But right now for me who just tried to hack jxl support into the favorite tool I hit a snag. All this  JxlDecoderGetColorAsEncodedProfile() is overwhelming if you don't have any prior knowledge about colorspace stuff. 
Hell I don't even know if those other formats could even hit me at all.

For now is it correct if I try something like this?
```
   JxlDecoderGetColorAsEncodedProfile(jxl,&format,  JXL_COLOR_PROFILE_TARGET_DATA,&color_encoding);
  JxlDecoderGetBasicInfo(jxl,&basic_info);
   if (basic_info.num_color_channels != 3 || color_encoding.color_space != JXL_COLOR_SPACE_RGB) {
            panic("not supported");
   } else  if(color_encoding.transfer_function == JXL_TRANSFER_FUNCTION_LINEAR && format.data_type == JXL_TYPE_FLOAT)
         // ok; linear srgb; convert
   } else if(color_encoding.transfer_function == JXL_TRANSFER_FUNCTION_SRGB  && format.data_type == JXL_TYPE_UINT8) {
       // ok; normal srgb; use as-is
   } else {
         panic("not supported");
   }
```

Thanks in advance!

**Comment by jonsneyers** [comment]
I think the gdk-pixbuf plugin is a useful example of how you're supposed to do things.

Doing proper color management is indeed not so simple, but it has become unavoidable now that screens are very much not just always sRGB anymore, but P3 and even HDR screens have become mainstream.

I'll close this issue now; if you have concrete suggestions on how to improve the decode api documentation feel free to open another issue or reopen this one.
