### ISSUE TITLE
Color encoding ambiguities (missing D65 based P3 JxlPrimaries)

### ISSUE THREAD

**Issue by kmilos** [libjxl/libjxl#709]
This is CICP (H.273) value of 12 - I suspect more content is mastered for this color space thanks to Apple's DisplayP3 screens and OS support than it is for actual DCI-P3...

**Comment by lvandeve** [comment]
> What takes precedence if you have both of those pieces of information (ICC and "custom" in codestream)

It's not possible to have both, if there's an ICC, there are no CICP fields

> This is CICP (H.273) value of 12 - I suspect more content is mastered for this color space thanks to Apple's DisplayP3 screens and OS support than it is for actual DCI-P3...

These primaries can be encoded using custom primaries, which is still relatively compact to represent (no full ICC profile necessary), it is then indeed necessary to check the custom primaries if the value is "2", and it's in theory possible to translate known custom primaries to other CICP enumeration values that were left out of the JXL specification, if the application requires this

**Comment by jonsneyers** [comment]
I think this issue is resolved, please reopen if I'm wrong.
