### ISSUE TITLE
Support compilation without bundled lodepng

### ISSUE THREAD

**Issue by Hello71** [libjxl/libjxl#711]
As briefly discussed on Discord, Linux distros (and I assume other users too) will prefer to avoid bundled libraries. Even though it is only used in tools, people's crappy vulnerability scanners will probably pick it up. Also, even though you probably shouldn't pass untrusted input to cjxl, someone will probably do it anyways.

Avoiding bundled lodepng could look like:

1. System-wide lodepng: I don't think this is a supported configuration upstream.
2. Use libpng for regular PNGs as well as APNG.
3. Allow disabling PNG support. I think this is not preferred but still a reasonable configuration, since you can simply convert your image to PPM first.

**Comment by eustas** [comment]
Indeed, the idea of lodepng is "codec without dependencies". Though it is not impossible to make it a lib...
@lvandeve are there any plans on releasing lodepng package?

**Comment by lvandeve** [comment]
Currently there are no such plants, so e.g. using the OS's libpng would work

**Comment by mo271** [comment]
Meanwhile, the lodepng dependency has been removed. 
https://github.com/libjxl/libjxl/pull/929
https://github.com/libjxl/libjxl/pull/923
