### ISSUE TITLE
Add LIBJXL_FORCE_SYSTEM_LCMS

### ISSUE THREAD

**Issue by Hello71** [libjxl/libjxl#712]
afaict no special patches are needed for lcms in libjxl, so it should be ok to use the system version. right now i am using https://cgit.alxu.ca/gentoo-overlay.git/tree/media-libs/libjxl/files/system-lcms.patch, but I'm not sure if `target_link_libraries(lcms2 INTERFACE PkgConfig::LCMS)` works on cmake 3.10, also i think my interpretation of FORCE_SYSTEM was not consistent with the other usages.

**Comment by Hello71** [comment]
or if, as it says at https://github.com/libjxl/libjxl/blob/ec30ce72cdb7e4d05e204ff20ed824b00bc9fda1/doc/color_management.md, skcms is preferred, is there work ongoing to make skcms suitable for distro packaging?

**Comment by jloqfjgk** [comment]
Related: [Use system installed vmaf and lcms](https://gitlab.com/wg1/jpeg-xl/-/issues/124)

**Comment by malaterre** [comment]
Using the patch above, I kept getting an error:

```
CMake Error at third_party/CMakeLists.txt:207 (add_library):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "INCLUDE_DIRECTORIES" is not allowed.
```

You need to fix (lib/jxl.cmake):

```
  target_include_directories(jxl_enc-obj PRIVATE
    $<TARGET_PROPERTY:lcms2,INCLUDE_DIRECTORIES>
  )
```
