### ISSUE TITLE
Windows (MSYS2+mingw-w64) -DBUILD_SHARED_LIBS:BOOL=TRUE does not disable static lib

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#714]
**Describe the bug**
building with -DBUILD_SHARED_LIBS:BOOL=TRUE, the static lib is built. But in CMakeList.txt : "option(BUILD_SHARED_LIBS "Build shared libraries instead of static ones" ON)"

**To Reproduce**
I compile with this script : 
```rm -rf builddir && mkdir builddir && cd builddir
cmake \
    -DCMAKE_TOOLCHAIN_FILE=cross_toolchain.txt \
    -DCMAKE_INSTALL_PREFIX=/opt/jxl \
    -DBUILD_SHARED_LIBS=ON \
    -DJPEGXL_ENABLE_JNI:BOOL=FALSE \
    -DJPEGXL_ENABLE_SKCMS:BOOL=FALSE \
    -DBUILD_TESTING=OFF \
    -DJPEGXL_FORCE_SYSTEM_BROTLI:BOOL=FALSE \
    -DJPEGXL_FORCE_SYSTEM_HWY:BOOL=FALSE \
    -G "Unix Makefiles" \
    ..

make -j7 install
```

**Expected behavior**
only shared library  is built and installed, but 

```
-- Installing: C:/Documents/msys2/opt/jxl/lib/libjxl-static.a
-- Installing: C:/Documents/msys2/opt/jxl/lib/libjxl_dec-static.a
-- Installing: C:/Documents/msys2/opt/jxl/lib/libjxl.dll.a
-- Installing: C:/Documents/msys2/opt/jxl/lib/libjxl.dll
```

**Environment**
 - OS: [e.g. Windows] Windows
 - Compiler version: [e.g. clang 11.0.1] gcc 10.3.0
 - CPU type: [e.g. x86_64] x86_6
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]]

**Comment by kmilos** [comment]
Btw, there's also no need for the "-static" suffix for MINGW64 builds (static is ".a" by default, whereas implib is ".dll.a" and does not clash). [This should probably](https://github.com/libjxl/libjxl/blob/0f387788921c76e9e3490c5aba3fd80cf2fb3cfe/lib/jxl.cmake#L450) set the OUTPUT_NAME w/o the suffix if not compiling w/ MSVC (and same for the "jxl_dec-static" and other targets).
