### ISSUE TITLE
released  tarbal and third party libs

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#722]
Hello

is it normal that the release tarball does not contain third party libs ? Otherwise, it needs internet connection to download them

thank you

**Comment by deymo** [comment]
Yes, the released tar.gz file is generated by github from the repository. There's a ./deps.sh helper file to download the unusual dependencies. There are other system dependencies that are not included in the .tar.gz, like the compilers, libpng-dev, libjpeg-dev, etc... We only release our software.
