### ISSUE TITLE
Add cmake options at the top of CMakeLists.txt

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#723]
As a new user, i'm completly lost with the cmake options. Would it be possible to add comments at the top of CMakeLists.txt, which lists and document them, like in this project : 

https://github.com/lexbor/lexbor/blob/master/CMakeLists.txt#L3

thank you

**Comment by mo271** [comment]
Thanks for the input, but want to avoid having duplicating that information in the build system.
