### ISSUE TITLE
Crash in Highway (base.h) with old CPU

### ISSUE THREAD

**Issue by gorza47** [libjxl/libjxl#726]
Hi,

Crash in Hwy "base.h", function: "PopCount" when using "_mm_popcnt"  on "old" CPU.

CPU: Intel(R) Core(TM)2 Quad CPU    Q9400
Compiler: MSVC 2017 or 2019
JXL lib version: 0.6

Solution: use the native code  in "PopCount".

Maybe this needs a flag in CMake or auto-detection of supported CPUs?

**Comment by deymo** [comment]
https://github.com/google/highway/commit/1da0278c7b1a4973c7937132752a6304007d2491
