### ISSUE TITLE
Should header files be marked as for C or C++?

### ISSUE THREAD

**Issue by xiota** [libjxl/libjxl#741]
Since `.h` files are ambiguous, with respect to C and C++, it might be worth indicating which can be used with C and which require C++.  On my Linux system, a number of files have a first-line comment containing `-*- C -*-` or  `-*- C++ -*-`.  Apparently, emacs uses this to identify the file type.  I know there are other editors that also use it, so they can collect symbol and text completion data.

**Comment by schmorp** [comment]
Right now, all c++ header files that are installed have a _cxc.h at the end, the rest works for both c and c++.
