### ISSUE TITLE
Failed to read image when encoding animated PNG

### ISSUE THREAD

**Issue by thebombzen** [libjxl/libjxl#756]
**Describe the bug**
Attempting to encode an animated PNG with `cjxl input.png output.jxl` yields an error message: `Failed to read image input.png` and exits.

**To Reproduce**
Take the animated PNG located at [https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png](https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png) and save it as `input.png`. [web.archive.org permalink](https://web.archive.org/web/20211014172423/https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png)

```
$ sha1sum input.png
4024517347a89acc6646e9266c946b4a61cbe531  input.png
$ cjxl input.png output.jxl
JPEG XL encoder v0.7.0 116326a [AVX2]
Failed to read image input.png.
```

**Expected behavior**
I'd expect `cjxl` to produce an animated jxl without error. The local file can be read just fine with Firefox and other software that works with animated PNGs.

**Environment**
 - OS: `Linux 5.14.12-arch1-1 x86_64`
 - Compiler version: `gcc version 11.1.0 (GCC)`
 - cjxl/djxl version string: `cjxl v0.7.0 116326a [AVX2]`

**Additional context**
Renaming the file did not change the results. Using `-d 0` and `-d 1` also did not change the results.

**Comment by Vaporeon** [comment]
It fails to decode anything created by [apngasm](https://github.com/apngasm/apngasm). I have not found a way to create apng files that `cjxl` can successfully parse.
