### ISSUE TITLE
Add option to cjxl do clear invisible pixels and/or do premultiplied alpha

### ISSUE THREAD

**Issue by jonsneyers** [libjxl/libjxl#76]
The bitstream can do premultiplied alpha, but currently cjxl has no way to select whether to do that or not.

Current behavior is that it does whatever the input format does, e.g. non-premultiplied alpha on PNG input and premultiplied alpha on EXR input.

It would be nice to have a flag to control this.

Also, in the non-premultiplied case, it would be good to have an option in the lossless mode to say "I don't care about the invisible pixels", so they can be made black or whatever else is good for compression (in lossy mode this is already done, but in lossless mode there is currently no way to do it, i.e. we now do what `cwebp -exact` does).

**Comment by ziemek99** [comment]
Shouldn't this issue be closed since #123 has been merged? (Tip: you can link multiple PRs to one issue.)

**Comment by jonsneyers** [comment]
Right, closing...
