### ISSUE TITLE
lossless transcode JPG->JXL failed

### ISSUE THREAD

**Issue by novomesk** [libjxl/libjxl#803]
Hello,

I am unable to transcode some JPG images to JXL. Majority of them works, but some some them trigger error.

Example: 
[mobile_photo.zip](https://github.com/libjxl/libjxl/files/7451997/mobile_photo.zip)

```
cjxl IMG_20211031_140031.jpg compressed.jxl
JPEG XL encoder v0.7.0 2b5e77c [AVX2]
Read 4624x2604 image, 148.7 MP/s
Encoding [Container | JPEG, lossless transcode, squirrel | JPEG reconstruction data | 16901-byte Exif | 749-byte XMP], 2 threads.
Compressed to 2361249 bytes (1.569 bpp).
4624 x 2604, 43.90 MP/s [43.90, 43.90], 1 reps, 2 threads.
./lib/jxl/fields.cc:729: JXL_FAILURE: No feasible selector for 9936393
./lib/jxl/fields.cc:487: JXL_RETURN_IF_ERROR code=1: ok_
./lib/jxl/fields.cc:632: JXL_RETURN_IF_ERROR code=1: CanEncode(fields, &extension_bits, &total_bits)
./lib/jxl/jpeg/enc_jpeg_data.cc:235: JXL_RETURN_IF_ERROR code=1: Bundle::Write(jpeg_data, &writer, 0, nullptr)
./tools/cjxl_main.cc:107: JXL_RETURN_IF_ERROR code=1: EncodeJPEGData(data_in, &jpeg_data)
```

**Comment by eddiezato** [comment]
Very strange behavior. No error and no file. With `--strip` the file is created.

```Powershell
ls -File
IMG_20211031_140031.jpg 13030382

cjxl IMG_20211031_140031.jpg IMG_20211031_140031.jxl
JPEG XL encoder v0.7.0 2b5e77c [SSE4]
Read 4624x2604 image, 201.3 MP/s
Encoding [Container | JPEG, lossless transcode, squirrel | JPEG reconstruction data | 16901-byte Exif | 749-byte XMP], 4 threads.
Compressed to 2361264 bytes (1.569 bpp).
4624 x 2604, 51.40 MP/s [51.40, 51.40], 1 reps, 4 threads.

ls -File
IMG_20211031_140031.jpg 13030382

cjxl IMG_20211031_140031.jpg IMG_20211031_140031.jxl --strip
JPEG XL encoder v0.7.0 2b5e77c [SSE4]
Read 4624x2604 image, 200.6 MP/s
Encoding [JPEG, lossless transcode, squirrel], 4 threads.
Compressed to 2361264 bytes (1.569 bpp).
4624 x 2604, 52.22 MP/s [52.22, 52.22], 1 reps, 4 threads.

ls -File
IMG_20211031_140031.jpg 13030382
IMG_20211031_140031.jxl  2361264
```

**Comment by novomesk** [comment]
Perhaps the issue is related to metadata.

**Comment by jonsneyers** [comment]
In this case, the issue is that there are 9936393 bytes of tail data (bytes after the end of the JPEG bitstream), while we only allow about 4 megabytes worth of arbitrary tail data in the `jbrd` box.
(it looks like the tail data in this case are more jpeg files, or something - maybe this is a burst shot stored simply as concatenated jpegs?)

**Comment by novomesk** [comment]
The first picture from IMG_20211031_140031.jpg has blurred background. The another bundled image seems to be original picture (no effect applied, no blurred background).

I didn't know that Xiaomi Android phone creates such files (storing both processed and unprocessed variants of pictures).

**Comment by jonsneyers** [comment]
I didn't know either, but this kind of thing is why we put some limit on the amount of tail bytes you can have; if there's more than 4 megabytes worth of stuff after the end of the jpeg bitstream, then it's likely that you don't just want to treat it as "arbitrary stuff at the end", but rather as something substantial that you either want to strip or you want to store it or recompress it separately, but just applying general-purpose compression on it (which is what `jbrd` does with tail bytes) is likely not the best idea.

**Comment by novomesk** [comment]
They store in XMP metadata some custom info called `MiCamera:XMPMeta=` ... with information that original image is following with the **depthmap** `rawlength="7053193" depthlength="2883200"`

People usually don't know there is another unprocessed image with depthmap afterwards. I think it is OK to throw it away but the metadata will still contain Xiaomi custom info about previous data bundle.

**Comment by jonsneyers** [comment]
https://github.com/libjxl/libjxl/pull/358 kind of fixes this, that is, cjxl will now produce a warning on this image and produce a lossless jxl that contains the XMP and Exif but not the `jbrd` (so you cannot reconstruct the JPEG file from it, but the image data and metadata is there - not the tail data though).
