### ISSUE TITLE
Use of uninitialized value in tools/djxl.cc - MSan

### ISSUE THREAD

**Issue by oxygen005** [libjxl/libjxl#840]
**Describe the bug**
When djxl is compiled with MSan it produces a stack trace when provided with any input file that is then converted to an output file:
```
==1828==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4aaae7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:220:6
    #1 0x4aaae7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:647
    #2 0x4aaae7 in jpegxl::tools::DecompressArgs::ValidateArgs(jpegxl::tools::CommandLineParser const&) /home/ubuntu/libjxl/tools/djxl.cc:166
    #3 0x49cca1 in main /home/ubuntu/libjxl/tools/djxl_main.cc:62:13
    #4 0x7f7d00231bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #5 0x41ffa9 in _start (/home/ubuntu/libjxl/build/tools/djxl+0x41ffa9)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:220:6 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
```

**To Reproduce**
Just run djxl with any input file (even just a file containing "test") and output file.
`djxl test /tmp/test.jpg`

**Expected behavior**
djxl should not make use of an uninitialized value

**Environment**
- OS: Ubuntu 18.04 (Windows Subsystem for Linux)
- Compiler version: clang 6.0
- CPU type: x86_64
- cjxl/djxl version string: JPEG XL decoder v0.7.0 6692183 [Scalar]

**Comment by deymo** [comment]
@oxygen005 is it possible that your libc is not compiled with msan support? How did you compile this?

In djxl.cc:166 I think the only ~basic_string call there is the one returned by jxl::Extension(). I suspect the issue is with the instrumentation itself.

**Comment by oxygen005** [comment]
I used this script to compile djxl:
```
export CC=afl-clang-fast CXX=afl-clang-fast++
export SANITIZER="msan"
export CMAKE_BUILD_TYPE="RelWithDebInfo"
export JPEGXL_ENABLE_TCMALLOC=OFF

cmake -DBUILD_TESTING=OFF -DCMAKE_C_FLAGS=" -DJXL_ENABLE_ASSERT=1 -g \
    -fsanitize=memory -DJXL_DEBUG_WARNING -DJXL_DEBUG_ON_ERROR" -DCMAKE_CXX_FLAGS=" -DJXL_ENABLE_ASSERT=1 -g \
    -fsanitize=memory -DJXL_DEBUG_WARNING -DJXL_DEBUG_ON_ERROR" \
    -DSANITIZER="msan" ..
```
Followed by:
`(cd build && ../env.sh && cmake --build . -- -j3 djxl)`

I think you're right that MSan was not compiled with libc support. I will follow the instructions at <https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo> before opening an issue next time. 
Thanks for the input!

**Comment by deymo** [comment]
`./ci.sh msan` might be useful here: It downloads and builds libc++ with msan in ~/.msan before building libjxl with it.

Another option is to look into the oss-fuzz build environment which also supports msan. We have some wrappers to make it easier (see doc/fuzzing.md). I don't remember if djxl is built by default in that case but it can be built. These wrappers assume libfuzzer, I don't think I've tried them with afl, but maybe is good enough to start.

These are developer workflows that might not work on other environments, so YMMV.
