### ISSUE TITLE
gdkpixbuf plugin calls explicitely skcms_Parse(), what if lcms2 is used ?

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#865]
afaics,  the gdkpixbuf plugin is explicitely calling skcms_Parse()

wouldn't there be a compiler error if lcms2 is used instead of skcms ?

**Comment by jonsneyers** [comment]
No, since the plugin is always using skcms.

Libjxl itself does not depend on any cms. The compile flag is only for cjxl/djxl/benchmark_xl.

I hope that answers your question, feel free to reopen otherwise.

**Comment by kmilos** [comment]
I guess the ask is to ideally enable the gdkpixbuf plugin to be lcms2-enabled as well so it is included in the same boat as cjxl/djxl w/ the global compile flag, no?
