### ISSUE TITLE
modify JxlAnimationHeader

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#869]
hello

I would like to know your opinion of this proposal : JxlAnimationHeader structure could have the number of frames, and, if the animation is repeated infinitely, having a bool for this (infinite : true/false)

thank you

**Comment by jonsneyers** [comment]
Num_loops indicates how often the animation is repeated, where 0 means infinite.

The number of frames is not known to the decoder until it has seen the last frame; it is not in the image header.

**Comment by vtorri** [comment]
and how do i know that i have decoded the last frame ? My toolkit  needs the number of frames to display an animated file

**Comment by jonsneyers** [comment]
When the decoder returns JXL_DEC_SUCCESS, it has returned all frames. The frame header has a boolean is_last which tells you that frame is the last one.

**Comment by vtorri** [comment]
do I increment the number of frame in JXL_DEC_FRAME ?

**Comment by jonsneyers** [comment]
Yes, whenever you get a JXL_DEC_FRAME event, there's a frame.

If you just want to count the number of frames quickly without doing actual decode, you can subscribe only to JXL_DEC_FRAME without subscribing to JXL_DEC_FULL_IMAGE (like what `jxlinfo` does), and then the decoder will only parse the frame headers without actually decoding anything.

**Comment by vtorri** [comment]
ok, thanks, closing
