### ISSUE TITLE
shadow variable

### ISSUE THREAD

**Issue by maddin200** [libjxl/libjxl#877]
/lib/jxl/dec_patch_dictionary.cc line 117
code:
  for (size_t i = 0; i < id_count; i++) {
      PatchPosition pos;
      pos.ref_pos = ref_pos;
      // .. some lines
      for (size_t i = 0; i < shared_->metadata->m.extra_channel_info.size() + 1; // <-- shadow variable
           i++) {

**Comment by jonsneyers** [comment]
I don't mind if you do these as issues, but it would be more convenient if you could do it as pull requests :)

Anyway thanks for spotting this!
