### ISSUE TITLE
[request] use X11 and GDI for a basic viewer instead of QT

### ISSUE THREAD

**Issue by vtorri** [libjxl/libjxl#880]
I wanted to view a JXL file on Windows and i tried to compile the embedded viewer, when i realized that it was using QT. I don't want to install QT just for that.

So my request is : would it be possible to add a basic viewer (or replace this one) with one which depends on GDI on Windows, and Xlib (or XCB) otherwise ?

**Comment by cagelight** [comment]
The JXL viewer in this repo is just a basic program intended for testing. You should use one of the many image viewers out there with support for JXL.

**Comment by jonsneyers** [comment]
See https://github.com/libjxl/libjxl/blob/main/doc/software_support.md#image-viewers for a list of viewers that support jxl.

Closing this issue since we're not going to add more viewers as part of this project.
