### ISSUE TITLE
./deps.sh: line 26: ${path^^}: bad substitution on macos

### ISSUE THREAD

**Issue by leleliu008** [libjxl/libjxl#881]
**Describe the bug**
```
./deps.sh: line 26: ${path^^}: bad substitution
```

**To Reproduce**
```
run ./deps.sh on macOS terminal
make sure you don't install another lastest version bash
beacuse macOS pre-installed a very old bash version (3.2)
```
**Expected behavior**
```
no error.
```

**Screenshots**

**Environment**
 - OS: macOS
 - Compiler version: clang 12
 - CPU type: x86_64
 - cjxl/djxl version string: https://github.com/libjxl/libjxl/archive/v0.6.1.tar.gz

**Additional context**
```
macOS pre-installed bash version is 3.2, it is a very old version, `${path^^}` feature is introduced in bash4.
```

**Comment by TransRapid** [comment]
Same issue on debian Bookworm.
