### ISSUE TITLE
Invitation for one or more libjxl maintainers to (temporarily?) join the libvips OSS Fuzz group

### ISSUE THREAD

**Issue by lovell** [libjxl/libjxl#883]
Hello, I notice as of https://github.com/libjxl/libjxl/pull/841 that libjxl has a new security policy.

The [libvips fuzzers](https://github.com/libvips/libvips/tree/master/fuzz) running on OSS Fuzz have found 4 new libjxl-related issues in the last couple of days, including 2 possible CVE-level problems, one of which causes a segfault on decode.

Would someone from the libjxl team like to be added, perhaps temporarily, to the `auto_ccs` list for the libvips OSS Fuzz project?

https://github.com/google/oss-fuzz/blob/master/projects/libvips/project.yaml

This will give you direct access to the issues as they are found, including stack traces and minimised samples. I suspect this approach might be easier than manually emailing files around.

**Comment by jonsneyers** [comment]
Thanks for the offer, that does indeed seem like a more convenient and faster approach.

Feel free to add me there.

Pinging @eustas since I suspect he might also want to be added there.

**Comment by eustas** [comment]
Hi. Thanks for the heads-up. Yup, add me, please.

**Comment by lovell** [comment]
Great, thanks both.

In the past OSS Fuzz has always required us to use gmail.com addresses for auth, although I think staff google.com addresses may also work.

May I suggest you open a PR to add your gmail address(es) to https://github.com/google/oss-fuzz/blob/master/projects/libvips/project.yaml and feel free to /cc me for approval.

**Comment by lovell** [comment]
You should both have access now, thank you, and anything you can do to help triage the issues listed at https://bugs.chromium.org/p/oss-fuzz/issues/list?q=libvips would be great, especially those marked Bug-Security.
