### ISSUE TITLE
No-coalescing + pixel callback = ?

### ISSUE THREAD

**Issue by jonsneyers** [libjxl/libjxl#896]
Currently when disabling coalescing and using the pixel callback function, it still returns image-sized frames. This is probably not what we want in that case; it should return a frame-sized frame instead, like it does with the buffer methods. That or we should just not allow using that combination (for now).

**Comment by sboukortt** [comment]
The pipeline has probably fixed this. Is it still a problem?

**Comment by mo271** [comment]
please re-open if the problem is still there
