### ISSUE TITLE
Wrong install path for gdk-pixbuf plugin

### ISSUE THREAD

**Issue by kmilos** [libjxl/libjxl#899]
gdk-pixbuf plugin will currently install in a wrong path when cross-compiling because `pkg_get_variable(GDK_PIXBUF_MODULEDIR gdk-pixbuf-2.0 gdk_pixbuf_moduledir)` will unfortunately return the absolute path on the build machine.

See [this idea](https://github.com/AOMediaCodec/libavif/blob/a50928936b068896bac6a1eb6c251089c6079a0c/contrib/gdk-pixbuf/CMakeLists.txt#L24) and [this idea](https://github.com/strukturag/libheif/blob/561abfc6b8c014499d42df5246cf2f6510fc196f/gdk-pixbuf/CMakeLists.txt#L7) for potential fixes.

**Comment by eustas** [comment]
Should be fixed via #1040
