### ISSUE TITLE
Subsampling Fails

### ISSUE THREAD

**Issue by jimbo2150** [libjxl/libjxl#91]
**Describe the bug**
Attempting to subsample colors causes encoding to fail.

**To Reproduce**
Add `--resampling=2` (or any other valid value other than 1).
An error occurs: `Failed to compress to VarDCT.`

**Expected behavior**
Produce an image.

**Environment**
 - OS: Windows 10
 - Compiler version: various
 - CPU type: x86_64
 - cjxl/djxl version string: [v0.3.7 | SIMD supported: AVX, Scalar]

**Comment by veluca93** [comment]
Interesting, what is the image that reproduces this?

**Comment by jonsneyers** [comment]
I cannot reproduce. On PNG input, it works as expected. On JPEG input, doing lossless JPEG recompression, it does do something that it probably shouldn't do (it encodes something that is the top-left quadrant, upsampled 2x, that decodes to pixels but not back to the original jpeg). I couldn't find a way to make it not produce a jxl file though.

**Comment by jimbo2150** [comment]
> 
> 
> Interesting, what is the image that reproduces this?

Every image I tried causes it to fail.

**Comment by jonsneyers** [comment]
Default cjxl options?

Are you using the current latest version from git?

(we should bump up the version number because 0.3.7 can mean anything at this point)

**Comment by jimbo2150** [comment]
I've tried with default and adding other options, nothing worked if resampling is set to anything other than 1.

It is 0.3.7, don't know the hash it was build on. Just using a build from the Discord links. Most don't work but the two I found that do both do the same thing. One appears to have SIMD while the other doesn't. They were both built around mid to end of May.
I can build one this weekend and see what happens.

**Comment by jimbo2150** [comment]
I just tried Raysar's new build and it works. Possibly the other builds floating around were missing something.

**Comment by jimbo2150** [comment]
Running into some issues again. Any photo I try to compress with quality below 52 fails.

**Comment by deymo** [comment]
@jimbo2150 what platform do you need builds for?

**Comment by jimbo2150** [comment]
> 
> 
> @jimbo2150 what platform do you need builds for?

Windows 10, but don't really need it now. Someone just did a build - first one I've seen in a few weeks. I can build it myself, but would need to do it over a weekend. Thanks.

**Comment by jimbo2150** [comment]
> 
> 
> Running into some issues again. Any photo I try to compress with quality below 52 fails.

![jxl-resampling-problem](https://user-images.githubusercontent.com/25777094/120891885-fccf8b80-c5d8-11eb-8aeb-67a224fb3f4b.png)

**Comment by veluca93** [comment]
Ah, I know what is going on -- try passing `--progressive_dc=0` too...

**Comment by jimbo2150** [comment]
> 
> 
> Ah, I know what is going on -- try passing `--progressive_dc=0` too...

That worked, but odd that you have to disable progressive decoding.

**Comment by veluca93** [comment]
> > Ah, I know what is going on -- try passing `--progressive_dc=0` too...
> 
> That worked, but odd that you have to disable progressive decoding.

Progressive DC doesn't work with downsampling - but we should not turn it on by default then :)

**Comment by jimbo2150** [comment]
Also fails on any speed above 7.

![jxl-resampling-speed-issue](https://user-images.githubusercontent.com/25777094/120892581-170b6880-c5dd-11eb-9df3-16237cd2e8e5.png)

**Comment by veluca93** [comment]
Ah, yes, I can see why that would be the case - we'll make sure to return an explicit error.

**Comment by ziemek99** [comment]
Any updates on this issue?
