### ISSUE TITLE
Crash when trying to save.

### ISSUE THREAD

**Issue by sati32** [libjxl/libjxl#915]
JxlEncoderStatus JxlEncoderOptionsSetDistance(JxlEncoderOptions* options, float distance)

there is a line:
  if (distance < 6.56f) {
    jpeg_quality = -5.456783f * std::log(0.0256f * distance - 0.16384f);
  } else {
    jpeg_quality = -11.11111f * distance + 101.11111f;
  }
this generates a crash, because log of negative values is not possible.
It should be
  if (distance > 6.56f) {

**Comment by jonsneyers** [comment]
Thanks for reporting!
