### ISSUE TITLE
Saving JPEG XL ends in jxl::Abort

### ISSUE THREAD

**Issue by sati32** [libjxl/libjxl#917]
code that already worked fine is no longer able to save an image.

What I do in principle:
JxlEncoderPtr				enc = JxlEncoderMake(NULL);
JxlThreadParallelRunnerPtr	runner = JxlThreadParallelRunnerMake(nullptr, JxlThreadParallelRunnerDefaultNumWorkerThreads());
	status = JxlEncoderSetParallelRunner(enc.get(), JxlThreadParallelRunner, runner.get());
	status = JxlEncoderSetBasicInfo(enc.get(), &basic_info);
	JxlColorEncodingSetToSRGB(&color_encoding, /*is_gray=*/pixelFormat.num_channels < 3);
	status = JxlEncoderSetColorEncoding(enc.get(), &color_encoding);
	encoderOptions = JxlEncoderOptionsCreate(enc.get(), nullptr);
	status = JxlEncoderOptionsSetDistance(encoderOptions, quality);
	status = JxlEncoderOptionsSetLossless(encoderOptions, FALSE);
	status = JxlEncoderAddImageFrame(encoderOptions, &pixelFormat, buffer, (size_t)buffer.getSize());
	status = JxlEncoderProcessOutput(enc.get(), &next_out, &avail_out);

this goes to RefillOutputByteQueu, WriteHeader, WriteImageMetadata, .... and ends in AllDefault
Bundle::AllDefault ... JXL_ABORT("AllDefault should never fail");

Little bit complex, I know, but it did work in the past. But not with the latest library.
What am I doing wrong?

**Comment by jonsneyers** [comment]
Could you share the full code? E.g. how are you initializing basic_info?

**Comment by sati32** [comment]
It's much code, I sent the whole file by email, here in short form:
					pixelFormat.num_channels = uint32_t(pic->getSamples() + hasAlpha);
					pixelFormat.data_type = JXL_TYPE_UINT8;
					if (pic->getKind() & PI_BIT16)
						pixelFormat.data_type = JXL_TYPE_UINT16;
					else if (pic->getKind() & PI_FLOAT)
						pixelFormat.data_type = JXL_TYPE_FLOAT;

					basic_info.xsize = (uint32_t)imageSize.w;
					basic_info.ysize = (uint32_t)imageSize.h;
					basic_info.orientation = JXL_ORIENT_IDENTITY;
					basic_info.bits_per_sample = (uint32_t)pic->getBitsPerSample();
					basic_info.exponent_bits_per_sample = 0;
					if (pic->getKind() & PI_FLOAT)
						basic_info.exponent_bits_per_sample = 8;

					basic_info.alpha_exponent_bits = 0;
					basic_info.alpha_bits = 0;
					if (hasAlpha)
					{
						basic_info.alpha_bits = (uint32_t)alpha->getBitsPerSample();
						if (pic->getKind() & PI_FLOAT)
							basic_info.alpha_exponent_bits =	8;
					}
					basic_info.uses_original_profile = JXL_FALSE;

					status = JxlEncoderSetBasicInfo(enc.get(), &basic_info);
					if (status == JXL_ENC_SUCCESS)
					{
						GSConstObjectPointer<GSICCProfile>	iccProfile;
						
						sourceImg->fillICCProfile(TRUE, &iccProfile);
						GSASSERT(iccProfile.get());
						GSASSERT(iccProfile->getPicKind() == pic->getSimpleKind());

						if (iccProfile.get() && (iccProfile->getPicKind() == pic->getSimpleKind()) && !iccProfile->isSRGB(FALSE))
						{
							const GSDynaArray<UCHAR>	&iccData = iccProfile->getData();

							status = JxlEncoderSetICCProfile(enc.get(), iccData.getAddr(), size_t(iccData.getCount()));
						}
						else
						{
							JxlColorEncoding	color_encoding = {};

							JxlColorEncodingSetToSRGB(&color_encoding, /*is_gray=*/pixelFormat.num_channels < 3);
							status = JxlEncoderSetColorEncoding(enc.get(), &color_encoding);
						}

						if (status == JXL_ENC_SUCCESS)
						{
							GSArrayPointer<UCHAR>	buffer;
							GSArrayPointer<UCHAR>	compressedBuffer;
//							jxl::JxlEncoderOptionsValues	values;

							buffer.alloc(imageSize.h * lineWidth);

							if (buffer)
							{
								GSPicture			picture(pic, alpha);
								GSPoint				point = gs_zero_point;
								UCHAR					*bufPtr = buffer;
								JxlEncoderOptions	*encoderOptions;
								float					quality = 1.0f;		// sollte 0.5f ... 3.0f sein

								quality = 3.0f - (float)_data.getCompress() * 3.0f;

								while (point.y < imageSize.h)
								{
									picture.getLine(&point, imageSize.w, bufPtr, hasAlpha);
									point.y++;
									bufPtr += lineWidth;
								}
								encoderOptions = JxlEncoderOptionsCreate(enc.get(), nullptr);
								status = JxlEncoderOptionsSetDistance(encoderOptions, quality);
								if (_data.getCompress() == 1.0f)
									status = JxlEncoderOptionsSetLossless(encoderOptions, TRUE);
								else
									status = JxlEncoderOptionsSetLossless(encoderOptions, FALSE);

								status = JxlEncoderAddImageFrame(encoderOptions, &pixelFormat, buffer, (size_t)buffer.getSize());

								if (status == JXL_ENC_SUCCESS)
								{
									compressedBuffer.alloc(16384);
									uint8_t	*next_out = compressedBuffer;
									size_t	avail_out = (size_t)compressedBuffer.getSize() - size_t(next_out - compressedBuffer);

									status  = JXL_ENC_NEED_MORE_OUTPUT;
									while (status == JXL_ENC_NEED_MORE_OUTPUT)
									{
										status = JxlEncoderProcessOutput(enc.get(), &next_out, &avail_out);
										if (status == JXL_ENC_NEED_MORE_OUTPUT)
										{
											size_t	offset = size_t(next_out - compressedBuffer);
									
											compressedBuffer.realloc(compressedBuffer.getSize() * 2);
											next_out = compressedBuffer + offset;
											avail_out = (size_t)compressedBuffer.getSize() - offset;
										}
									}
//									compressedBuffer.realloc(next_out - compressedBuffer);		// tut eh nichts
									if (status == JXL_ENC_SUCCESS)
										error = file->write(compressedBuffer, next_out - compressedBuffer);
								}
							}
						}
					}

**Comment by sati32** [comment]
got it. I have to setup intensity_target in JxlBasicInfo. The default value of 0 lets the library abort().

**Comment by jonsneyers** [comment]
More generally, you should call the initialization function on that struct. We might add more fields to it before we reach 1.0.

Also note that there are no default field values if you don't explicitly initialize a struct (i.e. if you just do `JxlBasicInfo basic_info;` without a `= {}` or without calling the initialization function). Things just get initialized with whatever happens to be in memory, which could be zeroes but it could also be anything else. That can lead to very surprising bugs.

**Comment by jonsneyers** [comment]
Any action we should take on this one? Improve documentation to clarify that you really need to call `JxlEncoderInitBasicInfo` before setting custom basicinfo values? We could also add a check (e.g. set the last few bytes of the padding in the struct to some signature and check it) and return a more helpful error in case the basicinfo wasn't initialized, to help catch this particular incorrect api usage.

**Comment by sati32** [comment]
Since the user should always call JxlEncoderInitBasicInfo(), I think it would be good to have a mechanism that checks it.

**Comment by novomesk** [comment]
BasicInfo must be properly initialized but forcing to use JxlEncoderInitBasicInfo() means that old libjxl 0.5 cannot be used. 

It's not a big deal to bump dependency for individual developer but some projects/repos do not upgrade so frequently.

If there are other breaking changes, it is good to bring them at the same time.

**Comment by jonsneyers** [comment]
As it is now, not initializing basicinfo will cause encoding to fail or at best do something weird, like setting a random orientation and intensity.

I agree that we should bundle breaking changes. I hope we can have a semi-finalized API soon (say end of year or so), and from then on just have no breaking changes at all anymore.

**Comment by mo271** [comment]
I think there's no concrete action to be taken here.
