### ISSUE TITLE
Stay on C++ Standard version 14

### ISSUE THREAD

**Issue by sati32** [libjxl/libjxl#932]
I compile the library with Visual Studio.
There is only one place in the code that needs C++ Standard version 20. Can you change it to
const JxlCmsInterface& GetJxlCms() {
  static constexpr JxlCmsInterface kInterface = {
      nullptr,
      &JxlCmsInit,
      &JxlCmsGetSrcBuf,
      &JxlCmsGetDstBuf,
      &DoColorSpaceTransform,
      &JxlCmsDestroy};
  return kInterface;
}
so it will work with Standard version 14.

**Comment by jonsneyers** [comment]
This was fixed by https://github.com/libjxl/libjxl/pull/924, right?

**Comment by sati32** [comment]
yes, sorry, did't get the latest version and didn't see this comment.
You can close this.
