### ISSUE TITLE
make it possible to get the original pixel values from losslessly transcoded jpeg files, or document that it can't be done

### ISSUE THREAD

**Issue by schmorp** [libjxl/libjxl#950]
**Is your feature request related to a problem? Please describe.**

I'm interested in lossless transcoding of JPEG images - specifically, getting identicalmpixel values out of the image. As far as I can see, this can be done by storing JPEG reconstruction data and reconstructing the original JPEG.

However, when not storing JPEG reconstruction data, this is not possible (apparently, at leats not with the reference API - it would be cool if one could get a non-bit-identical but equivalent JPEG file back), and the only way to get to the pixels seems to be to use the JXL decoder.

**Describe the solution you'd like**

When transcoding a JPEG file losslessly to JXL, it should be possible to get identical pixel values between decoding the original JPEG file and decoding the JXL file. This is not currently the case, even JXL files that can be reconstructed to the original JPEG file will decode to different pixel values when using the JXL decoder.

I understand that this is not directly possible as different jpeg decoders disagree on exact pixel values, but there should be some way to get identical results by picking a standard, for example, using the IJG libjpeg with a certain set of decoder options, where the IJG library and the JPEG-XL reference library would agree on pixel values.

While a workaround is to always reconstruct the JPEG and decode that, that is not possible when losslessly transcoding the JPEG image without reconstruction data, so you end up with a losslessly transcoded jpeg file that has different pixel values in the jxl representation.

**Describe alternatives you've considered**

Documenting that "lossless transcode" does NOT mean you get the same image when decoding the jxl file might be a good first step - the impression I got form documentation is that lossless means I get the same pixels when decoding the JXL image. Possibly that is the only thing that cna be done about it.

Alternatively, documenting that to get identical results, you need to reconstruct the JPEG file, so lossless transcodes REQUIRE jpeg reconstruction data and a JPEG decoder, might help.

Supporting "lossy" JPEG "reconstruction", where one can construct "an" equivalent (pixel-value-wise) JPEG image from a losslessly transcoded JPEG image might help - in that case, one can losslessly convert to JXL, and if one needs the original pixels for verification purposes, one could construct a JPEG file and use both jpeg files in a jpeg decoder of ones choice.

**Additional context**

I'm archiving >>100TB of JPEG (and other) images, and plan to convert most if not all into JXL files. Knowing how to get the exact "original" pixel values is important, to be able to verify that the image has been transcoded correctly. Doing this without the JPEG reconstruction data can yield considerable (for us) space savings in some applications (while mostly we would opt for JPEG reconstruction data to be stored).

Also, at this scale, conversion always requires a verification step, as something always goes wrong.

**Comment by jonsneyers** [comment]
There is no such thing as "original pixels" in the case of JPEG. Different JPEG decoders produce different pixels, and yet they can all conform to the spec.

Different versions of libjpeg-turbo might produce slightly different pixels, and there are probably also platform-dependent differences. Within the same version, you get different results depending on which implementation of the iDCT you use (e.g. `djpeg -dct float` is more accurate than the default `djpeg -dct int`).

So basically there are no "original pixels", only original quantized DCT coefficients. The JPEG spec leaves quite a bit of freedom in how exactly to do the dequantization, inverse DCT, chroma upsampling and color conversion. The most common jpeg decoder, libjpeg-turbo, makes some choices (mostly choosing speed over accuracy). Libjxl makes some other choices. We could in principle add a "libjpeg-turbo emulation mode" where we try to mimick the default behavior of libjpeg-turbo, but I don't think it's worth it to do that.

**Comment by jonsneyers** [comment]
If you just want to verify that the conversion went well, the easiest way is to keep the reconstruction data and check that you can get the exact same jpeg file back. An alternative would be to do some simple PSNR between the jxl and the jpeg: if you get a value above, say, 40, then at least you know nothing went hugely wrong and the only plausible explanation would be that the jxl actually does contain the same quantized DCT coefficients.

**Comment by schmorp** [comment]
@jonsneyers your response reads like some canned auto-response by a bot: If you read my original request you can see that I am fully aware of these issues and made various suggestions that would improve the situation, alkl of which you failed to reference in your reply.

Specifically, I wrote: "different jpeg decoders disagree on exact pixel values", but suggested either a standard profile, a way to get a pixel-equivalent JPEG file back without reconstruction data (assuming this is possible), or at least to document that lossless isn't really possible without JPEG reconstruction data.

**Comment by jonsneyers** [comment]
Lossless is really possible, and it is what happens, but there is no such thing as "pixel-equivalent" when you're talking about JPEG. What is lossless are the quantized DCT coefficients.

Producing a JPEG without `jbrd` (in case the data is actually 8x8-only etc) could in principle be done. Decoding to pixels in a way that mimicks a given JPEG decoder could also in principle be done.

**Comment by schmorp** [comment]
btw., the possible feature you mentioned in ##861 (libjxl being able to decode jpeg images itself) could potentially also be a solution, as decoding would presumably be deterministic (at least) when using the same arch/binary, between decoding transcoded jxl files and the original jpeg file with libjxl.

**Comment by mo271** [comment]
> Lossless is really possible, and it is what happens, but there is no such thing as "pixel-equivalent" when you're talking about JPEG. What is lossless are the quantized DCT coefficients.
> 
> Producing a JPEG without `jbrd` (in case the data is actually 8x8-only etc) could in principle be done. Decoding to pixels in a way that mimicks a given JPEG decoder could also in principle be done.
We aren't planning do to that though, are we?

**Comment by jonsneyers** [comment]
> > Lossless is really possible, and it is what happens, but there is no such thing as "pixel-equivalent" when you're talking about JPEG. What is lossless are the quantized DCT coefficients.
> > Producing a JPEG without `jbrd` (in case the data is actually 8x8-only etc) could in principle be done. Decoding to pixels in a way that mimicks a given JPEG decoder could also in principle be done.
> 
> We aren't planning do to that though, are we?

No, I don't see a need for that. The other way around, making libjxl decode jpeg bitstreams to pixels directly (i.e. without the detour of recompressing them to jxl), makes a lot more sense and would make libjxl a nice replacement for libjpeg.
