### ISSUE TITLE
Many tests fail when built with -Wp,-D_GLIBCXX_ASSERTIONS

### ISSUE THREAD

**Issue by afontenot** [libjxl/libjxl#98]
**Describe the bug**
When `-Wp,-D_GLIBCXX_ASSERTIONS` is added to CXXFLAGS, many tests fail when their processes unexpectedly abort. In my tests exactly 79 tests fail, a list of these compiled by another user is here: https://aur.archlinux.org/pkgbase/libjxl/#comment-811172

**To Reproduce**
With the latest release, add `-Wp,-D_GLIBCXX_ASSERTIONS` to CXXFLAGS. Try to build and run tests with cmake, e.g. 

    cmake --build . -- -j8
    cmake --build . -- test

**Expected behavior**
Tests complete successfully. 

**Environment**
 - OS: Arch Linux
 - Compiler version: clang 11.0.1
 - CPU type: x86_64
 - cjxl/djxl version string: [v0.3.7 | SIMD supported: SSE4,Scalar]

**Additional context**
Arch Linux recently added this option to its default CXXFLAGS for building packages. Users trying to build libjxl as a package on Arch Linux are likely to run into this problem.

Here is sample output from running one of the tests directly:

    "/home/adam/Downloads/jxl/libjxl/src/build/lib/tests/butteraugli_test" "--gtest_filter=ButteraugliTest.Distmap" "--gtest_also_run_disabled_tests"
    Running main() from /build/gtest/src/googletest-release-1.10.0/googletest/src/gtest_main.cc
    Note: Google Test filter = ButteraugliTest.Distmap
    [==========] Running 1 test from 1 test suite.
    [----------] Global test environment set-up.
    [----------] 1 test from ButteraugliTest
    [ RUN      ] ButteraugliTest.Distmap
    /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/atomic_base.h:268: void std::atomic_flag::clear(std::memory_order): Assertion '__b != memory_order_acq_rel' failed.
    zsh: abort (core dumped)  "/home/adam/Downloads/jxl/libjxl/src/build/lib/tests/butteraugli_test"

Possibly related bug: https://github.com/libjxl/libjxl/issues/64 (this user also had this compiler option enabled and failed to build libjxl)

**Comment by dbermond** [comment]
This is already fixed on the git master branch, as it builds fine with the `_GLIBCXX_ASSERTIONS` macro enabled.

A git bisect shows that the first good commit (the one that fixes this) is 30ea86ab4c1f1b98c21967a2e3d72a51fe77e454.

I think this can be closed.

**Comment by afontenot** [comment]
Confirmed; I thought I had tested the git master while debugging this issue, but apparently not. Closing.
