### ISSUE TITLE
Allow using pixbuf for output buffer

### ISSUE THREAD

**Issue by schmorp** [libjxl/libjxl#994]
**Is your feature request related to a problem? Please describe.**

I was trying to decode a JXL image into a gdk pixbuf. Unfortunately, allocating
a pixbuf with the same pixel dimensions as the JXL output and passing the result of gdk_pixbuf_get_byte length into JxlDecoderSetImageOutBuffer fails because libjxl requires extra space after the last pixel that gdk pixbuf does not provide.

Specifically, if row_size is the size of a pixel row in bytes, and row_skip is the extra space reserved between rows (i.e. align - row_size), then libjxl seems to use something like this formula:

   image_size = (row_size + row_skip) * rows

While gdk pixbuf uses something like:

   image_size = (row_size + row_skip) * (rows - 1) + row_size

i.e. it does not require extra alignment space after the pixels in the last row to actually exist.

The gdk buffer is thgerefore always smaller if extra alignment is needed, and therefore, jxl considers the buffer too small. This is a common case, as gdk aligns rows even when not strictly needed (e.g. RGB pixels and odd widths).

**Describe the solution you'd like**

I actually find gdk pixbuf's behaviour here slightly retarded :) However, it does what it does, and it might not be the only library to do so (it might be...). It's also very hard to work around this - you really require an extra copy, or you need to overallocate in non-intuitive ways.

In fact, gdk pixbuf internally allocates a larger buffer of the same size as libjxl expects, but this is not documented, and therefore, might just be an artifact of the current code base.

I see a few ways out of this issue:

- document that the extra space after a row is never accessed. this way, a program using gdk pixbuf cna just pretend the gbuffer is larger and everything would be fine. Documenting that the extra space is never accessed is also beneficial for other reasons, such as when one wants to decode an image into a large buffer (e.g. when preparing a texture atlas).

- mimic the size calculation of gdk pixbuf, i.e. return the number of bytes required from first to last pixel only.

**Describe alternatives you've considered**

There might be other solutions - I just want to bring this issue to your attention. At the moment, I went for simply assuming that gdk overallocates its buffer and returns a smaller byte size than the buffer length, and hoping that libjxl will not access the extra space anyway, even if some future gdk pixbuf version changes the buffer size internally.

**Comment by schmorp** [comment]
PS: "does not access" might be hard to materially define - if your last RGB pixel starts at an even address, it might be hard to avoid writing or at least reading 4 octets while still doing optimised accesses. It doesn't create an issue on typical architectures, but architectures/compilers that strictly check pointer range access can run into issues here. This problem exists for gdk pixbuf as well, which is why I think its calculation is a bit retarded, as it creates more issues as it solves.

**Comment by veluca93** [comment]
On the top of my head, I don't remember exactly what our decoder does for writing to the output buffer. I *think* it shouldn't extend beyond the row (as otherwise one would need up to ~252 extra bytes with AVX512), so it should be possible to only require a smaller buffer.

As for a possible workaround for this specific case - would it work to allocate one extra row and then shrink the pixbuf?

**Comment by schmorp** [comment]
Of course one can overallocate and shrink the buffer, but as I mentioned, that requires an extra copy (or not actually shrinking the buffer), which seems like a high price to pay. It's a valid option for libjxl, though - personally, I will just risk it by assuming assuming the buffer is large enough and then blame any resulting security issues on both libjxl and gdk pixbuf :*)

**Comment by veluca93** [comment]
I meant shrink the image without shrinking the buffer, yes :)

I'll check next week whether we can change that computation to match pixbuf
- I believe yes but not 100% certain.

**Comment by schmorp** [comment]
I just had a closer look at gdk pixbuf documentation, and, not unexpectedly, it is a bit confusing, but ultimately makes it clear the data beyond the last pixel might not exist:

    There may be padding at the end of a row.

    The “rowstride” value of a pixbuf, as returned by gdk_pixbuf_get_rowstride(), indicates 
    the number of bytes between rows.

    NOTE: If you are copying raw pixbuf data with memcpy() note that the last row in the pixbuf 
    may not be as wide as the full rowstride, but rather just as wide as the pixel data needs to be

This *seems* clear, but it isn't: you can never just memcpy (into) the padding data even for other rows that have it allocated, because it might belong to another pixbuf.

And obviously the pixbuf code itself is not bold/stupid enough to actually make this a reral requirement.

The question is really how common it is, and how easy to avoid by libjxl - it might mean having to support an inconvenient guarantee for all eternity.

**Comment by lvandeve** [comment]
There's no technical reason why JXL needs those last row_skip bytes, so this should be fixable
